# Config file for mypy

# Note: Do not put comments after settings.

[mypy]
python_version = 3.14
cache_dir = mypy_cache

# Defaults for all files.
check_untyped_defs = True
follow_imports = skip
ignore_missing_imports = True
incremental = False
show_error_codes = True
strict_optional = False

disable_error_code=attr-defined,index

# For v0.931, per https://github.com/python/mypy/issues/11936

exclude =
    
    # The first line must *not* start with |.
    # Thereafter, each line *must* start with |.
    # No trailing '|' on last entry!

    # Directories...
    doc/|dist/|editpane/|examples/|extensions/|external/|modes/|obsolete/|scripts/|themes/|unittests/|www/|
    
    # Special plugins...
    |freewin.py|scriptFile.py|beautify_node.py|viewrendered3|

    # Experimental plugins...
    |leo_pdf|leo_to_rtf|mnplugins|mod_speedups|settings_finder|stickynotes_plus|
    
    # qt_main.py is generated automatically, so it's pointless to add annotations.
    |qt_main

# #4766: more specific descriptions override less specific.
[mypy-leo.core.leoApp,leo.core.leoConfig,leo.core.leoNodes,leo.core.leoGlobals,leo.core.leoCommands]
strict_optional = True
