# Config file for mypy
# Note: Do not put comments after settings.

[mypy]
python_version = 3.14
ignore_missing_imports  = True
incremental = True
# cache_dir=nul
cache_dir = mypy_cache
show_error_codes = True
check_untyped_defs = True
# mypyc: strict_optional must be true: use--strict-optional
strict_optional = False
disable_error_code=attr-defined

# For v0.931, per https://github.com/python/mypy/issues/11936

exclude =
    
    # The first line must *not* start with |.
    # Thereafter, each line *must* start with |.
    # No trailing '|' on last entry!

    # Directories...
    doc/|dist/|editpane/|examples/|extensions/|external/|modes/|obsolete/|scripts/|themes/|unittests/|www/|
    
    # Special plugins...
    |freewin.py|scriptFile.py|beautify_node.py|viewrendered3|

    # Experimental plugins...
    |leo_pdf|leo_to_rtf|mnplugins|mod_speedups|settings_finder|stickynotes_plus|
    
    # qt_main.py is generated automatically, so it's pointless to add annotations.
    |qt_main

# The default for leo.core: full annotation.
[mypy-leo.core.*]
disallow_untyped_defs = True
disallow_incomplete_defs = True
strict_optional = True

# The default leo.commands: full annotation.
[mypy-leo.commands.*]
disallow_untyped_defs = True
disallow_incomplete_defs = True
strict_optional = True

# All importer and writer plugins: full annotation.
[mypy-leo.plugins.importers.*,leo.plugins.writers.*,leo.unittests.plugins.test_importers]
disallow_untyped_defs = True
disallow_incomplete_defs = True
strict_optional = True

# Exclusions...

# Don't check leo/modes.
[mypy-leo.modes]
follow_imports = skip
ignore_missing_imports  = True
disallow_untyped_defs = False
disallow_incomplete_defs = False
strict_optional = False

# Don't check third-party code.
[mypy-leo.core.leoRope]
follow_imports = skip
ignore_missing_imports  = True
disallow_untyped_defs = False
disallow_incomplete_defs = False
strict_optional = False

# leo.plugins.qt_*, part 1.
[mypy-leo.plugins.qt_commands,leo.plugins.qt_events,leo.plugins.qt_gui.py,leo.plugins.qt_idle_time]
follow_imports = skip
ignore_missing_imports  = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
strict_optional = True

# leo.plugins.qt_*, part 2
[mypy-leo.plugins.qt_layout,leo.plugins.qt_text.py,leo.plugins.qt_tree]
follow_imports = skip
ignore_missing_imports  = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
strict_optional = True


# Standard plugins: full annotation (to do)
    
[mypy-leo.plugins.contextmenu,leo.plugins.free_layout]
disallow_untyped_defs = True
disallow_incomplete_defs = True
strict_optional = False

[mypy-leo.plugins.mod_scripting,leo.plugins.nav_qt,leo.plugins.nodetags]
disallow_untyped_defs = True
disallow_incomplete_defs = True
strict_optional = False

[mypy-leo.plugins.pane_commands,leo.plugins.qt_quick_headlines]
disallow_untyped_defs = True
disallow_incomplete_defs = True
strict_optional = False

[mypy-mleo.plugins.plugins_menu,leo.plugins.quicksearch]
disallow_untyped_defs = True
disallow_incomplete_defs = True
strict_optional = False

[mypy-leo.plugins.todo,leo.plugins.viewrendered]
disallow_untyped_defs = True
disallow_incomplete_defs = True
strict_optional = False

# Don't check special cases.
[mypy-leo.core.runLeo,leo.core.leoclient,leo.core.leoPymacs]
follow_imports = skip
ignore_missing_imports  = True
disallow_untyped_defs = False
disallow_incomplete_defs = False
strict_optional = False
