<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2"/>
<globals/>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="ekr.20201214185419.1"><vh>git_diff_test.leo</vh></v>
<v t="ekr.20201214185435.1"><vh>node 1</vh></v>
<v t="ekr.20201214185703.1"><vh>new node 1</vh></v>
</vnodes>
<tnodes>
<t tx="ekr.20201214185419.1"></t>
<t tx="ekr.20201214185435.1"></t>
<t tx="ekr.20201214185703.1"></t>
</tnodes>
</leo_file>
