#@+leo-ver=5-thin
#@+node:ekr.20240406013108.1: * @file ../../ruff.toml
#@@language toml

# This file includes options only for the ruff linter.
# pyproject.toml contains all `ruff format` options.

# To add suppressions
# find: ^(\s+)(\w+) (.+?)$
# repl: \1"\2", # \3

[lint]
ignore = [
    # New errors.

    "UP031",    # Use format specifiers instead of percent format
    "UP032",    # Use f-string instead of `format` call
    "UP035",    # Import from `collections.abc` instead: `Iterable`
    "W605",     # Invalid escape sequence: `\*`
    "TC004",    # Move import `leo.core.leoNodes.Position` out of type-checking block.
                # Import is used for more than type hinting.
                
    # Good, but do these later.

    "RUF013",   # PEP 484 prohibits implicit `Optional`
    "UP024",    # Replace aliased errors with `OSError`
                
    # Deprecated functions.
    
    "DTZ003",   # `datetime.datetime.utcnow()` used
    "DTZ005",   # `datetime.datetime.now()` called without a `tz` argument
    "DTZ006",   # `datetime.datetime.fromtimestamp()` called without a `tz` argument
    "DTZ007",   # Naive datetime constructed using `datetime.datetime.strptime()` without %z
    "DTZ011",   # `datetime.date.today()` used

    # Maybe.
    
    "PIE790",   # Unnecessary `pass` statement
    "PIE807",   # Prefer `list` over useless lambda
    "PLR0402",  # Use `from leo.plugins.importers import otl` in lieu of alias
    "PLR1730",  # Replace `if` statement with `wsLimit = max(wsLimit, 1)`
    "PLW0120",  # `else` clause on loop without a `break` statement;remove the `else` and dedent its contents
    "PLW0406",  # Module `leo.plugins.demo` imports itself
    "PLW0602",  # Using global for `oldAppCloseLeoWindow` but no assignment is done
    "PLW1510",  # `subprocess.run` without explicit `check` argument
    "RUF010",   # Use explicit conversion flag
    "RUF015",   # Prefer `next(...)` over single element slice
    "RUF023",   # ShadowController.__slots__` is not sorted
    "RUF034",   # Useless `if`-`else` condition
    "RUF046",   # Value being cast to `int` is already an integer
    "RUF051",   # Use `pop` instead of `key in dict` followed by `del dict[key]`
    "RUF059",   # Unpacked variable `junk` is never used
    "SIM102",   # Use a single `if` statement instead of nested `if` statements
    "SIM103",   # Return the negated condition directly
    "SIM113",   # Use `enumerate()` for index variable `id_` in `for` loop
    "SIM114",   # Combine `if` branches using logical `or` operator
    "SIM115",   # Use a context manager for opening files
    "SIM117",   # Use a single `with` statement with multiple contexts instead of nested `with` statements
    "SIM118",   # Use `key in dict` instead of `key in dict.keys()`
    "SIM201",   # Use `_last_code_line_num != _numlines - 1` instead of `not _last_code_line_num == _numlines - 1`
    "SIM222",   # Use `True` instead of `True or ...`
    "SIM223",   # Use `False` instead of `False and ...`

    # New suppressions: Keep these for now.
    
    "B008",     # Do not perform function call in argument defaults
    "B019",     # Use of `functools.lru_cache` or `functools.cache` on methods can lead to memory leaks
    "B020",     # Loop control variable `p` overrides iterable it iterates
    "BLE001",   # Do not catch blind exception: `Exception`
    "C400",     # Unnecessary generator (rewrite as a list comprehension)
    "C401",     # Unnecessary generator (rewrite as a set comprehension)
    "C402",     # Unnecessary generator (rewrite as a dict comprehension)
    "C403",     # Unnecessary list comprehension (rewrite as a set comprehension)
    "C404",     # Unnecessary list comprehension (rewrite as a dict comprehension)
    "C405",     # Unnecessary list literal (rewrite as a set literal)
    "C408",     # Unnecessary `dict()` call (rewrite as a literal)
    "C413",     # Unnecessary `list()` call around `sorted()`
    "C414",     # Unnecessary `list()` call within `sorted()`
    "C417",     # Unnecessary `map()` usage (rewrite using a generator expression)
    "FLY002",   # Consider `f'{root.h}-->{p.h}'` instead of string join
    "FURB105",  # Unnecessary empty string passed to `print`
    "FURB167",  # Use of regular expression alias `re.M`
    "FURB188",  # Prefer `str.removesuffix()` over conditionally replacing with slice.
    "PERF102",  # When using only the values of a dict use the `values()` method
    "PERF402",  # Use `list` or `list.copy` to create a copy of a list
    "PIE794",   # Class field `valid_unls` is defined multiple times
    "PLC0206",  # Extracting value from dictionary without calling `.items()`
    "PLR1704",  # Redefining argument with the local name `p`
    "PYI041",   # Use `float` instead of `int | float`
    "RUF012",   # Mutable default value for class attribute
    "RUF100",   # Unused blanket `noqa` directive
    "S102",     # Use of `exec` detected
    "S110",     # `try`-`except`-`pass` detected, consider logging the exception
    "S112",     # `try`-`except`-`continue` detected, consider logging the exception
    "SIM905",   # Consider using a list literal instead of `str.split`
    "T100",     # Import for `xxx` found
    "TRY004",   # Prefer `TypeError` exception for invalid type
    "UP028",    # Replace `yield` over `for` loop with `yield from`
    "UP030",    # Use implicit references for positional format fields

    # Previous suppressions. Keep these.
    
    "E402", # Module level import not at top of file
    "E701", # Multiple statements on one line (colon)
    "E702", # Multiple statements on one line (semicolon)
    "E711", # Comparison to `None` should be `cond is None`
    "E731", # Do not assign a `lambda` expression, use a `def`
    "E741", # Ambiguous variable name: `l`. Bad style, but only occurs in minor plugins.

    "F401", # `xxx` imported but unused. Pyflakes checks this.
    "F841", # Local variable `xxx` is assigned to but never used. Pyflakes checks this.
    
    "I001",     # Import block is un-sorted or un-formatted
    "ISC004",   # Unparenthesized implicit string concatenation in collection
    "N999",     # Invalid module name: 'test_leoUndo'
]

exclude = [
    # Exclude entire folders...
    "leo/external/*.py",
    "leo/plugins/obsolete/*.py",
    "leo/plugins/leo_babel/babel*.py",
    "leo/plugins/leo_babel/tests/*.py",
    "leo/scripts/*.py",
    # Exclude unusual plugins.
    "leo/doc/sphinx-docs/conf.py",
    "leo/plugins/md_docer.py",
    "leo/plugins/qt_main.py",  # Generated automatically.
    "leo/plugins/test/failed_import.py",  # Contains unused import of 'xyzzy'.
    "leo/plugins/pygeotag/pygeotag.py",  # Contains strange errors.
    "leo/test/scriptFile.py",  # Generated by *user* scripts.
    "leo/test/beautify_node.py",  # Generated from user scripts.
    "leo/unittests/py3_test_grammar.py",  # Contains many errors on purpose.
]  # fmt: skip
    
#@-leo
