# Config for `ty`: https://github.com/astral-sh/ty
# See the `ty` job in .github/workflows/ci.yml

[src]
include = ["leo"]
exclude = [
    # Mirrors the [mypy] exclude list in .mypy.ini.
    "leo/doc",
    "leo/dist",
    "leo/editpane",
    "leo/examples",
    "leo/extensions",
    "leo/external",
    "leo/modes",
    "leo/plugins/obsolete",
    "leo/scripts",
    "leo/themes",
    "leo/unittests",
    "leo/www",
    "leo/plugins/QNCalendarWidget.py",
    "leo/plugins/freewin.py",
    "leo/plugins/xdb_pane.py",
    "leo/test/scriptFile.py",
    "leo/plugins/beautify_node.py",
    "leo/plugins/viewrendered3*",
    "leo/plugins/leo_pdf*",
    "leo/plugins/leo_to_rtf*",
    "leo/plugins/mnplugins*",
    "leo/plugins/mod_speedups*",
    "leo/plugins/settings_finder*",
    "leo/plugins/stickynotes_plus*",
    "leo/plugins/qt_main*",
]

[rules]

# Like `disable_error_code=attr-defined` in .mypy.ini.
unresolved-attribute = "ignore"

# Like `ignore_missing_imports = True` in .mypy.ini.
unresolved-import = "ignore"

# Don't warn about unused suppressions.
# They can arise because of environmental differences.
unused-type-ignore-comment = "ignore"

# Ignore warnings about overridden methods.
invalid-method-override = "ignore"
