<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo (http://leoeditor.com/leo_toc.html) -->
<?xml-stylesheet ekr_test?>
<leo_file xmlns:leo="http://www.leo-editor.org/2011/leo" >
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5" body_secondary_ratio="0.5">
	<global_window_position top="50" left="50" height="500" width="700"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="tbrown.20131122094200.3532"><vh>README</vh></v>
<v t="tbrown.20131122094200.3827"><vh>leo_dark theme 0</vh>
<v t="tbrown.20131122094200.3828"><vh>README</vh></v>
<v t="tbrown.20131122094200.3829"><vh>README - theme developers</vh></v>
<v t="tbrown.20131122094200.3830"><vh>@string color_theme = leo_dark_0</vh></v>
<v t="tbrown.20131122094200.3831"><vh>@bool color_theme_is_dark = True</vh></v>
<v t="tbrown.20131122094200.3832"><vh>@bk config 2013-11-20 12:14:30</vh></v>
<v t="tbrown.20131122094200.3833" a="E"><vh>Settings for theme</vh>
<v t="tbrown.20131122094200.3834"><vh>definitions</vh>
<v t="tbrown.20131122094200.3835"><vh>@color solarized-base03 = #002b36</vh></v>
<v t="tbrown.20131122094200.3836"><vh>@color solarized-base02 = #073642</vh></v>
<v t="tbrown.20131122094200.3837"><vh>@color solarized-base01 = #586e75</vh></v>
<v t="tbrown.20131122094200.3838"><vh>@color solarized-base00 = #657b83</vh></v>
<v t="tbrown.20131122094200.3839"><vh>@color solarized-base0 = #839496</vh></v>
<v t="tbrown.20131122094200.3840"><vh>@color solarized-base1 = #93a1a1</vh></v>
<v t="tbrown.20131122094200.3841"><vh>@color solarized-base2 = #eee8d5</vh></v>
<v t="tbrown.20131122094200.3842"><vh>@color solarized-base3 = #fdf6e3</vh></v>
<v t="tbrown.20131122094200.3843"><vh>@color solarized-yellow = #b58900</vh></v>
<v t="tbrown.20131122094200.3844"><vh>@color solarized-orange = #cb4b16</vh></v>
<v t="tbrown.20131122094200.3845"><vh>@color solarized-red = #dc322f</vh></v>
<v t="tbrown.20131122094200.3846"><vh>@color solarized-magenta = #d33682</vh></v>
<v t="tbrown.20131122094200.3847"><vh>@color solarized-violet = #6c71c4</vh></v>
<v t="tbrown.20131122094200.3848"><vh>@color solarized-blue = #268bd2</vh></v>
<v t="tbrown.20131122094200.3849"><vh>@color solarized-cyan = #2aa198</vh></v>
<v t="tbrown.20131122094200.3850"><vh>@color solarized-green = #859900</vh></v>
</v>
<v t="tbrown.20131122094200.3851"><vh>colors</vh>
<v t="tbrown.20131122094200.3852"><vh>@color text-foreground = @solarized-base0</vh></v>
<v t="tbrown.20131122094200.3853"><vh>@color text-foreground-bright = @solarized-base2</vh></v>
<v t="tbrown.20131122094200.3854"><vh>@color text-background = @solarized-base03</vh></v>
<v t="tbrown.20131122094200.3855"><vh>@color text-background-bright = @solarized-base02</vh></v>
<v t="tbrown.20131122094200.3856"><vh>@color splitter-bg = @solarized-base01</vh></v>
<v t="tbrown.20131122094200.3857"><vh>@color splitter-hover-bg = @solarized-violet</vh></v>
<v t="tbrown.20131122094200.3858"><vh>@color button-hover-bg = @solarized-base01</vh></v>
<v t="tbrown.20131122094200.3859"><vh>@color button-hover-fg = @solarized-base03</vh></v>
<v t="tbrown.20131122094200.3860"><vh>@color log_text_foreground_color = #93a1a1</vh></v>
<v t="tbrown.20131122094200.3861"><vh>@color log_text_background_color = #073642</vh></v>
<v t="tbrown.20131122094200.3862"><vh>@color log_error_color = #dc322f</vh></v>
<v t="tbrown.20131122094200.3863"><vh>@color log_warning_color = #268bd2</vh></v>
<v t="tbrown.20131122094200.3864"><vh>@color minibuffer_foreground_color = @solarized-yellow</vh></v>
<v t="tbrown.20131122094200.3865"><vh>@color minibuffer_background_color = @solarized-base03</vh></v>
<v t="tbrown.20131122094200.3866"><vh>@color minibuffer_warning_color = @solarized-base02</vh></v>
<v t="tbrown.20131122094200.3867"><vh>@color minibuffer_error_color = @solarized-red</vh></v>
</v>
<v t="tbrown.20131122094200.3868"><vh>fonts</vh>
<v t="tbrown.20131122094200.3869"><vh>@string font-family = Courier, Droid Sans Mono, DejaVu Sans Mono</vh></v>
<v t="tbrown.20131122094200.3870"><vh>@string font-family = Droid Sans Mono, DejaVu Sans Mono</vh></v>
<v t="tbrown.20131122094200.3871"><vh>@string font-family-tree = @font-family</vh></v>
<v t="tbrown.20131122094200.3872"><vh>@string font-family-body = @font-family</vh></v>
<v t="tbrown.20131122094200.3873"><vh>@string font-family-log = @font-family</vh></v>
<v t="tbrown.20131122094200.3874"><vh>@string font-size-body = 20px</vh></v>
<v t="tbrown.20131122094200.3875"><vh>@string font-size-tree = 18px</vh></v>
<v t="tbrown.20131122094200.3876"><vh>@string font-size-log = 16px</vh></v>
</v>
<v t="tbrown.20131122094200.3877"><vh>border</vh>
<v t="tbrown.20131122094200.3878"><vh>@string focused-border-style = none</vh></v>
<v t="tbrown.20131122094200.3879"><vh>@string focused-border-width = 3px</vh></v>
<v t="tbrown.20131122094200.3880"><vh>@string focused-border-focus-color = cyan</vh></v>
<v t="tbrown.20131122094200.3881"><vh>@string focused-border-hover-color = red</vh></v>
<v t="tbrown.20131122094200.3882"><vh>@string focused-border-unfocus-color = white</vh></v>
</v>
<v t="tbrown.20131122094200.3883"><vh>gradients</vh>
<v t="tbrown.20131122094200.3884"><vh>@string bg-gradient = qlineargradient( x1:0 y1:0, x2:0 y2:1, stop:0.1 @text-background-bright, stop:0.4 @text-background, stop:0.6 @text-background, stop:0.9 @text-background-bright)</vh></v>
<v t="tbrown.20131122094200.3885"><vh>@string bg-gradient-hover = qlineargradient( x1:0 y1:0, x2:0 y2:1, stop:0.1 @solarized-base00, stop:0.4 @solarized-base0, stop:0.6 @solarized-base0, stop:0.9 @solarized-base00)</vh></v>
</v>
</v>
<v t="tbrown.20131122094200.3886" a="E"><vh>stylesheet &amp; source</vh>
<v t="tbrown.20131122094200.3887" a="E"><vh>Color styles</vh>
<v t="tbrown.20131122094200.3888"><vh>base</vh></v>
<v t="tbrown.20131122094200.3889"><vh>body editor</vh></v>
<v t="tbrown.20131122094200.3890"><vh>tree</vh></v>
<v t="tbrown.20131122094200.3891"><vh>log</vh></v>
<v t="tbrown.20131122094200.3892"><vh>mini-buffer &amp; status</vh></v>
<v t="tbrown.20131122094200.3893"><vh>line edit</vh></v>
<v t="tbrown.20131122094200.3894"><vh>labels</vh></v>
<v t="tbrown.20131122094200.3895"><vh>buttons</vh></v>
<v t="tbrown.20131122094200.3896"><vh>tab bar</vh></v>
<v t="tbrown.20131122094200.3897"><vh>menus</vh></v>
<v t="tbrown.20131122094200.3898"><vh>scrollbar</vh></v>
<v t="tbrown.20131122094200.3899"><vh>splitters</vh></v>
<v t="tbrown.20131122094200.3900"><vh>minibuffer</vh></v>
</v>
<v t="tbrown.20131122094200.3901"><vh>Non-color styles (fonts etc.)</vh>
<v t="tbrown.20131122094200.3902"><vh>border</vh></v>
<v t="tbrown.20131122094200.3903"><vh>controls, default font size</vh></v>
<v t="tbrown.20131122094200.3904"><vh>body editor</vh></v>
<v t="tbrown.20131122094200.3905"><vh>tab bar</vh></v>
<v t="tbrown.20131122094200.3906"><vh>scroll bars</vh></v>
<v t="tbrown.20131122094200.3907"><vh>tree</vh></v>
<v t="tbrown.20131122094200.3908"><vh>log</vh></v>
<v t="tbrown.20131122094200.3909"><vh>mini-buffer &amp; status</vh></v>
</v>
<v t="tbrown.20131122094200.3910"><vh>@ignore Spare parts</vh></v>
<v t="tbrown.20131122094200.3911"><vh>@@data qt-gui-plugin-style-sheet</vh></v>
<v t="tbrown.20131122094200.3912"><vh>@@data qt-gui-plugin-style-sheet</vh></v>
<v t="tbrown.20131122094200.3913"><vh>@@data qt-gui-plugin-style-sheet</vh></v>
<v t="tbrown.20131122094200.3914"><vh>@@data qt-gui-plugin-style-sheet</vh></v>
<v t="tbrown.20131122094200.3915"><vh>@@data qt-gui-plugin-style-sheet</vh></v>
<v t="tbrown.20131122094200.3916"><vh>@@data qt-gui-plugin-style-sheet</vh></v>
<v t="tbrown.20131122094200.3917"><vh>@data qt-gui-plugin-style-sheet</vh></v>
</v>
<v t="tbrown.20131122094200.3918" a="E"><vh>Solarized colorizing settings</vh>
<v t="tbrown.20131122094200.3919"><vh>Solarized colors (Reference)</vh></v>
<v t="tbrown.20131122094200.3920" a="E"><vh>Default colors, used if no language-specific color are in effect</vh>
<v t="tbrown.20131122094200.3921"><vh>@color blank_color = grey</vh></v>
<v t="tbrown.20131122094200.3922"><vh>@color tab_color = red</vh></v>
<v t="tbrown.20131122094200.3923"><vh>@color label_color = red</vh></v>
<v t="tbrown.20131122094200.3924"><vh>@color keyword1_color = #268bd2</vh></v>
<v t="tbrown.20131122094200.3925"><vh>@color keyword2_color = #268bd2</vh></v>
<v t="tbrown.20131122094200.3926"><vh>@color keyword3_color = #268bd2</vh></v>
<v t="tbrown.20131122094200.3927"><vh>@color keyword4_color = #268bd2</vh></v>
<v t="tbrown.20131122094200.3928"><vh>@color literal1_color = #859900</vh></v>
<v t="tbrown.20131122094200.3929"><vh>@color literal2_color = #859900</vh></v>
<v t="tbrown.20131122094200.3930"><vh>@color literal3_color = #859900</vh></v>
<v t="tbrown.20131122094200.3931"><vh>@color literal4_color = #859900</vh></v>
<v t="tbrown.20131122094200.3932"><vh>@color markup_color = #2aa198</vh></v>
<v t="tbrown.20131122094200.3933"><vh>@color comment1_color = #d33682</vh></v>
<v t="tbrown.20131122094200.3934"><vh>@color comment2_color = #d33682</vh></v>
<v t="tbrown.20131122094200.3935"><vh>@color comment3_color = #d33682</vh></v>
<v t="tbrown.20131122094200.3936"><vh>@color comment4_color = #d33682</vh></v>
<v t="tbrown.20131122094200.3937"><vh>@color operator_color = None</vh></v>
</v>
</v>
<v t="tbrown.20131122094200.3938"><vh>@color plain null color = #6c71c4</vh></v>
<v t="tbrown.20131122094200.3939" a="E"><vh>Body pane colors</vh>
<v t="tbrown.20131122094200.3940"><vh>@@color body_text_background_color = #002b36</vh></v>
<v t="tbrown.20131122094200.3941"><vh>@@color unselected_body_bg_color = #002b36</vh></v>
<v t="tbrown.20131122094200.3942"><vh>@@color unselected_body_fg_color = #839496</vh></v>
<v t="tbrown.20131122094200.3943"><vh>@@color body_text_foreground_color = #839496</vh></v>
<v t="tbrown.20131122094200.3944"><vh>@@color insert_mode_bg_color = #002b36</vh></v>
<v t="tbrown.20131122094200.3945"><vh>@@color insert_mode_fg_color = #839496</vh></v>
</v>
<v t="tbrown.20131122094200.3946" a="E"><vh>Outline pane colors</vh>
<v t="tbrown.20131122094200.3947"><vh>@@color headline_text_unselected_background_color = #ffffff</vh></v>
<v t="tbrown.20131122094200.3948"><vh>@@color headline_text_unselected_foreground_color = None</vh></v>
<v t="tbrown.20131122094200.3949"><vh>@@color headline_text_selected_background_color = #586e75</vh></v>
<v t="tbrown.20131122094200.3950"><vh>@@color headline_text_selected_foreground_color = #002b36</vh></v>
<v t="tbrown.20131122094200.3951"><vh>@@color headline_text_editing_background_color = None</vh></v>
<v t="tbrown.20131122094200.3952"><vh>@@color headline_text_editing_foreground_color = None</vh></v>
<v t="tbrown.20131122094200.3953"><vh>@@color headline_text_editing_selection_foreground_color = None</vh></v>
<v t="tbrown.20131122094200.3954"><vh>@@color headline_text_editing_selection_background_color = None</vh></v>
<v t="tbrown.20131122094200.3955"><vh>@@color outline_pane_background_color = #ffffff</vh></v>
</v>
<v t="tbrown.20131122094200.3956" a="E"><vh>Log pane colors</vh>
<v t="tbrown.20131122094200.3957"><vh>@@color log_pane_background_color = #002b36</vh></v>
<v t="tbrown.20131122094200.3958"><vh>@@color log_pane_Find_tab_background_color = #d6c7d3</vh></v>
<v t="tbrown.20131122094200.3959"><vh>@@color log_pane_Spell_tab_background_color = MistyRose1</vh></v>
</v>
<v t="tbrown.20131122094200.3960"><vh>@color url_color = #6c71c4</vh></v>
</v>
<v t="tbrown.20131122094200.3612"><vh>leo_dark theme 1</vh>
<v t="tbrown.20131122094200.3613"><vh>README</vh></v>
<v t="tbrown.20131122094200.3614"><vh>@string color_theme = leo_dark_0</vh></v>
<v t="tbrown.20131122094200.3615"><vh>@bool color_theme_is_dark = True</vh></v>
<v t="tbrown.20131122094200.3616"><vh>stylesheet &amp; source</vh>
<v t="tbrown.20131122094200.3617"><vh>config</vh></v>
<v t="tbrown.20131122094200.3618"><vh>Color styles</vh>
<v t="tbrown.20131122094200.3619"><vh>ase</vh></v>
<v t="tbrown.20131122094200.3620"><vh>body editor</vh></v>
<v t="tbrown.20131122094200.3621"><vh>tree</vh></v>
<v t="tbrown.20131122094200.3622"><vh>log</vh></v>
<v t="tbrown.20131122094200.3623"><vh>mini-buffer &amp; status</vh></v>
<v t="tbrown.20131122094200.3624"><vh>line edit</vh></v>
<v t="tbrown.20131122094200.3625"><vh>labels</vh></v>
<v t="tbrown.20131122094200.3626"><vh>buttons</vh></v>
<v t="tbrown.20131122094200.3627"><vh>tab bar</vh></v>
<v t="tbrown.20131122094200.3628"><vh>menus</vh></v>
<v t="tbrown.20131122094200.3629"><vh>splitters</vh></v>
</v>
<v t="tbrown.20131122094200.3630"><vh>Non-color styles (fonts etc.)</vh>
<v t="tbrown.20131122094200.3631"><vh>controls, default font size</vh></v>
<v t="tbrown.20131122094200.3632"><vh>body editor</vh></v>
<v t="tbrown.20131122094200.3633"><vh>tab bar</vh></v>
<v t="tbrown.20131122094200.3634"><vh>scroll bars</vh></v>
<v t="tbrown.20131122094200.3635"><vh>tree</vh></v>
<v t="tbrown.20131122094200.3636"><vh>log</vh></v>
<v t="tbrown.20131122094200.3637"><vh>mini-buffer &amp; status</vh></v>
</v>
<v t="tbrown.20131122094200.3638"><vh>@ignore Spare parts</vh>
<v t="tbrown.20131122094200.3639"><vh>@ignore border</vh></v>
</v>
<v t="tbrown.20131122094200.3640"><vh>@@data qt-gui-plugin-style-sheet</vh></v>
<v t="tbrown.20131122094200.3641"><vh>@@data qt-gui-plugin-style-sheet</vh></v>
<v t="tbrown.20131122094200.3642"><vh>@@data qt-gui-plugin-style-sheet</vh></v>
<v t="tbrown.20131122094200.3643"><vh>@data qt-gui-plugin-style-sheet</vh></v>
</v>
<v t="tbrown.20131122094200.3644"><vh>Solarized colorizing settings</vh>
<v t="tbrown.20131122094200.3645"><vh>Solarized colors (Reference)</vh></v>
<v t="tbrown.20131122094200.3646"><vh>Default colors, used if no language-specific color are in effect</vh>
<v t="tbrown.20131122094200.3647"><vh>@color blank_color = grey</vh></v>
<v t="tbrown.20131122094200.3648"><vh>@color tab_color = red</vh></v>
<v t="tbrown.20131122094200.3649"><vh>@color label_color = red</vh></v>
<v t="tbrown.20131122094200.3650"><vh>@color keyword1_color = #268bd2</vh></v>
<v t="tbrown.20131122094200.3651"><vh>@color keyword2_color = #268bd2</vh></v>
<v t="tbrown.20131122094200.3652"><vh>@color keyword3_color = #268bd2</vh></v>
<v t="tbrown.20131122094200.3653"><vh>@color keyword4_color = #268bd2</vh></v>
<v t="tbrown.20131122094200.3654"><vh>@color literal1_color = #859900</vh></v>
<v t="tbrown.20131122094200.3655"><vh>@color literal2_color = #859900</vh></v>
<v t="tbrown.20131122094200.3656"><vh>@color literal3_color = #859900</vh></v>
<v t="tbrown.20131122094200.3657"><vh>@color literal4_color = #859900</vh></v>
<v t="tbrown.20131122094200.3658"><vh>@color markup_color = #2aa198</vh></v>
<v t="tbrown.20131122094200.3659"><vh>@color comment1_color = #d33682</vh></v>
<v t="tbrown.20131122094200.3660"><vh>@color comment2_color = #d33682</vh></v>
<v t="tbrown.20131122094200.3661"><vh>@color comment3_color = #d33682</vh></v>
<v t="tbrown.20131122094200.3662"><vh>@color comment4_color = #d33682</vh></v>
<v t="tbrown.20131122094200.3663"><vh>@color operator_color = None</vh></v>
</v>
</v>
<v t="tbrown.20131122094200.3664"><vh>@color plain null color = #6c71c4</vh></v>
<v t="tbrown.20131122094200.3665"><vh>Body pane colors</vh>
<v t="tbrown.20131122094200.3666"><vh>@color body_text_background_color = #002b36</vh></v>
<v t="tbrown.20131122094200.3667"><vh>@color unselected_body_bg_color = #002b36</vh></v>
<v t="tbrown.20131122094200.3668"><vh>@color unselected_body_fg_color = #839496</vh></v>
<v t="tbrown.20131122094200.3669"><vh>@color body_text_foreground_color = #839496</vh></v>
<v t="tbrown.20131122094200.3670"><vh>@color insert_mode_bg_color = #002b36</vh></v>
<v t="tbrown.20131122094200.3671"><vh>@color insert_mode_fg_color = #839496</vh></v>
</v>
<v t="tbrown.20131122094200.3672"><vh>Outline pane colors</vh>
<v t="tbrown.20131122094200.3673"><vh>@color headline_text_unselected_background_color = #ffffff</vh></v>
<v t="tbrown.20131122094200.3674"><vh>@color headline_text_unselected_foreground_color = None</vh></v>
<v t="tbrown.20131122094200.3675"><vh>@color headline_text_selected_background_color = #586e75</vh></v>
<v t="tbrown.20131122094200.3676"><vh>@color headline_text_selected_foreground_color = #002b36</vh></v>
<v t="tbrown.20131122094200.3677"><vh>@color headline_text_editing_background_color = None</vh></v>
<v t="tbrown.20131122094200.3678"><vh>@color headline_text_editing_foreground_color = None</vh></v>
<v t="tbrown.20131122094200.3679"><vh>@color headline_text_editing_selection_foreground_color = None</vh></v>
<v t="tbrown.20131122094200.3680"><vh>@color headline_text_editing_selection_background_color = None</vh></v>
<v t="tbrown.20131122094200.3681"><vh>@color outline_pane_background_color = #ffffff</vh></v>
</v>
<v t="tbrown.20131122094200.3682"><vh>Log pane colors</vh>
<v t="tbrown.20131122094200.3683"><vh>@color log_error_color = #dc322f</vh></v>
<v t="tbrown.20131122094200.3684"><vh>@color log_warning_color = #268bd2</vh></v>
<v t="tbrown.20131122094200.3685"><vh>@color log_text_foreground_color = #93a1a1</vh></v>
<v t="tbrown.20131122094200.3686"><vh>@color log_text_background_color = #073642</vh></v>
<v t="tbrown.20131122094200.3687"><vh>@color log_pane_background_color = #002b36</vh></v>
<v t="tbrown.20131122094200.3688"><vh>@color log_pane_Find_tab_background_color = #d6c7d3</vh></v>
<v t="tbrown.20131122094200.3689"><vh>@color log_pane_Spell_tab_background_color = MistyRose1</vh></v>
</v>
<v t="tbrown.20131122094200.3690"><vh>@color minibuffer_background_color = #073642</vh></v>
<v t="tbrown.20131122094200.3691"><vh>@color minibuffer_foreground_color = #b58900</vh></v>
<v t="tbrown.20131122094200.3692"><vh>@color url_color = #6c71c4</vh></v>
</v>
</vnodes>
<tnodes>
<t tx="tbrown.20131122094200.3532">@language rest

Enable themes by copying their nodes into your myLeoSettings.leo file,
as the last node under the @settings node. You may need to move any
existing `@color` and `@data qt-gui-plugin-style-sheet` nodes out of the
way, i.e. delete them or collect them under a top level node of their
own so they're no longer descendants of @settings.

See README node in individual themes for more information.</t>
<t tx="tbrown.20131122094200.3612">Sublime Text 2-like dark theme.

NOTE - NEEDS UPDATING TO Nov-2013 theme system

Copy into mySettings.leo under @settings to enable theme

Place this node at the *bottom* of the list of nodes under
@settings to ensure it overrides other style settings.

</t>
<t tx="tbrown.20131122094200.3613">@language rest

See parent nodes for installation notes.

A theme's folder should be in either .../leo/themes or
$HOME/.leo/themes.
NOTE: to use with a non-dark desktop theme, switch '@ignore base' below
      to 'base' and `run-script` on the `stylesheet &amp; source` node.

A theme is a combination of @color settings, a stylesheet, and,
optionally, some icons. Icons go in &lt;theme_dir&gt;/Icons.

*IMPORTANT:* to change the stylesheet, edit the Leo tree under the
`stylesheet &amp; source` node below, not the 
`@data qt-gui-plugin-style-sheet` node itself.

Then select the `stylesheet &amp; source` node and click the `run-script`
button. This creates a new `@data qt-gui-plugin-style-sheet` node and
disables the old one by adding `@@data`.

Finally, select the new `@data qt-gui-plugin-style-sheet` node and click
the `set-style` button to see the style without re-loading.

Within the `stylesheet &amp; source` tree you can reference Leo color
settings (without the hyphens/underscores, so log_background_color is
@logbackgroundcolor) and constants / macros defined within the
`stylesheet &amp; source` tree itself, see the `config` node.

Documentation of Qt stylesheets at 
http://qt-project.org/doc/qt-4.8/stylesheet-reference.html#list-of-stylable-widgets

Valid color names: http://www.w3.org/TR/SVG/types.html#ColorKeywords
</t>
<t tx="tbrown.20131122094200.3614"></t>
<t tx="tbrown.20131122094200.3615"></t>
<t tx="tbrown.20131122094200.3616">@language css  # (this node is python, descendants are css)

# To generate the stylesheet @data from this source,
# use `run-script` on this node.
#
# Don't forget to delete any previous '@data qt-gui-plugin-style-sheet' nodes.

#X cp = g.findNodeAnywhere(c, 'stylesheet &amp; source')
cp = c.p

import datetime
nd = cp.insertAsLastChild()
unl = cp.get_UNL()+'--&gt;'
nd.h = '@ignore'  # removed after processing
nd.b = "/*\n  AUTOMATICALLY GENERATED FROM:\n  %s\n  %s\n*/\n\n" % (
    cp.get_UNL(with_proto=True),
    datetime.datetime.now().strftime('%Y-%m-%d %H:%M'),
)

for i in cp.subtree():
    src = i.get_UNL().replace(unl, '')
    if i.h.startswith('@data '):
        i.h = '@'+i.h
    if ('@ignore' in src) or ('@data' in src):
        continue
    nd.b += "/*### %s %s*/\n%s\n\n" % (
        src, '#'*(70-len(src)),
        i.b.strip()
    )
    
nd.h = '@data qt-gui-plugin-style-sheet'

# make the style active
g.app.gui.frameFactory.masterFrame.setStyleSheet(
    g.expand_css_constants(nd.b))

# c.selectPosition(nd)

c.redraw()</t>
<t tx="tbrown.20131122094200.3617">/*

This *comment* is parsed to extract constants (macros) defined below.

constants:

@solarized-base03 = #272822
@solarized-base02 = #272822
@solarized-base01 = #586e75
@solarized-base00 = #657b83
@solarized-base0 = #839496
@solarized-base1 = #CFBFAD
@solarized-base2 = #eee8d5
@solarized-base3 = #fdf6e3

@solarized-yellow = #b58900
@solarized-orange = #cb4b16
@solarized-red = #dc322f
@solarized-magenta = #d33682
@solarized-violet = #6c71c4
@solarized-blue = #268bd2
@solarized-cyan = #2aa198
@solarized-green = #859900

@text-foreground = @solarized-base0
@text-foreground-bright = @solarized-base2
@text-background = @solarized-base03
@text-background-bright = @solarized-base02
@splitter-bg = @solarized-base01
@splitter-hover-bg = @solarized-violet
@button-hover-bg = @solarized-base01
@button-hover-fg = @solarized-base03

@bg-gradient = qlineargradient( x1:0 y1:0, x2:0 y2:1, \
    stop:0.1 @text-background-bright, stop:0.4 @text-background, \
    stop:0.6 @text-background, stop:0.9 @text-background-bright)
@bg-gradient-hover = qlineargradient( x1:0 y1:0, x2:0 y2:1, \
    stop:0.1 @solarized-base00, stop:0.4 @solarized-base0, \
    stop:0.6 @solarized-base0, stop:0.9 @solarized-base00)

@font-family = Droid Sans Mono, DejaVu Sans Mono
@font-family-tree = @font-family
@font-family-body = @font-family
@font-family-log = @font-family
@font-size-body = 18px

@focused-border-style = none
@focused-border-width = 3px
@focused-border-focus-color = cyan
@focused-border-unfocus-color = white



</t>
<t tx="tbrown.20131122094200.3618"></t>
<t tx="tbrown.20131122094200.3619">QWidget { color: @solarized-base1; background-color: @solarized-base03; 
  border-color: @solarized-base1; 
}

QScrollBar::add-page, QScrollBar::sub-page {
  background: @solarized-base03; }


QScrollBar::handle { 
  background: @solarized-base01; color: @solarized-base01; }
QScrollBar::handle:hover { 
  background: @solarized-base0; color: @solarized-base0; }
   
/* to make these show up, remove the ::handle style above... bug? */
QScrollBar::add-line, QScrollBar::sub-line { 
  background: @solarized-base01; color: @solarized-base01; }
</t>
<t tx="tbrown.20131122094200.3620">QTextEdit#richTextEdit {
    /* background-color: #ffffff; */ /* #fdf5f5; A kind of pink. */
    background-color: @solarized-base03;
    color: @bodytextforegroundcolor;
    selection-color: @solarized-base03;
    selection-background-color: @solarized-yellow;
}</t>
<t tx="tbrown.20131122094200.3621">QTreeView {
    /* These apply to the selected item, but not to editing items.*/
    /* background-color: #ffffff; */ /* #ffffec; Leo's traditional tree color */
    background-color: @solarized-base03;
    color: @solarized-base0;
    selection-color: @solarized-orange;
    selection-background-color: @solarized-base03;
    show-decoration-selected: 0;
 }
QTreeWidget::selected {
    background: @solarized-green; color: @solarized-base03; 
}
QTreeWidget::active:selected {
    background: @solarized-yellow; color: @solarized-base03; 
}

QTreeView::item:selected {
    background: @solarized-green; color: @solarized-base03; 
}
QTreeView::item:active:selected {
    background: @solarized-yellow; color: @solarized-base03; 
}

/* Headline edit widgets */
QTreeView QLineEdit {
    color: @solarized-base03;
    background-color: @solarized-yellow;
    selection-color: @solarized-base3;
    selection-background-color: @solarized-blue;  
}

</t>
<t tx="tbrown.20131122094200.3622">/* The log panes */
QTextEdit#log-widget {
    /*background-color: #ffffec;*/ /* #f2fdff; */
    background-color: @solarized-base02; /* solarized dark */
    color: @solarized-base0; /* solarized dark */
    selection-color: white;
    selection-background-color: blue;
}</t>
<t tx="tbrown.20131122094200.3623">/* The mini-buffer */
QLineEdit#lineEdit {
    background-color: @solarized-base03;
    color: red; 
    selection-color: red;
    selection-background-color: lightgrey;
}

QLabel#minibufferLabel { color: @solarized-violet; }

QLineEdit#status1 {
    background-color: @solarized-base03;
    border-color: @solarized-base02;
}

QLineEdit#status2 {
    background-color: @solarized-base03;
    border-color: @solarized-base02;
}</t>
<t tx="tbrown.20131122094200.3624">QLineEdit { border: none; padding: 3px; }</t>
<t tx="tbrown.20131122094200.3625">QLabel { color: @solarized-base1; }</t>
<t tx="tbrown.20131122094200.3626">QPushButton { color: @text-foreground; background: @bg-gradient; }
QPushButton:hover { color: @button-hover-fg; background: @bg-gradient-hover; }</t>
<t tx="tbrown.20131122094200.3627">QTabBar::tab { color: @text-foreground; 
background: @bg-gradient; margin-right: 5px; padding: 2px; 
}
QTabBar::tab:selected { color: @solarized-green; } 
QTabBar::tab:hover { background: @bg-gradient-hover; color: @button-hover-fg; }</t>
<t tx="tbrown.20131122094200.3628">QMenu { color: @text-foreground-bright }
QMenuBar::item:hover { color: red; background: white; }
QMenuBar::item { color: @text-foreground; background: @bg-gradient; }
QMenuBar::item:pressed { color: @text-foreground-bright; background: @bg-gradient; }</t>
<t tx="tbrown.20131122094200.3629">QSplitter::handle {
    background-color: @splitter-bg;  /* #CAE1FF;  lightSteelBlue1 */
}
QSplitter::handle:hover {
    background-color: @splitter-hover-bg;  /* #CAE1FF;  lightSteelBlue1 */
}
</t>
<t tx="tbrown.20131122094200.3630"></t>
<t tx="tbrown.20131122094200.3631">QPushButton, QDoubleSpinBox, QSpinBox, QDateEdit, QTimeEdit { border: none; padding: 3px; margin-right: 5px; }

QWidget { font-size: 16px }
</t>
<t tx="tbrown.20131122094200.3632">/* The body pane */
QTextEdit#richTextEdit {
    font-family: @font-family-body;
    /* font-family: Courier New; */
    font-size: @font-size-body;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}
</t>
<t tx="tbrown.20131122094200.3633">QTabBar::tab { 
   margin-right: 5px; padding: 2px; 
}
</t>
<t tx="tbrown.20131122094200.3634">QScrollBar::horizontal {
     height: 7px;
}

QScrollBar::vertical {
     width: 7px;
}</t>
<t tx="tbrown.20131122094200.3635">QTreeWidget {
    /* These apply to the selected item, but not to editing items.*/
    /* font-family: SansSerif; */
    font-family: @font-family-tree;
    font-size: 16px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
 }

/* Headline edit widgets */
QTreeWidget QLineEdit View{
    font-family: @font-family-tree;
    font-size: 16px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */ 
}
</t>
<t tx="tbrown.20131122094200.3636">/* The log panes */
QTextEdit#log-widget {
    /* font-family: Courier New; */
    font-family: @font-family-log;
    font-size: 16px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}</t>
<t tx="tbrown.20131122094200.3637">/* The mini-buffer */
QLineEdit#lineEdit {
    font-family: @font-family;
    font-size: 12px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

QLineEdit#status1 {
    border-width: 1px;
    border-style: solid;
}

QLineEdit#status2 {
    border-width: 1px;
    border-style: solid;
}</t>
<t tx="tbrown.20131122094200.3638">/* START: dark styles for non-dark desktop theme */
/*
QWidget { color: @solarized-base1; background-color: @solarized-base03; 
  border-color: @solarized-base1;
}

QScrollBar::add-page, QScrollBar::sub-page { 
    background: @solarized-base03; }
    
QScrollBar::add-line { background: red; 
  border: 1px solid red ; color: red }
  
QScrollBar::handle { background: @solarized-base01; 
  border: 1px solid @solarized-base02;  }
*/
/* END: dark styles for non-dark desktop theme */


/* 
QSpinBox::up-button { background: @text-background; }
QSpinBox::up-arrow { 
  background: @text-background;
  color: @text-foreground; 
  image: url(:/images/up_arrow.png);
} */



/* needs work
QSpinBox::up-button { background-color: @solarized-base03; }
QSpinBox::up-arrow { background-color: @solarized-base03; color: @solarized-base1; }
*/

QWidget[style_class~='focused_pane'] {
    border-color: orange;
    border-width: 3px;
    border-style: solid;
}
QWidget[style_class~='unfocused_pane'] {
    border-color: blue;
    border-width: 3px;
    border-style: solid;
}


QStackedWidget {
    /* background-color:lightpink; */
    border-color: red;
    padding: 0px;
    /* border-width: 0px; */
    /* background-color: yellow; */
}

QSplitter {
    border-color: white;
    /* background-color: white; */
    border-style: solid;
}




QTextEdit {
    font-family: DejaVu Sans Mono;
    font-size: 16px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}



XXQToolButton {
    /* background-color: #fdf5f5;  A kind of pink. */
    margin: 2px;
    padding; 4px;
    border-width: 2px;
    border-style: solid;
    border-color: darkgrey;
    font-size: 8px;
}

/* QMenuBar works, but not QMenu... */
XXQMenuBar {
    font-family: DejaVu Sans Mono;
    font-size: 12px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

*[name~='preview'] { color: green; }</t>
<t tx="tbrown.20131122094200.3639">/* unneeded alternative active pane highlighting */
QTextEdit#log-widget, LeoQTreeWidget#treeWidget, QTextEdit#richTextEdit { 
  border-style: @focused-border-style;
  border-width: @focused-border-width; 
  border-color: @focused-border-unfocus-color; 
}
QTextEdit:focus#log-widget, LeoQTreeWidget:focus#treeWidget, QTextEdit:focus#richTextEdit { 
  border-style: @focused-border-style;
  border-width: @focused-border-width; 
  border-color: @focused-border-focus-color; 
}
</t>
<t tx="tbrown.20131122094200.3640">/*
  AUTOMATICALLY GENERATED FROM:
  file:///mnt/usr1/usr1/home/tbrown/Package/leo/bzr/leo.repo/zoom2/leo/config/leoSettings.leo#Themes--&gt;leo_dark%20theme%200%20settings--&gt;stylesheet%20&amp;%20source
  2013-04-11 15:58
*/

/*### config ################################################################*/
/*

This *comment* is parsed to extract constants (macros) defined below.

constants:

@solarized-base03 = #002b36
@solarized-base02 = #073642
@solarized-base01 = #586e75
@solarized-base00 = #657b83
@solarized-base0 = #839496
@solarized-base1 = #93a1a1
@solarized-base2 = #eee8d5
@solarized-base3 = #fdf6e3
@solarized-yellow = #b58900
@solarized-orange = #cb4b16
@solarized-red = #dc322f
@solarized-magenta = #d33682
@solarized-violet = #6c71c4
@solarized-blue = #268bd2
@solarized-cyan = #2aa198
@solarized-green = #859900

@text-foreground = @solarized-base0
@text-foreground-bright = @solarized-base2
@text-background = @solarized-base03
@text-background-bright = @solarized-base02
@splitter-bg = @solarized-base01
@splitter-hover-bg = @solarized-violet
@button-hover-bg = @solarized-base01
@button-hover-fg = @solarized-base03

@bg-gradient = qlineargradient( x1:0 y1:0, x2:0 y2:1, \
    stop:0.1 @text-background-bright, stop:0.4 @text-background, \
    stop:0.6 @text-background, stop:0.9 @text-background-bright)
@bg-gradient-hover = qlineargradient( x1:0 y1:0, x2:0 y2:1, \
    stop:0.1 @solarized-base00, stop:0.4 @solarized-base0, \
    stop:0.6 @solarized-base0, stop:0.9 @solarized-base00)

@font-family = Droid Sans Mono, DejaVu Sans Mono
@font-family-tree = @font-family
@font-family-body = @font-family
@font-family-log = @font-family
@font-size-body = 18px

@focused-border-style = none
@focused-border-width = 3px
@focused-border-focus-color = cyan
@focused-border-unfocus-color = white

/*### border ################################################################*/
QTextEdit#log-widget, LeoQTreeWidget#treeWidget, QTextEdit#richTextEdit { 
  border-style: @focused-border-style;
  border-width: @focused-border-width; 
  border-color: @focused-border-unfocus-color; 
}
QTextEdit:focus#log-widget, LeoQTreeWidget:focus#treeWidget, QTextEdit:focus#richTextEdit { 
  border-style: @focused-border-style;
  border-width: @focused-border-width; 
  border-color: @focused-border-focus-color; 
}

/*### Color styles ##########################################################*/


/*### Color styles--&gt;ase ####################################################*/
QWidget { color: @solarized-base1; background-color: @solarized-base03; 
  border-color: @solarized-base1; 
}

QScrollBar::add-page, QScrollBar::sub-page {
  background: @solarized-base03; }


QScrollBar::handle { 
  background: @solarized-base01; color: @solarized-base01; }
QScrollBar::handle:hover { 
  background: @solarized-base0; color: @solarized-base0; }
   
/* to make these show up, remove the ::handle style above... bug? */
QScrollBar::add-line, QScrollBar::sub-line { 
  background: @solarized-base01; color: @solarized-base01; }

/*### Color styles--&gt;body editor ############################################*/
QTextEdit#richTextEdit {
    /* background-color: #ffffff; */ /* #fdf5f5; A kind of pink. */
    background-color: @solarized-base03;
    color: @bodytextforegroundcolor;
    selection-color: @solarized-base03;
    selection-background-color: @solarized-yellow;
}

/*### Color styles--&gt;tree ###################################################*/
QTreeView {
    /* These apply to the selected item, but not to editing items.*/
    /* background-color: #ffffff; */ /* #ffffec; Leo's traditional tree color */
    background-color: @solarized-base03;
    color: @solarized-base0;
    selection-color: @solarized-orange;
    selection-background-color: @solarized-base03;
    show-decoration-selected: 0;
 }
QTreeWidget::selected {
    background: @solarized-green; color: @solarized-base03; 
}
QTreeWidget::active:selected {
    background: @solarized-yellow; color: @solarized-base03; 
}

QTreeView::item:selected {
    background: @solarized-green; color: @solarized-base03; 
}
QTreeView::item:active:selected {
    background: @solarized-yellow; color: @solarized-base03; 
}

/* Headline edit widgets */
QTreeView QLineEdit {
    color: @solarized-base03;
    background-color: @solarized-yellow;
    selection-color: @solarized-base3;
    selection-background-color: @solarized-blue;  
}

/*### Color styles--&gt;log ####################################################*/
/* The log panes */
QTextEdit#log-widget {
    /*background-color: #ffffec;*/ /* #f2fdff; */
    background-color: @solarized-base02; /* solarized dark */
    color: @solarized-base0; /* solarized dark */
    selection-color: white;
    selection-background-color: blue;
}

/*### Color styles--&gt;mini-buffer &amp; status ###################################*/
/* The mini-buffer */
QLineEdit#lineEdit {
    background-color: @solarized-base03;
    color: red; 
    selection-color: red;
    selection-background-color: lightgrey;
}

QLabel#minibufferLabel { color: @solarized-violet; }

QLineEdit#status1 {
    background-color: @solarized-base03;
    border-color: @solarized-base02;
}

QLineEdit#status2 {
    background-color: @solarized-base03;
    border-color: @solarized-base02;
}

/*### Color styles--&gt;line edit ##############################################*/
QLineEdit { border: none; padding: 3px; }

/*### Color styles--&gt;labels #################################################*/
QLabel { color: @solarized-base1; }

/*### Color styles--&gt;buttons ################################################*/
QPushButton { color: @text-foreground; background: @bg-gradient; }
QPushButton:hover { color: @button-hover-fg; background: @bg-gradient-hover; }

/*### Color styles--&gt;tab bar ################################################*/
QTabBar::tab { color: @text-foreground; 
background: @bg-gradient; margin-right: 5px; padding: 2px; 
}
QTabBar::tab:selected { color: @solarized-green; } 
QTabBar::tab:hover { background: @bg-gradient-hover; color: @button-hover-fg; }

/*### Color styles--&gt;menus ##################################################*/
QMenu { color: @text-foreground-bright }
QMenuBar::item:hover { color: red; background: white; }
QMenuBar::item { color: @text-foreground; background: @bg-gradient; }
QMenuBar::item:pressed { color: @text-foreground-bright; background: @bg-gradient; }

/*### Color styles--&gt;splitters ##############################################*/
QSplitter::handle {
    background-color: @splitter-bg;  /* #CAE1FF;  lightSteelBlue1 */
}
QSplitter::handle:hover {
    background-color: @splitter-hover-bg;  /* #CAE1FF;  lightSteelBlue1 */
}

/*### Non-color styles (fonts etc.) #########################################*/


/*### Non-color styles (fonts etc.)--&gt;controls, default font size ###########*/
QPushButton, QDoubleSpinBox, QSpinBox, QDateEdit, QTimeEdit { border: none; padding: 3px; margin-right: 5px; }

QWidget { font-size: 16px }

/*### Non-color styles (fonts etc.)--&gt;body editor ###########################*/
/* The body pane */
QTextEdit#richTextEdit {
    font-family: @font-family-body;
    /* font-family: Courier New; */
    font-size: @font-size-body;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

/*### Non-color styles (fonts etc.)--&gt;tab bar ###############################*/
QTabBar::tab { 
   margin-right: 5px; padding: 2px; 
}

/*### Non-color styles (fonts etc.)--&gt;scroll bars ###########################*/
QScrollBar::horizontal {
     height: 7px;
}

QScrollBar::vertical {
     width: 7px;
}

/*### Non-color styles (fonts etc.)--&gt;tree ##################################*/
QTreeWidget {
    /* These apply to the selected item, but not to editing items.*/
    /* font-family: SansSerif; */
    font-family: @font-family-tree;
    font-size: 16px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
 }

/* Headline edit widgets */
QTreeWidget QLineEdit View{
    font-family: @font-family-tree;
    font-size: 16px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */ 
}

/*### Non-color styles (fonts etc.)--&gt;log ###################################*/
/* The log panes */
QTextEdit#log-widget {
    /* font-family: Courier New; */
    font-family: @font-family-log;
    font-size: 16px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/*### Non-color styles (fonts etc.)--&gt;mini-buffer &amp; status ##################*/
/* The mini-buffer */
QLineEdit#lineEdit {
    font-family: @font-family;
    font-size: 12px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

QLineEdit#status1 {
    border-width: 1px;
    border-style: solid;
}

QLineEdit#status2 {
    border-width: 1px;
    border-style: solid;
}

</t>
<t tx="tbrown.20131122094200.3641">/*
  AUTOMATICALLY GENERATED FROM:
  file:///home/ville/.leo/myLeoSettings.leo#@settings--&gt;leo_dark%20theme%200%20settings--&gt;stylesheet%20&amp;%20source
  2013-04-16 21:40
*/

/*### config ################################################################*/
/*

This *comment* is parsed to extract constants (macros) defined below.

constants:

@solarized-base03 = #272822
@solarized-base02 = #073642
@solarized-base01 = #586e75
@solarized-base00 = #657b83
@solarized-base0 = #839496
@solarized-base1 = #93a1a1
@solarized-base2 = #eee8d5
@solarized-base3 = #fdf6e3
@solarized-yellow = #b58900
@solarized-orange = #cb4b16
@solarized-red = #dc322f
@solarized-magenta = #d33682
@solarized-violet = #6c71c4
@solarized-blue = #268bd2
@solarized-cyan = #2aa198
@solarized-green = #859900

@text-foreground = @solarized-base0
@text-foreground-bright = @solarized-base2
@text-background = @solarized-base03
@text-background-bright = @solarized-base02
@splitter-bg = @solarized-base01
@splitter-hover-bg = @solarized-violet
@button-hover-bg = @solarized-base01
@button-hover-fg = @solarized-base03

@bg-gradient = qlineargradient( x1:0 y1:0, x2:0 y2:1, \
    stop:0.1 @text-background-bright, stop:0.4 @text-background, \
    stop:0.6 @text-background, stop:0.9 @text-background-bright)
@bg-gradient-hover = qlineargradient( x1:0 y1:0, x2:0 y2:1, \
    stop:0.1 @solarized-base00, stop:0.4 @solarized-base0, \
    stop:0.6 @solarized-base0, stop:0.9 @solarized-base00)

@font-family = Droid Sans Mono, DejaVu Sans Mono
@font-family-tree = @font-family
@font-family-body = @font-family
@font-family-log = @font-family
@font-size-body = 18px

@focused-border-style = none
@focused-border-width = 3px
@focused-border-focus-color = cyan
@focused-border-unfocus-color = white

/*### Color styles ##########################################################*/


/*### Color styles--&gt;ase ####################################################*/
QWidget { color: @solarized-base1; background-color: @solarized-base03; 
  border-color: @solarized-base1; 
}

QScrollBar::add-page, QScrollBar::sub-page {
  background: @solarized-base03; }


QScrollBar::handle { 
  background: @solarized-base01; color: @solarized-base01; }
QScrollBar::handle:hover { 
  background: @solarized-base0; color: @solarized-base0; }
   
/* to make these show up, remove the ::handle style above... bug? */
QScrollBar::add-line, QScrollBar::sub-line { 
  background: @solarized-base01; color: @solarized-base01; }

/*### Color styles--&gt;body editor ############################################*/
QTextEdit#richTextEdit {
    /* background-color: #ffffff; */ /* #fdf5f5; A kind of pink. */
    background-color: @solarized-base03;
    color: @bodytextforegroundcolor;
    selection-color: @solarized-base03;
    selection-background-color: @solarized-yellow;
}

/*### Color styles--&gt;tree ###################################################*/
QTreeView {
    /* These apply to the selected item, but not to editing items.*/
    /* background-color: #ffffff; */ /* #ffffec; Leo's traditional tree color */
    background-color: @solarized-base03;
    color: @solarized-base0;
    selection-color: @solarized-orange;
    selection-background-color: @solarized-base03;
    show-decoration-selected: 0;
 }
QTreeWidget::selected {
    background: @solarized-green; color: @solarized-base03; 
}
QTreeWidget::active:selected {
    background: @solarized-yellow; color: @solarized-base03; 
}

QTreeView::item:selected {
    background: @solarized-green; color: @solarized-base03; 
}
QTreeView::item:active:selected {
    background: @solarized-yellow; color: @solarized-base03; 
}

/* Headline edit widgets */
QTreeView QLineEdit {
    color: @solarized-base03;
    background-color: @solarized-yellow;
    selection-color: @solarized-base3;
    selection-background-color: @solarized-blue;  
}

/*### Color styles--&gt;log ####################################################*/
/* The log panes */
QTextEdit#log-widget {
    /*background-color: #ffffec;*/ /* #f2fdff; */
    background-color: @solarized-base02; /* solarized dark */
    color: @solarized-base0; /* solarized dark */
    selection-color: white;
    selection-background-color: blue;
}

/*### Color styles--&gt;mini-buffer &amp; status ###################################*/
/* The mini-buffer */
QLineEdit#lineEdit {
    background-color: @solarized-base03;
    color: red; 
    selection-color: red;
    selection-background-color: lightgrey;
}

QLabel#minibufferLabel { color: @solarized-violet; }

QLineEdit#status1 {
    background-color: @solarized-base03;
    border-color: @solarized-base02;
}

QLineEdit#status2 {
    background-color: @solarized-base03;
    border-color: @solarized-base02;
}

/*### Color styles--&gt;line edit ##############################################*/
QLineEdit { border: none; padding: 3px; }

/*### Color styles--&gt;labels #################################################*/
QLabel { color: @solarized-base1; }

/*### Color styles--&gt;buttons ################################################*/
QPushButton { color: @text-foreground; background: @bg-gradient; }
QPushButton:hover { color: @button-hover-fg; background: @bg-gradient-hover; }

/*### Color styles--&gt;tab bar ################################################*/
QTabBar::tab { color: @text-foreground; 
background: @bg-gradient; margin-right: 5px; padding: 2px; 
}
QTabBar::tab:selected { color: @solarized-green; } 
QTabBar::tab:hover { background: @bg-gradient-hover; color: @button-hover-fg; }

/*### Color styles--&gt;menus ##################################################*/
QMenu { color: @text-foreground-bright }
QMenuBar::item:hover { color: red; background: white; }
QMenuBar::item { color: @text-foreground; background: @bg-gradient; }
QMenuBar::item:pressed { color: @text-foreground-bright; background: @bg-gradient; }

/*### Color styles--&gt;splitters ##############################################*/
QSplitter::handle {
    background-color: @splitter-bg;  /* #CAE1FF;  lightSteelBlue1 */
}
QSplitter::handle:hover {
    background-color: @splitter-hover-bg;  /* #CAE1FF;  lightSteelBlue1 */
}

/*### Non-color styles (fonts etc.) #########################################*/


/*### Non-color styles (fonts etc.)--&gt;controls, default font size ###########*/
QPushButton, QDoubleSpinBox, QSpinBox, QDateEdit, QTimeEdit { border: none; padding: 3px; margin-right: 5px; }

QWidget { font-size: 16px }

/*### Non-color styles (fonts etc.)--&gt;body editor ###########################*/
/* The body pane */
QTextEdit#richTextEdit {
    font-family: @font-family-body;
    /* font-family: Courier New; */
    font-size: @font-size-body;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

/*### Non-color styles (fonts etc.)--&gt;tab bar ###############################*/
QTabBar::tab { 
   margin-right: 5px; padding: 2px; 
}

/*### Non-color styles (fonts etc.)--&gt;scroll bars ###########################*/
QScrollBar::horizontal {
     height: 7px;
}

QScrollBar::vertical {
     width: 7px;
}

/*### Non-color styles (fonts etc.)--&gt;tree ##################################*/
QTreeWidget {
    /* These apply to the selected item, but not to editing items.*/
    /* font-family: SansSerif; */
    font-family: @font-family-tree;
    font-size: 16px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
 }

/* Headline edit widgets */
QTreeWidget QLineEdit View{
    font-family: @font-family-tree;
    font-size: 16px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */ 
}

/*### Non-color styles (fonts etc.)--&gt;log ###################################*/
/* The log panes */
QTextEdit#log-widget {
    /* font-family: Courier New; */
    font-family: @font-family-log;
    font-size: 16px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/*### Non-color styles (fonts etc.)--&gt;mini-buffer &amp; status ##################*/
/* The mini-buffer */
QLineEdit#lineEdit {
    font-family: @font-family;
    font-size: 12px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

QLineEdit#status1 {
    border-width: 1px;
    border-style: solid;
}

QLineEdit#status2 {
    border-width: 1px;
    border-style: solid;
}

</t>
<t tx="tbrown.20131122094200.3642">/*
  AUTOMATICALLY GENERATED FROM:
  file:///home/ville/.leo/myLeoSettings.leo#@settings--&gt;leo_dark%20theme%200%20settings--&gt;stylesheet%20&amp;%20source
  2013-04-16 21:42
*/

/*### config ################################################################*/
/*

This *comment* is parsed to extract constants (macros) defined below.

constants:

@solarized-base03 = #272822
@solarized-base02 = #073642
@solarized-base01 = #586e75
@solarized-base00 = #657b83
@solarized-base0 = #839496
@solarized-base1 = #CFBFAD
@solarized-base2 = #eee8d5
@solarized-base3 = #fdf6e3

@solarized-yellow = #b58900
@solarized-orange = #cb4b16
@solarized-red = #dc322f
@solarized-magenta = #d33682
@solarized-violet = #6c71c4
@solarized-blue = #268bd2
@solarized-cyan = #2aa198
@solarized-green = #859900

@text-foreground = @solarized-base0
@text-foreground-bright = @solarized-base2
@text-background = @solarized-base03
@text-background-bright = @solarized-base02
@splitter-bg = @solarized-base01
@splitter-hover-bg = @solarized-violet
@button-hover-bg = @solarized-base01
@button-hover-fg = @solarized-base03

@bg-gradient = qlineargradient( x1:0 y1:0, x2:0 y2:1, \
    stop:0.1 @text-background-bright, stop:0.4 @text-background, \
    stop:0.6 @text-background, stop:0.9 @text-background-bright)
@bg-gradient-hover = qlineargradient( x1:0 y1:0, x2:0 y2:1, \
    stop:0.1 @solarized-base00, stop:0.4 @solarized-base0, \
    stop:0.6 @solarized-base0, stop:0.9 @solarized-base00)

@font-family = Droid Sans Mono, DejaVu Sans Mono
@font-family-tree = @font-family
@font-family-body = @font-family
@font-family-log = @font-family
@font-size-body = 18px

@focused-border-style = none
@focused-border-width = 3px
@focused-border-focus-color = cyan
@focused-border-unfocus-color = white

/*### Color styles ##########################################################*/


/*### Color styles--&gt;ase ####################################################*/
QWidget { color: @solarized-base1; background-color: @solarized-base03; 
  border-color: @solarized-base1; 
}

QScrollBar::add-page, QScrollBar::sub-page {
  background: @solarized-base03; }


QScrollBar::handle { 
  background: @solarized-base01; color: @solarized-base01; }
QScrollBar::handle:hover { 
  background: @solarized-base0; color: @solarized-base0; }
   
/* to make these show up, remove the ::handle style above... bug? */
QScrollBar::add-line, QScrollBar::sub-line { 
  background: @solarized-base01; color: @solarized-base01; }

/*### Color styles--&gt;body editor ############################################*/
QTextEdit#richTextEdit {
    /* background-color: #ffffff; */ /* #fdf5f5; A kind of pink. */
    background-color: @solarized-base03;
    color: @bodytextforegroundcolor;
    selection-color: @solarized-base03;
    selection-background-color: @solarized-yellow;
}

/*### Color styles--&gt;tree ###################################################*/
QTreeView {
    /* These apply to the selected item, but not to editing items.*/
    /* background-color: #ffffff; */ /* #ffffec; Leo's traditional tree color */
    background-color: @solarized-base03;
    color: @solarized-base0;
    selection-color: @solarized-orange;
    selection-background-color: @solarized-base03;
    show-decoration-selected: 0;
 }
QTreeWidget::selected {
    background: @solarized-green; color: @solarized-base03; 
}
QTreeWidget::active:selected {
    background: @solarized-yellow; color: @solarized-base03; 
}

QTreeView::item:selected {
    background: @solarized-green; color: @solarized-base03; 
}
QTreeView::item:active:selected {
    background: @solarized-yellow; color: @solarized-base03; 
}

/* Headline edit widgets */
QTreeView QLineEdit {
    color: @solarized-base03;
    background-color: @solarized-yellow;
    selection-color: @solarized-base3;
    selection-background-color: @solarized-blue;  
}

/*### Color styles--&gt;log ####################################################*/
/* The log panes */
QTextEdit#log-widget {
    /*background-color: #ffffec;*/ /* #f2fdff; */
    background-color: @solarized-base02; /* solarized dark */
    color: @solarized-base0; /* solarized dark */
    selection-color: white;
    selection-background-color: blue;
}

/*### Color styles--&gt;mini-buffer &amp; status ###################################*/
/* The mini-buffer */
QLineEdit#lineEdit {
    background-color: @solarized-base03;
    color: red; 
    selection-color: red;
    selection-background-color: lightgrey;
}

QLabel#minibufferLabel { color: @solarized-violet; }

QLineEdit#status1 {
    background-color: @solarized-base03;
    border-color: @solarized-base02;
}

QLineEdit#status2 {
    background-color: @solarized-base03;
    border-color: @solarized-base02;
}

/*### Color styles--&gt;line edit ##############################################*/
QLineEdit { border: none; padding: 3px; }

/*### Color styles--&gt;labels #################################################*/
QLabel { color: @solarized-base1; }

/*### Color styles--&gt;buttons ################################################*/
QPushButton { color: @text-foreground; background: @bg-gradient; }
QPushButton:hover { color: @button-hover-fg; background: @bg-gradient-hover; }

/*### Color styles--&gt;tab bar ################################################*/
QTabBar::tab { color: @text-foreground; 
background: @bg-gradient; margin-right: 5px; padding: 2px; 
}
QTabBar::tab:selected { color: @solarized-green; } 
QTabBar::tab:hover { background: @bg-gradient-hover; color: @button-hover-fg; }

/*### Color styles--&gt;menus ##################################################*/
QMenu { color: @text-foreground-bright }
QMenuBar::item:hover { color: red; background: white; }
QMenuBar::item { color: @text-foreground; background: @bg-gradient; }
QMenuBar::item:pressed { color: @text-foreground-bright; background: @bg-gradient; }

/*### Color styles--&gt;splitters ##############################################*/
QSplitter::handle {
    background-color: @splitter-bg;  /* #CAE1FF;  lightSteelBlue1 */
}
QSplitter::handle:hover {
    background-color: @splitter-hover-bg;  /* #CAE1FF;  lightSteelBlue1 */
}

/*### Non-color styles (fonts etc.) #########################################*/


/*### Non-color styles (fonts etc.)--&gt;controls, default font size ###########*/
QPushButton, QDoubleSpinBox, QSpinBox, QDateEdit, QTimeEdit { border: none; padding: 3px; margin-right: 5px; }

QWidget { font-size: 16px }

/*### Non-color styles (fonts etc.)--&gt;body editor ###########################*/
/* The body pane */
QTextEdit#richTextEdit {
    font-family: @font-family-body;
    /* font-family: Courier New; */
    font-size: @font-size-body;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

/*### Non-color styles (fonts etc.)--&gt;tab bar ###############################*/
QTabBar::tab { 
   margin-right: 5px; padding: 2px; 
}

/*### Non-color styles (fonts etc.)--&gt;scroll bars ###########################*/
QScrollBar::horizontal {
     height: 7px;
}

QScrollBar::vertical {
     width: 7px;
}

/*### Non-color styles (fonts etc.)--&gt;tree ##################################*/
QTreeWidget {
    /* These apply to the selected item, but not to editing items.*/
    /* font-family: SansSerif; */
    font-family: @font-family-tree;
    font-size: 16px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
 }

/* Headline edit widgets */
QTreeWidget QLineEdit View{
    font-family: @font-family-tree;
    font-size: 16px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */ 
}

/*### Non-color styles (fonts etc.)--&gt;log ###################################*/
/* The log panes */
QTextEdit#log-widget {
    /* font-family: Courier New; */
    font-family: @font-family-log;
    font-size: 16px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/*### Non-color styles (fonts etc.)--&gt;mini-buffer &amp; status ##################*/
/* The mini-buffer */
QLineEdit#lineEdit {
    font-family: @font-family;
    font-size: 12px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

QLineEdit#status1 {
    border-width: 1px;
    border-style: solid;
}

QLineEdit#status2 {
    border-width: 1px;
    border-style: solid;
}

</t>
<t tx="tbrown.20131122094200.3643">/*
  AUTOMATICALLY GENERATED FROM:
  file:///home/ville/.leo/myLeoSettings.leo#@settings--&gt;leo_dark%20theme%200%20settings--&gt;stylesheet%20&amp;%20source
  2013-04-16 21:44
*/

/*### config ################################################################*/
/*

This *comment* is parsed to extract constants (macros) defined below.

constants:

@solarized-base03 = #272822
@solarized-base02 = #272822
@solarized-base01 = #586e75
@solarized-base00 = #657b83
@solarized-base0 = #839496
@solarized-base1 = #CFBFAD
@solarized-base2 = #eee8d5
@solarized-base3 = #fdf6e3

@solarized-yellow = #b58900
@solarized-orange = #cb4b16
@solarized-red = #dc322f
@solarized-magenta = #d33682
@solarized-violet = #6c71c4
@solarized-blue = #268bd2
@solarized-cyan = #2aa198
@solarized-green = #859900

@text-foreground = @solarized-base0
@text-foreground-bright = @solarized-base2
@text-background = @solarized-base03
@text-background-bright = @solarized-base02
@splitter-bg = @solarized-base01
@splitter-hover-bg = @solarized-violet
@button-hover-bg = @solarized-base01
@button-hover-fg = @solarized-base03

@bg-gradient = qlineargradient( x1:0 y1:0, x2:0 y2:1, \
    stop:0.1 @text-background-bright, stop:0.4 @text-background, \
    stop:0.6 @text-background, stop:0.9 @text-background-bright)
@bg-gradient-hover = qlineargradient( x1:0 y1:0, x2:0 y2:1, \
    stop:0.1 @solarized-base00, stop:0.4 @solarized-base0, \
    stop:0.6 @solarized-base0, stop:0.9 @solarized-base00)

@font-family = Droid Sans Mono, DejaVu Sans Mono
@font-family-tree = @font-family
@font-family-body = @font-family
@font-family-log = @font-family
@font-size-body = 18px

@focused-border-style = none
@focused-border-width = 3px
@focused-border-focus-color = cyan
@focused-border-unfocus-color = white

/*### Color styles ##########################################################*/


/*### Color styles--&gt;ase ####################################################*/
QWidget { color: @solarized-base1; background-color: @solarized-base03; 
  border-color: @solarized-base1; 
}

QScrollBar::add-page, QScrollBar::sub-page {
  background: @solarized-base03; }


QScrollBar::handle { 
  background: @solarized-base01; color: @solarized-base01; }
QScrollBar::handle:hover { 
  background: @solarized-base0; color: @solarized-base0; }
   
/* to make these show up, remove the ::handle style above... bug? */
QScrollBar::add-line, QScrollBar::sub-line { 
  background: @solarized-base01; color: @solarized-base01; }

/*### Color styles--&gt;body editor ############################################*/
QTextEdit#richTextEdit {
    /* background-color: #ffffff; */ /* #fdf5f5; A kind of pink. */
    background-color: @solarized-base03;
    color: @bodytextforegroundcolor;
    selection-color: @solarized-base03;
    selection-background-color: @solarized-yellow;
}

/*### Color styles--&gt;tree ###################################################*/
QTreeView {
    /* These apply to the selected item, but not to editing items.*/
    /* background-color: #ffffff; */ /* #ffffec; Leo's traditional tree color */
    background-color: @solarized-base03;
    color: @solarized-base0;
    selection-color: @solarized-orange;
    selection-background-color: @solarized-base03;
    show-decoration-selected: 0;
 }
QTreeWidget::selected {
    background: @solarized-green; color: @solarized-base03; 
}
QTreeWidget::active:selected {
    background: @solarized-yellow; color: @solarized-base03; 
}

QTreeView::item:selected {
    background: @solarized-green; color: @solarized-base03; 
}
QTreeView::item:active:selected {
    background: @solarized-yellow; color: @solarized-base03; 
}

/* Headline edit widgets */
QTreeView QLineEdit {
    color: @solarized-base03;
    background-color: @solarized-yellow;
    selection-color: @solarized-base3;
    selection-background-color: @solarized-blue;  
}

/*### Color styles--&gt;log ####################################################*/
/* The log panes */
QTextEdit#log-widget {
    /*background-color: #ffffec;*/ /* #f2fdff; */
    background-color: @solarized-base02; /* solarized dark */
    color: @solarized-base0; /* solarized dark */
    selection-color: white;
    selection-background-color: blue;
}

/*### Color styles--&gt;mini-buffer &amp; status ###################################*/
/* The mini-buffer */
QLineEdit#lineEdit {
    background-color: @solarized-base03;
    color: red; 
    selection-color: red;
    selection-background-color: lightgrey;
}

QLabel#minibufferLabel { color: @solarized-violet; }

QLineEdit#status1 {
    background-color: @solarized-base03;
    border-color: @solarized-base02;
}

QLineEdit#status2 {
    background-color: @solarized-base03;
    border-color: @solarized-base02;
}

/*### Color styles--&gt;line edit ##############################################*/
QLineEdit { border: none; padding: 3px; }

/*### Color styles--&gt;labels #################################################*/
QLabel { color: @solarized-base1; }

/*### Color styles--&gt;buttons ################################################*/
QPushButton { color: @text-foreground; background: @bg-gradient; }
QPushButton:hover { color: @button-hover-fg; background: @bg-gradient-hover; }

/*### Color styles--&gt;tab bar ################################################*/
QTabBar::tab { color: @text-foreground; 
background: @bg-gradient; margin-right: 5px; padding: 2px; 
}
QTabBar::tab:selected { color: @solarized-green; } 
QTabBar::tab:hover { background: @bg-gradient-hover; color: @button-hover-fg; }

/*### Color styles--&gt;menus ##################################################*/
QMenu { color: @text-foreground-bright }
QMenuBar::item:hover { color: red; background: white; }
QMenuBar::item { color: @text-foreground; background: @bg-gradient; }
QMenuBar::item:pressed { color: @text-foreground-bright; background: @bg-gradient; }

/*### Color styles--&gt;splitters ##############################################*/
QSplitter::handle {
    background-color: @splitter-bg;  /* #CAE1FF;  lightSteelBlue1 */
}
QSplitter::handle:hover {
    background-color: @splitter-hover-bg;  /* #CAE1FF;  lightSteelBlue1 */
}

/*### Non-color styles (fonts etc.) #########################################*/


/*### Non-color styles (fonts etc.)--&gt;controls, default font size ###########*/
QPushButton, QDoubleSpinBox, QSpinBox, QDateEdit, QTimeEdit { border: none; padding: 3px; margin-right: 5px; }

QWidget { font-size: 16px }

/*### Non-color styles (fonts etc.)--&gt;body editor ###########################*/
/* The body pane */
QTextEdit#richTextEdit {
    font-family: @font-family-body;
    /* font-family: Courier New; */
    font-size: @font-size-body;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

/*### Non-color styles (fonts etc.)--&gt;tab bar ###############################*/
QTabBar::tab { 
   margin-right: 5px; padding: 2px; 
}

/*### Non-color styles (fonts etc.)--&gt;scroll bars ###########################*/
QScrollBar::horizontal {
     height: 7px;
}

QScrollBar::vertical {
     width: 7px;
}

/*### Non-color styles (fonts etc.)--&gt;tree ##################################*/
QTreeWidget {
    /* These apply to the selected item, but not to editing items.*/
    /* font-family: SansSerif; */
    font-family: @font-family-tree;
    font-size: 16px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
 }

/* Headline edit widgets */
QTreeWidget QLineEdit View{
    font-family: @font-family-tree;
    font-size: 16px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */ 
}

/*### Non-color styles (fonts etc.)--&gt;log ###################################*/
/* The log panes */
QTextEdit#log-widget {
    /* font-family: Courier New; */
    font-family: @font-family-log;
    font-size: 16px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/*### Non-color styles (fonts etc.)--&gt;mini-buffer &amp; status ##################*/
/* The mini-buffer */
QLineEdit#lineEdit {
    font-family: @font-family;
    font-size: 12px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

QLineEdit#status1 {
    border-width: 1px;
    border-style: solid;
}

QLineEdit#status2 {
    border-width: 1px;
    border-style: solid;
}

</t>
<t tx="tbrown.20131122094200.3644">Use these settings to get something like the solarized colors.</t>
<t tx="tbrown.20131122094200.3645">base03    #002b36  8/4 brblack  234 #1c1c1c 15 -12 -12   0  43  54 193 100  21
base02    #073642  0/4 black    235 #262626 20 -12 -12   7  54  66 192  90  26
base01    #586e75 10/7 brgreen  240 #585858 45 -07 -07  88 110 117 194  25  46
base00    #657b83 11/7 bryellow 241 #626262 50 -07 -07 101 123 131 195  23  51
base0     #839496 12/6 brblue   244 #808080 60 -06 -03 131 148 150 186  13  59
base1     #93a1a1 14/4 brcyan   245 #8a8a8a 65 -05 -02 147 161 161 180   9  63
base2     #eee8d5  7/7 white    254 #e4e4e4 92 -00  10 238 232 213  44  11  93
base3     #fdf6e3 15/7 brwhite  230 #ffffd7 97  00  10 253 246 227  44  10  99

# These can be used as usual, in *both* light and dark

yellow    #b58900  3/3 yellow   136 #af8700 60  10  65 181 137   0  45 100  71
orange    #cb4b16  9/3 brred    166 #d75f00 50  50  55 203  75  22  18  89  80
red       #dc322f  1/1 red      160 #d70000 50  65  45 220  50  47   1  79  86
magenta   #d33682  5/5 magenta  125 #af005f 50  65 -05 211  54 130 331  74  83
violet    #6c71c4 13/5 brmagenta 61 #5f5faf 50  15 -45 108 113 196 237  45  77
blue      #268bd2  4/4 blue      33 #0087ff 55 -10 -45  38 139 210 205  82  82
cyan      #2aa198  6/6 cyan      37 #00afaf 60 -35 -05  42 161 152 175  74  63
green     #859900  2/2 green     64 #5f8700 60 -20  65 133 153   0  68 100  60

Dark
====

    base1 optional emphasized content (keywords)
  * base0 default (body text)
    
    base01 comments
    base02 background highlights (selected background)
  * base03 background
    
Light
=====

    base01 optional emphasized content (keywords)
  * base00 default (body text)
    base1 comments
    base2 background highlights (selected background)
  * base3 background
</t>
<t tx="tbrown.20131122094200.3646"></t>
<t tx="tbrown.20131122094200.3647"></t>
<t tx="tbrown.20131122094200.3648"></t>
<t tx="tbrown.20131122094200.3649"></t>
<t tx="tbrown.20131122094200.3650">was blue

Solarized blue      #268bd2</t>
<t tx="tbrown.20131122094200.3651">was blue

Solarized blue      #268bd2</t>
<t tx="tbrown.20131122094200.3652">was blue

Solarized blue      #268bd2</t>
<t tx="tbrown.20131122094200.3653">was blue

Solarized blue      #268bd2</t>
<t tx="tbrown.20131122094200.3654">was #00aa00 (Idle comment green)

Solarize green      #859900
Solarized cyan      #2aa198
Solarized violet    #6c71c4
Solarized orange    #cb4b16</t>
<t tx="tbrown.20131122094200.3655"></t>
<t tx="tbrown.20131122094200.3656"></t>
<t tx="tbrown.20131122094200.3657"></t>
<t tx="tbrown.20131122094200.3658">was black</t>
<t tx="tbrown.20131122094200.3659">was firebrick3

Solarized colors:
    
magenta   #d33682

Dark comments   base01
Light comments  base1 comments
</t>
<t tx="tbrown.20131122094200.3660"></t>
<t tx="tbrown.20131122094200.3661"></t>
<t tx="tbrown.20131122094200.3662"></t>
<t tx="tbrown.20131122094200.3663"></t>
<t tx="tbrown.20131122094200.3664"></t>
<t tx="tbrown.20131122094200.3665"></t>
<t tx="tbrown.20131122094200.3666">Background color of body text.  This setting *is* used in the QtGui.

#ffecea

Note: this setting can be overridden by the x_mode_bg_color settings.</t>
<t tx="tbrown.20131122094200.3667">#f9f0f4 light pink
#fbfdfd very light blue

For some reason, colors in the text widget do not match the colors in the canvas widget.</t>
<t tx="tbrown.20131122094200.3668"></t>
<t tx="tbrown.20131122094200.3669">Foreground color of body text.  This setting *is* used in the QtGui.

Note: this setting can be overridden by the x_mode_fg_color settings.</t>
<t tx="tbrown.20131122094200.3670">Overrides body_text_background_color.

#fdf5f5 A light pink.
#f0fde1 A light green.
#f9e6dd A light orange.</t>
<t tx="tbrown.20131122094200.3671">Overrides body_text_foreground_color.</t>
<t tx="tbrown.20131122094200.3672"></t>
<t tx="tbrown.20131122094200.3673">Background color of unselected headline text.

LavenderBlush1</t>
<t tx="tbrown.20131122094200.3674">Foreground color of unselected headline text.</t>
<t tx="tbrown.20131122094200.3675">Background color of selected headline text that is not being edited.

LavenderBlush2</t>
<t tx="tbrown.20131122094200.3676">Foreground color of selected headline text that is not being edited.

DodgerBlue4</t>
<t tx="tbrown.20131122094200.3677">Background color of unselected headline text in a headline that is being edited.

Foreground color must also be specified for either setting to take effect.</t>
<t tx="tbrown.20131122094200.3678">Foreground color of unselected headline text in a headline that is being edited.

Background color must also be specified for either setting to take effect.</t>
<t tx="tbrown.20131122094200.3679">Foreground color of selected text headline text in a headline that is being edited.

Background must also be specified for either setting to take effect.</t>
<t tx="tbrown.20131122094200.3680">Background color of selected text headline text in a headline that is being edited.

Foreground must also be specified for either setting to take effect.</t>
<t tx="tbrown.20131122094200.3681">Background color of outline pane itself.

LavenderBlush1
#ffffe1 # a little too yellow.
#ffffec
LightSteelBlue1 # Good for testing.</t>
<t tx="tbrown.20131122094200.3682"></t>
<t tx="tbrown.20131122094200.3683">Color for error messages written to the log window.</t>
<t tx="tbrown.20131122094200.3684"></t>
<t tx="tbrown.20131122094200.3685">Foreground color of log text.

</t>
<t tx="tbrown.20131122094200.3686">Background color of log text.</t>
<t tx="tbrown.20131122094200.3687">LightYellow1

#f2fdff</t>
<t tx="tbrown.20131122094200.3688">#d6c7d3
#d2cad0
#c6d3d7</t>
<t tx="tbrown.20131122094200.3689">#d6c7d3
#d2cad0
#c6d3d7
#ffffec # Same as outline.</t>
<t tx="tbrown.20131122094200.3690"></t>
<t tx="tbrown.20131122094200.3691"></t>
<t tx="tbrown.20131122094200.3692"></t>
<t tx="tbrown.20131122094200.3827">"Solarized" dark theme.

Copy into mySettings.leo under @settings to enable theme

Place this node at the *bottom* of the list of nodes under
@settings to ensure it overrides other style settings.</t>
<t tx="tbrown.20131122094200.3828">@language rest

See parent nodes for installation notes.

NOTE: to use with a non-dark desktop theme, switch '@ignore base' below
      to 'base' and `run-script` on the `stylesheet &amp; source` node.

*IMPORTANT:* to change the stylesheet, edit the Leo tree under the
`stylesheet &amp; source` node below, not the 
`@data qt-gui-plugin-style-sheet` node itself.

Then select the `stylesheet &amp; source` node and click the `run-script`
button. This creates a new `@data qt-gui-plugin-style-sheet` node and
disables the old one by adding `@@data`.

Within the `stylesheet &amp; source` tree you can reference Leo color
settings (without the hyphens/underscores, so log_background_color is
@logbackgroundcolor) and constants / macros defined within the
`stylesheet &amp; source` tree itself, see the `config` node.

Documentation of Qt stylesheets at 
http://qt-project.org/doc/qt-4.8/stylesheet-reference.html#list-of-stylable-widgets

Valid color names: http://www.w3.org/TR/SVG/types.html#ColorKeywords
</t>
<t tx="tbrown.20131122094200.3829">A theme's folder should be in either .../leo/themes or
$HOME/.leo/themes.

A theme is a combination of @color settings, a stylesheet, and,
optionally, some icons. Icons go in &lt;theme_dir&gt;/Icons.</t>
<t tx="tbrown.20131122094200.3830">Name of the theme, used to find icon files</t>
<t tx="tbrown.20131122094200.3831">Set to true for dark themes, so bookmarks.py can generate
random background colors which are appropriate etc.</t>
<t tx="tbrown.20131122094200.3832"># backup 2013-11-20 12:14:30 - config
# file:///home/tbrown/.leo/myLeoSettings.leo#@settings--&gt;leo_dark%20theme%200%20settings--&gt;config

LyoKClRoaXMgKmNvbW1lbnQqIGlzIHBhcnNlZCB0byBleHRyYWN0IGNvbnN0YW50cyAobW
Fjcm9zKSBkZWZpbmVkIGJlbG93LgoKY29uc3RhbnRzOgoKTmFtZXMgZm9yIHNvbGFyaXpl
ZCBjb2xvcnMKCkBzb2xhcml6ZWQtYmFzZTAzID0gIzAwMmIzNgpAc29sYXJpemVkLWJhc2
UwMiA9ICMwNzM2NDIKQHNvbGFyaXplZC1iYXNlMDEgPSAjNTg2ZTc1CkBzb2xhcml6ZWQt
YmFzZTAwID0gIzY1N2I4MwpAc29sYXJpemVkLWJhc2UwID0gIzgzOTQ5NgpAc29sYXJpem
VkLWJhc2UxID0gIzkzYTFhMQpAc29sYXJpemVkLWJhc2UyID0gI2VlZThkNQpAc29sYXJp
emVkLWJhc2UzID0gI2ZkZjZlMwpAc29sYXJpemVkLXllbGxvdyA9ICNiNTg5MDAKQHNvbG
FyaXplZC1vcmFuZ2UgPSAjY2I0YjE2CkBzb2xhcml6ZWQtcmVkID0gI2RjMzIyZgpAc29s
YXJpemVkLW1hZ2VudGEgPSAjZDMzNjgyCkBzb2xhcml6ZWQtdmlvbGV0ID0gIzZjNzFjNA
pAc29sYXJpemVkLWJsdWUgPSAjMjY4YmQyCkBzb2xhcml6ZWQtY3lhbiA9ICMyYWExOTgK
QHNvbGFyaXplZC1ncmVlbiA9ICM4NTk5MDAKCkB0ZXh0LWZvcmVncm91bmQgPSBAc29sYX
JpemVkLWJhc2UwCkB0ZXh0LWZvcmVncm91bmQtYnJpZ2h0ID0gQHNvbGFyaXplZC1iYXNl
MgpAdGV4dC1iYWNrZ3JvdW5kID0gQHNvbGFyaXplZC1iYXNlMDMKQHRleHQtYmFja2dyb3
VuZC1icmlnaHQgPSBAc29sYXJpemVkLWJhc2UwMgpAc3BsaXR0ZXItYmcgPSBAc29sYXJp
emVkLWJhc2UwMQpAc3BsaXR0ZXItaG92ZXItYmcgPSBAc29sYXJpemVkLXZpb2xldApAYn
V0dG9uLWhvdmVyLWJnID0gQHNvbGFyaXplZC1iYXNlMDEKQGJ1dHRvbi1ob3Zlci1mZyA9
IEBzb2xhcml6ZWQtYmFzZTAzCgpAYmctZ3JhZGllbnQgPSBxbGluZWFyZ3JhZGllbnQoIH
gxOjAgeTE6MCwgeDI6MCB5MjoxLCBzdG9wOjAuMSBAdGV4dC1iYWNrZ3JvdW5kLWJyaWdo
dCwgc3RvcDowLjQgQHRleHQtYmFja2dyb3VuZCwgc3RvcDowLjYgQHRleHQtYmFja2dyb3
VuZCwgc3RvcDowLjkgQHRleHQtYmFja2dyb3VuZC1icmlnaHQpCkBiZy1ncmFkaWVudC1o
b3ZlciA9IHFsaW5lYXJncmFkaWVudCggeDE6MCB5MTowLCB4MjowIHkyOjEsIHN0b3A6MC
4xIEBzb2xhcml6ZWQtYmFzZTAwLCBzdG9wOjAuNCBAc29sYXJpemVkLWJhc2UwLCBzdG9w
OjAuNiBAc29sYXJpemVkLWJhc2UwLCBzdG9wOjAuOSBAc29sYXJpemVkLWJhc2UwMCkKCk
Bmb250LWZhbWlseSA9IERyb2lkIFNhbnMgTW9ubywgRGVqYVZ1IFNhbnMgTW9ubwpAZm9u
dC1mYW1pbHktdHJlZSA9IEBmb250LWZhbWlseQpAZm9udC1mYW1pbHktYm9keSA9IEBmb2
50LWZhbWlseQpAZm9udC1mYW1pbHktbG9nID0gQGZvbnQtZmFtaWx5CkBmb250LXNpemUt
Ym9keSA9IDE4cHgKCk5vdGUsIGZvciB0aGVzZSB0byB3b3JrLCB5b3UgbmVlZCB0byBhIG
5vZGUKICBAYm9vbCB1c2VfZm9jdXNfYm9yZGVyID0gRmFsc2UKdW5kZXIgeW91ciBAc2V0
dGluZ3Mgbm9kZSB0byB0dXJuIG9mZiBub24tc3R5bGVzaGVldCBiYXNlZCBib3JkZXIKaG
lnaGxpZ2h0aW5nLiAgQWxzbywgc2V0IEBmb2N1c2VkLWJvcmRlci1zdHlsZSB0byBzb21l
dGhpbmcgb3RoZXIKdGhhbiBub25lLCBiZWxvdy4gICdzb2xpZCcgd29ya3MuCgpAZm9jdX
NlZC1ib3JkZXItc3R5bGUgPSBub25lCkBmb2N1c2VkLWJvcmRlci13aWR0aCA9IDNweApA
Zm9jdXNlZC1ib3JkZXItZm9jdXMtY29sb3IgPSBjeWFuCkBmb2N1c2VkLWJvcmRlci1ob3
Zlci1jb2xvciA9IHJlZApAZm9jdXNlZC1ib3JkZXItdW5mb2N1cy1jb2xvciA9IHdoaXRl
Cg==</t>
<t tx="tbrown.20131122094200.3833">@nocolor
</t>
<t tx="tbrown.20131122094200.3834">These are definitions of colors not defined by default, so
you can refer to "solarized-red" as "@solarized-red" instead
of "#dc322f".  You probably don't need to touch these, although
you could add new color names of your own.  It would not make
sense to change the definitions of the solarized-* colors.</t>
<t tx="tbrown.20131122094200.3835"></t>
<t tx="tbrown.20131122094200.3836"></t>
<t tx="tbrown.20131122094200.3837"></t>
<t tx="tbrown.20131122094200.3838"></t>
<t tx="tbrown.20131122094200.3839"></t>
<t tx="tbrown.20131122094200.3840"></t>
<t tx="tbrown.20131122094200.3841"></t>
<t tx="tbrown.20131122094200.3842"></t>
<t tx="tbrown.20131122094200.3843"></t>
<t tx="tbrown.20131122094200.3844"></t>
<t tx="tbrown.20131122094200.3845"></t>
<t tx="tbrown.20131122094200.3846"></t>
<t tx="tbrown.20131122094200.3847"></t>
<t tx="tbrown.20131122094200.3848"></t>
<t tx="tbrown.20131122094200.3849"></t>
<t tx="tbrown.20131122094200.3850"></t>
<t tx="tbrown.20131122094200.3851">Here you can edit the colors by Leo, just edit the
node headings, and click the reload-style button.

Examples:
    
    @color text-foreground = white
    
    @color text-foreground = #ffffff
    
    @color text-foreground = @solarized-red

Most common color names are recognized.  The #RRGGBB format works, and
you can use reference to @settings defined elsehere, starting with an
'@', e.g. @solarized-red if a color called @solarized-red is defined
by a setting somewhere else.

Config. menu entry: Styles / Colors
</t>
<t tx="tbrown.20131122094200.3852"></t>
<t tx="tbrown.20131122094200.3853"></t>
<t tx="tbrown.20131122094200.3854"></t>
<t tx="tbrown.20131122094200.3855"></t>
<t tx="tbrown.20131122094200.3856"></t>
<t tx="tbrown.20131122094200.3857"></t>
<t tx="tbrown.20131122094200.3858"></t>
<t tx="tbrown.20131122094200.3859"></t>
<t tx="tbrown.20131122094200.3860">Foreground color of log text.

</t>
<t tx="tbrown.20131122094200.3861">Background color of log text.</t>
<t tx="tbrown.20131122094200.3862">Color for error messages written to the log window.</t>
<t tx="tbrown.20131122094200.3863"></t>
<t tx="tbrown.20131122094200.3864"></t>
<t tx="tbrown.20131122094200.3865"></t>
<t tx="tbrown.20131122094200.3866"></t>
<t tx="tbrown.20131122094200.3867"></t>
<t tx="tbrown.20131122094200.3868"></t>
<t tx="tbrown.20131122094200.3869">test text</t>
<t tx="tbrown.20131122094200.3870">test text</t>
<t tx="tbrown.20131122094200.3871"></t>
<t tx="tbrown.20131122094200.3872"></t>
<t tx="tbrown.20131122094200.3873"></t>
<t tx="tbrown.20131122094200.3874">(some body text here so there's something to see)</t>
<t tx="tbrown.20131122094200.3875"></t>
<t tx="tbrown.20131122094200.3876"></t>
<t tx="tbrown.20131122094200.3877">Note, for these to work, you need to a node
  @bool use_focus_border = False
under your @settings node to turn off non-stylesheet based border
highlighting.  Also, set @focused-border-style to something other
than none, below.  'solid' works.</t>
<t tx="tbrown.20131122094200.3878"></t>
<t tx="tbrown.20131122094200.3879"></t>
<t tx="tbrown.20131122094200.3880"></t>
<t tx="tbrown.20131122094200.3881"></t>
<t tx="tbrown.20131122094200.3882"></t>
<t tx="tbrown.20131122094200.3883"></t>
<t tx="tbrown.20131122094200.3884"></t>
<t tx="tbrown.20131122094200.3885"></t>
<t tx="tbrown.20131122094200.3886">@language css  # (this node is python, descendants are css)

# To generate the stylesheet @data from this source,
# use `run-script` on this node.
#
# Don't forget to delete any previous '@data qt-gui-plugin-style-sheet' nodes.

cp = g.findNodeInTree(
    c,
    g.findNodeAnywhere(c, '@settings'),
    'stylesheet &amp; source',
)
#X cp = c.p

import datetime
nd = cp.insertAsLastChild()
unl = cp.get_UNL()+'--&gt;'
nd.h = '@ignore'  # removed after processing
nd.b = ("/*\n  DON'T EDIT THIS, EDIT THE OTHER NODES UNDER "
    "'stylesheet &amp; source'\n  AND RECREATE THIS BY SELECTING "
    "'stylesheet &amp; source' AND USING CTRL-B"
    "\n\n  AUTOMATICALLY GENERATED FROM:\n  %s\n  %s\n*/\n\n"
    % (
    cp.get_UNL(with_proto=True),
    datetime.datetime.now().strftime('%Y-%m-%d %H:%M'),
))

for i in cp.subtree():
    src = i.get_UNL().replace(unl, '')
    if i.h.startswith('@data '):
        i.h = '@'+i.h
    if ('@ignore' in src) or ('@data' in src):
        continue
    nd.b += "/*### %s %s*/\n%s\n\n" % (
        src, '#'*(70-len(src)),
        i.b.strip()
    )
    
nd.h = '@data qt-gui-plugin-style-sheet'

# make the style active
# g.app.gui.frameFactory.masterFrame.setStyleSheet(
#     g.expand_css_constants(nd.b))

# c.selectPosition(nd)

c.redraw()</t>
<t tx="tbrown.20131122094200.3887"></t>
<t tx="tbrown.20131122094200.3888">QWidget { color: @solarized-base1; background-color: @solarized-base03; 
  border-color: @solarized-base1; 
}
</t>
<t tx="tbrown.20131122094200.3889">QTextEdit#richTextEdit {
    background-color: @solarized-base03;
    color: @text-foreground; /* bodytextforegroundcolor; */
    selection-color: @solarized-base03;
    selection-background-color: @solarized-yellow;
}</t>
<t tx="tbrown.20131122094200.3890">QTreeView {
    /* These apply to the selected item, but not to editing items.*/
    /* background-color: #ffffff; */ /* #ffffec; Leo's traditional tree color */
    background-color: @solarized-base03;
    color: @solarized-base0;
    selection-color: @solarized-orange;
    selection-background-color: @solarized-base03;
    show-decoration-selected: 0;
 }
QTreeWidget::selected {
    background: @solarized-green; color: @solarized-base03; 
}
QTreeWidget::active:selected {
    background: @solarized-yellow; color: @solarized-base03; 
}

QTreeView::item:selected {
    background: @solarized-green; color: @solarized-base03; 
}
QTreeView::item:active:selected {
    background: @solarized-yellow; color: @solarized-base03; 
}

/* Headline edit widgets */
QTreeView QLineEdit {
    color: @solarized-base03;
    background-color: @solarized-yellow;
    selection-color: @solarized-base3;
    selection-background-color: @solarized-blue;  
}

</t>
<t tx="tbrown.20131122094200.3891">/* The log panes */
QTextEdit#log-widget {
    /*background-color: #ffffec;*/ /* #f2fdff; */
    background-color: @log_text_background_color; /* solarized dark */
    color: @log_text_foreground_color; /* solarized dark */
    selection-color: white;
    selection-background-color: blue;
}</t>
<t tx="tbrown.20131122094200.3892">/* The mini-buffer */
QLineEdit#lineEdit {
    background-color: @solarized-base03;
    color: red; 
    selection-color: red;
    selection-background-color: lightgrey;
}

QLabel#minibufferLabel { color: @solarized-violet; }

QLineEdit#status1 {
    background-color: @solarized-base03;
    border-color: @solarized-base02;
}

QLineEdit#status2 {
    background-color: @solarized-base03;
    border-color: @solarized-base02;
}</t>
<t tx="tbrown.20131122094200.3893">QLineEdit { border: none; padding: 3px; }</t>
<t tx="tbrown.20131122094200.3894">QLabel { color: @solarized-base1; }</t>
<t tx="tbrown.20131122094200.3895">QPushButton { color: @text-foreground; background: @bg-gradient; }
QPushButton:hover { color: @button-hover-fg; background: @bg-gradient-hover; }</t>
<t tx="tbrown.20131122094200.3896">QTabBar::tab { color: @text-foreground; 
background: @bg-gradient; margin-right: 5px; padding: 2px; 
}
QTabBar::tab:selected { color: @solarized-green; } 
QTabBar::tab:hover { background: @bg-gradient-hover; color: @button-hover-fg; }</t>
<t tx="tbrown.20131122094200.3897">QMenu { color: @text-foreground-bright }
QMenuBar::item:selected { color: @button-hover-fg; background: @bg-gradient-hover; }
QMenu::item:selected { color: @button-hover-fg; background: @bg-gradient-hover; }
QMenuBar::item { color: @text-foreground; background: @bg-gradient; }
QMenuBar::item:pressed { color: @text-foreground-bright; background: @bg-gradient; }
</t>
<t tx="tbrown.20131122094200.3898">QScrollBar::add-page, QScrollBar::sub-page {
  background: @solarized-base03; }
QScrollBar::handle { 
  background: @solarized-base01; color: @solarized-base01; }
QScrollBar::handle:hover { 
  background: @solarized-base0; color: @solarized-base0; }
/* to make these show up, remove the ::handle style above... bug? */
QScrollBar::add-line, QScrollBar::sub-line { 
  background: @solarized-base01; color: @solarized-base01; }</t>
<t tx="tbrown.20131122094200.3899">QSplitter::handle {
    background-color: @splitter-bg;  /* #CAE1FF;  lightSteelBlue1 */
}
QSplitter::handle:hover {
    background-color: @splitter-hover-bg;  /* #CAE1FF;  lightSteelBlue1 */
}
</t>
<t tx="tbrown.20131122094200.3900">QLineEdit#lineEdit {
    color: @minibuffer_foreground_color;
    background-color: @minibuffer_background_color;
}

QLineEdit#lineEdit[style_class ~= 'minibuffer_warning'] {
    background-color: @minibuffer_warning_color;
}

QLineEdit#lineEdit[style_class ~= 'minibuffer_error'] {
    color: @minibuffer_error_color;
    background-color: @minibuffer_warning_color;
}
</t>
<t tx="tbrown.20131122094200.3901"></t>
<t tx="tbrown.20131122094200.3902">/* alternative active pane highlighting */
QTextEdit#log-widget, LeoQTreeWidget#treeWidget, QTextEdit#richTextEdit { 
  border-style: @focused-border-style;
  border-width: @focused-border-width; 
  border-color: @focused-border-unfocus-color; 
}
QTextEdit:focus#log-widget, LeoQTreeWidget:focus#treeWidget, QTextEdit:focus#richTextEdit { 
  border-color: @focused-border-focus-color; 
}
QTextEdit:hover#log-widget, LeoQTreeWidget:hover#treeWidget, QTextEdit:hover#richTextEdit { 
  border-color: @focused-border-hover-color; 
}
</t>
<t tx="tbrown.20131122094200.3903">QPushButton, QDoubleSpinBox, QSpinBox, QDateEdit, QTimeEdit { border: none; padding: 3px; margin-right: 5px; }

QWidget { font-size: 16px }
</t>
<t tx="tbrown.20131122094200.3904">/* The body pane */
QTextEdit#richTextEdit {
    font-family: @font-family-body;
    /* font-family: Courier New; */
    font-size: @font-size-body;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}
</t>
<t tx="tbrown.20131122094200.3905">QTabBar::tab { 
   margin-right: 5px; padding: 2px; 
}
</t>
<t tx="tbrown.20131122094200.3906">QScrollBar::horizontal {
     height: 7px;
}

QScrollBar::vertical {
     width: 7px;
}</t>
<t tx="tbrown.20131122094200.3907">QTreeWidget {
    /* These apply to the selected item, but not to editing items.*/
    /* font-family: SansSerif; */
    font-family: @font-family-tree;
    font-size: @font-size-tree;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
 }

/* Headline edit widgets */
QTreeWidget QLineEdit {
    font-family: @font-family-tree;
    font-size: @font-size-tree;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */ 
}
</t>
<t tx="tbrown.20131122094200.3908">/* The log panes */
QTextEdit#log-widget {
    /* font-family: Courier New; */
    font-family: @font-family-log;
    font-size: @font-size-log;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}</t>
<t tx="tbrown.20131122094200.3909">/* The mini-buffer */
QLineEdit#lineEdit {
    font-family: @font-family;
    font-size: 12px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

QLineEdit#status1 {
    border-width: 1px;
    border-style: solid;
}

QLineEdit#status2 {
    border-width: 1px;
    border-style: solid;
}</t>
<t tx="tbrown.20131122094200.3910">/* START: dark styles for non-dark desktop theme */
/*
QWidget { color: @solarized-base1; background-color: @solarized-base03; 
  border-color: @solarized-base1;
}

QScrollBar::add-page, QScrollBar::sub-page { 
    background: @solarized-base03; }
    
QScrollBar::add-line { background: red; 
  border: 1px solid red ; color: red }
  
QScrollBar::handle { background: @solarized-base01; 
  border: 1px solid @solarized-base02;  }
*/
/* END: dark styles for non-dark desktop theme */


/* 
QSpinBox::up-button { background: @text-background; }
QSpinBox::up-arrow { 
  background: @text-background;
  color: @text-foreground; 
  image: url(:/images/up_arrow.png);
} */



/* needs work
QSpinBox::up-button { background-color: @solarized-base03; }
QSpinBox::up-arrow { background-color: @solarized-base03; color: @solarized-base1; }
*/

QWidget[style_class~='focused_pane'] {
    border-color: orange;
    border-width: 3px;
    border-style: solid;
}
QWidget[style_class~='unfocused_pane'] {
    border-color: blue;
    border-width: 3px;
    border-style: solid;
}


QStackedWidget {
    /* background-color:lightpink; */
    border-color: red;
    padding: 0px;
    /* border-width: 0px; */
    /* background-color: yellow; */
}

QSplitter {
    border-color: white;
    /* background-color: white; */
    border-style: solid;
}




QTextEdit {
    font-family: DejaVu Sans Mono;
    font-size: 16px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}



XXQToolButton {
    /* background-color: #fdf5f5;  A kind of pink. */
    margin: 2px;
    padding; 4px;
    border-width: 2px;
    border-style: solid;
    border-color: darkgrey;
    font-size: 8px;
}

/* QMenuBar works, but not QMenu... */
XXQMenuBar {
    font-family: DejaVu Sans Mono;
    font-size: 12px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

*[name~='preview'] { color: green; }</t>
<t tx="tbrown.20131122094200.3911">/*
  DON'T EDIT THIS, EDIT THE OTHER NODES UNDER 'stylesheet &amp; source'
  AND RECREATE THIS BY SELECTING 'stylesheet &amp; source' AND USING CTRL-B

  AUTOMATICALLY GENERATED FROM:
  file:///home/tbrown/.leo/myLeoSettings.leo#@settings--&gt;leo_dark%20theme%200%20settings--&gt;stylesheet%20&amp;%20source
  2013-11-20 21:14
*/

/*### Color styles ##########################################################*/


/*### Color styles--&gt;base ###################################################*/
QWidget { color: @solarized-base1; background-color: @solarized-base03; 
  border-color: @solarized-base1; 
}

/*### Color styles--&gt;body editor ############################################*/
QTextEdit#richTextEdit {
    background-color: @solarized-base03;
    color: @text-foreground; /* bodytextforegroundcolor; */
    selection-color: @solarized-base03;
    selection-background-color: @solarized-yellow;
}

/*### Color styles--&gt;tree ###################################################*/
QTreeView {
    /* These apply to the selected item, but not to editing items.*/
    /* background-color: #ffffff; */ /* #ffffec; Leo's traditional tree color */
    background-color: @solarized-base03;
    color: @solarized-base0;
    selection-color: @solarized-orange;
    selection-background-color: @solarized-base03;
    show-decoration-selected: 0;
 }
QTreeWidget::selected {
    background: @solarized-green; color: @solarized-base03; 
}
QTreeWidget::active:selected {
    background: @solarized-yellow; color: @solarized-base03; 
}

QTreeView::item:selected {
    background: @solarized-green; color: @solarized-base03; 
}
QTreeView::item:active:selected {
    background: @solarized-yellow; color: @solarized-base03; 
}

/* Headline edit widgets */
QTreeView QLineEdit {
    color: @solarized-base03;
    background-color: @solarized-yellow;
    selection-color: @solarized-base3;
    selection-background-color: @solarized-blue;  
}

/*### Color styles--&gt;log ####################################################*/
/* The log panes */
QTextEdit#log-widget {
    /*background-color: #ffffec;*/ /* #f2fdff; */
    background-color: @log_text_background_color; /* solarized dark */
    color: @log_text_foreground_color; /* solarized dark */
    selection-color: white;
    selection-background-color: blue;
}

/*### Color styles--&gt;mini-buffer &amp; status ###################################*/
/* The mini-buffer */
QLineEdit#lineEdit {
    background-color: @solarized-base03;
    color: red; 
    selection-color: red;
    selection-background-color: lightgrey;
}

QLabel#minibufferLabel { color: @solarized-violet; }

QLineEdit#status1 {
    background-color: @solarized-base03;
    border-color: @solarized-base02;
}

QLineEdit#status2 {
    background-color: @solarized-base03;
    border-color: @solarized-base02;
}

/*### Color styles--&gt;line edit ##############################################*/
QLineEdit { border: none; padding: 3px; }

/*### Color styles--&gt;labels #################################################*/
QLabel { color: @solarized-base1; }

/*### Color styles--&gt;buttons ################################################*/
QPushButton { color: @text-foreground; background: @bg-gradient; }
QPushButton:hover { color: @button-hover-fg; background: @bg-gradient-hover; }

/*### Color styles--&gt;tab bar ################################################*/
QTabBar::tab { color: @text-foreground; 
background: @bg-gradient; margin-right: 5px; padding: 2px; 
}
QTabBar::tab:selected { color: @solarized-green; } 
QTabBar::tab:hover { background: @bg-gradient-hover; color: @button-hover-fg; }

/*### Color styles--&gt;menus ##################################################*/
QMenu { color: @text-foreground-bright }
QMenuBar::item:selected { color: @button-hover-fg; background: @bg-gradient-hover; }
QMenu::item:selected { color: @button-hover-fg; background: @bg-gradient-hover; }
QMenuBar::item { color: @text-foreground; background: @bg-gradient; }
QMenuBar::item:pressed { color: @text-foreground-bright; background: @bg-gradient; }

/*### Color styles--&gt;scrollbar ##############################################*/
QScrollBar::add-page, QScrollBar::sub-page {
  background: @solarized-base03; }
QScrollBar::handle { 
  background: @solarized-base01; color: @solarized-base01; }
QScrollBar::handle:hover { 
  background: @solarized-base0; color: @solarized-base0; }
/* to make these show up, remove the ::handle style above... bug? */
QScrollBar::add-line, QScrollBar::sub-line { 
  background: @solarized-base01; color: @solarized-base01; }

/*### Color styles--&gt;splitters ##############################################*/
QSplitter::handle {
    background-color: @splitter-bg;  /* #CAE1FF;  lightSteelBlue1 */
}
QSplitter::handle:hover {
    background-color: @splitter-hover-bg;  /* #CAE1FF;  lightSteelBlue1 */
}

/*### Color styles--&gt;minibuffer #############################################*/
QLineEdit#lineEdit {
    color: @minibuffer_foreground_color;
    background-color: @minibuffer_background_color;
}

QLineEdit#lineEdit[style_class = 'minibuffer_warning'] {
    background-color: @minibuffer_warning_color;
}

QLineEdit#lineEdit[style_class = 'minibuffer_error'] {
    color: @minibuffer_error_color;
    background-color: @minibuffer_warning_color;
}

/*### Non-color styles (fonts etc.) #########################################*/


/*### Non-color styles (fonts etc.)--&gt;border ################################*/
/* alternative active pane highlighting */
QTextEdit#log-widget, LeoQTreeWidget#treeWidget, QTextEdit#richTextEdit { 
  border-style: @focused-border-style;
  border-width: @focused-border-width; 
  border-color: @focused-border-unfocus-color; 
}
QTextEdit:focus#log-widget, LeoQTreeWidget:focus#treeWidget, QTextEdit:focus#richTextEdit { 
  border-color: @focused-border-focus-color; 
}
QTextEdit:hover#log-widget, LeoQTreeWidget:hover#treeWidget, QTextEdit:hover#richTextEdit { 
  border-color: @focused-border-hover-color; 
}

/*### Non-color styles (fonts etc.)--&gt;controls, default font size ###########*/
QPushButton, QDoubleSpinBox, QSpinBox, QDateEdit, QTimeEdit { border: none; padding: 3px; margin-right: 5px; }

QWidget { font-size: 16px }

/*### Non-color styles (fonts etc.)--&gt;body editor ###########################*/
/* The body pane */
QTextEdit#richTextEdit {
    font-family: @font-family-body;
    /* font-family: Courier New; */
    font-size: @font-size-body;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

/*### Non-color styles (fonts etc.)--&gt;tab bar ###############################*/
QTabBar::tab { 
   margin-right: 5px; padding: 2px; 
}

/*### Non-color styles (fonts etc.)--&gt;scroll bars ###########################*/
QScrollBar::horizontal {
     height: 7px;
}

QScrollBar::vertical {
     width: 7px;
}

/*### Non-color styles (fonts etc.)--&gt;tree ##################################*/
QTreeWidget {
    /* These apply to the selected item, but not to editing items.*/
    /* font-family: SansSerif; */
    font-family: @font-family-tree;
    font-size: @font-size-tree;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
 }

/* Headline edit widgets */
QTreeWidget QLineEdit {
    font-family: @font-family-tree;
    font-size: @font-size-tree;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */ 
}

/*### Non-color styles (fonts etc.)--&gt;log ###################################*/
/* The log panes */
QTextEdit#log-widget {
    /* font-family: Courier New; */
    font-family: @font-family-log;
    font-size: @font-size-log;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/*### Non-color styles (fonts etc.)--&gt;mini-buffer &amp; status ##################*/
/* The mini-buffer */
QLineEdit#lineEdit {
    font-family: @font-family;
    font-size: 12px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

QLineEdit#status1 {
    border-width: 1px;
    border-style: solid;
}

QLineEdit#status2 {
    border-width: 1px;
    border-style: solid;
}

</t>
<t tx="tbrown.20131122094200.3912">/*
  DON'T EDIT THIS, EDIT THE OTHER NODES UNDER 'stylesheet &amp; source'
  AND RECREATE THIS BY SELECTING 'stylesheet &amp; source' AND USING CTRL-B

  AUTOMATICALLY GENERATED FROM:
  file:///home/tbrown/.leo/myLeoSettings.leo#@settings--&gt;leo_dark%20theme%200%20settings--&gt;stylesheet%20&amp;%20source
  2013-11-20 21:17
*/

/*### Color styles ##########################################################*/


/*### Color styles--&gt;base ###################################################*/
QWidget { color: @solarized-base1; background-color: @solarized-base03; 
  border-color: @solarized-base1; 
}

/*### Color styles--&gt;body editor ############################################*/
QTextEdit#richTextEdit {
    background-color: @solarized-base03;
    color: @text-foreground; /* bodytextforegroundcolor; */
    selection-color: @solarized-base03;
    selection-background-color: @solarized-yellow;
}

/*### Color styles--&gt;tree ###################################################*/
QTreeView {
    /* These apply to the selected item, but not to editing items.*/
    /* background-color: #ffffff; */ /* #ffffec; Leo's traditional tree color */
    background-color: @solarized-base03;
    color: @solarized-base0;
    selection-color: @solarized-orange;
    selection-background-color: @solarized-base03;
    show-decoration-selected: 0;
 }
QTreeWidget::selected {
    background: @solarized-green; color: @solarized-base03; 
}
QTreeWidget::active:selected {
    background: @solarized-yellow; color: @solarized-base03; 
}

QTreeView::item:selected {
    background: @solarized-green; color: @solarized-base03; 
}
QTreeView::item:active:selected {
    background: @solarized-yellow; color: @solarized-base03; 
}

/* Headline edit widgets */
QTreeView QLineEdit {
    color: @solarized-base03;
    background-color: @solarized-yellow;
    selection-color: @solarized-base3;
    selection-background-color: @solarized-blue;  
}

/*### Color styles--&gt;log ####################################################*/
/* The log panes */
QTextEdit#log-widget {
    /*background-color: #ffffec;*/ /* #f2fdff; */
    background-color: @log_text_background_color; /* solarized dark */
    color: @log_text_foreground_color; /* solarized dark */
    selection-color: white;
    selection-background-color: blue;
}

/*### Color styles--&gt;mini-buffer &amp; status ###################################*/
/* The mini-buffer */
QLineEdit#lineEdit {
    background-color: @solarized-base03;
    color: red; 
    selection-color: red;
    selection-background-color: lightgrey;
}

QLabel#minibufferLabel { color: @solarized-violet; }

QLineEdit#status1 {
    background-color: @solarized-base03;
    border-color: @solarized-base02;
}

QLineEdit#status2 {
    background-color: @solarized-base03;
    border-color: @solarized-base02;
}

/*### Color styles--&gt;line edit ##############################################*/
QLineEdit { border: none; padding: 3px; }

/*### Color styles--&gt;labels #################################################*/
QLabel { color: @solarized-base1; }

/*### Color styles--&gt;buttons ################################################*/
QPushButton { color: @text-foreground; background: @bg-gradient; }
QPushButton:hover { color: @button-hover-fg; background: @bg-gradient-hover; }

/*### Color styles--&gt;tab bar ################################################*/
QTabBar::tab { color: @text-foreground; 
background: @bg-gradient; margin-right: 5px; padding: 2px; 
}
QTabBar::tab:selected { color: @solarized-green; } 
QTabBar::tab:hover { background: @bg-gradient-hover; color: @button-hover-fg; }

/*### Color styles--&gt;menus ##################################################*/
QMenu { color: @text-foreground-bright }
QMenuBar::item:selected { color: @button-hover-fg; background: @bg-gradient-hover; }
QMenu::item:selected { color: @button-hover-fg; background: @bg-gradient-hover; }
QMenuBar::item { color: @text-foreground; background: @bg-gradient; }
QMenuBar::item:pressed { color: @text-foreground-bright; background: @bg-gradient; }

/*### Color styles--&gt;scrollbar ##############################################*/
QScrollBar::add-page, QScrollBar::sub-page {
  background: @solarized-base03; }
QScrollBar::handle { 
  background: @solarized-base01; color: @solarized-base01; }
QScrollBar::handle:hover { 
  background: @solarized-base0; color: @solarized-base0; }
/* to make these show up, remove the ::handle style above... bug? */
QScrollBar::add-line, QScrollBar::sub-line { 
  background: @solarized-base01; color: @solarized-base01; }

/*### Color styles--&gt;splitters ##############################################*/
QSplitter::handle {
    background-color: @splitter-bg;  /* #CAE1FF;  lightSteelBlue1 */
}
QSplitter::handle:hover {
    background-color: @splitter-hover-bg;  /* #CAE1FF;  lightSteelBlue1 */
}

/*### Color styles--&gt;minibuffer #############################################*/
QLineEdit#lineEdit {
    color: @minibuffer_foreground_color;
    background-color: @minibuffer_background_color;
}

QLineEdit#lineEdit[style_class = 'minibuffer_warning'] {
    background-color: @minibuffer_warning_color;
}

QLineEdit#lineEdit[style_class = 'minibuffer_error'] {
    color: @minibuffer_error_color;
    background-color: @minibuffer_warning_color;
}

/*### Non-color styles (fonts etc.) #########################################*/


/*### Non-color styles (fonts etc.)--&gt;border ################################*/
/* alternative active pane highlighting */
QTextEdit#log-widget, LeoQTreeWidget#treeWidget, QTextEdit#richTextEdit { 
  border-style: @focused-border-style;
  border-width: @focused-border-width; 
  border-color: @focused-border-unfocus-color; 
}
QTextEdit:focus#log-widget, LeoQTreeWidget:focus#treeWidget, QTextEdit:focus#richTextEdit { 
  border-color: @focused-border-focus-color; 
}
QTextEdit:hover#log-widget, LeoQTreeWidget:hover#treeWidget, QTextEdit:hover#richTextEdit { 
  border-color: @focused-border-hover-color; 
}

/*### Non-color styles (fonts etc.)--&gt;controls, default font size ###########*/
QPushButton, QDoubleSpinBox, QSpinBox, QDateEdit, QTimeEdit { border: none; padding: 3px; margin-right: 5px; }

QWidget { font-size: 16px }

/*### Non-color styles (fonts etc.)--&gt;body editor ###########################*/
/* The body pane */
QTextEdit#richTextEdit {
    font-family: @font-family-body;
    /* font-family: Courier New; */
    font-size: @font-size-body;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

/*### Non-color styles (fonts etc.)--&gt;tab bar ###############################*/
QTabBar::tab { 
   margin-right: 5px; padding: 2px; 
}

/*### Non-color styles (fonts etc.)--&gt;scroll bars ###########################*/
QScrollBar::horizontal {
     height: 7px;
}

QScrollBar::vertical {
     width: 7px;
}

/*### Non-color styles (fonts etc.)--&gt;tree ##################################*/
QTreeWidget {
    /* These apply to the selected item, but not to editing items.*/
    /* font-family: SansSerif; */
    font-family: @font-family-tree;
    font-size: @font-size-tree;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
 }

/* Headline edit widgets */
QTreeWidget QLineEdit {
    font-family: @font-family-tree;
    font-size: @font-size-tree;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */ 
}

/*### Non-color styles (fonts etc.)--&gt;log ###################################*/
/* The log panes */
QTextEdit#log-widget {
    /* font-family: Courier New; */
    font-family: @font-family-log;
    font-size: @font-size-log;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/*### Non-color styles (fonts etc.)--&gt;mini-buffer &amp; status ##################*/
/* The mini-buffer */
QLineEdit#lineEdit {
    font-family: @font-family;
    font-size: 12px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

QLineEdit#status1 {
    border-width: 1px;
    border-style: solid;
}

QLineEdit#status2 {
    border-width: 1px;
    border-style: solid;
}

</t>
<t tx="tbrown.20131122094200.3913">/*
  DON'T EDIT THIS, EDIT THE OTHER NODES UNDER 'stylesheet &amp; source'
  AND RECREATE THIS BY SELECTING 'stylesheet &amp; source' AND USING CTRL-B

  AUTOMATICALLY GENERATED FROM:
  file:///home/tbrown/.leo/myLeoSettings.leo#@settings--&gt;leo_dark%20theme%200%20settings--&gt;stylesheet%20&amp;%20source
  2013-11-20 21:18
*/

/*### Color styles ##########################################################*/


/*### Color styles--&gt;base ###################################################*/
QWidget { color: @solarized-base1; background-color: @solarized-base03; 
  border-color: @solarized-base1; 
}

/*### Color styles--&gt;body editor ############################################*/
QTextEdit#richTextEdit {
    background-color: @solarized-base03;
    color: @text-foreground; /* bodytextforegroundcolor; */
    selection-color: @solarized-base03;
    selection-background-color: @solarized-yellow;
}

/*### Color styles--&gt;tree ###################################################*/
QTreeView {
    /* These apply to the selected item, but not to editing items.*/
    /* background-color: #ffffff; */ /* #ffffec; Leo's traditional tree color */
    background-color: @solarized-base03;
    color: @solarized-base0;
    selection-color: @solarized-orange;
    selection-background-color: @solarized-base03;
    show-decoration-selected: 0;
 }
QTreeWidget::selected {
    background: @solarized-green; color: @solarized-base03; 
}
QTreeWidget::active:selected {
    background: @solarized-yellow; color: @solarized-base03; 
}

QTreeView::item:selected {
    background: @solarized-green; color: @solarized-base03; 
}
QTreeView::item:active:selected {
    background: @solarized-yellow; color: @solarized-base03; 
}

/* Headline edit widgets */
QTreeView QLineEdit {
    color: @solarized-base03;
    background-color: @solarized-yellow;
    selection-color: @solarized-base3;
    selection-background-color: @solarized-blue;  
}

/*### Color styles--&gt;log ####################################################*/
/* The log panes */
QTextEdit#log-widget {
    /*background-color: #ffffec;*/ /* #f2fdff; */
    background-color: @log_text_background_color; /* solarized dark */
    color: @log_text_foreground_color; /* solarized dark */
    selection-color: white;
    selection-background-color: blue;
}

/*### Color styles--&gt;mini-buffer &amp; status ###################################*/
/* The mini-buffer */
QLineEdit#lineEdit {
    background-color: @solarized-base03;
    color: red; 
    selection-color: red;
    selection-background-color: lightgrey;
}

QLabel#minibufferLabel { color: @solarized-violet; }

QLineEdit#status1 {
    background-color: @solarized-base03;
    border-color: @solarized-base02;
}

QLineEdit#status2 {
    background-color: @solarized-base03;
    border-color: @solarized-base02;
}

/*### Color styles--&gt;line edit ##############################################*/
QLineEdit { border: none; padding: 3px; }

/*### Color styles--&gt;labels #################################################*/
QLabel { color: @solarized-base1; }

/*### Color styles--&gt;buttons ################################################*/
QPushButton { color: @text-foreground; background: @bg-gradient; }
QPushButton:hover { color: @button-hover-fg; background: @bg-gradient-hover; }

/*### Color styles--&gt;tab bar ################################################*/
QTabBar::tab { color: @text-foreground; 
background: @bg-gradient; margin-right: 5px; padding: 2px; 
}
QTabBar::tab:selected { color: @solarized-green; } 
QTabBar::tab:hover { background: @bg-gradient-hover; color: @button-hover-fg; }

/*### Color styles--&gt;menus ##################################################*/
QMenu { color: @text-foreground-bright }
QMenuBar::item:selected { color: @button-hover-fg; background: @bg-gradient-hover; }
QMenu::item:selected { color: @button-hover-fg; background: @bg-gradient-hover; }
QMenuBar::item { color: @text-foreground; background: @bg-gradient; }
QMenuBar::item:pressed { color: @text-foreground-bright; background: @bg-gradient; }

/*### Color styles--&gt;scrollbar ##############################################*/
QScrollBar::add-page, QScrollBar::sub-page {
  background: @solarized-base03; }
QScrollBar::handle { 
  background: @solarized-base01; color: @solarized-base01; }
QScrollBar::handle:hover { 
  background: @solarized-base0; color: @solarized-base0; }
/* to make these show up, remove the ::handle style above... bug? */
QScrollBar::add-line, QScrollBar::sub-line { 
  background: @solarized-base01; color: @solarized-base01; }

/*### Color styles--&gt;splitters ##############################################*/
QSplitter::handle {
    background-color: @splitter-bg;  /* #CAE1FF;  lightSteelBlue1 */
}
QSplitter::handle:hover {
    background-color: @splitter-hover-bg;  /* #CAE1FF;  lightSteelBlue1 */
}

/*### Color styles--&gt;minibuffer #############################################*/
QLineEdit#lineEdit {
    color: @minibuffer_foreground_color;
    background-color: @minibuffer_background_color;
}

QLineEdit#lineEdit[style_class ~= 'minibuffer_warning'] {
    background-color: @minibuffer_warning_color;
}

QLineEdit#lineEdit[style_class ~= 'minibuffer_error'] {
    color: @minibuffer_error_color;
    background-color: @minibuffer_warning_color;
}

/*### Non-color styles (fonts etc.) #########################################*/


/*### Non-color styles (fonts etc.)--&gt;border ################################*/
/* alternative active pane highlighting */
QTextEdit#log-widget, LeoQTreeWidget#treeWidget, QTextEdit#richTextEdit { 
  border-style: @focused-border-style;
  border-width: @focused-border-width; 
  border-color: @focused-border-unfocus-color; 
}
QTextEdit:focus#log-widget, LeoQTreeWidget:focus#treeWidget, QTextEdit:focus#richTextEdit { 
  border-color: @focused-border-focus-color; 
}
QTextEdit:hover#log-widget, LeoQTreeWidget:hover#treeWidget, QTextEdit:hover#richTextEdit { 
  border-color: @focused-border-hover-color; 
}

/*### Non-color styles (fonts etc.)--&gt;controls, default font size ###########*/
QPushButton, QDoubleSpinBox, QSpinBox, QDateEdit, QTimeEdit { border: none; padding: 3px; margin-right: 5px; }

QWidget { font-size: 16px }

/*### Non-color styles (fonts etc.)--&gt;body editor ###########################*/
/* The body pane */
QTextEdit#richTextEdit {
    font-family: @font-family-body;
    /* font-family: Courier New; */
    font-size: @font-size-body;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

/*### Non-color styles (fonts etc.)--&gt;tab bar ###############################*/
QTabBar::tab { 
   margin-right: 5px; padding: 2px; 
}

/*### Non-color styles (fonts etc.)--&gt;scroll bars ###########################*/
QScrollBar::horizontal {
     height: 7px;
}

QScrollBar::vertical {
     width: 7px;
}

/*### Non-color styles (fonts etc.)--&gt;tree ##################################*/
QTreeWidget {
    /* These apply to the selected item, but not to editing items.*/
    /* font-family: SansSerif; */
    font-family: @font-family-tree;
    font-size: @font-size-tree;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
 }

/* Headline edit widgets */
QTreeWidget QLineEdit {
    font-family: @font-family-tree;
    font-size: @font-size-tree;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */ 
}

/*### Non-color styles (fonts etc.)--&gt;log ###################################*/
/* The log panes */
QTextEdit#log-widget {
    /* font-family: Courier New; */
    font-family: @font-family-log;
    font-size: @font-size-log;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/*### Non-color styles (fonts etc.)--&gt;mini-buffer &amp; status ##################*/
/* The mini-buffer */
QLineEdit#lineEdit {
    font-family: @font-family;
    font-size: 12px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

QLineEdit#status1 {
    border-width: 1px;
    border-style: solid;
}

QLineEdit#status2 {
    border-width: 1px;
    border-style: solid;
}

</t>
<t tx="tbrown.20131122094200.3914">/*
  DON'T EDIT THIS, EDIT THE OTHER NODES UNDER 'stylesheet &amp; source'
  AND RECREATE THIS BY SELECTING 'stylesheet &amp; source' AND USING CTRL-B

  AUTOMATICALLY GENERATED FROM:
  file:///home/tbrown/.leo/myLeoSettings.leo#@settings--&gt;leo_dark%20theme%200%20settings--&gt;stylesheet%20&amp;%20source
  2013-11-21 09:12
*/

/*### Color styles ##########################################################*/


/*### Color styles--&gt;base ###################################################*/
QWidget { color: @solarized-base1; background-color: @solarized-base03; 
  border-color: @solarized-base1; 
}

/*### Color styles--&gt;body editor ############################################*/
QTextEdit#richTextEdit {
    background-color: @solarized-base03;
    color: @text-foreground; /* bodytextforegroundcolor; */
    selection-color: @solarized-base03;
    selection-background-color: @solarized-yellow;
}

/*### Color styles--&gt;tree ###################################################*/
QTreeView {
    /* These apply to the selected item, but not to editing items.*/
    /* background-color: #ffffff; */ /* #ffffec; Leo's traditional tree color */
    background-color: @solarized-base03;
    color: @solarized-base0;
    selection-color: @solarized-orange;
    selection-background-color: @solarized-base03;
    show-decoration-selected: 0;
 }
QTreeWidget::selected {
    background: @solarized-green; color: @solarized-base03; 
}
QTreeWidget::active:selected {
    background: @solarized-yellow; color: @solarized-base03; 
}

QTreeView::item:selected {
    background: @solarized-green; color: @solarized-base03; 
}
QTreeView::item:active:selected {
    background: @solarized-yellow; color: @solarized-base03; 
}

/* Headline edit widgets */
QTreeView QLineEdit {
    color: @solarized-base03;
    background-color: @solarized-yellow;
    selection-color: @solarized-base3;
    selection-background-color: @solarized-blue;  
}

/*### Color styles--&gt;log ####################################################*/
/* The log panes */
QTextEdit#log-widget {
    /*background-color: #ffffec;*/ /* #f2fdff; */
    background-color: @log_text_background_color; /* solarized dark */
    color: @log_text_foreground_color; /* solarized dark */
    selection-color: white;
    selection-background-color: blue;
}

/*### Color styles--&gt;mini-buffer &amp; status ###################################*/
/* The mini-buffer */
QLineEdit#lineEdit {
    background-color: @solarized-base03;
    color: red; 
    selection-color: red;
    selection-background-color: lightgrey;
}

QLabel#minibufferLabel { color: @solarized-violet; }

QLineEdit#status1 {
    background-color: @solarized-base03;
    border-color: @solarized-base02;
}

QLineEdit#status2 {
    background-color: @solarized-base03;
    border-color: @solarized-base02;
}

/*### Color styles--&gt;line edit ##############################################*/
QLineEdit { border: none; padding: 3px; }

/*### Color styles--&gt;labels #################################################*/
QLabel { color: @solarized-base1; }

/*### Color styles--&gt;buttons ################################################*/
QPushButton { color: @text-foreground; background: @bg-gradient; }
QPushButton:hover { color: @button-hover-fg; background: @bg-gradient-hover; }

/*### Color styles--&gt;tab bar ################################################*/
QTabBar::tab { color: @text-foreground; 
background: @bg-gradient; margin-right: 5px; padding: 2px; 
}
QTabBar::tab:selected { color: @solarized-green; } 
QTabBar::tab:hover { background: @bg-gradient-hover; color: @button-hover-fg; }

/*### Color styles--&gt;menus ##################################################*/
QMenu { color: @text-foreground-bright }
QMenuBar::item:selected { color: @button-hover-fg; background: @bg-gradient-hover; }
QMenu::item:selected { color: @button-hover-fg; background: @bg-gradient-hover; }
QMenuBar::item { color: @text-foreground; background: @bg-gradient; }
QMenuBar::item:pressed { color: @text-foreground-bright; background: @bg-gradient; }

/*### Color styles--&gt;scrollbar ##############################################*/
QScrollBar::add-page, QScrollBar::sub-page {
  background: @solarized-base03; }
QScrollBar::handle { 
  background: @solarized-base01; color: @solarized-base01; }
QScrollBar::handle:hover { 
  background: @solarized-base0; color: @solarized-base0; }
/* to make these show up, remove the ::handle style above... bug? */
QScrollBar::add-line, QScrollBar::sub-line { 
  background: @solarized-base01; color: @solarized-base01; }

/*### Color styles--&gt;splitters ##############################################*/
QSplitter::handle {
    background-color: @splitter-bg;  /* #CAE1FF;  lightSteelBlue1 */
}
QSplitter::handle:hover {
    background-color: @splitter-hover-bg;  /* #CAE1FF;  lightSteelBlue1 */
}

/*### Color styles--&gt;minibuffer #############################################*/
QLineEdit#lineEdit {
    color: @minibuffer_foreground_color;
    background-color: @minibuffer_background_color;
}

QLineEdit#lineEdit[style_class ~= 'minibuffer_warning'] {
    background-color: @minibuffer_warning_color;
}

QLineEdit#lineEdit[style_class ~= 'minibuffer_error'] {
    color: @minibuffer_error_color;
    background-color: @minibuffer_warning_color;
}

/*### Non-color styles (fonts etc.) #########################################*/


/*### Non-color styles (fonts etc.)--&gt;border ################################*/
/* alternative active pane highlighting */
QTextEdit#log-widget, LeoQTreeWidget#treeWidget, QTextEdit#richTextEdit { 
  border-style: @focused-border-style;
  border-width: @focused-border-width; 
  border-color: @focused-border-unfocus-color; 
}
QTextEdit:focus#log-widget, LeoQTreeWidget:focus#treeWidget, QTextEdit:focus#richTextEdit { 
  border-color: @focused-border-focus-color; 
}
QTextEdit:hover#log-widget, LeoQTreeWidget:hover#treeWidget, QTextEdit:hover#richTextEdit { 
  border-color: @focused-border-hover-color; 
}

/*### Non-color styles (fonts etc.)--&gt;controls, default font size ###########*/
QPushButton, QDoubleSpinBox, QSpinBox, QDateEdit, QTimeEdit { border: none; padding: 3px; margin-right: 5px; }

QWidget { font-size: 16px }

/*### Non-color styles (fonts etc.)--&gt;body editor ###########################*/
/* The body pane */
QTextEdit#richTextEdit {
    font-family: @font-family-body;
    /* font-family: Courier New; */
    font-size: @font-size-body;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

/*### Non-color styles (fonts etc.)--&gt;tab bar ###############################*/
QTabBar::tab { 
   margin-right: 5px; padding: 2px; 
}

/*### Non-color styles (fonts etc.)--&gt;scroll bars ###########################*/
QScrollBar::horizontal {
     height: 7px;
}

QScrollBar::vertical {
     width: 7px;
}

/*### Non-color styles (fonts etc.)--&gt;tree ##################################*/
QTreeWidget {
    /* These apply to the selected item, but not to editing items.*/
    /* font-family: SansSerif; */
    font-family: @font-family-tree;
    font-size: @font-size-tree;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
 }

/* Headline edit widgets */
QTreeWidget QLineEdit {
    font-family: @font-family-tree;
    font-size: @font-size-tree;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */ 
}

/*### Non-color styles (fonts etc.)--&gt;log ###################################*/
/* The log panes */
QTextEdit#log-widget {
    /* font-family: Courier New; */
    font-family: @font-family-log;
    font-size: @font-size-log;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/*### Non-color styles (fonts etc.)--&gt;mini-buffer &amp; status ##################*/
/* The mini-buffer */
QLineEdit#lineEdit {
    font-family: @font-family;
    font-size: 12px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

QLineEdit#status1 {
    border-width: 1px;
    border-style: solid;
}

QLineEdit#status2 {
    border-width: 1px;
    border-style: solid;
}

</t>
<t tx="tbrown.20131122094200.3915">/*
  DON'T EDIT THIS, EDIT THE OTHER NODES UNDER 'stylesheet &amp; source'
  AND RECREATE THIS BY SELECTING 'stylesheet &amp; source' AND USING CTRL-B

  AUTOMATICALLY GENERATED FROM:
  file:///home/tbrown/.leo/myLeoSettings.leo#@settings--&gt;leo_dark%20theme%200%20settings--&gt;stylesheet%20&amp;%20source
  2013-11-21 09:12
*/

/*### Color styles ##########################################################*/


/*### Color styles--&gt;base ###################################################*/
QWidget { color: @solarized-base1; background-color: @solarized-base03; 
  border-color: @solarized-base1; 
}

/*### Color styles--&gt;body editor ############################################*/
QTextEdit#richTextEdit {
    background-color: @solarized-base03;
    color: @text-foreground; /* bodytextforegroundcolor; */
    selection-color: @solarized-base03;
    selection-background-color: @solarized-yellow;
}

/*### Color styles--&gt;tree ###################################################*/
QTreeView {
    /* These apply to the selected item, but not to editing items.*/
    /* background-color: #ffffff; */ /* #ffffec; Leo's traditional tree color */
    background-color: @solarized-base03;
    color: @solarized-base0;
    selection-color: @solarized-orange;
    selection-background-color: @solarized-base03;
    show-decoration-selected: 0;
 }
QTreeWidget::selected {
    background: @solarized-green; color: @solarized-base03; 
}
QTreeWidget::active:selected {
    background: @solarized-yellow; color: @solarized-base03; 
}

QTreeView::item:selected {
    background: @solarized-green; color: @solarized-base03; 
}
QTreeView::item:active:selected {
    background: @solarized-yellow; color: @solarized-base03; 
}

/* Headline edit widgets */
QTreeView QLineEdit {
    color: @solarized-base03;
    background-color: @solarized-yellow;
    selection-color: @solarized-base3;
    selection-background-color: @solarized-blue;  
}

/*### Color styles--&gt;log ####################################################*/
/* The log panes */
QTextEdit#log-widget {
    /*background-color: #ffffec;*/ /* #f2fdff; */
    background-color: @log_text_background_color; /* solarized dark */
    color: @log_text_foreground_color; /* solarized dark */
    selection-color: white;
    selection-background-color: blue;
}

/*### Color styles--&gt;mini-buffer &amp; status ###################################*/
/* The mini-buffer */
QLineEdit#lineEdit {
    background-color: @solarized-base03;
    color: red; 
    selection-color: red;
    selection-background-color: lightgrey;
}

QLabel#minibufferLabel { color: @solarized-violet; }

QLineEdit#status1 {
    background-color: @solarized-base03;
    border-color: @solarized-base02;
}

QLineEdit#status2 {
    background-color: @solarized-base03;
    border-color: @solarized-base02;
}

/*### Color styles--&gt;line edit ##############################################*/
QLineEdit { border: none; padding: 3px; }

/*### Color styles--&gt;labels #################################################*/
QLabel { color: @solarized-base1; }

/*### Color styles--&gt;buttons ################################################*/
QPushButton { color: @text-foreground; background: @bg-gradient; }
QPushButton:hover { color: @button-hover-fg; background: @bg-gradient-hover; }

/*### Color styles--&gt;tab bar ################################################*/
QTabBar::tab { color: @text-foreground; 
background: @bg-gradient; margin-right: 5px; padding: 2px; 
}
QTabBar::tab:selected { color: @solarized-green; } 
QTabBar::tab:hover { background: @bg-gradient-hover; color: @button-hover-fg; }

/*### Color styles--&gt;menus ##################################################*/
QMenu { color: @text-foreground-bright }
QMenuBar::item:selected { color: @button-hover-fg; background: @bg-gradient-hover; }
QMenu::item:selected { color: @button-hover-fg; background: @bg-gradient-hover; }
QMenuBar::item { color: @text-foreground; background: @bg-gradient; }
QMenuBar::item:pressed { color: @text-foreground-bright; background: @bg-gradient; }

/*### Color styles--&gt;scrollbar ##############################################*/
QScrollBar::add-page, QScrollBar::sub-page {
  background: @solarized-base03; }
QScrollBar::handle { 
  background: @solarized-base01; color: @solarized-base01; }
QScrollBar::handle:hover { 
  background: @solarized-base0; color: @solarized-base0; }
/* to make these show up, remove the ::handle style above... bug? */
QScrollBar::add-line, QScrollBar::sub-line { 
  background: @solarized-base01; color: @solarized-base01; }

/*### Color styles--&gt;splitters ##############################################*/
QSplitter::handle {
    background-color: @splitter-bg;  /* #CAE1FF;  lightSteelBlue1 */
}
QSplitter::handle:hover {
    background-color: @splitter-hover-bg;  /* #CAE1FF;  lightSteelBlue1 */
}

/*### Color styles--&gt;minibuffer #############################################*/
QLineEdit#lineEdit {
    color: @minibuffer_foreground_color;
    background-color: @minibuffer_background_color;
}

QLineEdit#lineEdit[style_class ~= 'minibuffer_warning'] {
    background-color: @minibuffer_warning_color;
}

QLineEdit#lineEdit[style_class ~= 'minibuffer_error'] {
    color: @minibuffer_error_color;
    background-color: @minibuffer_warning_color;
}

/*### Non-color styles (fonts etc.) #########################################*/


/*### Non-color styles (fonts etc.)--&gt;border ################################*/
/* alternative active pane highlighting */
QTextEdit#log-widget, LeoQTreeWidget#treeWidget, QTextEdit#richTextEdit { 
  border-style: @focused-border-style;
  border-width: @focused-border-width; 
  border-color: @focused-border-unfocus-color; 
}
QTextEdit:focus#log-widget, LeoQTreeWidget:focus#treeWidget, QTextEdit:focus#richTextEdit { 
  border-color: @focused-border-focus-color; 
}
QTextEdit:hover#log-widget, LeoQTreeWidget:hover#treeWidget, QTextEdit:hover#richTextEdit { 
  border-color: @focused-border-hover-color; 
}

/*### Non-color styles (fonts etc.)--&gt;controls, default font size ###########*/
QPushButton, QDoubleSpinBox, QSpinBox, QDateEdit, QTimeEdit { border: none; padding: 3px; margin-right: 5px; }

QWidget { font-size: 16px }

/*### Non-color styles (fonts etc.)--&gt;body editor ###########################*/
/* The body pane */
QTextEdit#richTextEdit {
    font-family: @font-family-body;
    /* font-family: Courier New; */
    font-size: @font-size-body;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

/*### Non-color styles (fonts etc.)--&gt;tab bar ###############################*/
QTabBar::tab { 
   margin-right: 5px; padding: 2px; 
}

/*### Non-color styles (fonts etc.)--&gt;scroll bars ###########################*/
QScrollBar::horizontal {
     height: 7px;
}

QScrollBar::vertical {
     width: 7px;
}

/*### Non-color styles (fonts etc.)--&gt;tree ##################################*/
QTreeWidget {
    /* These apply to the selected item, but not to editing items.*/
    /* font-family: SansSerif; */
    font-family: @font-family-tree;
    font-size: @font-size-tree;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
 }

/* Headline edit widgets */
QTreeWidget QLineEdit {
    font-family: @font-family-tree;
    font-size: @font-size-tree;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */ 
}

/*### Non-color styles (fonts etc.)--&gt;log ###################################*/
/* The log panes */
QTextEdit#log-widget {
    /* font-family: Courier New; */
    font-family: @font-family-log;
    font-size: @font-size-log;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/*### Non-color styles (fonts etc.)--&gt;mini-buffer &amp; status ##################*/
/* The mini-buffer */
QLineEdit#lineEdit {
    font-family: @font-family;
    font-size: 12px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

QLineEdit#status1 {
    border-width: 1px;
    border-style: solid;
}

QLineEdit#status2 {
    border-width: 1px;
    border-style: solid;
}

</t>
<t tx="tbrown.20131122094200.3916">/*
  DON'T EDIT THIS, EDIT THE OTHER NODES UNDER 'stylesheet &amp; source'
  AND RECREATE THIS BY SELECTING 'stylesheet &amp; source' AND USING CTRL-B

  AUTOMATICALLY GENERATED FROM:
  file:///home/tbrown/.leo/myLeoSettings.leo#@settings--&gt;leo_dark%20theme%200%20settings--&gt;stylesheet%20&amp;%20source
  2013-11-21 09:12
*/

/*### Color styles ##########################################################*/


/*### Color styles--&gt;base ###################################################*/
QWidget { color: @solarized-base1; background-color: @solarized-base03; 
  border-color: @solarized-base1; 
}

/*### Color styles--&gt;body editor ############################################*/
QTextEdit#richTextEdit {
    background-color: @solarized-base03;
    color: @text-foreground; /* bodytextforegroundcolor; */
    selection-color: @solarized-base03;
    selection-background-color: @solarized-yellow;
}

/*### Color styles--&gt;tree ###################################################*/
QTreeView {
    /* These apply to the selected item, but not to editing items.*/
    /* background-color: #ffffff; */ /* #ffffec; Leo's traditional tree color */
    background-color: @solarized-base03;
    color: @solarized-base0;
    selection-color: @solarized-orange;
    selection-background-color: @solarized-base03;
    show-decoration-selected: 0;
 }
QTreeWidget::selected {
    background: @solarized-green; color: @solarized-base03; 
}
QTreeWidget::active:selected {
    background: @solarized-yellow; color: @solarized-base03; 
}

QTreeView::item:selected {
    background: @solarized-green; color: @solarized-base03; 
}
QTreeView::item:active:selected {
    background: @solarized-yellow; color: @solarized-base03; 
}

/* Headline edit widgets */
QTreeView QLineEdit {
    color: @solarized-base03;
    background-color: @solarized-yellow;
    selection-color: @solarized-base3;
    selection-background-color: @solarized-blue;  
}

/*### Color styles--&gt;log ####################################################*/
/* The log panes */
QTextEdit#log-widget {
    /*background-color: #ffffec;*/ /* #f2fdff; */
    background-color: @log_text_background_color; /* solarized dark */
    color: @log_text_foreground_color; /* solarized dark */
    selection-color: white;
    selection-background-color: blue;
}

/*### Color styles--&gt;mini-buffer &amp; status ###################################*/
/* The mini-buffer */
QLineEdit#lineEdit {
    background-color: @solarized-base03;
    color: red; 
    selection-color: red;
    selection-background-color: lightgrey;
}

QLabel#minibufferLabel { color: @solarized-violet; }

QLineEdit#status1 {
    background-color: @solarized-base03;
    border-color: @solarized-base02;
}

QLineEdit#status2 {
    background-color: @solarized-base03;
    border-color: @solarized-base02;
}

/*### Color styles--&gt;line edit ##############################################*/
QLineEdit { border: none; padding: 3px; }

/*### Color styles--&gt;labels #################################################*/
QLabel { color: @solarized-base1; }

/*### Color styles--&gt;buttons ################################################*/
QPushButton { color: @text-foreground; background: @bg-gradient; }
QPushButton:hover { color: @button-hover-fg; background: @bg-gradient-hover; }

/*### Color styles--&gt;tab bar ################################################*/
QTabBar::tab { color: @text-foreground; 
background: @bg-gradient; margin-right: 5px; padding: 2px; 
}
QTabBar::tab:selected { color: @solarized-green; } 
QTabBar::tab:hover { background: @bg-gradient-hover; color: @button-hover-fg; }

/*### Color styles--&gt;menus ##################################################*/
QMenu { color: @text-foreground-bright }
QMenuBar::item:selected { color: @button-hover-fg; background: @bg-gradient-hover; }
QMenu::item:selected { color: @button-hover-fg; background: @bg-gradient-hover; }
QMenuBar::item { color: @text-foreground; background: @bg-gradient; }
QMenuBar::item:pressed { color: @text-foreground-bright; background: @bg-gradient; }

/*### Color styles--&gt;scrollbar ##############################################*/
QScrollBar::add-page, QScrollBar::sub-page {
  background: @solarized-base03; }
QScrollBar::handle { 
  background: @solarized-base01; color: @solarized-base01; }
QScrollBar::handle:hover { 
  background: @solarized-base0; color: @solarized-base0; }
/* to make these show up, remove the ::handle style above... bug? */
QScrollBar::add-line, QScrollBar::sub-line { 
  background: @solarized-base01; color: @solarized-base01; }

/*### Color styles--&gt;splitters ##############################################*/
QSplitter::handle {
    background-color: @splitter-bg;  /* #CAE1FF;  lightSteelBlue1 */
}
QSplitter::handle:hover {
    background-color: @splitter-hover-bg;  /* #CAE1FF;  lightSteelBlue1 */
}

/*### Color styles--&gt;minibuffer #############################################*/
QLineEdit#lineEdit {
    color: @minibuffer_foreground_color;
    background-color: @minibuffer_background_color;
}

QLineEdit#lineEdit[style_class ~= 'minibuffer_warning'] {
    background-color: @minibuffer_warning_color;
}

QLineEdit#lineEdit[style_class ~= 'minibuffer_error'] {
    color: @minibuffer_error_color;
    background-color: @minibuffer_warning_color;
}

/*### Non-color styles (fonts etc.) #########################################*/


/*### Non-color styles (fonts etc.)--&gt;border ################################*/
/* alternative active pane highlighting */
QTextEdit#log-widget, LeoQTreeWidget#treeWidget, QTextEdit#richTextEdit { 
  border-style: @focused-border-style;
  border-width: @focused-border-width; 
  border-color: @focused-border-unfocus-color; 
}
QTextEdit:focus#log-widget, LeoQTreeWidget:focus#treeWidget, QTextEdit:focus#richTextEdit { 
  border-color: @focused-border-focus-color; 
}
QTextEdit:hover#log-widget, LeoQTreeWidget:hover#treeWidget, QTextEdit:hover#richTextEdit { 
  border-color: @focused-border-hover-color; 
}

/*### Non-color styles (fonts etc.)--&gt;controls, default font size ###########*/
QPushButton, QDoubleSpinBox, QSpinBox, QDateEdit, QTimeEdit { border: none; padding: 3px; margin-right: 5px; }

QWidget { font-size: 16px }

/*### Non-color styles (fonts etc.)--&gt;body editor ###########################*/
/* The body pane */
QTextEdit#richTextEdit {
    font-family: @font-family-body;
    /* font-family: Courier New; */
    font-size: @font-size-body;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

/*### Non-color styles (fonts etc.)--&gt;tab bar ###############################*/
QTabBar::tab { 
   margin-right: 5px; padding: 2px; 
}

/*### Non-color styles (fonts etc.)--&gt;scroll bars ###########################*/
QScrollBar::horizontal {
     height: 7px;
}

QScrollBar::vertical {
     width: 7px;
}

/*### Non-color styles (fonts etc.)--&gt;tree ##################################*/
QTreeWidget {
    /* These apply to the selected item, but not to editing items.*/
    /* font-family: SansSerif; */
    font-family: @font-family-tree;
    font-size: @font-size-tree;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
 }

/* Headline edit widgets */
QTreeWidget QLineEdit {
    font-family: @font-family-tree;
    font-size: @font-size-tree;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */ 
}

/*### Non-color styles (fonts etc.)--&gt;log ###################################*/
/* The log panes */
QTextEdit#log-widget {
    /* font-family: Courier New; */
    font-family: @font-family-log;
    font-size: @font-size-log;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/*### Non-color styles (fonts etc.)--&gt;mini-buffer &amp; status ##################*/
/* The mini-buffer */
QLineEdit#lineEdit {
    font-family: @font-family;
    font-size: 12px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

QLineEdit#status1 {
    border-width: 1px;
    border-style: solid;
}

QLineEdit#status2 {
    border-width: 1px;
    border-style: solid;
}

</t>
<t tx="tbrown.20131122094200.3917">/*
  DON'T EDIT THIS, EDIT THE OTHER NODES UNDER 'stylesheet &amp; source'
  AND RECREATE THIS BY SELECTING 'stylesheet &amp; source' AND USING CTRL-B

  AUTOMATICALLY GENERATED FROM:
  file:///home/tbrown/.leo/myLeoSettings.leo#@settings--&gt;leo_dark%20theme%200%20settings--&gt;stylesheet%20&amp;%20source
  2013-11-22 09:41
*/

/*### Color styles ##########################################################*/


/*### Color styles--&gt;base ###################################################*/
QWidget { color: @solarized-base1; background-color: @solarized-base03; 
  border-color: @solarized-base1; 
}

/*### Color styles--&gt;body editor ############################################*/
QTextEdit#richTextEdit {
    background-color: @solarized-base03;
    color: @text-foreground; /* bodytextforegroundcolor; */
    selection-color: @solarized-base03;
    selection-background-color: @solarized-yellow;
}

/*### Color styles--&gt;tree ###################################################*/
QTreeView {
    /* These apply to the selected item, but not to editing items.*/
    /* background-color: #ffffff; */ /* #ffffec; Leo's traditional tree color */
    background-color: @solarized-base03;
    color: @solarized-base0;
    selection-color: @solarized-orange;
    selection-background-color: @solarized-base03;
    show-decoration-selected: 0;
 }
QTreeWidget::selected {
    background: @solarized-green; color: @solarized-base03; 
}
QTreeWidget::active:selected {
    background: @solarized-yellow; color: @solarized-base03; 
}

QTreeView::item:selected {
    background: @solarized-green; color: @solarized-base03; 
}
QTreeView::item:active:selected {
    background: @solarized-yellow; color: @solarized-base03; 
}

/* Headline edit widgets */
QTreeView QLineEdit {
    color: @solarized-base03;
    background-color: @solarized-yellow;
    selection-color: @solarized-base3;
    selection-background-color: @solarized-blue;  
}

/*### Color styles--&gt;log ####################################################*/
/* The log panes */
QTextEdit#log-widget {
    /*background-color: #ffffec;*/ /* #f2fdff; */
    background-color: @log_text_background_color; /* solarized dark */
    color: @log_text_foreground_color; /* solarized dark */
    selection-color: white;
    selection-background-color: blue;
}

/*### Color styles--&gt;mini-buffer &amp; status ###################################*/
/* The mini-buffer */
QLineEdit#lineEdit {
    background-color: @solarized-base03;
    color: red; 
    selection-color: red;
    selection-background-color: lightgrey;
}

QLabel#minibufferLabel { color: @solarized-violet; }

QLineEdit#status1 {
    background-color: @solarized-base03;
    border-color: @solarized-base02;
}

QLineEdit#status2 {
    background-color: @solarized-base03;
    border-color: @solarized-base02;
}

/*### Color styles--&gt;line edit ##############################################*/
QLineEdit { border: none; padding: 3px; }

/*### Color styles--&gt;labels #################################################*/
QLabel { color: @solarized-base1; }

/*### Color styles--&gt;buttons ################################################*/
QPushButton { color: @text-foreground; background: @bg-gradient; }
QPushButton:hover { color: @button-hover-fg; background: @bg-gradient-hover; }

/*### Color styles--&gt;tab bar ################################################*/
QTabBar::tab { color: @text-foreground; 
background: @bg-gradient; margin-right: 5px; padding: 2px; 
}
QTabBar::tab:selected { color: @solarized-green; } 
QTabBar::tab:hover { background: @bg-gradient-hover; color: @button-hover-fg; }

/*### Color styles--&gt;menus ##################################################*/
QMenu { color: @text-foreground-bright }
QMenuBar::item:selected { color: @button-hover-fg; background: @bg-gradient-hover; }
QMenu::item:selected { color: @button-hover-fg; background: @bg-gradient-hover; }
QMenuBar::item { color: @text-foreground; background: @bg-gradient; }
QMenuBar::item:pressed { color: @text-foreground-bright; background: @bg-gradient; }

/*### Color styles--&gt;scrollbar ##############################################*/
QScrollBar::add-page, QScrollBar::sub-page {
  background: @solarized-base03; }
QScrollBar::handle { 
  background: @solarized-base01; color: @solarized-base01; }
QScrollBar::handle:hover { 
  background: @solarized-base0; color: @solarized-base0; }
/* to make these show up, remove the ::handle style above... bug? */
QScrollBar::add-line, QScrollBar::sub-line { 
  background: @solarized-base01; color: @solarized-base01; }

/*### Color styles--&gt;splitters ##############################################*/
QSplitter::handle {
    background-color: @splitter-bg;  /* #CAE1FF;  lightSteelBlue1 */
}
QSplitter::handle:hover {
    background-color: @splitter-hover-bg;  /* #CAE1FF;  lightSteelBlue1 */
}

/*### Color styles--&gt;minibuffer #############################################*/
QLineEdit#lineEdit {
    color: @minibuffer_foreground_color;
    background-color: @minibuffer_background_color;
}

QLineEdit#lineEdit[style_class ~= 'minibuffer_warning'] {
    background-color: @minibuffer_warning_color;
}

QLineEdit#lineEdit[style_class ~= 'minibuffer_error'] {
    color: @minibuffer_error_color;
    background-color: @minibuffer_warning_color;
}

/*### Non-color styles (fonts etc.) #########################################*/


/*### Non-color styles (fonts etc.)--&gt;border ################################*/
/* alternative active pane highlighting */
QTextEdit#log-widget, LeoQTreeWidget#treeWidget, QTextEdit#richTextEdit { 
  border-style: @focused-border-style;
  border-width: @focused-border-width; 
  border-color: @focused-border-unfocus-color; 
}
QTextEdit:focus#log-widget, LeoQTreeWidget:focus#treeWidget, QTextEdit:focus#richTextEdit { 
  border-color: @focused-border-focus-color; 
}
QTextEdit:hover#log-widget, LeoQTreeWidget:hover#treeWidget, QTextEdit:hover#richTextEdit { 
  border-color: @focused-border-hover-color; 
}

/*### Non-color styles (fonts etc.)--&gt;controls, default font size ###########*/
QPushButton, QDoubleSpinBox, QSpinBox, QDateEdit, QTimeEdit { border: none; padding: 3px; margin-right: 5px; }

QWidget { font-size: 16px }

/*### Non-color styles (fonts etc.)--&gt;body editor ###########################*/
/* The body pane */
QTextEdit#richTextEdit {
    font-family: @font-family-body;
    /* font-family: Courier New; */
    font-size: @font-size-body;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

/*### Non-color styles (fonts etc.)--&gt;tab bar ###############################*/
QTabBar::tab { 
   margin-right: 5px; padding: 2px; 
}

/*### Non-color styles (fonts etc.)--&gt;scroll bars ###########################*/
QScrollBar::horizontal {
     height: 7px;
}

QScrollBar::vertical {
     width: 7px;
}

/*### Non-color styles (fonts etc.)--&gt;tree ##################################*/
QTreeWidget {
    /* These apply to the selected item, but not to editing items.*/
    /* font-family: SansSerif; */
    font-family: @font-family-tree;
    font-size: @font-size-tree;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
 }

/* Headline edit widgets */
QTreeWidget QLineEdit {
    font-family: @font-family-tree;
    font-size: @font-size-tree;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */ 
}

/*### Non-color styles (fonts etc.)--&gt;log ###################################*/
/* The log panes */
QTextEdit#log-widget {
    /* font-family: Courier New; */
    font-family: @font-family-log;
    font-size: @font-size-log;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/*### Non-color styles (fonts etc.)--&gt;mini-buffer &amp; status ##################*/
/* The mini-buffer */
QLineEdit#lineEdit {
    font-family: @font-family;
    font-size: 12px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

QLineEdit#status1 {
    border-width: 1px;
    border-style: solid;
}

QLineEdit#status2 {
    border-width: 1px;
    border-style: solid;
}

</t>
<t tx="tbrown.20131122094200.3918">Use these settings to get something like the solarized colors.</t>
<t tx="tbrown.20131122094200.3919">base03    #002b36  8/4 brblack  234 #1c1c1c 15 -12 -12   0  43  54 193 100  21
base02    #073642  0/4 black    235 #262626 20 -12 -12   7  54  66 192  90  26
base01    #586e75 10/7 brgreen  240 #585858 45 -07 -07  88 110 117 194  25  46
base00    #657b83 11/7 bryellow 241 #626262 50 -07 -07 101 123 131 195  23  51
base0     #839496 12/6 brblue   244 #808080 60 -06 -03 131 148 150 186  13  59
base1     #93a1a1 14/4 brcyan   245 #8a8a8a 65 -05 -02 147 161 161 180   9  63
base2     #eee8d5  7/7 white    254 #e4e4e4 92 -00  10 238 232 213  44  11  93
base3     #fdf6e3 15/7 brwhite  230 #ffffd7 97  00  10 253 246 227  44  10  99

# These can be used as usual, in *both* light and dark

yellow    #b58900  3/3 yellow   136 #af8700 60  10  65 181 137   0  45 100  71
orange    #cb4b16  9/3 brred    166 #d75f00 50  50  55 203  75  22  18  89  80
red       #dc322f  1/1 red      160 #d70000 50  65  45 220  50  47   1  79  86
magenta   #d33682  5/5 magenta  125 #af005f 50  65 -05 211  54 130 331  74  83
violet    #6c71c4 13/5 brmagenta 61 #5f5faf 50  15 -45 108 113 196 237  45  77
blue      #268bd2  4/4 blue      33 #0087ff 55 -10 -45  38 139 210 205  82  82
cyan      #2aa198  6/6 cyan      37 #00afaf 60 -35 -05  42 161 152 175  74  63
green     #859900  2/2 green     64 #5f8700 60 -20  65 133 153   0  68 100  60

Dark
====

    base1 optional emphasized content (keywords)
  * base0 default (body text)
    
    base01 comments
    base02 background highlights (selected background)
  * base03 background
    
Light
=====

    base01 optional emphasized content (keywords)
  * base00 default (body text)
    base1 comments
    base2 background highlights (selected background)
  * base3 background
</t>
<t tx="tbrown.20131122094200.3920"></t>
<t tx="tbrown.20131122094200.3921"></t>
<t tx="tbrown.20131122094200.3922"></t>
<t tx="tbrown.20131122094200.3923"></t>
<t tx="tbrown.20131122094200.3924">was blue

Solarized blue      #268bd2</t>
<t tx="tbrown.20131122094200.3925">was blue

Solarized blue      #268bd2</t>
<t tx="tbrown.20131122094200.3926">was blue

Solarized blue      #268bd2</t>
<t tx="tbrown.20131122094200.3927">was blue

Solarized blue      #268bd2</t>
<t tx="tbrown.20131122094200.3928">was #00aa00 (Idle comment green)

Solarize green      #859900
Solarized cyan      #2aa198
Solarized violet    #6c71c4
Solarized orange    #cb4b16</t>
<t tx="tbrown.20131122094200.3929"></t>
<t tx="tbrown.20131122094200.3930"></t>
<t tx="tbrown.20131122094200.3931"></t>
<t tx="tbrown.20131122094200.3932">was black</t>
<t tx="tbrown.20131122094200.3933">was firebrick3

Solarized colors:
    
magenta   #d33682

Dark comments   base01
Light comments  base1 comments
</t>
<t tx="tbrown.20131122094200.3934"></t>
<t tx="tbrown.20131122094200.3935"></t>
<t tx="tbrown.20131122094200.3936"></t>
<t tx="tbrown.20131122094200.3937"></t>
<t tx="tbrown.20131122094200.3938"></t>
<t tx="tbrown.20131122094200.3939"></t>
<t tx="tbrown.20131122094200.3940">Background color of body text.  This setting *is* used in the QtGui.

#ffecea

Note: this setting can be overridden by the x_mode_bg_color settings.</t>
<t tx="tbrown.20131122094200.3941">#f9f0f4 light pink
#fbfdfd very light blue

For some reason, colors in the text widget do not match the colors in the canvas widget.</t>
<t tx="tbrown.20131122094200.3942"></t>
<t tx="tbrown.20131122094200.3943">Foreground color of body text.  This setting *is* used in the QtGui.

Note: this setting can be overridden by the x_mode_fg_color settings.</t>
<t tx="tbrown.20131122094200.3944">Overrides body_text_background_color.

#fdf5f5 A light pink.
#f0fde1 A light green.
#f9e6dd A light orange.</t>
<t tx="tbrown.20131122094200.3945">Overrides body_text_foreground_color.</t>
<t tx="tbrown.20131122094200.3946"></t>
<t tx="tbrown.20131122094200.3947">Background color of unselected headline text.

LavenderBlush1</t>
<t tx="tbrown.20131122094200.3948">Foreground color of unselected headline text.</t>
<t tx="tbrown.20131122094200.3949">Background color of selected headline text that is not being edited.

LavenderBlush2</t>
<t tx="tbrown.20131122094200.3950">Foreground color of selected headline text that is not being edited.

DodgerBlue4</t>
<t tx="tbrown.20131122094200.3951">Background color of unselected headline text in a headline that is being edited.

Foreground color must also be specified for either setting to take effect.</t>
<t tx="tbrown.20131122094200.3952">Foreground color of unselected headline text in a headline that is being edited.

Background color must also be specified for either setting to take effect.</t>
<t tx="tbrown.20131122094200.3953">Foreground color of selected text headline text in a headline that is being edited.

Background must also be specified for either setting to take effect.</t>
<t tx="tbrown.20131122094200.3954">Background color of selected text headline text in a headline that is being edited.

Foreground must also be specified for either setting to take effect.</t>
<t tx="tbrown.20131122094200.3955">Background color of outline pane itself.

LavenderBlush1
#ffffe1 # a little too yellow.
#ffffec
LightSteelBlue1 # Good for testing.</t>
<t tx="tbrown.20131122094200.3956"></t>
<t tx="tbrown.20131122094200.3957">LightYellow1

#f2fdff</t>
<t tx="tbrown.20131122094200.3958">#d6c7d3
#d2cad0
#c6d3d7</t>
<t tx="tbrown.20131122094200.3959">#d6c7d3
#d2cad0
#c6d3d7
#ffffec # Same as outline.</t>
<t tx="tbrown.20131122094200.3960"></t>
</tnodes>
</leo_file>
