from typing import Any

gBridgeController: Any

def controller(gui: str = ..., loadPlugins: bool = ..., readSettings: bool = ..., silent: bool = ..., tracePlugins: bool = ..., useCaches: bool = ..., verbose: bool = ...): ...

class BridgeController:
    g: Any
    gui: Any
    guiName: Any
    loadPlugins: Any
    readSettings: Any
    silentMode: Any
    tracePlugins: Any
    useCaches: Any
    verbose: Any
    mainLoop: bool
    def __init__(self, guiName, loadPlugins, readSettings, silent, tracePlugins, useCaches, verbose) -> None: ...
    def globals(self): ...
    def initLeo(self) -> None: ...
    def adjustSysPath(self) -> None: ...
    def createGui(self) -> None: ...
    def isValidPython(self): ...
    def reportDirectories(self) -> None: ...
    def isOpen(self): ...
    def openLeoFile(self, fileName): ...
    def completeFileName(self, fileName): ...
    def createFrame(self, fileName): ...
    def reopen_cachers(self) -> None: ...
