from typing import Any

def import_fail(s) -> None: ...
def qtshell_f(event) -> None: ...
def ipython_exec(event) -> None: ...

class InternalIPKernel:
    consoles: Any
    kernelApp: Any
    namespace: Any
    def __init__(self, backend: str = ...) -> None: ...
    def cleanup_consoles(self, event: Any | None = ...) -> None: ...
    def count(self, event: Any | None = ...) -> None: ...
    def new_qt_console(self, event: Any | None = ...): ...
    def pdb(self, message: str = ...) -> None: ...
    def print_namespace(self, event: Any | None = ...) -> None: ...
    def put_log(self, s, raw: bool = ...) -> None: ...
    def put_stdout(self, s) -> None: ...
    def put_warning(self, s, raw: bool = ...) -> None: ...
    def pylab_kernel(self, gui): ...
    def run(self) -> None: ...
    def run_script(self, file_name, script) -> None: ...
    def test(self) -> None: ...

class LeoNameSpace:
    commander: Any
    commanders_list: Any
    g: Any
    def __init__(self) -> None: ...
    c: Any
    commanders: Any
    def find_c(self, path): ...
    def update(self) -> None: ...
