from leo.core.leoQt import QtGui as QtGui, QtWidgets as QtWidgets, isQt6 as isQt6, printsupport as printsupport
from typing import Any

def cmd(name): ...

class PrintingController:
    c: Any
    def __init__(self, c) -> None: ...
    font_size: Any
    font_family: Any
    stylesheet: Any
    def reload_settings(self) -> None: ...
    reloadSettings: Any
    def construct_stylesheet(self): ...
    def complex_document(self, nodes, heads: bool = ...): ...
    def document(self, text, head: Any | None = ...): ...
    def html_document(self, text): ...
    def expand(self, p): ...
    def getBodies(self, p): ...
    def getNodes(self, p): ...
    def sanitize_html(self, html): ...
    def preview_body(self, event: Any | None = ...) -> None: ...
    def preview_html(self, event: Any | None = ...) -> None: ...
    def preview_expanded_body(self, event: Any | None = ...) -> None: ...
    def preview_expanded_html(self, event: Any | None = ...) -> None: ...
    def preview_marked_bodies(self, event: Any | None = ...) -> None: ...
    def preview_marked_html(self, event: Any | None = ...) -> None: ...
    def preview_marked_nodes(self, event: Any | None = ...) -> None: ...
    def preview_node(self, event: Any | None = ...) -> None: ...
    def preview_tree_bodies(self, event: Any | None = ...) -> None: ...
    def preview_tree_nodes(self, event: Any | None = ...) -> None: ...
    def preview_tree_html(self, event: Any | None = ...) -> None: ...
    def print_body(self, event: Any | None = ...) -> None: ...
    def print_html(self, event: Any | None = ...) -> None: ...
    def print_expanded_body(self, event: Any | None = ...) -> None: ...
    def print_expanded_html(self, event: Any | None = ...) -> None: ...
    def print_marked_bodies(self, event: Any | None = ...) -> None: ...
    def print_marked_html(self, event: Any | None = ...) -> None: ...
    def print_marked_nodes(self, event: Any | None = ...) -> None: ...
    def print_node(self, event: Any | None = ...) -> None: ...
    def print_tree_bodies(self, event: Any | None = ...) -> None: ...
    def print_tree_html(self, event: Any | None = ...) -> None: ...
    def print_tree_nodes(self, event: Any | None = ...) -> None: ...
    def print_doc(self, doc) -> None: ...
    def preview_doc(self, doc) -> None: ...
