from typing import Any

has_rope: bool

class RopeController:
    c: Any
    proj: Any
    def __init__(self, c) -> None: ...
    def modules(self): ...
    def path(self, fn): ...
    def refactor(self) -> None: ...
    def run(self) -> None: ...

def test(c) -> None: ...
