from typing import Any

class LeoSessionException(Exception): ...

class SessionManager:
    path: Any
    def __init__(self) -> None: ...
    def clear_session(self, c) -> None: ...
    def get_session(self): ...
    def get_session_path(self): ...
    def load_session(self, c: Any | None = ..., unls: Any | None = ...) -> None: ...
    def load_snapshot(self): ...
    def save_snapshot(self, c: Any | None = ...) -> None: ...

def session_clear_command(event) -> None: ...
def session_create_command(event) -> None: ...
def session_refresh_command(event) -> None: ...
def session_restore_command(event) -> None: ...
def session_snapshot_load_command(event) -> None: ...
def session_snapshot_save_command(event) -> None: ...
