import unittest
from leo.core import leoserver as leoserver
from leo.core.leoGui import StringFindTabManager as StringFindTabManager
from leo.core.leoNodes import Position as Position
from typing import Any

g: Any
g_leoserver: Any
g_server: Any
wsHost: str
wsPort: int

class InternalServerError(Exception): ...
class ServerError(Exception): ...
class TerminateServer(Exception): ...

class LeoServer:
    c: Any
    dummy_c: Any
    action: Any
    bad_commands_list: Any
    config: Any
    current_id: int
    log_flag: bool
    bridge: Any
    g: Any
    def __init__(self, testing: bool = ...) -> None: ...
    def click_button(self, package): ...
    def get_buttons(self, package): ...
    def remove_button(self, package): ...
    def open_file(self, package): ...
    def close_file(self, package): ...
    def save_file(self, package): ...
    def find_all(self, package): ...
    def change_all(self, package): ...
    def change_then_find(self, package): ...
    def clone_find_all(self, package): ...
    def clone_find_all_flattened(self, package): ...
    def clone_find_tag(self, package): ...
    def find_def(self, package): ...
    def find_next(self, package): ...
    def find_previous(self, package): ...
    def find_var(self, package): ...
    def tag_children(self, package): ...
    def get_all_open_commanders(self, package): ...
    def get_all_positions(self, package): ...
    def get_body(self, package): ...
    def get_body_states(self, package): ...
    def get_children(self, package): ...
    def get_focus(self, packages): ...
    def get_parent(self, package): ...
    def get_position_data_dict(self, package): ...
    def get_ua(self, package): ...
    def get_sign_on(self, package): ...
    def get_ui_states(self, package): ...
    def clone_node(self, package): ...
    def contract_node(self, package): ...
    def cut_node(self, package): ...
    def delete_node(self, package): ...
    def expand_node(self, package): ...
    def insert_node(self, package): ...
    def page_down(self, package): ...
    def page_up(self, package): ...
    def redo(self, package): ...
    def set_body(self, package): ...
    def set_current_position(self, package): ...
    def set_headline(self, package): ...
    def set_selection(self, package): ...
    def toggle_mark(self, package): ...
    def undo(self, package): ...
    def error(self, package) -> None: ...
    def get_all_leo_commands(self, package): ...
    def get_all_server_commands(self, package): ...
    def shut_down(self, package) -> None: ...

class TestLeoServer(unittest.TestCase):
    request_number: int
    @classmethod
    def setUpClass(cls) -> None: ...
    @classmethod
    def tearDownClass(cls) -> None: ...
    server: Any
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def test_leo_commands(self) -> None: ...
    def test_most_public_server_methods(self) -> None: ...
    def test_open_and_close(self) -> None: ...
    def test_find_commands(self) -> None: ...

def main(): ...
