<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5" body_secondary_ratio="0.5">
	<global_window_position top="50" left="50" height="500" width="700"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="ekr.20180307012127.1"><vh>@settings</vh>
<v t="ekr.20180307024753.1"><vh>@theme Breeze Dark</vh>
<v t="ekr.20180307024753.2"><vh>Breeze Dark Color definitions</vh>
<v t="ekr.20180307024753.3"><vh>@color dark-base06 = #3b0000</vh></v>
<v t="ekr.20180307024753.4"><vh>@color dark-base05 = #003b00</vh></v>
<v t="ekr.20180307024753.5"><vh>@color dark-base04 = #000059</vh></v>
<v t="ekr.20180307024753.6"><vh>@color dark-base03 = #31363b</vh></v>
<v t="ekr.20180307024753.7"><vh>@color dark-base02 = #073642</vh></v>
<v t="ekr.20180307024753.8"><vh>@color dark-base01 = #586e75</vh></v>
<v t="ekr.20180307024753.9"><vh>@color dark-base00 = #657b83</vh></v>
<v t="ekr.20180307024753.10"><vh>@color dark-base0 = #fcfcfc</vh></v>
<v t="ekr.20180307024753.11"><vh>@color dark-base1 = #93a1a1</vh></v>
<v t="ekr.20180307024753.12"><vh>@color dark-base2 = #eee8d5</vh></v>
<v t="ekr.20180307024753.13"><vh>@color dark-base3 = #fdf6e3</vh></v>
</v>
<v t="ekr.20180307024753.14"><vh>Settings for Leo Breeze Dark</vh>
<v t="ekr.20180307024753.15"><vh>Colors: Syntax coloring</vh>
<v t="ekr.20180307024753.16"><vh>Colors: defaults</vh>
<v t="ekr.20180307024753.17"><vh>@color blank_color = grey</vh></v>
<v t="ekr.20180307024753.18"><vh>@color tab_color = red</vh></v>
<v t="ekr.20180307024753.19"><vh>@color label_color = red</vh></v>
<v t="ekr.20180307024753.20"><vh>@color keyword1_color = #268bd2</vh></v>
<v t="ekr.20180307024753.21"><vh>@color keyword2_color = #268bd2</vh></v>
<v t="ekr.20180307024753.22"><vh>@color keyword3_color = #268bd2</vh></v>
<v t="ekr.20180307024753.23"><vh>@color keyword4_color = #268bd2</vh></v>
<v t="ekr.20180307024753.24"><vh>@color literal1_color = #859900</vh></v>
<v t="ekr.20180307024753.25"><vh>@color literal2_color = #859900</vh></v>
<v t="ekr.20180307024753.26"><vh>@color literal3_color = #859900</vh></v>
<v t="ekr.20180307024753.27"><vh>@color literal4_color = #859900</vh></v>
<v t="ekr.20180307024753.28"><vh>@color markup_color = #268bd2</vh></v>
<v t="ekr.20180307024753.29"><vh>@color comment1_color = #d33682</vh></v>
<v t="ekr.20180307024753.30"><vh>@color comment2_color = #d33682</vh></v>
<v t="ekr.20180307024753.31"><vh>@color comment3_color = #d33682</vh></v>
<v t="ekr.20180307024753.32"><vh>@color comment4_color = #d33682</vh></v>
</v>
<v t="ekr.20180307024753.33"><vh>Colors: Leo constructs</vh>
<v t="ekr.20180307024753.34"><vh>@color section_name_brackets_color = @solarized-blue</vh></v>
<v t="ekr.20180307024753.35"><vh>@color null_color = #6c71c4</vh></v>
<v t="ekr.20180307024753.36"><vh>@color operator_color = #6c71c4</vh></v>
<v t="ekr.20180307024753.37"><vh>@color doc_part_color = @solarized-red</vh></v>
<v t="ekr.20180307024753.38"><vh>@color leo_keyword_color = @solarized-green</vh></v>
<v t="ekr.20180307024753.39"><vh>@color section_name_color = @solarized-red</vh></v>
<v t="ekr.20180307024753.40"><vh>@color show_invisibles_space_color = #E5E5E5</vh></v>
<v t="ekr.20180307024753.41"><vh>@color show_invisibles_tab_color = #CCCCCC</vh></v>
<v t="ekr.20180307024753.42"><vh>@color undefined_section_name_color = red</vh></v>
<v t="ekr.20180307024753.43"><vh>@color url_color = @solarized-purple</vh></v>
</v>
</v>
<v t="ekr.20180307024753.44"><vh>Colors: Text</vh>
<v t="ekr.20180307024753.45"><vh>@color log_text_background_color = @dark-base03</vh></v>
<v t="ekr.20180307024753.46"><vh>@color log_text_foreground_color = @dark-base0</vh></v>
<v t="ekr.20180307024753.47"><vh>@color text-background = @dark-base03</vh></v>
<v t="ekr.20180307024753.48"><vh>@color text-background-bright = @dark-base02</vh></v>
<v t="ekr.20180307024753.49"><vh>@color text-foreground = @dark-base0</vh></v>
<v t="ekr.20180307024753.50"><vh>@color text-foreground-bright = @dark-base2</vh></v>
</v>
<v t="ekr.20180307024753.51"><vh>Colors: Widgets</vh>
<v t="ekr.20180307024753.52"><vh>@color button-hover-fg =@dark-base03</vh></v>
</v>
<v t="ekr.20180307024753.53"><vh>Fonts &amp; text sizes</vh>
<v t="ekr.20180307024753.54"><vh>@string font-family = Inconsolata,Droid Sans Mono, DejaVu Sans Mono</vh></v>
<v t="ekr.20180307024753.55"><vh>@string font-family-body =@font-family</vh></v>
<v t="ekr.20180307024753.56"><vh>@string font-family-log =@font-family</vh></v>
<v t="ekr.20180307024753.57"><vh>@string font-family-tree =@font-family</vh></v>
<v t="ekr.20180307024753.58"><vh>@string font-size-body = 22px</vh></v>
<v t="ekr.20180307024753.59"><vh>@string font-size-log = 16px</vh></v>
<v t="ekr.20180307024753.60"><vh>@string font-size-tree = 18px</vh></v>
</v>
<v t="ekr.20180307024753.61"><vh>Gradients</vh>
<v t="ekr.20180307024753.62"><vh>@string bg-gradient =qlineargradient( x1:0 y1:0, x2:0 y2:1, stop:0.1@text-background-bright, stop:0.4 @text-background, stop:0.6@text-background, stop:0.9 @text-background-bright)</vh></v>
<v t="ekr.20180307024753.63"><vh>@string bg-gradient-hover =qlineargradient( x1:0 y1:0, x2:0 y2:1, stop:0.1 @dark-base00,stop:0.4 @dark-base0, stop:0.6 @dark-base0, stop:0.9@dark-base00)</vh></v>
</v>
<v t="ekr.20180307024753.64"><vh>Plugins settings</vh>
<v t="ekr.20180307024753.65"><vh>bookmarks</vh>
<v t="ekr.20180307024753.66"><vh>@color bookmarks_current_color = @solarized-orange</vh></v>
<v t="ekr.20180307024753.67"><vh>bookmarks base</vh>
<v t="ekr.20180307024753.68"><vh>@color bookmarks_base_color = @text-foreground</vh></v>
<v t="ekr.20180307024753.69"><vh>@string bookmarks_base_border = none</vh></v>
<v t="ekr.20180307024753.70"><vh>@string bookmarks_base_decoration = none</vh></v>
<v t="ekr.20180307024753.71"><vh>@string bookmarks_base_family = none</vh></v>
<v t="ekr.20180307024753.72"><vh>@string bookmarks_base_margin = 0</vh></v>
<v t="ekr.20180307024753.73"><vh>@string bookmarks_base_padding = 1</vh></v>
<v t="ekr.20180307024753.74"><vh>@string bookmarks_base_size = @bookmarks_font_size</vh></v>
<v t="ekr.20180307024753.75"><vh>@string bookmarks_base_style = normal</vh></v>
<v t="ekr.20180307024753.76"><vh>@string bookmarks_base_weight = regular</vh></v>
</v>
<v t="ekr.20180307024753.77"><vh>bookmarks children</vh>
<v t="ekr.20180307024753.78"><vh>@color bookmarks_children_color = @text-foreground</vh></v>
<v t="ekr.20180307024753.79"><vh>@string bookmarks_children_decoration = underline</vh></v>
<v t="ekr.20180307024753.80"><vh>@string bookmarks_children_family = none</vh></v>
<v t="ekr.20180307024753.81"><vh>@string bookmarks_children_size = ignore</vh></v>
<v t="ekr.20180307024753.82"><vh>@string bookmarks_children_style = ignore</vh></v>
<v t="ekr.20180307024753.83"><vh>@string bookmarks_children_weight = ignore</vh></v>
</v>
<v t="ekr.20180307024753.84"><vh>bookmarks current</vh>
<v t="ekr.20180307024753.85"><vh>@color bookmarks_current_color = blue</vh></v>
<v t="ekr.20180307024753.86"><vh>@string bookmarks_current_decoration = ignore</vh></v>
<v t="ekr.20180307024753.87"><vh>@string bookmarks_current_size = ignore</vh></v>
<v t="ekr.20180307024753.88"><vh>@string bookmarks_current_style = ignore</vh></v>
<v t="ekr.20180307024753.89"><vh>@string bookmarks_current_weight = bold</vh></v>
</v>
<v t="ekr.20180307024753.90"><vh>bookmarks expanded</vh>
<v t="ekr.20180307024753.91"><vh>@color bookmarks_expanded_color = @text-foreground</vh></v>
<v t="ekr.20180307024753.92"><vh>@string bookmarks_expanded_decoration = underline</vh></v>
<v t="ekr.20180307024753.93"><vh>@string bookmarks_expanded_size = ignore</vh></v>
<v t="ekr.20180307024753.94"><vh>@string bookmarks_expanded_style = ignore</vh></v>
<v t="ekr.20180307024753.95"><vh>@string bookmarks_expanded_weight = bold</vh></v>
<v t="ekr.20180307024753.96"><vh>@string bookmarks_font_size = 11pt</vh></v>
</v>
</v>
</v>
<v t="ekr.20180307024753.97"><vh>Outline indicators</vh>
<v t="ekr.20180307024753.98"><vh>@string tree-image-closed = nodes-dark/triangles/closed.png</vh></v>
<v t="ekr.20180307024753.99"><vh>@string tree-image-open = nodes-dark/triangles/open.png</vh></v>
</v>
<v t="ekr.20180307024753.100"><vh>Theme description settings</vh>
<v t="ekr.20180307024753.101"><vh>@bool color_theme_is_dark = True</vh></v>
<v t="ekr.20180307024753.102"><vh>@string color_theme = leo_dark_0</vh></v>
</v>
</v>
<v t="ekr.20180307024753.103"><vh>@data qt-gui-plugin-style-sheet</vh>
<v t="ekr.20180307024753.104"><vh>Body &amp; other text</vh></v>
<v t="ekr.20180307024753.105"><vh>Borders</vh></v>
<v t="ekr.20180307024753.106"><vh>Buttons</vh></v>
<v t="ekr.20180307024753.107"><vh>Log</vh></v>
<v t="ekr.20180307024753.108"><vh>Menus</vh></v>
<v t="ekr.20180307024753.109"><vh>Minibuffer &amp; label</vh></v>
<v t="ekr.20180307024753.110"><vh>Plugins</vh></v>
<v t="ekr.20180307024753.111"><vh>Scroll bars</vh></v>
<v t="ekr.20180307024753.112"><vh>Splitters</vh></v>
<v t="ekr.20180307024753.113"><vh>Status area</vh></v>
<v t="ekr.20180307024753.114"><vh>Tab bar</vh></v>
<v t="ekr.20180307024753.115"><vh>Tree</vh></v>
<v t="ekr.20180307024753.116"><vh>Widgets: general</vh></v>
</v>
</v>
<v t="ekr.20180307024846.1"><vh>@bool show-tips = False</vh></v>
<v t="ekr.20180307024911.1"><vh>@bool use-gutter = False</vh></v>
</v>
<v t="ekr.20180307012426.2"><vh>Syntax coloring test</vh>
<v t="ekr.20180307012426.3"><vh>&lt;&lt; defined section &gt;&gt;</vh></v>
</v>
<v t="ekr.20180307012426.4"><vh>Test g.es(color=*)</vh></v>
</vnodes>
<tnodes>
<t tx="ekr.20180307012127.1"></t>
<t tx="ekr.20180307012426.2">@language python

@ This should be *colored* as rST.
@c

# Details: http://leoeditor.com/

&lt;&lt; undefined section &gt;&gt;
&lt;&lt; defined section &gt;&gt;

a = 2

def spam():
    pass
</t>
<t tx="ekr.20180307012426.3">Test.</t>
<t tx="ekr.20180307012426.4">table = (
    # g.actualColor calls 
    'error', 'info', 'warning',
    'black', 'white',
    'xxx',
    'firebrick', 'grey', 'pink', 'purple', # Tk colors.
    # Solarized colors...
    'blue', 'cyan', 'green','magenta', 'orange', 'red',
    'violet', 'yellow',
)
for s in table:
    g.es(s, color=s)
</t>
<t tx="ekr.20180307024753.1" lineYOffset="4b002e">@language rest
@wrap
@tabwidth -2

*Important*: disable myLeoSettings.leo to test this file.

By Chris George.
Changed by EKR:
- Changed @solarized-base to @dark-base everywhere.
- Removed definitions of non-base solarized colors.
  They are in leoSettings.leo.
- Put all settings in an @settings tree.
</t>
<t tx="ekr.20180307024753.10"></t>
<t tx="ekr.20180307024753.100"></t>
<t tx="ekr.20180307024753.101" lineYOffset="4b002e">Set to true for dark themes, so bookmarks.py can generate
random background colors which are appropriate etc.</t>
<t tx="ekr.20180307024753.102" lineYOffset="4b002e">Name of the theme,
used to find icon files</t>
<t tx="ekr.20180307024753.103">/*
@language css
at-tabwidth -2 causes a crash in parse-template!
*/</t>
<t tx="ekr.20180307024753.104">/* The body pane */
/* QTextEdit#richTextEdit, QTextBrowser#vr-body { */
/* QTextBrowser, #body-text-renderer, #viewrendered_pane */
QTextEdit#richTextEdit {
  background: @dark-base03;
  color: @dark-base0;
  font-family: @font-family-body;
  font-size: @font-size-body;
  font-weight: normal; /* normal,bold,100,..,900 */
  font-style: normal; /* normal,italic,oblique */
  padding-left: 3px;
  padding-top: 3px;
  padding-bottom: 3px;
  padding-right: 3px;
  height: 200%;
}
</t>
<t tx="ekr.20180307024753.105">/* active pane highlighting */
QTextEdit#log-widget, LeoQTreeWidget#treeWidget, QTextEdit#richTextEdit {
  border-style: solid;
  border-width: 3px;
}
QTextEdit#log-widget {
  border-color: @log_text_background_color;
}
LeoQTreeWidget#treeWidget {
  border-color: @dark-base03;
}
QTextEdit#richTextEdit {
  border-color: @text-background;

}
QTextEdit:focus#log-widget,LeoQTreeWidget:focus#treeWidget, QTextEdit:focus#richTextEdit {
  border-color: @solarized-blue;
}
</t>
<t tx="ekr.20180307024753.106">QPushButton {
  color: @dark-base0;
  background: @dark-base03;
  border: 2px solid #31363b;
  border-bottom-color: #31363b;
  padding: 3px;
  margin-right: 5px;
}
QPushButton:hover {
  color: @dark-base0;
  border-color: #7ed2ff;
  background: @dark-base03;
}
</t>
<t tx="ekr.20180307024753.107">QTextEdit#log-widget {
  background: @solarize-base03;
  color: @solarize-base0;
  selection-color: white;
  selection-background-color: blue;
  font-family: @font-family-log;
  font-size: @font-size-log;
  font-weight: normal; /* normal,bold,100,..,900 */
  font-style: normal; /* normal, italic,oblique */
}</t>
<t tx="ekr.20180307024753.108">QMenu {
  color: @text-foreground-bright
}
QMenuBar::item:selected {
  color: @dark-base0;
  background: @dark-base03;
  border: 2px solid @dark-base03;
  border-bottom-color: @solarized-blue; /* same as the pane color */
  padding: 2px;
}
QMenu::item {
  color: @dark-base0;
  background: #4a5159;
  border: 8px solid #4a5159;
}
QMenu::item:selected {
  color: @dark-base0;
  background: @dark-base01;
  border: 2px solid @dark-base01;
  border-bottom-color: #2eacff; /* same as the pane color */
  padding: 2px;
}
QMenuBar::item {
  color: @text-foreground;
  background: @dark-base03;
}
QMenuBar::item:pressed {
  color: @text-foreground-bright;
  background: @dark-base01;
}
</t>
<t tx="ekr.20180307024753.109">/* The mini-buffer */
QLabel#minibufferLabel {
  color: @solarized-violet;
}
/* The minibuffer */
QLineEdit#lineEdit {
  color: @dark-base0; 
  background: @dark-base01;
  selection-color: @dark-base03; /* Yeah, it's a background color. */
  selection-background-color: @solarized-red;
  font-family: @font-family;
  font-size: 16px;
  font-weight: normal; /* normal,bold,100,..,900 */
  font-style: normal; /* normal,italic,oblique */
}
</t>
<t tx="ekr.20180307024753.11"></t>
<t tx="ekr.20180307024753.110">/* bookmarks plugin styling */

#show_bookmarks QPushButton {
  margin: 0; padding: 1; border: none;
  font-size: @bookmarks_base_size;
  color: @bookmarks_base_color;
  font-weight: @bookmarks_base_weight;
  text-decoration: @bookmarks_base_decoration;
}
#show_bookmarks QPushButton[style_class='bookmark_children'] {
  font-size: @bookmarks_children_size;
  color: @bookmarks_children_color;
  font-weight: @bookmarks_children_weight;
  text-decoration: @bookmarks_children_decoration;
}
#show_bookmarks QPushButton[style_class='bookmark_expanded'] {
  font-size: @bookmarks_expanded_size;
  color: @bookmarks_expanded_color;
  font-weight: @bookmarks_expanded_weight;
  text-decoration: @bookmarks_expanded_decoration;
}
#show_bookmarks QPushButton[style_class='bookmark_current'] {
  font-size: @bookmarks_current_size;
  color: @bookmarks_current_color;
  font-weight: @bookmarks_current_weight;
  text-decoration: @bookmarks_current_decoration;
}
</t>
<t tx="ekr.20180307024753.111">QScrollBar::horizontal {
   height: 7px;
}
QScrollBar::vertical {
   width: 7px;
}
QScrollBar::add-page, QScrollBar::sub-page {
  background: @dark-base03;
}
QScrollBar::handle {
  background: @dark-base01;
  color: @dark-base01;
}
QScrollBar::handle:hover {
  background: @dark-base0;
  color: @dark-base0;
}
/* to make these show up, remove the ::handle style above... bug? */
QScrollBar::add-line, QScrollBar::sub-line {
  background: @dark-base01;
  color: @dark-base01;
}</t>
<t tx="ekr.20180307024753.112">QSplitter::handle {
  background: @dark-base01;
}

QSplitter::handle:hover {
  background: @solarized-violet;
}
</t>
<t tx="ekr.20180307024753.113">/* The status area */
QLineEdit#status1 {
  background: @dark-base03;
  border-color: @dark-base02;
  border-width: 1px;
  border-style: solid;
}
QLineEdit#status2 {
  background: @dark-base03;
  border-color: @dark-base02;
  border-width: 1px;
  border-style: solid;
}
QLineEdit#status1[style_class ~= 'info'],
QLineEdit#status2[style_class ~= 'info'] {
    background: @solarized-blue;
    color:      @solarized-white;
}

QLineEdit#status1[style_class ~= 'fail'],
QLineEdit#status2[style_class ~= 'fail'] {
    background: @solarized-red;
    color:      @solarized-white;
}
</t>
<t tx="ekr.20180307024753.114">QTabWidget::pane { /* The tab widget frame */
    border-top: 2px solid #31363b;
}

QTabWidget::tab-bar {
    left: 5px; /* move to the right by 5px */
}

/* Style the tab using the tab sub-control. */
QTabBar::tab {
    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,
                                stop: 0 #232629, stop: 0.4 #23262A,
                                stop: 0.5 #23262A, stop: 1.0 #232629);
    border: 4px solid #31363b;
    border-bottom-color: #31363b; /* same as the pane color */
    border-top-left-radius: 4px;
    border-top-right-radius: 4px;
    min-width: 8ex;
    padding: 2px;
}

QTabBar::tab:selected, QTabBar::tab:hover {
    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,
                                stop: 0 #23262A, stop: 0.4 #232629,
                                stop: 0.5 #232629, stop: 1.0 #23262A);
    border-bottom-color: #1a6394;
}

QTabBar::tab:selected {
    border-color: #31363b;
    border-bottom-color: @solarized-blue; /* same as pane color */
}

QTabBar::tab:!selected {
    margin-top: 2px; /* make non-selected tabs look smaller */
}</t>
<t tx="ekr.20180307024753.115">LeoQTreeWidget#treeWidget {
  /* These apply to the selected item, but not to editing items.*/
  background: @dark-base03;
  color: @dark-base0;
  show-decoration-selected: 1; /* Extend the selection */
  padding: 2px solid @dark-base01;
  border-color: @dark-base03;
  font-family: @font-family-tree;
  font-size: @font-size-tree;
  font-weight: normal; /* normal,bold,100,..,900 */
  font-style: normal; /* normal, italic,oblique */
}
QTreeView::item:selected, QTreeView::item:active:selected {
  background: @dark-base01;
}
QTreeView::item:active:selected {
  background: @dark-base01;
  color: @dark-base0;
}
QTreeView::branch:closed:has-children{
    image: @tree-image-closed;
}
QTreeView::branch:open:has-children{
    image: @tree-image-open;
}

/* Headline edit widgets */
QTreeView QLineEdit {
  color: @dark-base03;
  background: @solarized-violet;
  selection-color: @solarized-violet; 
  selection-background-color: @dark-base3;
  font-family: @font-family-tree;
  font-size: @font-size-tree;
  font-weight: normal; /* normal,bold,100,..,900 */
  font-style: normal; /* normal, italic,oblique */
  padding: 0px;
}

QTreeWidget {
  /* These apply to the selected item, but not to editing items.*/
  background: @dark-base01;
  font-family: @font-family-tree;
  font-size: @font-size-tree;
  font-weight: normal; /* normal,bold,100,..,900 */
  font-style: normal; /* normal, italic,oblique */
  padding: 2px solid @dark-base03;
  border-color: @dark-base01;
}
QTreeWidget::selected {
  background: @dark-base01;
  color: @dark-base03; 
}
</t>
<t tx="ekr.20180307024753.116">QDockWidget {
 border: 5px solid red;
}
QDoubleSpinBox, QSpinBox, QDateEdit, QTimeEdit {
  border: none;
  padding: 3px;
  margin-right: 5px;
}
QLabel {
  color: @dark-base01;
}
QLineEdit {
  border: none;
  padding: 3px;
}
QWidget {
  /* Not for text widgets */
  background:  @dark-base03;
  color: @dark-base0;
  border-color: @dark-base01;
  font-size: 16px;
}
</t>
<t tx="ekr.20180307024753.12"></t>
<t tx="ekr.20180307024753.13"></t>
<t tx="ekr.20180307024753.14" lineYOffset="4b002e"></t>
<t tx="ekr.20180307024753.15" lineYOffset="4b002e">These settings must exist because they are *not* used in the css.</t>
<t tx="ekr.20180307024753.16"></t>
<t tx="ekr.20180307024753.17"></t>
<t tx="ekr.20180307024753.18"></t>
<t tx="ekr.20180307024753.19"></t>
<t tx="ekr.20180307024753.2"></t>
<t tx="ekr.20180307024753.20">was blue

Solarized blue      #268bd2</t>
<t tx="ekr.20180307024753.21">was blue

Solarized blue      #268bd2</t>
<t tx="ekr.20180307024753.22">was blue

Solarized blue      #268bd2</t>
<t tx="ekr.20180307024753.23">was blue

Solarized blue      #268bd2</t>
<t tx="ekr.20180307024753.24">was #00aa00 (Idle comment green)

Solarize green      #859900
Solarized cyan      #2aa198
Solarized violet    #6c71c4
Solarized orange    #cb4b16</t>
<t tx="ekr.20180307024753.25"></t>
<t tx="ekr.20180307024753.26"></t>
<t tx="ekr.20180307024753.27"></t>
<t tx="ekr.20180307024753.28">was black
was #2aa198</t>
<t tx="ekr.20180307024753.29">was firebrick3

Solarized colors:

magenta   #d33682

Dark comments   base01
Light comments  base1 comments
</t>
<t tx="ekr.20180307024753.3"></t>
<t tx="ekr.20180307024753.30"></t>
<t tx="ekr.20180307024753.31"></t>
<t tx="ekr.20180307024753.32"></t>
<t tx="ekr.20180307024753.33"></t>
<t tx="ekr.20180307024753.34"># New: solarized-blue
</t>
<t tx="ekr.20180307024753.35"></t>
<t tx="ekr.20180307024753.36"></t>
<t tx="ekr.20180307024753.37">The color of text in doc parts.

firebrick3
</t>
<t tx="ekr.20180307024753.38">The color of Leo keywords such as @ignore, @color, etc.

#00aa00
</t>
<t tx="ekr.20180307024753.39">The color of name in &lt; &lt; name &gt; &gt; when name is defined.

red

</t>
<t tx="ekr.20180307024753.4"></t>
<t tx="ekr.20180307024753.40">The background color that represents spaces when Show Invisibles mode is in effect.

gray80: #CCCCCC
gray90: #E5E5E5
</t>
<t tx="ekr.20180307024753.41">The foreground color that represents tabs when Show Invisibles mode is in effect.

gray80: #CCCCCC
gray90: #E5E5E5
</t>
<t tx="ekr.20180307024753.42">The color of name in &lt;&lt; name &gt;&gt; when name is undefined.
</t>
<t tx="ekr.20180307024753.43">purple
</t>
<t tx="ekr.20180307024753.44">Text to test with.</t>
<t tx="ekr.20180307024753.45">Background color of log text.</t>
<t tx="ekr.20180307024753.46">Foreground color of log text.

</t>
<t tx="ekr.20180307024753.47"></t>
<t tx="ekr.20180307024753.48"></t>
<t tx="ekr.20180307024753.49"></t>
<t tx="ekr.20180307024753.5"></t>
<t tx="ekr.20180307024753.50"></t>
<t tx="ekr.20180307024753.51">Most widgets are colored in their css nodes.

Only colors appearing in several places are given here.</t>
<t tx="ekr.20180307024753.52"></t>
<t tx="ekr.20180307024753.53"></t>
<t tx="ekr.20180307024753.54">test text</t>
<t tx="ekr.20180307024753.55"></t>
<t tx="ekr.20180307024753.56"></t>
<t tx="ekr.20180307024753.57"></t>
<t tx="ekr.20180307024753.58"></t>
<t tx="ekr.20180307024753.59"></t>
<t tx="ekr.20180307024753.6"></t>
<t tx="ekr.20180307024753.60"></t>
<t tx="ekr.20180307024753.61">Utility constants.</t>
<t tx="ekr.20180307024753.62"></t>
<t tx="ekr.20180307024753.63"></t>
<t tx="ekr.20180307024753.64"></t>
<t tx="ekr.20180307024753.65"></t>
<t tx="ekr.20180307024753.66"></t>
<t tx="ekr.20180307024753.67"></t>
<t tx="ekr.20180307024753.68"></t>
<t tx="ekr.20180307024753.69"></t>
<t tx="ekr.20180307024753.7"></t>
<t tx="ekr.20180307024753.70">none or underline</t>
<t tx="ekr.20180307024753.71"></t>
<t tx="ekr.20180307024753.72"></t>
<t tx="ekr.20180307024753.73"></t>
<t tx="ekr.20180307024753.74"></t>
<t tx="ekr.20180307024753.75">Valid values are: normal,italic,oblique</t>
<t tx="ekr.20180307024753.76">Huh?
valid values are: normal,bold,100,..,900
</t>
<t tx="ekr.20180307024753.77"></t>
<t tx="ekr.20180307024753.78"></t>
<t tx="ekr.20180307024753.79">none or underline</t>
<t tx="ekr.20180307024753.8"></t>
<t tx="ekr.20180307024753.80"></t>
<t tx="ekr.20180307024753.81"></t>
<t tx="ekr.20180307024753.82"></t>
<t tx="ekr.20180307024753.83">bold or regular</t>
<t tx="ekr.20180307024753.84"></t>
<t tx="ekr.20180307024753.85"></t>
<t tx="ekr.20180307024753.86">none or underline</t>
<t tx="ekr.20180307024753.87"></t>
<t tx="ekr.20180307024753.88"></t>
<t tx="ekr.20180307024753.89">bold or regular</t>
<t tx="ekr.20180307024753.9"></t>
<t tx="ekr.20180307024753.90"></t>
<t tx="ekr.20180307024753.91"></t>
<t tx="ekr.20180307024753.92">none or underline</t>
<t tx="ekr.20180307024753.93"></t>
<t tx="ekr.20180307024753.94"></t>
<t tx="ekr.20180307024753.95">bold or regular</t>
<t tx="ekr.20180307024753.96"></t>
<t tx="ekr.20180307024753.97">Outline indicators indicate the expansion state of outline nodes. The leo/Icons/nodes-dark folders contains two sets of indicators::
    
    leo/Icons/nodes-dark/plusminus/
    leo/Icons/nodes-dark/triangles/
    
The following settings specify the indicators.  You can use an absolute path, or more conveniently, a path relative either to:

- Your home directory or
- Leo's leo/Icons directory
</t>
<t tx="ekr.20180307024753.98">Must be relative to either the users home directory or leo/Icons directory.

url(/home/chris/leo-editor/leo/Icons/nodes-dark/triangles/closed.png)</t>
<t tx="ekr.20180307024753.99">url(/home/chris/leo-editor/leo/Icons/nodes-dark/triangles/open.png)</t>
<t tx="ekr.20180307024846.1">True: show user tips on startup.</t>
<t tx="ekr.20180307024911.1"># For line_numbering plugin.</t>
</tnodes>
</leo_file>
