<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5" body_secondary_ratio="0.5">
	<global_window_position top="50" left="50" height="500" width="700"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="ekr.20180307012127.1" a="E"><vh>@settings</vh>
<v t="chris.20180308171552.1" a="E"><vh>@theme Breeze Dark</vh>
<v t="chris.20180308171552.2"><vh>BreezeDark StyleSheet</vh></v>
<v t="chris.20180308171552.3"><vh>Breeze Dark Color definitions</vh>
<v t="chris.20180309180448.2"><vh>@color dark-base0 = #eff0f1</vh></v>
<v t="chris.20180309180448.3"><vh>@color dark-base1 = #909396</vh></v>
<v t="chris.20180309180448.4"><vh>@color dark-base2 = #ffffff</vh></v>
<v t="chris.20180309180448.5"><vh>@color dark-base3 = #31363b</vh></v>
<v t="chris.20180309180448.6"><vh>@color dark-base4 = #575b5f</vh></v>
<v t="chris.20180309180448.7"><vh>@color dark-base5 = #232629</vh></v>
<v t="chris.20180309180448.8"><vh>@color dark-base6 = #3daee9</vh></v>
<v t="chris.20180309180448.9"><vh>@color dark-base7 = #224e65</vh></v>
<v t="chris.20180309180448.10"><vh>@color dark-base8 = #ff0000</vh></v>
</v>
<v t="chris.20180308171552.15" a="E"><vh>Settings for Leo Breeze Dark</vh>
<v t="chris.20180308171552.16"><vh>Colors: Logical colors</vh>
<v t="chris.20180308171552.17"><vh>@color log_black_color = @text-foreground</vh></v>
<v t="chris.20180308171552.18"><vh>@color log_blue_color = @solarized-blue</vh></v>
<v t="chris.20180308171552.19"><vh>@color log_cyan_color = @solarized-cyan</vh></v>
<v t="chris.20180308171552.20"><vh>@color log_error_color = @solarized-red</vh></v>
<v t="chris.20180308171552.21"><vh>@color log_green_color = @solarized-green</vh></v>
<v t="chris.20180308171552.22"><vh>@color log_info_color = @solarized-blue</vh></v>
<v t="chris.20180308171552.23"><vh>@color log_magenta_color = @solarized-magenta</vh></v>
<v t="chris.20180308171552.24"><vh>@color log_note_color = @solarized-blue</vh></v>
<v t="chris.20180308171552.25"><vh>@color log_orange_color = @solarized-orange</vh></v>
<v t="chris.20180308171552.26"><vh>@color log_red_color = @solarized-red</vh></v>
<v t="chris.20180308171552.27"><vh>@color log_violet_color = @solarized-violet</vh></v>
<v t="chris.20180308171552.28"><vh>@color log_warning_color_= @solarized-red</vh></v>
<v t="chris.20180308171552.29"><vh>@color log_white_color = @solarized-white</vh></v>
<v t="chris.20180308171552.30"><vh>@color log_yellow_color = @solarized-yellow</vh></v>
</v>
<v t="chris.20180308171552.31"><vh>Colors: Syntax coloring</vh>
<v t="chris.20180308171552.32"><vh>Colors: defaults</vh>
<v t="chris.20180308171552.33"><vh>@color blank_color = grey</vh></v>
<v t="chris.20180308171552.34"><vh>@color tab_color = red</vh></v>
<v t="chris.20180308171552.35"><vh>@color label_color = red</vh></v>
<v t="chris.20180308171552.36"><vh>@color keyword1_color = #268bd2</vh></v>
<v t="chris.20180308171552.37"><vh>@color keyword2_color = #268bd2</vh></v>
<v t="chris.20180308171552.38"><vh>@color keyword3_color = #268bd2</vh></v>
<v t="chris.20180308171552.39"><vh>@color keyword4_color = #268bd2</vh></v>
<v t="chris.20180308171552.40"><vh>@color literal1_color = #859900</vh></v>
<v t="chris.20180308171552.41"><vh>@color literal2_color = #859900</vh></v>
<v t="chris.20180308171552.42"><vh>@color literal3_color = #859900</vh></v>
<v t="chris.20180308171552.43"><vh>@color literal4_color = #859900</vh></v>
<v t="chris.20180308171552.44"><vh>@color markup_color = #268bd2</vh></v>
<v t="chris.20180308171552.45"><vh>@color comment1_color = #d33682</vh></v>
<v t="chris.20180308171552.46"><vh>@color comment2_color = #d33682</vh></v>
<v t="chris.20180308171552.47"><vh>@color comment3_color = #d33682</vh></v>
<v t="chris.20180308171552.48"><vh>@color comment4_color = #d33682</vh></v>
</v>
<v t="chris.20180308171552.49"><vh>Colors: Leo constructs</vh>
<v t="chris.20180308171552.50"><vh>@color section_name_brackets_color = @solarized-blue</vh></v>
<v t="chris.20180308171552.51"><vh>@color null_color = #6c71c4</vh></v>
<v t="chris.20180308171552.52"><vh>@color operator_color = #6c71c4</vh></v>
<v t="chris.20180308171552.53"><vh>@color doc_part_color = @solarized-red</vh></v>
<v t="chris.20180308171552.54"><vh>@color leo_keyword_color = @solarized-green</vh></v>
<v t="chris.20180308171552.55"><vh>@color section_name_color = @solarized-red</vh></v>
<v t="chris.20180308171552.56"><vh>@color show_invisibles_space_color = #E5E5E5</vh></v>
<v t="chris.20180308171552.57"><vh>@color show_invisibles_tab_color = #CCCCCC</vh></v>
<v t="chris.20180308171552.58"><vh>@color undefined_section_name_color = red</vh></v>
<v t="chris.20180308171552.59"><vh>@color url_color = @solarized-purple</vh></v>
</v>
</v>
<v t="chris.20180308171552.60"><vh>Colors: Text</vh>
<v t="chris.20180308171552.61"><vh>@color log_text_background_color = @dark-base3</vh></v>
<v t="chris.20180308171552.62"><vh>@color log_text_foreground_color = @dark-base0</vh></v>
<v t="chris.20180308171552.63"><vh>@color text-background = @dark-base3</vh></v>
<v t="chris.20180308171552.64"><vh>@color text-background-bright = @dark-base4</vh></v>
<v t="chris.20180308171552.65"><vh>@color text-foreground = @dark-base0</vh></v>
<v t="chris.20180308171552.66"><vh>@color text-foreground-bright = @dark-base2</vh></v>
</v>
<v t="chris.20180308171552.67"><vh>Colors: Widgets</vh>
<v t="chris.20180308171552.68"><vh>@color button-hover-fg =@dark-base3</vh></v>
</v>
<v t="chris.20180308171552.69"><vh>Fonts &amp; text sizes</vh>
<v t="chris.20180308171552.70"><vh>@string font-family = Inconsolata,Droid Sans Mono, DejaVu Sans Mono</vh></v>
<v t="chris.20180308171552.71"><vh>@string font-family-body =@font-family</vh></v>
<v t="chris.20180308171552.72"><vh>@string font-family-log =@font-family</vh></v>
<v t="chris.20180308171552.73"><vh>@string font-family-tree =@font-family</vh></v>
<v t="chris.20180308171552.74"><vh>@string font-size-body = 22px</vh></v>
<v t="chris.20180308171552.75"><vh>@string font-size-log = 16px</vh></v>
<v t="chris.20180308171552.76"><vh>@string font-size-tree = 18px</vh></v>
</v>
<v t="chris.20180308171552.77"><vh>Gradients</vh>
<v t="chris.20180308171552.78"><vh>@string bg-gradient =qlineargradient( x1:0 y1:0, x2:0 y2:1, stop:0.1@text-background-bright, stop:0.4 @text-background, stop:0.6@text-background, stop:0.9 @text-background-bright)</vh></v>
<v t="chris.20180308171552.79"><vh>@string bg-gradient-hover =qlineargradient( x1:0 y1:0, x2:0 y2:1, stop:0.1 @dark-base4,stop:0.4 @dark-base0, stop:0.6 @dark-base0, stop:0.9@dark-base4)</vh></v>
</v>
<v t="chris.20180308171552.80" a="E"><vh>Plugins settings</vh>
<v t="chris.20180308171552.81"><vh>bookmarks</vh>
<v t="chris.20180308171552.82"><vh>@color bookmarks_current_color = @solarized-orange</vh></v>
<v t="chris.20180308171552.83"><vh>bookmarks base</vh>
<v t="chris.20180308171552.84"><vh>@color bookmarks_base_color = @text-foreground</vh></v>
<v t="chris.20180308171552.85"><vh>@string bookmarks_base_border = none</vh></v>
<v t="chris.20180308171552.86"><vh>@string bookmarks_base_decoration = none</vh></v>
<v t="chris.20180308171552.87"><vh>@string bookmarks_base_family = none</vh></v>
<v t="chris.20180308171552.88"><vh>@string bookmarks_base_margin = 0</vh></v>
<v t="chris.20180308171552.89"><vh>@string bookmarks_base_padding = 1</vh></v>
<v t="chris.20180308171552.90"><vh>@string bookmarks_base_size = @bookmarks_font_size</vh></v>
<v t="chris.20180308171552.91"><vh>@string bookmarks_base_style = normal</vh></v>
<v t="chris.20180308171552.92"><vh>@string bookmarks_base_weight = regular</vh></v>
</v>
<v t="chris.20180308171552.93"><vh>bookmarks children</vh>
<v t="chris.20180308171552.94"><vh>@color bookmarks_children_color = @text-foreground</vh></v>
<v t="chris.20180308171552.95"><vh>@string bookmarks_children_decoration = underline</vh></v>
<v t="chris.20180308171552.96"><vh>@string bookmarks_children_family = none</vh></v>
<v t="chris.20180308171552.97"><vh>@string bookmarks_children_size = ignore</vh></v>
<v t="chris.20180308171552.98"><vh>@string bookmarks_children_style = ignore</vh></v>
<v t="chris.20180308171552.99"><vh>@string bookmarks_children_weight = ignore</vh></v>
</v>
<v t="chris.20180308171552.100"><vh>bookmarks current</vh>
<v t="chris.20180308171552.101"><vh>@color bookmarks_current_color = blue</vh></v>
<v t="chris.20180308171552.102"><vh>@string bookmarks_current_decoration = ignore</vh></v>
<v t="chris.20180308171552.103"><vh>@string bookmarks_current_size = ignore</vh></v>
<v t="chris.20180308171552.104"><vh>@string bookmarks_current_style = ignore</vh></v>
<v t="chris.20180308171552.105"><vh>@string bookmarks_current_weight = bold</vh></v>
</v>
<v t="chris.20180308171552.106"><vh>bookmarks expanded</vh>
<v t="chris.20180308171552.107"><vh>@color bookmarks_expanded_color = @text-foreground</vh></v>
<v t="chris.20180308171552.108"><vh>@string bookmarks_expanded_decoration = underline</vh></v>
<v t="chris.20180308171552.109"><vh>@string bookmarks_expanded_size = ignore</vh></v>
<v t="chris.20180308171552.110"><vh>@string bookmarks_expanded_style = ignore</vh></v>
<v t="chris.20180308171552.111"><vh>@string bookmarks_expanded_weight = bold</vh></v>
<v t="chris.20180308171552.112"><vh>@string bookmarks_font_size = 11pt</vh></v>
</v>
</v>
</v>
<v t="chris.20180308171552.113"><vh>Outline indicators</vh>
<v t="chris.20180308171552.114"><vh>@string tree-image-closed = dark/branch_closed.svg</vh></v>
<v t="chris.20180308171552.115"><vh>@string tree-image-open = dark/branch_open.svg</vh></v>
</v>
<v t="chris.20180308171552.116"><vh>Theme description settings</vh>
<v t="chris.20180308171552.117"><vh>@bool color_theme_is_dark = True</vh></v>
<v t="chris.20180308171552.118"><vh>@string color_theme = dark</vh></v>
</v>
</v>
<v t="chris.20180308171552.119" a="E"><vh>@data qt-gui-plugin-style-sheet</vh>
<v t="chris.20180308171552.120"><vh>All General Widgets</vh></v>
<v t="chris.20180308171552.121"><vh>Body &amp; other text</vh></v>
<v t="chris.20180308171552.122"><vh>Borders</vh></v>
<v t="chris.20180308171552.123"><vh>Buttons</vh></v>
<v t="chris.20180308171552.124"><vh>Log</vh></v>
<v t="chris.20180308171552.125"><vh>Menus</vh></v>
<v t="chris.20180308171552.126"><vh>Minibuffer &amp; label</vh></v>
<v t="chris.20180308171552.127"><vh>Plugins</vh></v>
<v t="chris.20180308171552.128"><vh>Scroll bars</vh></v>
<v t="chris.20180308171552.129"><vh>Splitters</vh></v>
<v t="chris.20180308171552.131"><vh>Tab bar</vh></v>
<v t="chris.20180309182828.1"><vh>Tree</vh></v>
<v t="chris.20180308171552.130"><vh>Z Status area</vh></v>
</v>
<v t="chris.20180311131013.1"><vh>Full</vh></v>
</v>
<v t="ekr.20180307024846.1"><vh>@bool show-tips = False</vh></v>
<v t="ekr.20180307024911.1"><vh>@bool use-gutter = False</vh></v>
</v>
<v t="ekr.20180307012426.2"><vh>Syntax coloring test</vh>
<v t="ekr.20180307012426.3"><vh>&lt;&lt; defined section &gt;&gt;</vh></v>
</v>
<v t="ekr.20180307012426.4"><vh>Test g.es(color=*)</vh></v>
</vnodes>
<tnodes>
<t tx="chris.20180308171552.1" lineYOffset="4b002e">@language rest
@wrap
@tabwidth -2

Modified by Chris George.

Expect more once I figure out how to source images.

</t>
<t tx="chris.20180308171552.100"></t>
<t tx="chris.20180308171552.101"></t>
<t tx="chris.20180308171552.102">none or underline</t>
<t tx="chris.20180308171552.103"></t>
<t tx="chris.20180308171552.104"></t>
<t tx="chris.20180308171552.105">bold or regular</t>
<t tx="chris.20180308171552.106"></t>
<t tx="chris.20180308171552.107"></t>
<t tx="chris.20180308171552.108">none or underline</t>
<t tx="chris.20180308171552.109"></t>
<t tx="chris.20180308171552.110"></t>
<t tx="chris.20180308171552.111">bold or regular</t>
<t tx="chris.20180308171552.112"></t>
<t tx="chris.20180308171552.113">Outline indicators indicate the expansion state of outline nodes. The leo/Icons/nodes-dark folders contains two sets of indicators::
    
    leo/Icons/nodes-dark/plusminus/
    leo/Icons/nodes-dark/triangles/
    
The following settings specify the indicators.  You can use an absolute path, or more conveniently, a path relative either to:

- Your home directory or
- Leo's leo/Icons directory
</t>
<t tx="chris.20180308171552.114">Must be relative to either the users home directory or leo/Icons directory.

</t>
<t tx="chris.20180308171552.115"></t>
<t tx="chris.20180308171552.116"></t>
<t tx="chris.20180308171552.117" lineYOffset="4b002e">Set to true for dark themes, so bookmarks.py can generate
random background colors which are appropriate etc.</t>
<t tx="chris.20180308171552.118" lineYOffset="4b002e">Name of the theme,
used to find icon files</t>
<t tx="chris.20180308171552.119">/*
@language css
at-tabwidth -2 causes a crash in parse-template!
*/</t>
<t tx="chris.20180308171552.120">QDockWidget {
 border: 5px solid red;
}
QDoubleSpinBox, QSpinBox, QDateEdit, QTimeEdit {
  border: none;
  padding: 3px;
  margin-right: 5px;
}
QLabel {
  color: @dark-base4;
}
QLineEdit {
  border: none;
  padding: 3px;
}
QWidget {
  /* Not for text widgets */
  background:  @dark-base3;
  color: @dark-base0;
  border-color: @dark-base4;
  font-size: 16px;
}</t>
<t tx="chris.20180308171552.121">/* The body pane */
QTextEdit#richTextEdit {
  background-color: @dark-base5;
  color: @dark-base0;
  border: 0.1ex solid @dark-base4;
  font-family: @font-family-body;
  font-size: @font-size-body;
  font-weight: normal; /* normal,bold,100,..,900 */
  font-style: normal; /* normal,italic,oblique */
  padding-left: 3px;
  padding-top: 3px;
  padding-bottom: 3px;
  padding-right: 3px;
  height: 200%;
}

</t>
<t tx="chris.20180308171552.122">/* active pane highlighting */
QTextEdit#log-widget, LeoQTreeWidget#treeWidget, QTextEdit#richTextEdit {
  border-style: solid;
  border-width: 3px;
}
QTextEdit#log-widget {
  border-color: @log_text_background_color;
}
LeoQTreeWidget#treeWidget {
  border-color: @dark-base3;
}
QTextEdit#richTextEdit {
  border-color: @text-background;

}
QTextEdit:focus#log-widget,LeoQTreeWidget:focus#treeWidget, QTextEdit:focus#richTextEdit {
  border-color: @solarized-blue;
}</t>
<t tx="chris.20180308171552.123">QPushButton
{
    color: @dark-base0;
    background-color: qlineargradient(x1: 0.5, y1: 0.5 x2: 0.5, y2: 1, stop: 0 @dark-base4, stop: 0.5 @dark-base3);
    border-width: 0.1ex;
    border-color: @dark-base4;
    border-style: solid;
    padding: 0.5ex;
    border-radius: 0.2ex;
    outline: none;
}

QPushButton:disabled
{
    background-color: @dark-base3;
    border-width: 0.1ex;
    border-color: @dark-base4;
    border-style: solid;
    padding-top: 0.5ex;
    padding-bottom: 0.5ex;
    padding-left: 1ex;
    padding-right: 1ex;
    border-radius: 0.2ex;
    color: @dark-base4;
}

QPushButton:hover
{
    background-color: @dark-base7;
}

QPushButton:focus
{
    color: white;
}

QPushButton:pressed
{
    background-color: @dark-base3;
    padding-top: -1.5ex;
    padding-bottom: -1.7ex;
}</t>
<t tx="chris.20180308171552.124">QTextEdit#log-widget {
  background-color: @dark-base3;
  color: @dark-base0;
  /* selection-color: white; */
  /* selection-background-color: blue; */
  font-family: @font-family-log;
  font-size: @font-size-log;
  font-weight: normal; /* normal,bold,100,..,900 */
  font-style: normal; /* normal, italic,oblique */
}


QLineEdit#findPattern {
  background-color: @dark-base5;
}

QLineEdit#findChange {
  background-color: @dark-base5;
}

QListWidget#nodetags-listWidget {
  background-color: @dark-base5;
}



</t>
<t tx="chris.20180308171552.125">QMenuBar
{
    background-color: @dark-base3;
    color: @dark-base0;
}

QMenuBar::item
{
    background: transparent;
}

QMenuBar::item:selected
{
    background: @dark-base7;
    border: 0.1ex solid @dark-base4;
}

QMenuBar::item:pressed
{
    border: 0.1ex solid @dark-base4;
    background-color: @dark-base6;
    color: @dark-base0;
    margin-bottom: -0.1ex;
    padding-bottom: 0.1ex;
}

QMenu
{
    border: 0.1ex solid @dark-base4;
    color: @dark-base0;
    margin: 0.2ex;
}

QMenu::icon
{
    margin: 0.5ex;
}

QMenu::item
{
    padding: 0.5ex 3ex 0.5ex 3ex;
    margin-left: 0.5ex;
    border: 0.1ex solid transparent; /* reserve space for selection border */
}

QMenu::item:selected
{
    background: @dark-base7;
    color: @dark-base0;
}

QMenu::separator
{
    height: 0.2ex;
    background: lightblue;
    margin-left: 1ex;
    margin-right: 0.5ex;
}</t>
<t tx="chris.20180308171552.126">/* The mini-buffer */
QLabel#minibufferLabel {
  color: @dark-base6;
}
/* The minibuffer */
QLineEdit#lineEdit {
    background-color: @dark-base5;
    padding: 0.5ex;
    border-style: solid;
    border: 0.1ex solid @dark-base4;
    border-radius: 0.2ex;
    color: @dark-base0;
}</t>
<t tx="chris.20180308171552.127">/* bookmarks plugin styling */

#show_bookmarks QPushButton {
  margin: 0; padding: 1; border: none;
  font-size: @bookmarks_base_size;
  color: @bookmarks_base_color;
  font-weight: @bookmarks_base_weight;
  text-decoration: @bookmarks_base_decoration;
}
#show_bookmarks QPushButton[style_class='bookmark_children'] {
  font-size: @bookmarks_children_size;
  color: @bookmarks_children_color;
  font-weight: @bookmarks_children_weight;
  text-decoration: @bookmarks_children_decoration;
}
#show_bookmarks QPushButton[style_class='bookmark_expanded'] {
  font-size: @bookmarks_expanded_size;
  color: @bookmarks_expanded_color;
  font-weight: @bookmarks_expanded_weight;
  text-decoration: @bookmarks_expanded_decoration;
}
#show_bookmarks QPushButton[style_class='bookmark_current'] {
  font-size: @bookmarks_current_size;
  color: @bookmarks_current_color;
  font-weight: @bookmarks_current_weight;
  text-decoration: @bookmarks_current_decoration;
}
</t>
<t tx="chris.20180308171552.128">QAbstractScrollArea
{
    border-radius: 0.2ex;
    border: 0.1ex solid @dark-base4;
    background-color: transparent;
}

QScrollBar:horizontal
{
    height: 1.5ex;
    margin: 0.3ex 1.5ex 0.3ex 1.5ex;
    border: 0.1ex transparent @dark-base3;
    border-radius: 0.4ex;
    background-color: @dark-base3;
}

QScrollBar:horizontal:hover
{
    height: 1.5ex;
    margin: 0.3ex 1.5ex 0.3ex 1.5ex;
    border: 0.1ex transparent @dark-base4;
    border-radius: 0.4ex;
    background-color: @dark-base4;
}

QScrollBar::handle:horizontal
{
    background-color: @dark-base1;
    min-width: 0.5ex;
    border-radius: 0.4ex;
}

QScrollBar::handle:horizontal:hover
{
    background-color: @dark-base6;
    min-width: 0.5ex;
    border-radius: 0.4ex;
}

QScrollBar::add-line:horizontal
{
    margin: 0px 0.3ex 0px 0.3ex;
    border-image: url(:/dark/right_arrow_disabled.svg);
    width: 1ex;
    height: 1ex;
    subcontrol-position: right;
    subcontrol-origin: margin;
}

QScrollBar::sub-line:horizontal
{
    margin: 0ex 0.3ex 0ex 0.3ex;
    border-image: url(:/dark/left_arrow_disabled.svg);
    width: 1ex;
    height: 1ex;
    subcontrol-position: left;
    subcontrol-origin: margin;
}

QScrollBar::add-line:horizontal:hover,
QScrollBar::add-line:horizontal:on
{
    border-image: url(:/dark/right_arrow.svg);
    width: 1ex;
    height: 1ex;
    subcontrol-position: right;
    subcontrol-origin: margin;
}


QScrollBar::sub-line:horizontal:hover,
QScrollBar::sub-line:horizontal:on
{
    border-image: url(:/dark/left_arrow.svg);
    width: 1ex;
    height: 1ex;
    subcontrol-position: left;
    subcontrol-origin: margin;
}

QScrollBar::up-arrow:horizontal,
QScrollBar::down-arrow:horizontal
{
    background: none;
}


QScrollBar::add-page:horizontal,
QScrollBar::sub-page:horizontal
{
    background: none;
}
QScrollBar:vertical
{
    width: 1.5ex;
    margin: 1.5ex 0.3ex 1.5ex 0.3ex;
    border: 0.1ex transparent @dark-base3;
    border-radius: 0.4ex;
    background-color: @dark-base3;
}

QScrollBar:vertical:hover
{
    width: 1.5ex;
    margin: 1.5ex 0.3ex 1.5ex 0.3ex;
    border: 0.1ex transparent @dark-base4;
    border-radius: 0.4ex;
    background-color: @dark-base4;
}

QScrollBar::handle:vertical
{
    background-color: @dark-base1;
    min-height: 0.5ex;
    border-radius: 0.4ex;
}

QScrollBar::handle:vertical:hover
{
    background-color: @dark-base6;
    min-height: 0.5ex;
    border-radius: 0.4ex;
}

QScrollBar::sub-line:vertical
{
    margin: 0.3ex 0ex 0.3ex 0ex;
    border-image: url(:/dark/up_arrow_disabled.svg);
    height: 1ex;
    width: 1ex;
    subcontrol-position: top;
    subcontrol-origin: margin;
}

QScrollBar::add-line:vertical
{
    margin: 0.3ex 0ex 0.3ex 0ex;
    border-image: url(:/dark/down_arrow_disabled.svg);
    height: 1ex;
    width: 1ex;
    subcontrol-position: bottom;
    subcontrol-origin: margin;
}

QScrollBar::sub-line:vertical:hover,
QScrollBar::sub-line:vertical:on
{

    border-image: url(:/dark/up_arrow.svg);
    height: 1ex;
    width: 1ex;
    subcontrol-position: top;
    subcontrol-origin: margin;
}


QScrollBar::add-line:vertical:hover,
QScrollBar::add-line:vertical:on
{
    border-image: url(:/dark/down_arrow.svg);
    height: 1ex;
    width: 1ex;
    subcontrol-position: bottom;
    subcontrol-origin: margin;
}

QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical
{
    background: none;
}


QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical
{
    background: none;
}</t>
<t tx="chris.20180308171552.129">QSplitter::handle
{
    border: 0.1ex dashed @dark-base4;
}

QSplitter::handle:hover
{
    background-color: @dark-base1;
    border: 0.1ex solid @dark-base4;
}

QSplitter::handle:horizontal
{
    width: 0.1ex;
}

QSplitter::handle:vertical
{
    height: 0.1ex;
}
</t>
<t tx="chris.20180308171552.130">/* The status area */
QLineEdit#status1 {
  background: @dark-base3;
  border-color: @dark-base4;
  border-width: 1px;
  border-style: solid;
}
QLineEdit#status2 {
  background: @dark-base3;
  border-color: @dark-base4;
  border-width: 1px;
  border-style: solid;
}
QLineEdit#status1[style_class ~= 'info'],
QLineEdit#status2[style_class ~= 'info'] {
    background: @dark-base3;
    color:      @dark-base0;
}

QLineEdit#status1[style_class ~= 'fail'],
QLineEdit#status2[style_class ~= 'fail'] {
    background: @dark-base8;
    color:      @dark-base0;
}</t>
<t tx="chris.20180308171552.131">QTabBar
{
    left: 0.5ex; /* move to the right by 0.5ex */
    border-radius: 0.3ex;
}

QTabBar:focus
{
    border: 0ex transparent black;
}

QTabBar::tab {
    background: @dark-base3;
    border: 3px solid @dark-base3;
    border-bottom-color: @dark-base3; /* same as the pane color */
    border-top-left-radius: 4px;
    border-top-right-radius: 4px;
    min-width: 8ex;
    padding: 2px;
}

QTabBar::tab:hover {
    background: @dark-base7;
    border-bottom-color: @dark-base7;
}

QTabBar::tab:selected {
    background-color: @dark-base4;
    border-bottom-color: @dark-base6;
}

QTabBar::tab:!selected {
    margin-top: 2px; /* make non-selected tabs look smaller */
}</t>
<t tx="chris.20180308171552.15" lineYOffset="4b002e"></t>
<t tx="chris.20180308171552.16"></t>
<t tx="chris.20180308171552.17">Use a light color, not black!
@solarized-white</t>
<t tx="chris.20180308171552.18"></t>
<t tx="chris.20180308171552.19"></t>
<t tx="chris.20180308171552.2">/*
 *  BreezeDark stylesheet.
 *
 *  :author: Colin Duquesnoy
 *  :editor: Alex Huszagh
 *  :license: MIT, see LICENSE.md
 *
 *  This is originally a fork of QDarkStyleSheet, and is based on Breeze/
 *  BreezeDark color scheme, but is in no way affiliated with KDE.
 *
 * ---------------------------------------------------------------------
 *  The MIT License (MIT)
 *
 * Copyright (c) &lt;2013-2014&gt; &lt;Colin Duquesnoy&gt;
 * Copyright (c) &lt;2015-2016&gt; &lt;Alex Huszagh&gt;
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 * ---------------------------------------------------------------------
 */

Inspiration and code borrowed shamelessly. Modifications were required. :-)

Chris George

</t>
<t tx="chris.20180308171552.20"></t>
<t tx="chris.20180308171552.21"></t>
<t tx="chris.20180308171552.22"></t>
<t tx="chris.20180308171552.23"></t>
<t tx="chris.20180308171552.24"></t>
<t tx="chris.20180308171552.25"></t>
<t tx="chris.20180308171552.26"></t>
<t tx="chris.20180308171552.27"></t>
<t tx="chris.20180308171552.28"></t>
<t tx="chris.20180308171552.29"># Not an official solarized color: same as solorarized-base3</t>
<t tx="chris.20180308171552.3">/*
 *  BreezeDark stylesheet.
 *
 *  :author: Colin Duquesnoy
 *  :editor: Alex Huszagh
 *  :license: MIT, see LICENSE.md
 *
 *  This is originally a fork of QDarkStyleSheet, and is based on Breeze/
 *  BreezeDark color scheme, but is in no way affiliated with KDE.
 *
 * ---------------------------------------------------------------------
 *  The MIT License (MIT)
 *
 * Copyright (c) &lt;2013-2014&gt; &lt;Colin Duquesnoy&gt;
 * Copyright (c) &lt;2015-2016&gt; &lt;Alex Huszagh&gt;
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 * ---------------------------------------------------------------------
 */

QToolTip
{
    border: 0.1ex solid #eff0f1;
    background-color: @dark-base3;
    alternate-background-color: #3b4045;
    color: #eff0f1;
    padding: 0.5ex;
    opacity: 200;
}

QWidget
{
    color: #eff0f1;
    background-color: @dark-base3;
    selection-background-color:#3daee9;
    selection-color: #eff0f1;
    background-clip: border;
    border-image: none;
    border: 0px transparent black;
    outline: 0;
}

QWidget:item:hover
{
    background-color: #3daee9;
    color: #eff0f1;
}

QWidget:item:selected
{
    background-color: #3daee9;
}


QCheckBox
{
    spacing: 0.5ex;
    outline: none;
    color: #eff0f1;
    margin-bottom: 0.2ex;
    opacity: 200;
}

QCheckBox:disabled
{
    color: #76797c;
}

QGroupBox::indicator
{
    margin-left: 0.2ex;
}

QCheckBox::indicator:unchecked,
QCheckBox::indicator:unchecked:focus
{
    border-image: url(:/dark/checkbox_unchecked_disabled.svg);
}

QCheckBox::indicator:unchecked:hover,
QCheckBox::indicator:unchecked:pressed,
QGroupBox::indicator:unchecked:hover,
QGroupBox::indicator:unchecked:focus,
QGroupBox::indicator:unchecked:pressed
{
    border: none;
    border-image: url(:/dark/checkbox_unchecked.svg);
}

QCheckBox::indicator:checked
{
    border-image: url(:/dark/checkbox_checked.svg);
}

QCheckBox::indicator:checked:hover,
QCheckBox::indicator:checked:focus,
QCheckBox::indicator:checked:pressed,
QGroupBox::indicator:checked:hover,
QGroupBox::indicator:checked:focus,
QGroupBox::indicator:checked:pressed
{
    border: none;
    border-image: url(:/dark/checkbox_checked.svg);
}

QCheckBox::indicator:indeterminate
{
    border-image: url(:/dark/checkbox_indeterminate.svg);
}

QCheckBox::indicator:indeterminate:focus,
QCheckBox::indicator:indeterminate:hover,
QCheckBox::indicator:indeterminate:pressed
{
    border-image: url(:/dark/checkbox_indeterminate.svg);
}

QCheckBox::indicator:indeterminate:disabled
{
    border-image: url(:/dark/checkbox_indeterminate_disabled.svg);
}

QCheckBox::indicator:checked:disabled,
QGroupBox::indicator:checked:disabled
{
    border-image: url(:/dark/checkbox_checked_disabled.svg);
}

QCheckBox::indicator:unchecked:disabled,
QGroupBox::indicator:unchecked:disabled
{
    border-image: url(:/dark/checkbox_unchecked_disabled.svg);
}

QRadioButton
{
    spacing: 0.5ex;
    outline: none;
    color: #eff0f1;
    margin-bottom: 0.2ex;
}

QRadioButton:disabled
{
    color: #76797c;
}

QRadioButton::indicator:unchecked,
QRadioButton::indicator:unchecked:focus
{
    border-image: url(:/dark/radio_unchecked_disabled.svg);
}


QRadioButton::indicator:unchecked:hover,
QRadioButton::indicator:unchecked:pressed
{
    border: none;
    outline: none;
    border-image: url(:/dark/radio_unchecked.svg);
}


QRadioButton::indicator:checked
{
    border: none;
    outline: none;
    border-image: url(:/dark/radio_checked.svg);
}

QRadioButton::indicator:checked:hover,
QRadioButton::indicator:checked:focus,
QRadioButton::indicator:checked:pressed
{
    border: none;
    outline: none;
    border-image: url(:/dark/radio_checked.svg);
}

QRadioButton::indicator:checked:disabled
{
    outline: none;
    border-image: url(:/dark/radio_checked_disabled.svg);
}

QRadioButton::indicator:unchecked:disabled
{
    border-image: url(:/dark/radio_unchecked_disabled.svg);
}

QMenuBar
{
    background-color: @dark-base3;
    color: #eff0f1;
}

QMenuBar::item
{
    background: transparent;
}

QMenuBar::item:selected
{
    background: transparent;
    border: 0.1ex solid #76797c;
}

QMenuBar::item:pressed
{
    border: 0.1ex solid #76797c;
    background-color: #3daee9;
    color: #eff0f1;
    margin-bottom: -0.1ex;
    padding-bottom: 0.1ex;
}

QMenu
{
    border: 0.1ex solid #76797c;
    color: #eff0f1;
    margin: 0.2ex;
}

QMenu::icon
{
    margin: 0.5ex;
}

QMenu::item
{
    padding: 0.5ex 3ex 0.5ex 3ex;
    margin-left: 0.5ex;
    border: 0.1ex solid transparent; /* reserve space for selection border */
}

QMenu::item:selected
{
    color: #eff0f1;
}

QMenu::separator
{
    height: 0.2ex;
    background: lightblue;
    margin-left: 1ex;
    margin-right: 0.5ex;
}

/* non-exclusive indicator = check box style indicator
   (see QActionGroup::setExclusive) */
QMenu::indicator:non-exclusive:unchecked
{
    border-image: url(:/dark/checkbox_unchecked_disabled.svg);
}

QMenu::indicator:non-exclusive:unchecked:selected
{
    border-image: url(:/dark/checkbox_unchecked_disabled.svg);
}

QMenu::indicator:non-exclusive:checked
{
    border-image: url(:/dark/checkbox_checked.svg);
}

QMenu::indicator:non-exclusive:checked:selected
{
    border-image: url(:/dark/checkbox_checked.svg);
}

/* exclusive indicator = radio button style indicator (see QActionGroup::setExclusive) */
QMenu::indicator:exclusive:unchecked
{
    border-image: url(:/dark/radio_unchecked_disabled.svg);
}

QMenu::indicator:exclusive:unchecked:selected
{
    border-image: url(:/dark/radio_unchecked_disabled.svg);
}

QMenu::indicator:exclusive:checked
{
    border-image: url(:/dark/radio_checked.svg);
}

QMenu::indicator:exclusive:checked:selected
{
    border-image: url(:/dark/radio_checked.svg);
}

QMenu::right-arrow
{
    margin: 0.5ex;
    border-image: url(:/light/right_arrow.svg);
    width: 0.6ex;
    height: 0.9ex;
}


QWidget:disabled
{
    color: #454545;
    background-color: @dark-base3;
}

QAbstractItemView
{
    alternate-background-color: @dark-base3;
    color: #eff0f1;
    border: 0.1ex solid 3A3939;
    border-radius: 0.2ex;
}

QWidget:focus,
QMenuBar:focus
{
    border: 0.1ex solid #3daee9;
}

QTabWidget:focus,
QCheckBox:focus,
QRadioButton:focus,
QSlider:focus
{
    border: none;
}

QLineEdit
{
    background-color: #232629;
    padding: 0.5ex;
    border-style: solid;
    border: 0.1ex solid #76797c;
    border-radius: 0.2ex;
    color: #eff0f1;
}

QGroupBox
{
    border: 0.1ex solid #76797c;
    border-radius: 0.2ex;
    padding-top: 1ex;
    margin-top: 1ex;
}

QGroupBox::title
{
    subcontrol-origin: margin;
    subcontrol-position: top center;
    padding-left: 0.1ex;
    padding-right: 0.1ex;
    margin-top: -0.7ex;
}

QAbstractScrollArea
{
    border-radius: 0.2ex;
    border: 0.1ex solid #76797c;
    background-color: transparent;
}

QScrollBar:horizontal
{
    height: 1.5ex;
    margin: 0.3ex 1.5ex 0.3ex 1.5ex;
    border: 0.1ex transparent #2A2929;
    border-radius: 0.4ex;
    background-color: #2A2929;
}

QScrollBar::handle:horizontal
{
    background-color: #3daee9;
    min-width: 0.5ex;
    border-radius: 0.4ex;
}

QScrollBar::add-line:horizontal
{
    margin: 0px 0.3ex 0px 0.3ex;
    border-image: url(:/dark/right_arrow_disabled.svg);
    width: 1ex;
    height: 1ex;
    subcontrol-position: right;
    subcontrol-origin: margin;
}

QScrollBar::sub-line:horizontal
{
    margin: 0ex 0.3ex 0ex 0.3ex;
    border-image: url(:/dark/left_arrow_disabled.svg);
    width: 1ex;
    height: 1ex;
    subcontrol-position: left;
    subcontrol-origin: margin;
}

QScrollBar::add-line:horizontal:hover,
QScrollBar::add-line:horizontal:on
{
    border-image: url(:/dark/right_arrow.svg);
    width: 1ex;
    height: 1ex;
    subcontrol-position: right;
    subcontrol-origin: margin;
}


QScrollBar::sub-line:horizontal:hover,
QScrollBar::sub-line:horizontal:on
{
    border-image: url(:/dark/left_arrow.svg);
    width: 1ex;
    height: 1ex;
    subcontrol-position: left;
    subcontrol-origin: margin;
}

QScrollBar::up-arrow:horizontal,
QScrollBar::down-arrow:horizontal
{
    background: none;
}


QScrollBar::add-page:horizontal,
QScrollBar::sub-page:horizontal
{
    background: none;
}

QScrollBar:vertical
{
    background-color: #2A2929;
    width: 1.5ex;
    margin: 1.5ex 0.3ex 1.5ex 0.3ex;
    border: 0.1ex transparent #2A2929;
    border-radius: 0.4ex;
}

QScrollBar::handle:vertical
{
    background-color: #3daee9;
    min-height: 0.5ex;
    border-radius: 0.4ex;
}

QScrollBar::sub-line:vertical
{
    margin: 0.3ex 0ex 0.3ex 0ex;
    border-image: url(:/dark/up_arrow_disabled.svg);
    height: 1ex;
    width: 1ex;
    subcontrol-position: top;
    subcontrol-origin: margin;
}

QScrollBar::add-line:vertical
{
    margin: 0.3ex 0ex 0.3ex 0ex;
    border-image: url(:/dark/down_arrow_disabled.svg);
    height: 1ex;
    width: 1ex;
    subcontrol-position: bottom;
    subcontrol-origin: margin;
}

QScrollBar::sub-line:vertical:hover,
QScrollBar::sub-line:vertical:on
{

    border-image: url(:/dark/up_arrow.svg);
    height: 1ex;
    width: 1ex;
    subcontrol-position: top;
    subcontrol-origin: margin;
}


QScrollBar::add-line:vertical:hover,
QScrollBar::add-line:vertical:on
{
    border-image: url(:/dark/down_arrow.svg);
    height: 1ex;
    width: 1ex;
    subcontrol-position: bottom;
    subcontrol-origin: margin;
}

QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical
{
    background: none;
}


QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical
{
    background: none;
}

QTextEdit
{
    background-color: #232629;
    color: #eff0f1;
    border: 0.1ex solid #76797c;
}

QPlainTextEdit
{
    background-color: #232629;;
    color: #eff0f1;
    border-radius: 0.2ex;
    border: 0.1ex solid #76797c;
}

QHeaderView::section
{
    background-color: #76797c;
    color: #eff0f1;
    padding: 0.5ex;
    border: 0.1ex solid #76797c;
}

QSizeGrip
{
    border-image: url(:/dark/sizegrip.svg);
    width: 1.2ex;
    height: 1.2ex;
}

QMainWindow::separator
{
    background-color: @dark-base3;
    color: white;
    padding-left: 0.4ex;
    spacing: 0.2ex;
    border: 0.1ex dashed #76797c;
}

QMainWindow::separator:hover
{

    background-color: #787876;
    color: white;
    padding-left: 0.4ex;
    border: 0.1ex solid #76797c;
    spacing: 0.2ex;
}

QMenu::separator
{
    height: 0.1ex;
    background-color: #76797c;
    color: white;
    padding-left: 0.4ex;
    margin-left: 1ex;
    margin-right: 0.5ex;
}

QFrame[frameShape="2"],  /* QFrame::Panel == 0x0003 */
QFrame[frameShape="3"],  /* QFrame::WinPanel == 0x0003 */
QFrame[frameShape="4"],  /* QFrame::HLine == 0x0004 */
QFrame[frameShape="5"],  /* QFrame::VLine == 0x0005 */
QFrame[frameShape="6"]  /* QFrame::StyledPanel == 0x0006 */
{
    border-width: 0.1ex;
    padding: 0.1ex;
    border-style: solid;
    border-color: @dark-base3;
    background-color: #76797c;
    border-radius: 0.5ex;
}

QStackedWidget
{
    border: 0.1ex transparent black;
}

QToolBar
{
    border: 0.1ex transparent #393838;
    background: 0.1ex solid @dark-base3;
    font-weight: bold;
}

QToolBar::handle:horizontal
{
    border-image: url(:/dark/hmovetoolbar.svg);
    width = 1.6ex;
    height = 6.4ex;
}

QToolBar::handle:vertical
{
    border-image: url(:/dark/vmovetoolbar.svg);
    width = 5.4ex;
    height = 1ex;
}

QToolBar::separator:horizontal
{
    border-image: url(:/dark/hsepartoolbar.svg);
    width = 0.7ex;
    height = 6.3ex;
}

QToolBar::separator:vertical
{
    border-image: url(:/dark/vsepartoolbars.svg);
    width = 6.3ex;
    height = 0.7ex;
}

QPushButton
{
    color: #eff0f1;
    background-color: qlineargradient(x1: 0.5, y1: 0.5 x2: 0.5, y2: 1, stop: 0 #3b4045, stop: 0.5 @dark-base3);
    border-width: 0.1ex;
    border-color: #76797c;
    border-style: solid;
    padding: 0.5ex;
    border-radius: 0.2ex;
    outline: none;
}

QPushButton:disabled
{
    background-color: @dark-base3;
    border-width: 0.1ex;
    border-color: #454545;
    border-style: solid;
    padding-top: 0.5ex;
    padding-bottom: 0.5ex;
    padding-left: 1ex;
    padding-right: 1ex;
    border-radius: 0.2ex;
    color: #454545;
}

QPushButton:focus
{
    color: white;
}

QPushButton:pressed
{
    background-color: @dark-base3;
    padding-top: -1.5ex;
    padding-bottom: -1.7ex;
}

QComboBox
{
    selection-background-color: #3daee9;
    border-style: solid;
    border: 0.1ex solid #76797c;
    border-radius: 0.2ex;
    padding: 0.5ex;
    min-width: 7.5ex;
}

QPushButton:checked
{
    background-color: #76797c;
    border-color: #6A6969;
}

QPushButton:hover
{
    background-color: qlineargradient(x1: 0.5, y1: 0.5 x2: 0.5, y2: 1, stop: 0 #454a4f, stop: 0.5 #3b4045);
    border: 0.1ex solid #3daee9;
    color: #eff0f1;
}

QPushButton:checked:hover
{
    background-color: qlineargradient(x1: 0.5, y1: 0.5 x2: 0.5, y2: 1, stop: 0 #808386, stop: 0.5 #76797c);
    border: 0.1ex solid #3daee9;
    color: #eff0f1;
}

QComboBox:hover,
QAbstractSpinBox:hover,
QLineEdit:hover,
QTextEdit:hover,
QPlainTextEdit:hover,
QAbstractView:hover,
QTreeView:hover
{
    border: 0.1ex solid #3daee9;
    color: #eff0f1;
}

QComboBox:hover:pressed,
QPushButton:hover:pressed,
QAbstractSpinBox:hover:pressed,
QLineEdit:hover:pressed,
QTextEdit:hover:pressed,
QPlainTextEdit:hover:pressed,
QAbstractView:hover:pressed,
QTreeView:hover:pressed
{
    background-color: @dark-base3;
}

QComboBox:on
{
    padding-top: 0.3ex;
    padding-left: 0.4ex;
    selection-background-color: #4a4a4a;
}

QComboBox QAbstractItemView
{
    background-color: #232629;
    border-radius: 0.2ex;
    border: 0.1ex solid #76797c;
    selection-background-color: #3daee9;
}

QComboBox::drop-down
{
    subcontrol-origin: padding;
    subcontrol-position: top right;
    width: 1.5ex;

    border-left-width: 0ex;
    border-left-color: darkgray;
    border-left-style: solid;
    border-top-right-radius: 0.3ex;
    border-bottom-right-radius: 0.3ex;
}

QComboBox::down-arrow
{
    border-image: url(:/dark/down_arrow_disabled.svg);
    width: 0.9ex;
    height: 0.6ex;
}

QComboBox::down-arrow:on,
QComboBox::down-arrow:hover,
QComboBox::down-arrow:focus
{
    border-image: url(:/dark/down_arrow.svg);
    width: 0.9ex;
    height: 0.6ex;
}

QAbstractSpinBox
{
    padding: 0.5ex;
    border: 0.1ex solid #76797c;
    background-color: #232629;
    color: #eff0f1;
    border-radius: 0.2ex;
    min-width: 7.5ex;
}

QAbstractSpinBox:up-button
{
    background-color: transparent;
    subcontrol-origin: border;
    subcontrol-position: center right;
}

QAbstractSpinBox:down-button
{
    background-color: transparent;
    subcontrol-origin: border;
    subcontrol-position: center left;
}

QAbstractSpinBox::up-arrow,
QAbstractSpinBox::up-arrow:disabled,
QAbstractSpinBox::up-arrow:off
{
    border-image: url(:/dark/up_arrow_disabled.svg);
    width: 0.9ex;
    height: 0.6ex;
}

QAbstractSpinBox::up-arrow:hover
{
    border-image: url(:/dark/up_arrow.svg);
    width: 0.9ex;
    height: 0.6ex;
}

QAbstractSpinBox::down-arrow,
QAbstractSpinBox::down-arrow:disabled,
QAbstractSpinBox::down-arrow:off
{
    border-image: url(:/dark/down_arrow_disabled.svg);
    width: 0.9ex;
    height: 0.6ex;
}

QAbstractSpinBox::down-arrow:hover
{
    border-image: url(:/dark/down_arrow.svg);
    width: 0.9ex;
    height: 0.6ex;
}

QLabel
{
    border: 0ex solid black;
}

/* BORDERS */
QTabWidget::pane
{
    padding: 0.5ex;
    margin: 0.1ex;
}

QTabWidget::pane:top
{
    border: 0.1ex solid #76797c;
    top: -0.1ex;
}

QTabWidget::pane:bottom
{
    border: 0.1ex solid #76797c;
    bottom: -0.1ex;
}

QTabWidget::pane:left
{
    border: 0.1ex solid #76797c;
    right: -0.1ex;
}

QTabWidget::pane:right
{
    border: 0.1ex solid #76797c;
    left: -0.1ex;
}


QTabBar
{
    qproperty-drawBase: 0;
    left: 0.5ex; /* move to the right by 0.5ex */
    border-radius: 0.3ex;
}

QTabBar:focus
{
    border: 0ex transparent black;
}

QTabBar::close-button
{
    border-image: url(:/dark/close.svg);
    background: transparent;
}

QTabBar::close-button:hover
{
    border-image: url(:/dark/close-hover.svg);
    width: 1.2ex;
    height: 1.2ex;
    background: transparent;
}

QTabBar::close-button:pressed
{
    border-image: url(:/dark/close-pressed.svg);
    width: 1.2ex;
    height: 1.2ex;
    background: transparent;
}

/* TOP TABS */
QTabBar::tab:top
{
    color: #eff0f1;
    border: 0.1ex transparent black;
    border-left: 0.1ex solid #76797c;
    border-top: 0.1ex solid #76797c;
    background-color: @dark-base3;
    padding: 0.5ex;
    min-width: 50px;
    border-top-left-radius: 0.2ex;
    border-top-right-radius: 0.2ex;
}

QTabBar::tab:top:last,
QTabBar::tab:top:only-one
{
    color: #eff0f1;
    border: 0.1ex transparent black;
    border-left: 0.1ex solid #76797c;
    border-right: 0.1ex solid #76797c;
    border-top: 0.1ex solid #76797c;
    background-color: @dark-base3;
    padding: 0.5ex;
    min-width: 50px;
    border-top-left-radius: 0.2ex;
    border-top-right-radius: 0.2ex;
}

QTabBar::tab:top:!selected
{
    color: #eff0f1;
    background-color: #54575B;
    border: 0.1ex transparent black;
    border-left: 0.1ex solid #76797c;
    border-top-left-radius: 0.2ex;
    border-top-right-radius: 0.2ex;
}

QTabBar::tab:top:first:!selected
{
    color: #eff0f1;
    background-color: #54575B;
    border: 0.1ex transparent black;
    border-top-left-radius: 0.2ex;
    border-top-right-radius: 0.2ex;
}

QTabBar::tab:top:!selected:hover
{
    background-color: rgba(61, 173, 232, 0.2);
    border: 0.1ex rgba(61, 173, 232, 0.2);
    border-left: 0.1ex solid #76797c;
}

QTabBar::tab:top:!selected:first:hover
{
    background-color: rgba(61, 173, 232, 0.2);
    border: 0.1ex rgba(61, 173, 232, 0.2);
}

/* BOTTOM TABS */

QTabBar::tab:bottom
{
    color: #eff0f1;
    border: 0.1ex transparent black;
    border-left: 0.1ex solid #76797c;
    border-bottom: 0.1ex solid #76797c;
    background-color: @dark-base3;
    padding: 0.5ex;
    border-bottom-left-radius: 0.2ex;
    border-bottom-right-radius: 0.2ex;
    min-width: 50px;
}

QTabBar::tab:bottom:last,
QTabBar::tab:bottom:only-one
{
    color: #eff0f1;
    border: 0.1ex transparent black;
    border-left: 0.1ex solid #76797c;
    border-right: 0.1ex solid #76797c;
    border-bottom: 0.1ex solid #76797c;
    background-color: @dark-base3;
    padding: 0.5ex;
    border-bottom-left-radius: 0.2ex;
    border-bottom-right-radius: 0.2ex;
    min-width: 50px;
}

QTabBar::tab:bottom:!selected
{
    color: #eff0f1;
    background-color: #54575B;
    border: 0.1ex transparent black;
    border-left: 0.1ex solid #76797c;
    border-bottom-left-radius: 0.2ex;
    border-bottom-right-radius: 0.2ex;
}

QTabBar::tab:bottom:first:!selected
{
    color: #eff0f1;
    background-color: #54575B;
    border: 0.1ex transparent black;
    border-top-left-radius: 0.2ex;
    border-top-right-radius: 0.2ex;
}

QTabBar::tab:bottom:!selected:hover
{
    background-color: rgba(61, 173, 232, 0.2);
    border: 0.1ex rgba(61, 173, 232, 0.2);
    border-left: 0.1ex solid #76797c;
}

QTabBar::tab:bottom:!selected:first:hover
{
    background-color: rgba(61, 173, 232, 0.2);
    border: 0.1ex rgba(61, 173, 232, 0.2);
}

/* LEFT TABS */
QTabBar::tab:left
{
    color: #eff0f1;
    border: 0.1ex transparent black;
    border-top: 0.1ex solid #76797c;
    border-right: 0.1ex solid #76797c;
    background-color: @dark-base3;
    padding: 0.5ex;
    border-top-right-radius: 0.2ex;
    border-bottom-right-radius: 0.2ex;
    min-height: 50px;
}

QTabBar::tab:left:last,
QTabBar::tab:left:only-one
{
    color: #eff0f1;
    border: 0.1ex transparent black;
    border-top: 0.1ex solid #76797c;
    border-bottom: 0.1ex solid #76797c;
    border-right: 0.1ex solid #76797c;
    background-color: @dark-base3;
    padding: 0.5ex;
    border-top-right-radius: 0.2ex;
    border-bottom-right-radius: 0.2ex;
    min-height: 50px;
}

QTabBar::tab:left:!selected
{
    color: #eff0f1;
    background-color: #54575B;
    border: 0.1ex transparent black;
    border-top: 0.1ex solid #76797c;
    border-top-right-radius: 0.2ex;
    border-bottom-right-radius: 0.2ex;
}

QTabBar::tab:left:!selected:hover
{
    background-color: rgba(61, 173, 232, 0.2);
    border: 0.1ex rgba(61, 173, 232, 0.2);
    border-top: 0.1ex solid #76797c;
}

QTabBar::tab:left:!selected:first:hover
{
    background-color: rgba(61, 173, 232, 0.2);
    border: 0.1ex rgba(61, 173, 232, 0.2);
}

/* RIGHT TABS */
QTabBar::tab:right
{
    color: #eff0f1;
    border: 0.1ex transparent black;
    border-top: 0.1ex solid #76797c;
    border-left: 0.1ex solid #76797c;
    background-color: @dark-base3;
    padding: 0.5ex;
    border-top-left-radius: 0.2ex;
    border-bottom-left-radius: 0.2ex;
    min-height: 50px;
}

QTabBar::tab:right:last,
QTabBar::tab:right:only-one
{
    color: #eff0f1;
    border: 0.1ex transparent black;
    border-top: 0.1ex solid #76797c;
    border-bottom: 0.1ex solid #76797c;
    border-left: 0.1ex solid #76797c;
    background-color: @dark-base3;
    padding: 0.5ex;
    border-top-left-radius: 0.2ex;
    border-bottom-left-radius: 0.2ex;
    min-height: 50px;
}

QTabBar::tab:right:!selected
{
    color: #eff0f1;
    background-color: #54575B;
    border: 0.1ex transparent black;
    border-top: 0.1ex solid #76797c;
    border-top-left-radius: 0.2ex;
    border-bottom-left-radius: 0.2ex;
}

QTabBar::tab:right:!selected:hover
{
    background-color: rgba(61, 173, 232, 0.2);
    border: 0.1ex rgba(61, 173, 232, 0.2);
    border-top: 0.1ex solid #76797c;
}

QTabBar::tab:right:!selected:first:hover
{
    background-color: rgba(61, 173, 232, 0.2);
    border: 0.1ex rgba(61, 173, 232, 0.2);
}

QTabBar QToolButton::right-arrow:enabled
{
    border-image: url(:/dark/right_arrow.svg);
}

QTabBar QToolButton::left-arrow:enabled
{
    border-image: url(:/dark/left_arrow.svg);
}

QTabBar QToolButton::right-arrow:disabled
{
    border-image: url(:/dark/right_arrow_disabled.svg);
}

QTabBar QToolButton::left-arrow:disabled
{
    border-image: url(:/dark/left_arrow_disabled.svg);
}

QDockWidget
{
    background: @dark-base3;
    border: 0.1ex solid #403F3F;
    titlebar-close-icon: url(:/dark/transparent.svg);
    titlebar-normal-icon: url(:/dark/transparent.svg);
}

QDockWidget::close-button,
QDockWidget::float-button
{
    border: 0.1ex solid transparent;
    border-radius: 0.2ex;
    background: transparent;
}

QDockWidget::float-button
{
    border-image: url(:/dark/undock.svg);
}

QDockWidget::float-button:hover
{
    border-image: url(:/dark/undock-hover.svg) ;
}

QDockWidget::close-button
{
    border-image: url(:/dark/close.svg) ;
}

QDockWidget::close-button:hover
{
    border-image: url(:/dark/close-hover.svg) ;
}

QDockWidget::close-button:pressed
{
    border-image: url(:/dark/close-pressed.svg) ;
}

QTreeView,
QListView
{
    border: 0.1ex solid #76797c;
    background-color: #232629;
}

QTreeView::branch:has-siblings:!adjoins-item
{
    border-image: url(:/dark/stylesheet-vline.svg) 0;
}

QTreeView::branch:has-siblings:adjoins-item
{
    border-image: url(:/dark/stylesheet-branch-more.svg) 0;
}

QTreeView::branch:!has-children:!has-siblings:adjoins-item
{
    border-image: url(:/dark/stylesheet-branch-end.svg) 0;
}

QTreeView::branch:has-children:!has-siblings:closed,
QTreeView::branch:closed:has-children:has-siblings
{
    border-image: url(:/dark/branch-closed.svg);
}

QTreeView::branch:open:has-children:!has-siblings,
QTreeView::branch:open:has-children:has-siblings
{
    border-image: url(:/dark/branch-open.svg);
}

QTableView::item,
QListView::item,
QTreeView::item
{
    padding: 0.3ex;
}

QTableView::item:!selected:hover,
QListView::item:!selected:hover,
QTreeView::item:!selected:hover
{
    background-color: rgba(61, 173, 232, 0.2);
    outline: 0;
    color: #eff0f1;
    padding: 0.3ex;
}

QSlider::groove:horizontal
{
    border: 0.1ex solid @dark-base3;
    height: 0.4ex;
    background: #565a5e;
    margin: 0ex;
    border-radius: 0.2ex;
}

QSlider::handle:horizontal
{
    background: #232629;
    border: 0.1ex solid #626568;
    width: 1.6ex;
    height: 1.6ex;
    margin: -0.8ex 0;
    border-radius: 0.9ex;
}

QSlider::groove:vertical
{
    border: 0.1ex solid @dark-base3;
    width: 0.4ex;
    background: #565a5e;
    margin: 0ex;
    border-radius: 0.3ex;
}

QSlider::handle:vertical
{
    background: #232629;
    border: 0.1ex solid #626568;
    width: 1.6ex;
    height: 1.6ex;
    margin: 0 -0.8ex;
    border-radius: 0.9ex;
}

QSlider::handle:horizontal:hover,
QSlider::handle:horizontal:focus,
QSlider::handle:vertical:hover,
QSlider::handle:vertical:focus
{
    border: 0.1ex solid #3daee9;
}

QSlider::sub-page:horizontal,
QSlider::add-page:vertical
{
    background: #3daee9;
    border-radius: 0.3ex;
}

QSlider::add-page:horizontal,
QSlider::sub-page:vertical
{
    background: #626568;
    border-radius: 0.3ex;
}

QToolButton
{
    background-color: transparent;
    border: 0.1ex solid #76797c;
    border-radius: 0.2ex;
    margin: 0.3ex;
    padding: 0.5ex;
}

QToolButton[popupMode="1"]  /* only for MenuButtonPopup */
{
    padding-right: 2ex; /* make way for the popup button */
}

QToolButton[popupMode="2"]  /* only for InstantPopup */
{
    padding-right: 1ex; /* make way for the popup button */
}

QToolButton::menu-indicator
{
    border-image: none;
    image: url(:/dark/down_arrow.svg);
    top: -0.7ex;
    left: -0.2ex;
}

QToolButton::menu-arrow
{
    border-image: none;
    image: url(:/dark/down_arrow.svg);
}

QToolButton:hover,
QToolButton::menu-button:hover
{
    background-color: transparent;
    border: 0.1ex solid #3daee9;
}

QToolButton:checked,
QToolButton:pressed,
QToolButton::menu-button:pressed
{
    background-color: #3daee9;
    border: 0.1ex solid #3daee9;
    padding: 0.5ex;
}

QToolButton::menu-button
{
    border: 0.1ex solid #76797c;
    border-top-right-radius: 6px;
    border-bottom-right-radius: 6px;
    /* 1ex width + 0.4ex for border + no text = 2ex allocated above */
    width: 1ex;
    padding: 0.5ex;
    outline: none;
}

QToolButton::menu-arrow:open
{
    border: 0.1ex solid #76797c;
}

QPushButton::menu-indicator
{
    subcontrol-origin: padding;
    subcontrol-position: bottom right;
    left: 0.8ex;
}

QTableView
{
    border: 0.1ex solid #76797c;
    gridline-color: @dark-base3;
    background-color: #232629;
}


QTableView,
QHeaderView
{
    border-radius: 0px;
}

QTableView::item:pressed,
QListView::item:pressed,
QTreeView::item:pressed
{
    background: #3daee9;
    color: #eff0f1;
}

QTableView::item:selected:active,
QTreeView::item:selected:active,
QListView::item:selected:active
{
    background: #3daee9;
    color: #eff0f1;
}

QListView::item:selected:hover,
QTreeView::item:selected:hover
{
    background-color: #47b8f3;
    color: #eff0f1;
}

QHeaderView
{
    background-color: @dark-base3;
    border: 0.1ex transparent;
    border-radius: 0px;
    margin: 0px;
    padding: 0px;

}

QHeaderView::section
{
    background-color: @dark-base3;
    color: #eff0f1;
    padding: 0.5ex;
    border: 0.1ex solid #76797c;
    border-radius: 0px;
    text-align: center;
}

QHeaderView::section::vertical::first,
QHeaderView::section::vertical::only-one
{
    border-top: 0.1ex solid #76797c;
}

QHeaderView::section::vertical
{
    border-top: transparent;
}

QHeaderView::section::horizontal::first,
QHeaderView::section::horizontal::only-one
{
    border-left: 0.1ex solid #76797c;
}

QHeaderView::section::horizontal
{
    border-left: transparent;
}


QHeaderView::section:checked
{
    color: white;
    background-color: #334e5e;
}

 /* style the sort indicator */
QHeaderView::down-arrow
{
    image: url(:/dark/down_arrow.svg);
}

QHeaderView::up-arrow
{
    image: url(:/dark/up_arrow.svg);
}

QTableCornerButton::section
{
    background-color: @dark-base3;
    border: 0.1ex transparent #76797c;
    border-radius: 0px;
}

QToolBox
{
    padding: 0.5ex;
    border: 0.1ex transparent black;
}

QToolBox:selected
{
    background-color: @dark-base3;
    border-color: #3daee9;
}

QToolBox:hover
{
    border-color: #3daee9;
}

QStatusBar::item
{
    border: 0px transparent dark;
}

QFrame[height="3"],
QFrame[width="3"]
{
    background-color: #76797c;
}

QSplitter::handle
{
    border: 0.1ex dashed #76797c;
}

QSplitter::handle:hover
{
    background-color: #787876;
    border: 0.1ex solid #76797c;
}

QSplitter::handle:horizontal
{
    width: 0.1ex;
}

QSplitter::handle:vertical
{
    height: 0.1ex;
}

QProgressBar:horizontal
{
    background-color: #626568;
    border: 0.1ex solid @dark-base3;
    border-radius: 0.3ex;
    height: 0.5ex;
    text-align: right;
    margin-top: 0.5ex;
    margin-bottom: 0.5ex;
    margin-right: 5ex;
    padding: 0px;
}

QProgressBar::chunk:horizontal
{
    background-color: #3daee9;
    border: 0.1ex transparent;
    border-radius: 0.3ex;
}

QSpinBox,
QDoubleSpinBox
{
    padding-right: 1.5ex;
}

QSpinBox::up-button,
QDoubleSpinBox::up-button
{
    subcontrol-origin: content;
    subcontrol-position: right top;

    width: 1.6ex;
    border-width: 0.1ex;
}

QSpinBox::up-arrow,
QDoubleSpinBox::up-arrow
{
    border-image: url(:/dark/up_arrow.svg);
    width: 0.9ex;
    height: 0.6ex;
}

QSpinBox::up-arrow:hover,
QSpinBox::up-arrow:pressed,
QDoubleSpinBox::up-arrow:hover,
QDoubleSpinBox::up-arrow:pressed
{
    border-image: url(:/dark/up_arrow-hover.svg);
    width: 0.9ex;
    height: 0.6ex;
}

QSpinBox::up-arrow:disabled,
QSpinBox::up-arrow:off,
QDoubleSpinBox::up-arrow:disabled,
QDoubleSpinBox::up-arrow:off
{
   border-image: url(:/dark/up_arrow_disabled.svg);
}

QSpinBox::down-button,
QDoubleSpinBox::down-button
{
    subcontrol-origin: content;
    subcontrol-position: right bottom;

    width: 1.6ex;
    border-width: 0.1ex;
}

QSpinBox::down-arrow,
QDoubleSpinBox::down-arrow
{
    border-image: url(:/dark/down_arrow.svg);
    width: 0.9ex;
    height: 0.6ex;
}

QSpinBox::down-arrow:hover,
QSpinBox::down-arrow:pressed,
QDoubleSpinBox::down-arrow:hover,
QDoubleSpinBox::down-arrow:pressed
{
    border-image: url(:/dark/down_arrow-hover.svg);
    width: 0.9ex;
    height: 0.6ex;
}

QSpinBox::down-arrow:disabled,
QSpinBox::down-arrow:off,
QDoubleSpinBox::down-arrow:disabled,
QDoubleSpinBox::down-arrow:off
{
   border-image: url(:/dark/down_arrow_disabled.svg);
}</t>
<t tx="chris.20180308171552.30"></t>
<t tx="chris.20180308171552.31" lineYOffset="4b002e">These settings must exist because they are *not* used in the css.</t>
<t tx="chris.20180308171552.32"></t>
<t tx="chris.20180308171552.33"></t>
<t tx="chris.20180308171552.34"></t>
<t tx="chris.20180308171552.35"></t>
<t tx="chris.20180308171552.36">was blue

Solarized blue      #268bd2</t>
<t tx="chris.20180308171552.37">was blue

Solarized blue      #268bd2</t>
<t tx="chris.20180308171552.38">was blue

Solarized blue      #268bd2</t>
<t tx="chris.20180308171552.39">was blue

Solarized blue      #268bd2</t>
<t tx="chris.20180308171552.40">was #00aa00 (Idle comment green)

Solarize green      #859900
Solarized cyan      #2aa198
Solarized violet    #6c71c4
Solarized orange    #cb4b16</t>
<t tx="chris.20180308171552.41"></t>
<t tx="chris.20180308171552.42"></t>
<t tx="chris.20180308171552.43"></t>
<t tx="chris.20180308171552.44">was black
was #2aa198</t>
<t tx="chris.20180308171552.45">was firebrick3

Solarized colors:

magenta   #d33682

Dark comments   base01
Light comments  base1 comments
</t>
<t tx="chris.20180308171552.46"></t>
<t tx="chris.20180308171552.47"></t>
<t tx="chris.20180308171552.48"></t>
<t tx="chris.20180308171552.49"></t>
<t tx="chris.20180308171552.50"># New: solarized-blue
</t>
<t tx="chris.20180308171552.51"></t>
<t tx="chris.20180308171552.52"></t>
<t tx="chris.20180308171552.53">The color of text in doc parts.

firebrick3
</t>
<t tx="chris.20180308171552.54">The color of Leo keywords such as @ignore, @color, etc.

#00aa00
</t>
<t tx="chris.20180308171552.55">The color of name in &lt; &lt; name &gt; &gt; when name is defined.

red

</t>
<t tx="chris.20180308171552.56">The background color that represents spaces when Show Invisibles mode is in effect.

gray80: #CCCCCC
gray90: #E5E5E5
</t>
<t tx="chris.20180308171552.57">The foreground color that represents tabs when Show Invisibles mode is in effect.

gray80: #CCCCCC
gray90: #E5E5E5
</t>
<t tx="chris.20180308171552.58">The color of name in &lt;&lt; name &gt;&gt; when name is undefined.
</t>
<t tx="chris.20180308171552.59">purple
</t>
<t tx="chris.20180308171552.60">Text to test with.</t>
<t tx="chris.20180308171552.61">Background color of log text.</t>
<t tx="chris.20180308171552.62">Foreground color of log text.

</t>
<t tx="chris.20180308171552.63"></t>
<t tx="chris.20180308171552.64"></t>
<t tx="chris.20180308171552.65"></t>
<t tx="chris.20180308171552.66"></t>
<t tx="chris.20180308171552.67">Most widgets are colored in their css nodes.

Only colors appearing in several places are given here.</t>
<t tx="chris.20180308171552.68"></t>
<t tx="chris.20180308171552.69"></t>
<t tx="chris.20180308171552.70">test text</t>
<t tx="chris.20180308171552.71"></t>
<t tx="chris.20180308171552.72"></t>
<t tx="chris.20180308171552.73"></t>
<t tx="chris.20180308171552.74"></t>
<t tx="chris.20180308171552.75"></t>
<t tx="chris.20180308171552.76"></t>
<t tx="chris.20180308171552.77">Utility constants.</t>
<t tx="chris.20180308171552.78"></t>
<t tx="chris.20180308171552.79"></t>
<t tx="chris.20180308171552.80"></t>
<t tx="chris.20180308171552.81"></t>
<t tx="chris.20180308171552.82"></t>
<t tx="chris.20180308171552.83"></t>
<t tx="chris.20180308171552.84"></t>
<t tx="chris.20180308171552.85"></t>
<t tx="chris.20180308171552.86">none or underline</t>
<t tx="chris.20180308171552.87"></t>
<t tx="chris.20180308171552.88"></t>
<t tx="chris.20180308171552.89"></t>
<t tx="chris.20180308171552.90"></t>
<t tx="chris.20180308171552.91">Valid values are: normal,italic,oblique</t>
<t tx="chris.20180308171552.92">Huh?
valid values are: normal,bold,100,..,900
</t>
<t tx="chris.20180308171552.93"></t>
<t tx="chris.20180308171552.94"></t>
<t tx="chris.20180308171552.95">none or underline</t>
<t tx="chris.20180308171552.96"></t>
<t tx="chris.20180308171552.97"></t>
<t tx="chris.20180308171552.98"></t>
<t tx="chris.20180308171552.99">bold or regular</t>
<t tx="chris.20180309180448.10"></t>
<t tx="chris.20180309180448.2"></t>
<t tx="chris.20180309180448.3"></t>
<t tx="chris.20180309180448.4"></t>
<t tx="chris.20180309180448.5"></t>
<t tx="chris.20180309180448.6"></t>
<t tx="chris.20180309180448.7"></t>
<t tx="chris.20180309180448.8"></t>
<t tx="chris.20180309180448.9"></t>
<t tx="chris.20180309182828.1">LeoQTreeWidget#treeWidget 
{
  background: @dark-base3;
  color: @dark-base0;
  show-decoration-selected: 1; 
  padding: 2px solid @dark-base3;
  border-color: @dark-base3;
  font-family: @font-family-tree;
  font-size: @font-size-tree;
  font-weight: normal;
  font-style: normal;
}

QTreeView::branch:has-children:!has-siblings:closed,
QTreeView::branch:closed:has-children:has-siblings
{
    border-image: @tree-image-closed;
}

QTreeView::branch:open:has-children:!has-siblings,
QTreeView::branch:open:has-children:has-siblings
{
    border-image: @tree-image-open;
}

QTreeView::item:hover {
  background-color: @dark-base1;
  color: @dark-base0;
}

QTreeView::item:selected {
  background-color: @dark-base6;
  color: @dark-base0;
}

QTreeView QLineEdit {
  color: @dark-base0;
  background: @dark-base5;
  selection-color: @dark-base5; 
  selection-background-color: @dark-base6;
  font-family: @font-family-tree;
  font-size: @font-size-tree;
  font-weight: normal;
  font-style: normal;
  padding: 1px;
}

/*


QTreeWidget {
  
  background: @dark-base1;
  font-family: @font-family-tree;
  font-size: @font-size-tree;
  font-weight: normal; 
  font-style: normal; 
  padding: 2px solid @dark-base3;
  border-color: @dark-base1;
}

*/</t>
<t tx="chris.20180311131013.1">/* ===== From qt-gui-plugin-style-sheet ===== */

/*
@language css
at-tabwidth -2 causes a crash in parse-template!
*/
QDockWidget {
border: 5px solid red;
}
QDoubleSpinBox, QSpinBox, QDateEdit, QTimeEdit {
border: none;
padding: 3px;
margin-right: 5px;
}
QLabel {
color: #575b5f;
}
QLineEdit {
border: none;
padding: 3px;
}
QWidget {
/* Not for text widgets */
background:  #31363b;
color: #eff0f1;
border-color: #575b5f;
font-size: 16px;
}
/* The body pane */
QTextEdit#richTextEdit {
background-color: #232629;
color: #eff0f1;
border: 0.1ex solid #575b5f;
font-family: Inconsolata,Droid Sans Mono, DejaVu Sans Mono;
font-size: 22px;
font-weight: normal; /* normal,bold,100,..,900 */
font-style: normal; /* normal,italic,oblique */
padding-left: 3px;
padding-top: 3px;
padding-bottom: 3px;
padding-right: 3px;
height: 200%;
}
/* active pane highlighting */
QTextEdit#log-widget, LeoQTreeWidget#treeWidget, QTextEdit#richTextEdit {
border-style: solid;
border-width: 3px;
}
QTextEdit#log-widget {
border-color: #31363b;
}
LeoQTreeWidget#treeWidget {
border-color: #31363b;
}
QTextEdit#richTextEdit {
border-color: #31363b;
}
QTextEdit:focus#log-widget,LeoQTreeWidget:focus#treeWidget, QTextEdit:focus#richTextEdit {
border-color: #268bd2;
}
QPushButton
{
color: #eff0f1;
background-color: qlineargradient(x1: 0.5, y1: 0.5 x2: 0.5, y2: 1, stop: 0 #575b5f, stop: 0.5 #31363b);
border-width: 0.1ex;
border-color: #575b5f;
border-style: solid;
padding: 0.5ex;
border-radius: 0.2ex;
outline: none;
}
QPushButton:disabled
{
background-color: #31363b;
border-width: 0.1ex;
border-color: #575b5f;
border-style: solid;
padding-top: 0.5ex;
padding-bottom: 0.5ex;
padding-left: 1ex;
padding-right: 1ex;
border-radius: 0.2ex;
color: #575b5f;
}
QPushButton:hover
{
background-color: #224e65;
}
QPushButton:focus
{
color: white;
}
QPushButton:pressed
{
background-color: #31363b;
padding-top: -1.5ex;
padding-bottom: -1.7ex;
}
QTextEdit#log-widget {
background-color: #31363b;
color: #eff0f1;
/* selection-color: white; */
/* selection-background-color: blue; */
font-family: Inconsolata,Droid Sans Mono, DejaVu Sans Mono;
font-size: 16px;
font-weight: normal; /* normal,bold,100,..,900 */
font-style: normal; /* normal, italic,oblique */
}
QLineEdit#findPattern {
background-color: #232629;
}
QLineEdit#findChange {
background-color: #232629;
}
QListWidget#nodetags-listWidget {
background-color: #232629;
}
QMenuBar
{
background-color: #31363b;
color: #eff0f1;
}
QMenuBar::item
{
background: transparent;
}
QMenuBar::item:selected
{
background: #224e65;
border: 0.1ex solid #575b5f;
}
QMenuBar::item:pressed
{
border: 0.1ex solid #575b5f;
background-color: #3daee9;
color: #eff0f1;
margin-bottom: -0.1ex;
padding-bottom: 0.1ex;
}
QMenu
{
border: 0.1ex solid #575b5f;
color: #eff0f1;
margin: 0.2ex;
}
QMenu::icon
{
margin: 0.5ex;
}
QMenu::item
{
padding: 0.5ex 3ex 0.5ex 3ex;
margin-left: 0.5ex;
border: 0.1ex solid transparent; /* reserve space for selection border */
}
QMenu::item:selected
{
background: #224e65;
color: #eff0f1;
}
QMenu::separator
{
height: 0.2ex;
background: lightblue;
margin-left: 1ex;
margin-right: 0.5ex;
}
/* The mini-buffer */
QLabel#minibufferLabel {
color: #3daee9;
}
/* The minibuffer */
QLineEdit#lineEdit {
background-color: #232629;
padding: 0.5ex;
border-style: solid;
border: 0.1ex solid #575b5f;
border-radius: 0.2ex;
color: #eff0f1;
}
/* bookmarks plugin styling */
#show_bookmarks QPushButton {
margin: 0; padding: 1; border: none;
font-size: 11pt;
color: #eff0f1;
font-weight: regular;
text-decoration: @bookmarks_base_decoration;
}
#show_bookmarks QPushButton[style_class='bookmark_children'] {
font-size: ignore;
color: #eff0f1;
font-weight: ignore;
text-decoration: underline;
}
#show_bookmarks QPushButton[style_class='bookmark_expanded'] {
font-size: ignore;
color: #eff0f1;
font-weight: bold;
text-decoration: underline;
}
#show_bookmarks QPushButton[style_class='bookmark_current'] {
font-size: ignore;
color: blue;
font-weight: bold;
text-decoration: ignore;
}
QAbstractScrollArea
{
border-radius: 0.2ex;
border: 0.1ex solid #575b5f;
background-color: transparent;
}
QScrollBar:horizontal
{
height: 1.5ex;
margin: 0.3ex 1.5ex 0.3ex 1.5ex;
border: 0.1ex transparent #31363b;
border-radius: 0.4ex;
background-color: #31363b;
}
QScrollBar:horizontal:hover
{
height: 1.5ex;
margin: 0.3ex 1.5ex 0.3ex 1.5ex;
border: 0.1ex transparent #575b5f;
border-radius: 0.4ex;
background-color: #575b5f;
}
QScrollBar::handle:horizontal
{
background-color: #909396;
min-width: 0.5ex;
border-radius: 0.4ex;
}
QScrollBar::handle:horizontal:hover
{
background-color: #3daee9;
min-width: 0.5ex;
border-radius: 0.4ex;
}
QScrollBar::add-line:horizontal
{
margin: 0px 0.3ex 0px 0.3ex;
border-image: url(:/dark/right_arrow_disabled.svg);
width: 1ex;
height: 1ex;
subcontrol-position: right;
subcontrol-origin: margin;
}
QScrollBar::sub-line:horizontal
{
margin: 0ex 0.3ex 0ex 0.3ex;
border-image: url(:/dark/left_arrow_disabled.svg);
width: 1ex;
height: 1ex;
subcontrol-position: left;
subcontrol-origin: margin;
}
QScrollBar::add-line:horizontal:hover,
QScrollBar::add-line:horizontal:on
{
border-image: url(:/dark/right_arrow.svg);
width: 1ex;
height: 1ex;
subcontrol-position: right;
subcontrol-origin: margin;
}
QScrollBar::sub-line:horizontal:hover,
QScrollBar::sub-line:horizontal:on
{
border-image: url(:/dark/left_arrow.svg);
width: 1ex;
height: 1ex;
subcontrol-position: left;
subcontrol-origin: margin;
}
QScrollBar::up-arrow:horizontal,
QScrollBar::down-arrow:horizontal
{
background: none;
}
QScrollBar::add-page:horizontal,
QScrollBar::sub-page:horizontal
{
background: none;
}
QScrollBar:vertical
{
width: 1.5ex;
margin: 1.5ex 0.3ex 1.5ex 0.3ex;
border: 0.1ex transparent #31363b;
border-radius: 0.4ex;
background-color: #31363b;
}
QScrollBar:vertical:hover
{
width: 1.5ex;
margin: 1.5ex 0.3ex 1.5ex 0.3ex;
border: 0.1ex transparent #575b5f;
border-radius: 0.4ex;
background-color: #575b5f;
}
QScrollBar::handle:vertical
{
background-color: #909396;
min-height: 0.5ex;
border-radius: 0.4ex;
}
QScrollBar::handle:vertical:hover
{
background-color: #3daee9;
min-height: 0.5ex;
border-radius: 0.4ex;
}
QScrollBar::sub-line:vertical
{
margin: 0.3ex 0ex 0.3ex 0ex;
border-image: url(:/dark/up_arrow_disabled.svg);
height: 1ex;
width: 1ex;
subcontrol-position: top;
subcontrol-origin: margin;
}
QScrollBar::add-line:vertical
{
margin: 0.3ex 0ex 0.3ex 0ex;
border-image: url(:/dark/down_arrow_disabled.svg);
height: 1ex;
width: 1ex;
subcontrol-position: bottom;
subcontrol-origin: margin;
}
QScrollBar::sub-line:vertical:hover,
QScrollBar::sub-line:vertical:on
{
border-image: url(:/dark/up_arrow.svg);
height: 1ex;
width: 1ex;
subcontrol-position: top;
subcontrol-origin: margin;
}
QScrollBar::add-line:vertical:hover,
QScrollBar::add-line:vertical:on
{
border-image: url(:/dark/down_arrow.svg);
height: 1ex;
width: 1ex;
subcontrol-position: bottom;
subcontrol-origin: margin;
}
QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical
{
background: none;
}
QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical
{
background: none;
}
QSplitter::handle
{
border: 0.1ex dashed #575b5f;
}
QSplitter::handle:hover
{
background-color: #909396;
border: 0.1ex solid #575b5f;
}
QSplitter::handle:horizontal
{
width: 0.1ex;
}
QSplitter::handle:vertical
{
height: 0.1ex;
}
/* The status area */
QLineEdit#status1 {
background: #31363b;
border-color: #575b5f;
border-width: 1px;
border-style: solid;
}
QLineEdit#status2 {
background: #31363b;
border-color: #575b5f;
border-width: 1px;
border-style: solid;
}
QLineEdit#status1[style_class ~= 'info'],
QLineEdit#status2[style_class ~= 'info'] {
background: #268bd2;
color:      #fdf6e3;
}
QLineEdit#status1[style_class ~= 'fail'],
QLineEdit#status2[style_class ~= 'fail'] {
background: #ff0000;
color:      #eff0f1;
}
QTabBar
{
qproperty-drawBase: 0;
left: 0.5ex; /* move to the right by 0.5ex */
border-radius: 0.3ex;
}
QTabBar:focus
{
border: 0ex transparent black;
}
QTabBar::tab {
background: #31363b;
border: 3px solid #31363b;
border-bottom-color: #31363b; /* same as the pane color */
border-top-left-radius: 4px;
border-top-right-radius: 4px;
min-width: 8ex;
padding: 2px;
}
QTabBar::tab:hover {
background: #224e65;
border-bottom-color: #224e65;
}
QTabBar::tab:selected {
background-color: #575b5f;
border-bottom-color: #3daee9;
}
QTabBar::tab:!selected {
margin-top: 2px; /* make non-selected tabs look smaller */
}
LeoQTreeWidget#treeWidget
{
background: #31363b;
color: #eff0f1;
show-decoration-selected: 1;
padding: 2px solid #31363b;
border-color: #31363b;
font-family: Inconsolata,Droid Sans Mono, DejaVu Sans Mono;
font-size: 18px;
font-weight: normal;
font-style: normal;
}
QTreeView::branch:has-children:!has-siblings:closed,
QTreeView::branch:closed:has-children:has-siblings
{
border-image: url(/home/chris/leo-editor/leo/Icons/dark/branch_closed.svg);
}
QTreeView::branch:open:has-children:!has-siblings,
QTreeView::branch:open:has-children:has-siblings
{
border-image: url(/home/chris/leo-editor/leo/Icons/dark/branch_open.svg);
}
QTreeView::item:hover {
background-color: #909396;
color: #eff0f1;
}
QTreeView::item:selected {
background-color: #3daee9;
color: #eff0f1;
}
QTreeView QLineEdit {
color: #eff0f1;
background: #232629;
selection-color: #232629;
selection-background-color: #3daee9;
font-family: Inconsolata,Droid Sans Mono, DejaVu Sans Mono;
font-size: 18px;
font-weight: normal;
font-style: normal;
padding: 1px;
}
/*
QTreeWidget {
background: #909396;
font-family: Inconsolata,Droid Sans Mono, DejaVu Sans Mono;
font-size: 18px;
font-weight: normal;
font-style: normal;
padding: 2px solid #31363b;
border-color: #909396;
}
*/

</t>
<t tx="ekr.20180307012127.1"></t>
<t tx="ekr.20180307012426.2">@language python

@ This should be *colored* as rST.
@c

# Details: http://leoeditor.com/

&lt;&lt; undefined section &gt;&gt;
&lt;&lt; defined section &gt;&gt;

a = 2

def spam():
    pass
</t>
<t tx="ekr.20180307012426.3">Test.</t>
<t tx="ekr.20180307012426.4">@language python

table = (
    # g.actualColor calls 
    'error', 'info', 'warning',
    'black', 'white',
    'xxx',
    'firebrick', 'grey', 'pink', 'purple', # Tk colors.
    # Solarized colors...
    'blue', 'cyan', 'green','magenta', 'orange', 'red',
    'violet', 'yellow',
)
for s in table:
    g.es(s, color=s)
</t>
<t tx="ekr.20180307024846.1">True: show user tips on startup.</t>
<t tx="ekr.20180307024911.1"># For line_numbering plugin.</t>
</tnodes>
</leo_file>
