<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5" body_secondary_ratio="0.5">
	<global_window_position top="50" left="50" height="500" width="700"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="ekr.20180307012127.1"><vh>@settings</vh>
<v t="chris.20180306194051.1"><vh>@theme Breeze Dark</vh>
<v t="chris.20180306194034.1"><vh>Breeze Dark Color definitions</vh>
<v t="chris.20180306194034.2"><vh>@color dark-base06 = #3b0000</vh></v>
<v t="chris.20180306194034.3"><vh>@color solarized-base05 = #003b00</vh></v>
<v t="chris.20180306194034.4"><vh>@color solarized-base04 = #000059</vh></v>
<v t="chris.20180306194034.5"><vh>@color solarized-base03 = #31363b</vh></v>
<v t="chris.20180306194034.6"><vh>@color solarized-base02 = #073642</vh></v>
<v t="chris.20180306194034.7"><vh>@color solarized-base01 = #586e75</vh></v>
<v t="chris.20180306194034.8"><vh>@color dark-base00 = #657b83</vh></v>
<v t="chris.20180306194034.9"><vh>@color dark-base0 = #fcfcfc</vh></v>
<v t="chris.20180306194034.10"><vh>@color dark-base1 = #93a1a1</vh></v>
<v t="chris.20180306194034.11"><vh>@color dark-base2 = #eee8d5</vh></v>
<v t="chris.20180306194034.12"><vh>@color dark-base3 = #fdf6e3</vh></v>
</v>
<v t="chris.20180306194051.2"><vh>Settings for Leo Breeze Dark</vh>
<v t="chris.20180306194051.3"><vh>Colors: Syntax coloring</vh>
<v t="chris.20180306194051.4"><vh>Colors: defaults</vh>
<v t="chris.20180306194051.5"><vh>@color blank_color = grey</vh></v>
<v t="chris.20180306194051.6"><vh>@color tab_color = red</vh></v>
<v t="chris.20180306194051.7"><vh>@color label_color = red</vh></v>
<v t="chris.20180306194051.8"><vh>@color keyword1_color = #268bd2</vh></v>
<v t="chris.20180306194051.9"><vh>@color keyword2_color = #268bd2</vh></v>
<v t="chris.20180306194051.10"><vh>@color keyword3_color = #268bd2</vh></v>
<v t="chris.20180306194051.11"><vh>@color keyword4_color = #268bd2</vh></v>
<v t="chris.20180306194051.12"><vh>@color literal1_color = #859900</vh></v>
<v t="chris.20180306194051.13"><vh>@color literal2_color = #859900</vh></v>
<v t="chris.20180306194051.14"><vh>@color literal3_color = #859900</vh></v>
<v t="chris.20180306194051.15"><vh>@color literal4_color = #859900</vh></v>
<v t="chris.20180306194051.16"><vh>@color markup_color = #268bd2</vh></v>
<v t="chris.20180306194051.17"><vh>@color comment1_color = #d33682</vh></v>
<v t="chris.20180306194051.18"><vh>@color comment2_color = #d33682</vh></v>
<v t="chris.20180306194051.19"><vh>@color comment3_color = #d33682</vh></v>
<v t="chris.20180306194051.20"><vh>@color comment4_color = #d33682</vh></v>
</v>
<v t="chris.20180306194051.21"><vh>Colors: Leo constructs</vh>
<v t="chris.20180306194051.22"><vh>@color section_name_brackets_color = @solarized-blue</vh></v>
<v t="chris.20180306194051.23"><vh>@color null_color = #6c71c4</vh></v>
<v t="chris.20180306194051.24"><vh>@color operator_color = #6c71c4</vh></v>
<v t="chris.20180306194051.25"><vh>@color doc_part_color = @solarized-red</vh></v>
<v t="chris.20180306194051.26"><vh>@color leo_keyword_color = @solarized-green</vh></v>
<v t="chris.20180306194051.27"><vh>@color section_name_color = @solarized-red</vh></v>
<v t="chris.20180306194051.28"><vh>@color show_invisibles_space_color = #E5E5E5</vh></v>
<v t="chris.20180306194051.29"><vh>@color show_invisibles_tab_color = #CCCCCC</vh></v>
<v t="chris.20180306194051.30"><vh>@color undefined_section_name_color = red</vh></v>
<v t="chris.20180306194051.31"><vh>@color url_color = @solarized-purple</vh></v>
</v>
</v>
<v t="chris.20180306194051.32"><vh>Colors: Text</vh>
<v t="chris.20180306194051.33"><vh>@color log_text_background_color = @dark-base03</vh></v>
<v t="chris.20180306194051.34"><vh>@color log_text_foreground_color = @dark-base0</vh></v>
<v t="chris.20180306194051.35"><vh>@color text-background = @dark-base03</vh></v>
<v t="chris.20180306194051.36"><vh>@color text-background-bright = @dark-base02</vh></v>
<v t="chris.20180306194051.37"><vh>@color text-foreground = @dark-base0</vh></v>
<v t="chris.20180306194051.38"><vh>@color text-foreground-bright = @dark-base2</vh></v>
</v>
<v t="chris.20180306194051.39"><vh>Colors: Widgets</vh>
<v t="chris.20180306194051.40"><vh>@color button-hover-fg =@dark-base03</vh></v>
</v>
<v t="chris.20180306194051.41"><vh>Fonts &amp; text sizes</vh>
<v t="chris.20180306194051.42"><vh>@string font-family = Inconsolata,Droid Sans Mono, DejaVu Sans Mono</vh></v>
<v t="chris.20180306194051.43"><vh>@string font-family-body =@font-family</vh></v>
<v t="chris.20180306194051.44"><vh>@string font-family-log =@font-family</vh></v>
<v t="chris.20180306194051.45"><vh>@string font-family-tree =@font-family</vh></v>
<v t="chris.20180306194051.46"><vh>@string font-size-body = 22px</vh></v>
<v t="chris.20180306194051.47"><vh>@string font-size-log = 16px</vh></v>
<v t="chris.20180306194051.48"><vh>@string font-size-tree = 18px</vh></v>
</v>
<v t="chris.20180306194051.49"><vh>Gradients</vh>
<v t="chris.20180306194051.50"><vh>@string bg-gradient =qlineargradient( x1:0 y1:0, x2:0 y2:1, stop:0.1@text-background-bright, stop:0.4 @text-background, stop:0.6@text-background, stop:0.9 @text-background-bright)</vh></v>
<v t="chris.20180306194051.51"><vh>@string bg-gradient-hover =qlineargradient( x1:0 y1:0, x2:0 y2:1, stop:0.1 @dark-base00,stop:0.4 @dark-base0, stop:0.6 @dark-base0, stop:0.9@dark-base00)</vh></v>
</v>
<v t="chris.20180306194051.52"><vh>Plugins settings</vh>
<v t="chris.20180306194051.53"><vh>bookmarks</vh>
<v t="chris.20180306194051.54"><vh>@color bookmarks_current_color = @solarized-orange</vh></v>
<v t="chris.20180306194051.55"><vh>bookmarks base</vh>
<v t="chris.20180306194051.56"><vh>@color bookmarks_base_color = @text-foreground</vh></v>
<v t="chris.20180306194051.57"><vh>@string bookmarks_base_border = none</vh></v>
<v t="chris.20180306194051.58"><vh>@string bookmarks_base_decoration = none</vh></v>
<v t="chris.20180306194051.59"><vh>@string bookmarks_base_family = none</vh></v>
<v t="chris.20180306194051.60"><vh>@string bookmarks_base_margin = 0</vh></v>
<v t="chris.20180306194051.61"><vh>@string bookmarks_base_padding = 1</vh></v>
<v t="chris.20180306194051.62"><vh>@string bookmarks_base_size = @bookmarks_font_size</vh></v>
<v t="chris.20180306194051.63"><vh>@string bookmarks_base_style = normal</vh></v>
<v t="chris.20180306194051.64"><vh>@string bookmarks_base_weight = regular</vh></v>
</v>
<v t="chris.20180306194051.65"><vh>bookmarks children</vh>
<v t="chris.20180306194051.66"><vh>@color bookmarks_children_color = @text-foreground</vh></v>
<v t="chris.20180306194051.67"><vh>@string bookmarks_children_decoration = underline</vh></v>
<v t="chris.20180306194051.68"><vh>@string bookmarks_children_family = none</vh></v>
<v t="chris.20180306194051.69"><vh>@string bookmarks_children_size = ignore</vh></v>
<v t="chris.20180306194051.70"><vh>@string bookmarks_children_style = ignore</vh></v>
<v t="chris.20180306194051.71"><vh>@string bookmarks_children_weight = ignore</vh></v>
</v>
<v t="chris.20180306194051.72"><vh>bookmarks current</vh>
<v t="chris.20180306194051.73"><vh>@color bookmarks_current_color = blue</vh></v>
<v t="chris.20180306194051.74"><vh>@string bookmarks_current_decoration = ignore</vh></v>
<v t="chris.20180306194051.75"><vh>@string bookmarks_current_size = ignore</vh></v>
<v t="chris.20180306194051.76"><vh>@string bookmarks_current_style = ignore</vh></v>
<v t="chris.20180306194051.77"><vh>@string bookmarks_current_weight = bold</vh></v>
</v>
<v t="chris.20180306194051.78"><vh>bookmarks expanded</vh>
<v t="chris.20180306194051.79"><vh>@color bookmarks_expanded_color = @text-foreground</vh></v>
<v t="chris.20180306194051.80"><vh>@string bookmarks_expanded_decoration = underline</vh></v>
<v t="chris.20180306194051.81"><vh>@string bookmarks_expanded_size = ignore</vh></v>
<v t="chris.20180306194051.82"><vh>@string bookmarks_expanded_style = ignore</vh></v>
<v t="chris.20180306194051.83"><vh>@string bookmarks_expanded_weight = bold</vh></v>
<v t="chris.20180306194051.84"><vh>@string bookmarks_font_size = 11pt</vh></v>
</v>
</v>
</v>
<v t="chris.20180306194051.85"><vh>Outline indicators</vh>
<v t="chris.20180306194051.86"><vh>@string tree-image-closed = nodes-dark/triangles/closed.png</vh></v>
<v t="chris.20180306194051.87"><vh>@string tree-image-open = nodes-dark/triangles/open.png</vh></v>
</v>
<v t="chris.20180306194051.88"><vh>Theme description settings</vh>
<v t="chris.20180306194051.89"><vh>@bool color_theme_is_dark = True</vh></v>
<v t="chris.20180306194051.90"><vh>@string color_theme = leo_dark_0</vh></v>
</v>
</v>
<v t="chris.20180306194051.91"><vh>@data qt-gui-plugin-style-sheet</vh>
<v t="chris.20180306194051.92"><vh>Body &amp; other text</vh></v>
<v t="chris.20180306194051.93"><vh>Borders</vh></v>
<v t="chris.20180306194051.94"><vh>Buttons</vh></v>
<v t="chris.20180306194051.95"><vh>Log</vh></v>
<v t="chris.20180306194051.96"><vh>Menus</vh></v>
<v t="chris.20180306194051.97"><vh>Minibuffer &amp; label</vh></v>
<v t="chris.20180306194051.98"><vh>Plugins</vh></v>
<v t="chris.20180306194051.99"><vh>Scroll bars</vh></v>
<v t="chris.20180306194051.100"><vh>Splitters</vh></v>
<v t="chris.20180306194051.101"><vh>Status area</vh></v>
<v t="chris.20180306194051.102"><vh>Tab bar</vh></v>
<v t="chris.20180306194051.103"><vh>Tree</vh></v>
<v t="chris.20180306194051.104"><vh>Widgets: general</vh></v>
</v>
</v>
</v>
<v t="ekr.20180307012426.2"><vh>Syntax coloring test</vh>
<v t="ekr.20180307012426.3"><vh>&lt;&lt; defined section &gt;&gt;</vh></v>
</v>
<v t="ekr.20180307012426.4"><vh>Test g.es(color=*)</vh></v>
</vnodes>
<tnodes>
<t tx="chris.20180306194034.1"></t>
<t tx="chris.20180306194034.10"></t>
<t tx="chris.20180306194034.11"></t>
<t tx="chris.20180306194034.12"></t>
<t tx="chris.20180306194034.2"></t>
<t tx="chris.20180306194034.3"></t>
<t tx="chris.20180306194034.4"></t>
<t tx="chris.20180306194034.5"></t>
<t tx="chris.20180306194034.6"></t>
<t tx="chris.20180306194034.7"></t>
<t tx="chris.20180306194034.8"></t>
<t tx="chris.20180306194034.9"></t>
<t tx="chris.20180306194051.1" lineYOffset="4b002e">@language rest
@wrap
@tabwidth -2

*Important*: disable myLeoSettings.leo to test this file.

By Chris George.
Changed by EKR:
- Changed @solarized-base to @dark-base everywhere.
- Removed definitions of non-base solarized colors.
  They are in leoSettings.leo.
- Put all settings in an @settings tree.
</t>
<t tx="chris.20180306194051.10">was blue

Solarized blue      #268bd2</t>
<t tx="chris.20180306194051.100">QSplitter::handle {
  background: @dark-base01;
}

QSplitter::handle:hover {
  background: @solarized-violet;
}
</t>
<t tx="chris.20180306194051.101">/* The status area */
QLineEdit#status1 {
  background: @dark-base03;
  border-color: @dark-base02;
  border-width: 1px;
  border-style: solid;
}
QLineEdit#status2 {
  background: @dark-base03;
  border-color: @dark-base02;
  border-width: 1px;
  border-style: solid;
}
QLineEdit#status1[style_class ~= 'info'],
QLineEdit#status2[style_class ~= 'info'] {
    background: @solarized-blue;
    color:      @solarized-white;
}

QLineEdit#status1[style_class ~= 'fail'],
QLineEdit#status2[style_class ~= 'fail'] {
    background: @solarized-red;
    color:      @solarized-white;
}
</t>
<t tx="chris.20180306194051.102">QTabWidget::pane { /* The tab widget frame */
    border-top: 2px solid #31363b;
}

QTabWidget::tab-bar {
    left: 5px; /* move to the right by 5px */
}

/* Style the tab using the tab sub-control. */
QTabBar::tab {
    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,
                                stop: 0 #232629, stop: 0.4 #23262A,
                                stop: 0.5 #23262A, stop: 1.0 #232629);
    border: 4px solid #31363b;
    border-bottom-color: #31363b; /* same as the pane color */
    border-top-left-radius: 4px;
    border-top-right-radius: 4px;
    min-width: 8ex;
    padding: 2px;
}

QTabBar::tab:selected, QTabBar::tab:hover {
    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,
                                stop: 0 #23262A, stop: 0.4 #232629,
                                stop: 0.5 #232629, stop: 1.0 #23262A);
    border-bottom-color: #1a6394;
}

QTabBar::tab:selected {
    border-color: #31363b;
    border-bottom-color: @solarized-blue; /* same as pane color */
}

QTabBar::tab:!selected {
    margin-top: 2px; /* make non-selected tabs look smaller */
}</t>
<t tx="chris.20180306194051.103">LeoQTreeWidget#treeWidget {
  /* These apply to the selected item, but not to editing items.*/
  background: @dark-base03;
  color: @dark-base0;
  show-decoration-selected: 1; /* Extend the selection */
  padding: 2px solid @dark-base01;
  border-color: @dark-base03;
  font-family: @font-family-tree;
  font-size: @font-size-tree;
  font-weight: normal; /* normal,bold,100,..,900 */
  font-style: normal; /* normal, italic,oblique */
}
QTreeView::item:selected, QTreeView::item:active:selected {
  background: @dark-base01;
}
QTreeView::item:active:selected {
  background: @dark-base01;
  color: @dark-base0;
}
QTreeView::branch:closed:has-children{
    image: @tree-image-closed;
}
QTreeView::branch:open:has-children{
    image: @tree-image-open;
}

/* Headline edit widgets */
QTreeView QLineEdit {
  color: @dark-base03;
  background: @solarized-violet;
  selection-color: @solarized-violet; 
  selection-background-color: @dark-base3;
  font-family: @font-family-tree;
  font-size: @font-size-tree;
  font-weight: normal; /* normal,bold,100,..,900 */
  font-style: normal; /* normal, italic,oblique */
  padding: 0px;
}

QTreeWidget {
  /* These apply to the selected item, but not to editing items.*/
  background: @dark-base01;
  font-family: @font-family-tree;
  font-size: @font-size-tree;
  font-weight: normal; /* normal,bold,100,..,900 */
  font-style: normal; /* normal, italic,oblique */
  padding: 2px solid @dark-base03;
  border-color: @dark-base01;
}
QTreeWidget::selected {
  background: @dark-base01;
  color: @dark-base03; 
}
</t>
<t tx="chris.20180306194051.104">QDockWidget {
 border: 5px solid red;
}
QDoubleSpinBox, QSpinBox, QDateEdit, QTimeEdit {
  border: none;
  padding: 3px;
  margin-right: 5px;
}
QLabel {
  color: @dark-base01;
}
QLineEdit {
  border: none;
  padding: 3px;
}
QWidget {
  /* Not for text widgets */
  background:  @dark-base03;
  color: @dark-base0;
  border-color: @dark-base01;
  font-size: 16px;
}
</t>
<t tx="chris.20180306194051.11">was blue

Solarized blue      #268bd2</t>
<t tx="chris.20180306194051.12">was #00aa00 (Idle comment green)

Solarize green      #859900
Solarized cyan      #2aa198
Solarized violet    #6c71c4
Solarized orange    #cb4b16</t>
<t tx="chris.20180306194051.13"></t>
<t tx="chris.20180306194051.14"></t>
<t tx="chris.20180306194051.15"></t>
<t tx="chris.20180306194051.16">was black
was #2aa198</t>
<t tx="chris.20180306194051.17">was firebrick3

Solarized colors:

magenta   #d33682

Dark comments   base01
Light comments  base1 comments
</t>
<t tx="chris.20180306194051.18"></t>
<t tx="chris.20180306194051.19"></t>
<t tx="chris.20180306194051.2" lineYOffset="4b002e"></t>
<t tx="chris.20180306194051.20"></t>
<t tx="chris.20180306194051.21"></t>
<t tx="chris.20180306194051.22"># New: solarized-blue
</t>
<t tx="chris.20180306194051.23"></t>
<t tx="chris.20180306194051.24"></t>
<t tx="chris.20180306194051.25">The color of text in doc parts.

firebrick3
</t>
<t tx="chris.20180306194051.26">The color of Leo keywords such as @ignore, @color, etc.

#00aa00
</t>
<t tx="chris.20180306194051.27">The color of name in &lt; &lt; name &gt; &gt; when name is defined.

red

</t>
<t tx="chris.20180306194051.28">The background color that represents spaces when Show Invisibles mode is in effect.

gray80: #CCCCCC
gray90: #E5E5E5
</t>
<t tx="chris.20180306194051.29">The foreground color that represents tabs when Show Invisibles mode is in effect.

gray80: #CCCCCC
gray90: #E5E5E5
</t>
<t tx="chris.20180306194051.3" lineYOffset="4b002e">These settings must exist because they are *not* used in the css.</t>
<t tx="chris.20180306194051.30">The color of name in &lt;&lt; name &gt;&gt; when name is undefined.
</t>
<t tx="chris.20180306194051.31">purple
</t>
<t tx="chris.20180306194051.32">Text to test with.</t>
<t tx="chris.20180306194051.33">Background color of log text.</t>
<t tx="chris.20180306194051.34">Foreground color of log text.

</t>
<t tx="chris.20180306194051.35"></t>
<t tx="chris.20180306194051.36"></t>
<t tx="chris.20180306194051.37"></t>
<t tx="chris.20180306194051.38"></t>
<t tx="chris.20180306194051.39">Most widgets are colored in their css nodes.

Only colors appearing in several places are given here.</t>
<t tx="chris.20180306194051.4"></t>
<t tx="chris.20180306194051.40"></t>
<t tx="chris.20180306194051.41"></t>
<t tx="chris.20180306194051.42">test text</t>
<t tx="chris.20180306194051.43"></t>
<t tx="chris.20180306194051.44"></t>
<t tx="chris.20180306194051.45"></t>
<t tx="chris.20180306194051.46"></t>
<t tx="chris.20180306194051.47"></t>
<t tx="chris.20180306194051.48"></t>
<t tx="chris.20180306194051.49">Utility constants.</t>
<t tx="chris.20180306194051.5"></t>
<t tx="chris.20180306194051.50"></t>
<t tx="chris.20180306194051.51"></t>
<t tx="chris.20180306194051.52"></t>
<t tx="chris.20180306194051.53"></t>
<t tx="chris.20180306194051.54"></t>
<t tx="chris.20180306194051.55"></t>
<t tx="chris.20180306194051.56"></t>
<t tx="chris.20180306194051.57"></t>
<t tx="chris.20180306194051.58">none or underline</t>
<t tx="chris.20180306194051.59"></t>
<t tx="chris.20180306194051.6"></t>
<t tx="chris.20180306194051.60"></t>
<t tx="chris.20180306194051.61"></t>
<t tx="chris.20180306194051.62"></t>
<t tx="chris.20180306194051.63">Valid values are: normal,italic,oblique</t>
<t tx="chris.20180306194051.64">Huh?
valid values are: normal,bold,100,..,900
</t>
<t tx="chris.20180306194051.65"></t>
<t tx="chris.20180306194051.66"></t>
<t tx="chris.20180306194051.67">none or underline</t>
<t tx="chris.20180306194051.68"></t>
<t tx="chris.20180306194051.69"></t>
<t tx="chris.20180306194051.7"></t>
<t tx="chris.20180306194051.70"></t>
<t tx="chris.20180306194051.71">bold or regular</t>
<t tx="chris.20180306194051.72"></t>
<t tx="chris.20180306194051.73"></t>
<t tx="chris.20180306194051.74">none or underline</t>
<t tx="chris.20180306194051.75"></t>
<t tx="chris.20180306194051.76"></t>
<t tx="chris.20180306194051.77">bold or regular</t>
<t tx="chris.20180306194051.78"></t>
<t tx="chris.20180306194051.79"></t>
<t tx="chris.20180306194051.8">was blue

Solarized blue      #268bd2</t>
<t tx="chris.20180306194051.80">none or underline</t>
<t tx="chris.20180306194051.81"></t>
<t tx="chris.20180306194051.82"></t>
<t tx="chris.20180306194051.83">bold or regular</t>
<t tx="chris.20180306194051.84"></t>
<t tx="chris.20180306194051.85">Outline indicators indicate the expansion state of outline nodes. The leo/Icons/nodes-dark folders contains two sets of indicators::
    
    leo/Icons/nodes-dark/plusminus/
    leo/Icons/nodes-dark/triangles/
    
The following settings specify the indicators.  You can use an absolute path, or more conveniently, a path relative either to:

- Your home directory or
- Leo's leo/Icons directory
</t>
<t tx="chris.20180306194051.86">Must be relative to either the users home directory or leo/Icons directory.

url(/home/chris/leo-editor/leo/Icons/nodes-dark/triangles/closed.png)</t>
<t tx="chris.20180306194051.87">url(/home/chris/leo-editor/leo/Icons/nodes-dark/triangles/open.png)</t>
<t tx="chris.20180306194051.88"></t>
<t tx="chris.20180306194051.89" lineYOffset="4b002e">Set to true for dark themes, so bookmarks.py can generate
random background colors which are appropriate etc.</t>
<t tx="chris.20180306194051.9">was blue

Solarized blue      #268bd2</t>
<t tx="chris.20180306194051.90" lineYOffset="4b002e">Name of the theme,
used to find icon files</t>
<t tx="chris.20180306194051.91">/*
@language css
at-tabwidth -2 causes a crash in parse-template!
*/</t>
<t tx="chris.20180306194051.92">/* The body pane */
/* QTextEdit#richTextEdit, QTextBrowser#vr-body { */
/* QTextBrowser, #body-text-renderer, #viewrendered_pane */
QTextEdit#richTextEdit {
  background: @dark-base03;
  color: @dark-base0;
  font-family: @font-family-body;
  font-size: @font-size-body;
  font-weight: normal; /* normal,bold,100,..,900 */
  font-style: normal; /* normal,italic,oblique */
  padding-left: 3px;
  padding-top: 3px;
  padding-bottom: 3px;
  padding-right: 3px;
  height: 200%;
}
</t>
<t tx="chris.20180306194051.93">/* active pane highlighting */
QTextEdit#log-widget, LeoQTreeWidget#treeWidget, QTextEdit#richTextEdit {
  border-style: solid;
  border-width: 3px;
}
QTextEdit#log-widget {
  border-color: @log_text_background_color;
}
LeoQTreeWidget#treeWidget {
  border-color: @dark-base03;
}
QTextEdit#richTextEdit {
  border-color: @text-background;

}
QTextEdit:focus#log-widget,LeoQTreeWidget:focus#treeWidget, QTextEdit:focus#richTextEdit {
  border-color: @solarized-blue;
}
</t>
<t tx="chris.20180306194051.94">QPushButton {
  color: @dark-base0;
  background: @dark-base03;
  border: 2px solid #31363b;
  border-bottom-color: #31363b;
  padding: 3px;
  margin-right: 5px;
}
QPushButton:hover {
  color: @dark-base0;
  border-color: #7ed2ff;
  background: @dark-base03;
}
</t>
<t tx="chris.20180306194051.95">QTextEdit#log-widget {
  background: @solarize-base03;
  color: @solarize-base0;
  selection-color: white;
  selection-background-color: blue;
  font-family: @font-family-log;
  font-size: @font-size-log;
  font-weight: normal; /* normal,bold,100,..,900 */
  font-style: normal; /* normal, italic,oblique */
}</t>
<t tx="chris.20180306194051.96">QMenu {
  color: @text-foreground-bright
}
QMenuBar::item:selected {
  color: @dark-base0;
  background: @dark-base03;
  border: 2px solid @dark-base03;
  border-bottom-color: @solarized-blue; /* same as the pane color */
  padding: 2px;
}
QMenu::item {
  color: @dark-base0;
  background: #4a5159;
  border: 8px solid #4a5159;
}
QMenu::item:selected {
  color: @dark-base0;
  background: @dark-base01;
  border: 2px solid @dark-base01;
  border-bottom-color: #2eacff; /* same as the pane color */
  padding: 2px;
}
QMenuBar::item {
  color: @text-foreground;
  background: @dark-base03;
}
QMenuBar::item:pressed {
  color: @text-foreground-bright;
  background: @dark-base01;
}
</t>
<t tx="chris.20180306194051.97">/* The mini-buffer */
QLabel#minibufferLabel {
  color: @solarized-violet;
}
/* The minibuffer */
QLineEdit#lineEdit {
  color: @dark-base0; 
  background: @dark-base01;
  selection-color: @dark-base03; /* Yeah, it's a background color. */
  selection-background-color: @solarized-red;
  font-family: @font-family;
  font-size: 16px;
  font-weight: normal; /* normal,bold,100,..,900 */
  font-style: normal; /* normal,italic,oblique */
}
</t>
<t tx="chris.20180306194051.98">/* bookmarks plugin styling */

#show_bookmarks QPushButton {
  margin: 0; padding: 1; border: none;
  font-size: @bookmarks_base_size;
  color: @bookmarks_base_color;
  font-weight: @bookmarks_base_weight;
  text-decoration: @bookmarks_base_decoration;
}
#show_bookmarks QPushButton[style_class='bookmark_children'] {
  font-size: @bookmarks_children_size;
  color: @bookmarks_children_color;
  font-weight: @bookmarks_children_weight;
  text-decoration: @bookmarks_children_decoration;
}
#show_bookmarks QPushButton[style_class='bookmark_expanded'] {
  font-size: @bookmarks_expanded_size;
  color: @bookmarks_expanded_color;
  font-weight: @bookmarks_expanded_weight;
  text-decoration: @bookmarks_expanded_decoration;
}
#show_bookmarks QPushButton[style_class='bookmark_current'] {
  font-size: @bookmarks_current_size;
  color: @bookmarks_current_color;
  font-weight: @bookmarks_current_weight;
  text-decoration: @bookmarks_current_decoration;
}
</t>
<t tx="chris.20180306194051.99">QScrollBar::horizontal {
   height: 7px;
}
QScrollBar::vertical {
   width: 7px;
}
QScrollBar::add-page, QScrollBar::sub-page {
  background: @dark-base03;
}
QScrollBar::handle {
  background: @dark-base01;
  color: @dark-base01;
}
QScrollBar::handle:hover {
  background: @dark-base0;
  color: @dark-base0;
}
/* to make these show up, remove the ::handle style above... bug? */
QScrollBar::add-line, QScrollBar::sub-line {
  background: @dark-base01;
  color: @dark-base01;
}</t>
<t tx="ekr.20180307012127.1"></t>
<t tx="ekr.20180307012426.2">@language python

@ This should be *colored* as rST.
@c

# Details: http://leoeditor.com/

&lt;&lt; undefined section &gt;&gt;
&lt;&lt; defined section &gt;&gt;

a = 2

def spam():
    pass
</t>
<t tx="ekr.20180307012426.3">Test.</t>
<t tx="ekr.20180307012426.4">table = (
    # g.actualColor calls 
    'error', 'info', 'warning',
    'black', 'white',
    'xxx',
    'firebrick', 'grey', 'pink', 'purple', # Tk colors.
    # Solarized colors...
    'blue', 'cyan', 'green','magenta', 'orange', 'red',
    'violet', 'yellow',
)
for s in table:
    g.es(s, color=s)
</t>
</tnodes>
</leo_file>
