<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2"/>
<globals/>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="ekr.20180307015158.1"><vh>Themes</vh>
<v t="ekr.20180307015158.115"><vh>@data qt-gui-plugin-style-sheet</vh>
<v t="ekr.20180307015158.116"><vh>Body pane</vh></v>
<v t="ekr.20180307015158.117"><vh>Buttons</vh></v>
<v t="ekr.20180307015158.118"><vh>Dialogs (QLabel)</vh></v>
<v t="ekr.20180307015158.119"><vh>Find Tab</vh></v>
<v t="ekr.20180307015158.120"><vh>Gutter</vh></v>
<v t="ekr.20180307015158.121"><vh>Log panes</vh></v>
<v t="ekr.20180307015158.122"><vh>Minibuffer</vh></v>
<v t="ekr.20180307015158.123"><vh>Outline pane (change default path)</vh></v>
<v t="ekr.20180307015158.124"><vh>Plugins</vh>
<v t="ekr.20180307015158.125"><vh>Bookmarks plugin (stylesheet)</vh></v>
<v t="ekr.20180307015158.126"><vh>Screencast plugin</vh></v>
<v t="ekr.20180307015158.127"><vh>Interact plugin</vh></v>
<v t="ekr.20180307015158.128"><vh>Quickmove plugin</vh></v>
</v>
<v t="ekr.20180307015158.129"><vh>Rendering pane</vh></v>
<v t="ekr.20180307015158.130"><vh>Splitter</vh></v>
<v t="ekr.20180307015158.131"><vh>Status areas</vh></v>
<v t="ekr.20180307015158.132"><vh>Vim mode borders</vh></v>
<v t="ekr.20180307015158.133"><vh>Widgets</vh></v>
<v t="ekr.20190106114300.1"><vh>zz must be last</vh></v>
</v>
<v t="ekr.20180307015158.22"><vh>@theme base dark</vh>
<v t="ekr.20180307015158.23"><vh>settings (base dark)</vh>
<v t="ekr.20180307015158.24"><vh>style sheet settings (base dark)</vh>
<v t="ekr.20180307015158.25"><vh>border settings (base dark)</vh>
<v t="ekr.20180307015158.26"><vh>@@@color focused-border-hover-color = red</vh></v>
<v t="ekr.20180307015158.27"><vh>@color focused-border-focus-color = red</vh></v>
<v t="ekr.20180307015158.28"><vh>@string focused-border-style = solid</vh></v>
<v t="ekr.20180307015158.29"><vh>@string focused-border-unfocus-color = @solarized-base02</vh></v>
<v t="ekr.20180307015158.30"><vh>@string focused-border-width = 5px</vh></v>
</v>
<v t="ekr.20180307015158.31"><vh>color settings (base dark)</vh>
<v t="ekr.20180307015158.32"><vh>@color button-hover-bg = @solarized-base01</vh></v>
<v t="ekr.20180307015158.33"><vh>@color button-hover-fg = @solarized-base03</vh></v>
<v t="ekr.20180307015158.34"><vh>@color log_error_color = #dc322f</vh></v>
<v t="ekr.20180307015158.35"><vh>@color log_text_background_color = #073642</vh></v>
<v t="ekr.20180307015158.36"><vh>@color log_text_foreground_color = #93a1a1</vh></v>
<v t="ekr.20180307015158.37"><vh>@color log_warning_color = #268bd2</vh></v>
<v t="ekr.20180307015158.38"><vh>@color minibuffer_background_color = @solarized-base03</vh></v>
<v t="ekr.20180307015158.39"><vh>@color minibuffer_error_color = @solarized-red</vh></v>
<v t="ekr.20180307015158.40"><vh>@color minibuffer_foreground_color = @solarized-yellow</vh></v>
<v t="ekr.20180307015158.41"><vh>@color minibuffer_warning_color = @solarized-base02</vh></v>
<v t="ekr.20180307015158.42"><vh>@color splitter-bg = @solarized-base01</vh></v>
<v t="ekr.20180307015158.43"><vh>@color splitter-hover-bg = @solarized-violet</vh></v>
<v t="ekr.20180307015158.44"><vh>@color text-background = @solarized-base03</vh></v>
<v t="ekr.20180307015158.45"><vh>@color text-background-bright = @solarized-base02</vh></v>
<v t="ekr.20180307015158.46"><vh>@color text-foreground = @solarized-base0</vh></v>
<v t="ekr.20180307015158.47"><vh>@color text-foreground-bright = @solarized-base2</vh></v>
</v>
<v t="ekr.20180307015158.48"><vh>font settings (base dark)</vh>
<v t="ekr.20180307015158.49"><vh>@string font-family = DejaVu Sans Mono</vh></v>
<v t="ekr.20180307015158.50"><vh>@string font-family = DejaVu Sans Mono</vh></v>
<v t="ekr.20180307015158.51"><vh>@string font-family-tree = @font-family</vh></v>
<v t="ekr.20180307015158.52"><vh>@string font-family-body = @font-family</vh></v>
<v t="ekr.20180307015158.53"><vh>@string font-family-log = @font-family</vh></v>
<v t="ekr.20180307015158.54"><vh>@string font-size = 12pt</vh></v>
<v t="ekr.20180307015158.55"><vh>@string font-size-body = 12pt</vh></v>
<v t="ekr.20180307015158.56"><vh>@string font-size-tree = 12pt</vh></v>
<v t="ekr.20180307015158.57"><vh>@string font-size-log = 12pt</vh></v>
</v>
<v t="ekr.20180307015158.58"><vh>gradients (base dark)</vh>
<v t="ekr.20180307015158.59"><vh>@string bg-gradient = qlineargradient( x1:0 y1:0, x2:0 y2:1, stop:0.1 @text-background-bright, stop:0.4 @text-background, stop:0.6 @text-background, stop:0.9 @text-background-bright)</vh></v>
<v t="ekr.20180307015158.60"><vh>@string bg-gradient-hover = qlineargradient( x1:0 y1:0, x2:0 y2:1, stop:0.1 @solarized-base00, stop:0.4 @solarized-base0, stop:0.6 @solarized-base0, stop:0.9 @solarized-base00)</vh></v>
</v>
<v t="ekr.20180307015158.61"><vh>outline indicators (base dark)</vh>
<v t="ekr.20180307015158.62"><vh>@string tree-image-closed = nodes-dark/triangles/closed.png</vh></v>
<v t="ekr.20180307015158.63"><vh>@string tree-image-open = nodes-dark/triangles/open.png</vh></v>
</v>
<v t="ekr.20180307015158.64"><vh>plugins settings (base dark)</vh>
<v t="ekr.20180307015158.65"><vh>bookmark settings (base dark)</vh>
<v t="ekr.20180307015158.66"><vh>@color bookmarks_current_color = @solarized-orange</vh></v>
</v>
</v>
</v>
<v t="ekr.20180307015158.552"><vh>syntax coloring settings (common to all themes)</vh>
<v t="ekr.20180307015158.553"><vh>Colors for Leo constructs (all themes)</vh>
<v t="ekr.20180307015158.554"><vh>@color doc_part_color = #d33682</vh></v>
<v t="ekr.20180307015158.555"><vh>@color leo_keyword_color = #268bd2</vh></v>
<v t="ekr.20180307015158.556"><vh>@color section_name_brackets_color = #268bd2</vh></v>
<v t="ekr.20180307015158.557"><vh>@color section_name_color = #d33682</vh></v>
<v t="ekr.20180307015158.558"><vh>@color show_invisibles_space_color = #d33682</vh></v>
<v t="ekr.20180307015158.559"><vh>@color show_invisibles_tab_color = red</vh></v>
<v t="ekr.20180307015158.560"><vh>@color undefined_section_name_color = #d33682</vh></v>
<v t="ekr.20180307015158.561"><vh>@color url_color = #6c71c4</vh></v>
</v>
<v t="ekr.20180307015158.562"><vh>Colors for jEdit constructs (all themes)</vh>
<v t="ekr.20180307015158.563"><vh>@color blank_color = #d33682</vh></v>
<v t="ekr.20180307015158.564"><vh>@color comment1_color = #d33682</vh></v>
<v t="ekr.20180307015158.565"><vh>@color comment2_color = #d33682</vh></v>
<v t="ekr.20180307015158.566"><vh>@color comment3_color = #d33682</vh></v>
<v t="ekr.20180307015158.567"><vh>@color comment4_color = #d33682</vh></v>
<v t="ekr.20180307015158.568"><vh>@color keyword1_color = #268bd2</vh></v>
<v t="ekr.20180307015158.569"><vh>@color keyword2_color = #268bd2</vh></v>
<v t="ekr.20180307015158.570"><vh>@color keyword3_color = #268bd2</vh></v>
<v t="ekr.20180307015158.571"><vh>@color keyword4_color = #268bd2</vh></v>
<v t="ekr.20180307015158.572"><vh>@color literal1_color = #2aa198</vh></v>
<v t="ekr.20180307015158.573"><vh>@color literal2_color = #2aa198</vh></v>
<v t="ekr.20180307015158.574"><vh>@color literal3_color = #2aa198</vh></v>
<v t="ekr.20180307015158.575"><vh>@color literal4_color = #2aa198</vh></v>
<v t="ekr.20180307015158.576"><vh>@color markup_color = #eee8d5</vh></v>
<v t="ekr.20180307015158.577"><vh>@color operator_color = #eee8d5</vh></v>
<v t="ekr.20180307015158.578"><vh>@color plain null color = None</vh></v>
<v t="ekr.20180307015158.579"><vh>@color tab_color = red</vh></v>
</v>
</v>
<v t="ekr.20180307015158.95"><vh>theme settings (base dark)</vh>
<v t="ekr.20180307015158.96"><vh>@string color_theme = base_dark</vh></v>
<v t="ekr.20180307015158.97"><vh>@bool color_theme_is_dark = True</vh></v>
</v>
</v>
<v t="ekr.20180307015158.98"><vh>@data qt-gui-plugin-style-sheet</vh>
<v t="ekr.20180307015158.99"><vh>style-sheet (base dark)</vh>
<v t="ekr.20180307015158.100"><vh>active pane highlighting (base dark)</vh></v>
<v t="ekr.20180307015158.101"><vh>body editor (base dark)</vh></v>
<v t="ekr.20180307015158.102"><vh>bookmarks (base dark)</vh></v>
<v t="ekr.20180307015158.103"><vh>buttons (base dark)</vh></v>
<v t="ekr.20180307015158.104"><vh>log pane (base dark)</vh></v>
<v t="ekr.20180307015158.105"><vh>menus (base dark)</vh></v>
<v t="ekr.20180307015158.106"><vh>mini-buffer (base dark)</vh></v>
<v t="ekr.20180307015158.107"><vh>status line (base dark)</vh></v>
<v t="ekr.20180307015158.108"><vh>scrollbar (base dark)</vh></v>
<v t="ekr.20180307015158.109"><vh>splitters (base dark)</vh></v>
<v t="ekr.20180307015158.110"><vh>tab bar (base dark)</vh></v>
<v t="ekr.20180307015158.111"><vh>tree (base dark) </vh></v>
<v t="ekr.20180307015158.112"><vh>widgets (base dark)</vh></v>
</v>
</v>
</v>
<v t="ekr.20180307015158.113"><vh>@theme windows ekr light</vh>
<v t="ekr.20180307015158.114"><vh>@string focused-border-unfocus-color = @solarized-base2</vh></v>
<v t="ekr.20180307015158.115"></v>
<v t="ekr.20180307015158.134"><vh>@data qt-gui-user-style-sheet</vh></v>
</v>
<v t="ekr.20180307015158.135"><vh>@theme windows ekr dark</vh>
<v t="ekr.20180307015158.136"><vh>settings</vh>
<v t="ekr.20180307015158.137"><vh>style sheet settings (base dark)</vh>
<v t="ekr.20180307015158.138"><vh>border settings (base dark)</vh>
<v t="ekr.20180307015158.139"><vh>@@@color focused-border-hover-color = red</vh></v>
<v t="ekr.20180307015158.140"><vh>@color focused-border-focus-color = red</vh></v>
<v t="ekr.20180307015158.141"><vh>@string focused-border-style = solid</vh></v>
<v t="ekr.20180307015158.142"><vh>@string focused-border-unfocus-color = @solarized-base02</vh></v>
<v t="ekr.20180307015158.143"><vh>@string focused-border-width = 5px</vh></v>
</v>
<v t="ekr.20180307015158.144"><vh>color settings (base dark)</vh>
<v t="ekr.20180307015158.145"><vh>@color button-hover-bg = @solarized-base01</vh></v>
<v t="ekr.20180307015158.146"><vh>@color button-hover-fg = @solarized-base03</vh></v>
<v t="ekr.20180307015158.147"><vh>@color log_error_color = #dc322f</vh></v>
<v t="ekr.20180307015158.148"><vh>@color log_text_background_color = #073642</vh></v>
<v t="ekr.20180307015158.149"><vh>@color log_text_foreground_color = #93a1a1</vh></v>
<v t="ekr.20180307015158.150"><vh>@color log_warning_color = #268bd2</vh></v>
<v t="ekr.20180307015158.151"><vh>@color minibuffer_background_color = @solarized-base03</vh></v>
<v t="ekr.20180307015158.152"><vh>@color minibuffer_error_color = @solarized-red</vh></v>
<v t="ekr.20180307015158.153"><vh>@color minibuffer_foreground_color = @solarized-yellow</vh></v>
<v t="ekr.20180307015158.154"><vh>@color minibuffer_warning_color = @solarized-base02</vh></v>
<v t="ekr.20180307015158.155"><vh>@color splitter-bg = @solarized-base01</vh></v>
<v t="ekr.20180307015158.156"><vh>@color splitter-hover-bg = @solarized-violet</vh></v>
<v t="ekr.20180307015158.157"><vh>@color text-background = @solarized-base03</vh></v>
<v t="ekr.20180307015158.158"><vh>@color text-background-bright = @solarized-base02</vh></v>
<v t="ekr.20180307015158.159"><vh>@color text-foreground = @solarized-base0</vh></v>
<v t="ekr.20180307015158.160"><vh>@color text-foreground-bright = @solarized-base2</vh></v>
</v>
<v t="ekr.20180307015158.161"><vh>font settings (base dark)</vh>
<v t="ekr.20180307015158.162"><vh>@string font-family = DejaVu Sans Mono</vh></v>
<v t="ekr.20180307015158.163"><vh>@string font-family = DejaVu Sans Mono</vh></v>
<v t="ekr.20180307015158.164"><vh>@string font-family-tree = @font-family</vh></v>
<v t="ekr.20180307015158.165"><vh>@string font-family-body = @font-family</vh></v>
<v t="ekr.20180307015158.166"><vh>@string font-family-log = @font-family</vh></v>
<v t="ekr.20180307015158.167"><vh>@string font-size = 12pt</vh></v>
<v t="ekr.20180307015158.168"><vh>@string font-size-body = 12pt</vh></v>
<v t="ekr.20180307015158.169"><vh>@string font-size-tree = 12pt</vh></v>
<v t="ekr.20180307015158.170"><vh>@string font-size-log = 12pt</vh></v>
</v>
<v t="ekr.20180307015158.171"><vh>gradients (base dark)</vh>
<v t="ekr.20180307015158.172"><vh>@string bg-gradient = qlineargradient( x1:0 y1:0, x2:0 y2:1, stop:0.1 @text-background-bright, stop:0.4 @text-background, stop:0.6 @text-background, stop:0.9 @text-background-bright)</vh></v>
<v t="ekr.20180307015158.173"><vh>@string bg-gradient-hover = qlineargradient( x1:0 y1:0, x2:0 y2:1, stop:0.1 @solarized-base00, stop:0.4 @solarized-base0, stop:0.6 @solarized-base0, stop:0.9 @solarized-base00)</vh></v>
</v>
<v t="ekr.20180307015158.174"><vh>outline indicators (base dark)</vh>
<v t="ekr.20180307015158.175"><vh>@string tree-image-closed = nodes-dark/triangles/closed.png</vh></v>
<v t="ekr.20180307015158.176"><vh>@string tree-image-open = nodes-dark/triangles/open.png</vh></v>
</v>
<v t="ekr.20180307015158.177"><vh>plugins settings (base dark)</vh>
<v t="ekr.20180307015158.178"><vh>bookmark settings (base dark)</vh>
<v t="ekr.20180307015158.179"><vh>@color bookmarks_current_color = @solarized-orange</vh></v>
</v>
</v>
</v>
<v t="ekr.20180307015158.180"><vh>syntax coloring settings (common to all themes)</vh>
<v t="ekr.20180307015158.181"><vh>Colors for Leo constructs (all themes)</vh>
<v t="ekr.20180307015158.182"><vh>@color doc_part_color = #d33682</vh></v>
<v t="ekr.20180307015158.183"><vh>@color leo_keyword_color = #268bd2</vh></v>
<v t="ekr.20180307015158.184"><vh>@color section_name_brackets_color = #268bd2</vh></v>
<v t="ekr.20180307015158.185"><vh>@color section_name_color = #d33682</vh></v>
<v t="ekr.20180307015158.186"><vh>@color show_invisibles_space_color = #d33682</vh></v>
<v t="ekr.20180307015158.187"><vh>@color show_invisibles_tab_color = red</vh></v>
<v t="ekr.20180307015158.188"><vh>@color undefined_section_name_color = #d33682</vh></v>
<v t="ekr.20180307015158.189"><vh>@color url_color = #6c71c4</vh></v>
</v>
<v t="ekr.20180307015158.190"><vh>Colors for jEdit constructs (all themes)</vh>
<v t="ekr.20180307015158.191"><vh>@color blank_color = #d33682</vh></v>
<v t="ekr.20180307015158.192"><vh>@color comment1_color = #d33682</vh></v>
<v t="ekr.20180307015158.193"><vh>@color comment2_color = #d33682</vh></v>
<v t="ekr.20180307015158.194"><vh>@color comment3_color = #d33682</vh></v>
<v t="ekr.20180307015158.195"><vh>@color comment4_color = #d33682</vh></v>
<v t="ekr.20180307015158.196"><vh>@color keyword1_color = #268bd2</vh></v>
<v t="ekr.20180307015158.197"><vh>@color keyword2_color = #268bd2</vh></v>
<v t="ekr.20180307015158.198"><vh>@color keyword3_color = #268bd2</vh></v>
<v t="ekr.20180307015158.199"><vh>@color keyword4_color = #268bd2</vh></v>
<v t="ekr.20180307015158.200"><vh>@color literal1_color = #2aa198</vh></v>
<v t="ekr.20180307015158.201"><vh>@color literal2_color = #2aa198</vh></v>
<v t="ekr.20180307015158.202"><vh>@color literal3_color = #2aa198</vh></v>
<v t="ekr.20180307015158.203"><vh>@color literal4_color = #2aa198</vh></v>
<v t="ekr.20180307015158.204"><vh>@color markup_color = #eee8d5</vh></v>
<v t="ekr.20180307015158.205"><vh>@color operator_color = #eee8d5</vh></v>
<v t="ekr.20180307015158.206"><vh>@color plain null color = None</vh></v>
<v t="ekr.20180307015158.207"><vh>@color tab_color = red</vh></v>
</v>
</v>
<v t="ekr.20180307015158.208"><vh>zz settings overrides (ekr dark)</vh>
<v t="ekr.20180307015158.209"><vh>@string focused-border-width = 5px</vh></v>
<v t="ekr.20180307015158.210"><vh>@string font-size = 16pt</vh></v>
<v t="ekr.20180307015158.211"><vh>@string font-size-body = 16pt</vh></v>
<v t="ekr.20180307015158.212"><vh>@string font-size-tree = 16pt</vh></v>
<v t="ekr.20180307015158.213"><vh>@string font-size-log = 16pt</vh></v>
</v>
<v t="ekr.20180307015158.214"><vh>theme settings</vh>
<v t="ekr.20180307015158.215"><vh>@string color_theme = leo_dark_0</vh></v>
<v t="ekr.20180307015158.216"><vh>@bool color_theme_is_dark = True</vh></v>
</v>
</v>
<v t="ekr.20180307015158.217"><vh>@data qt-gui-plugin-style-sheet</vh>
<v t="ekr.20180307015158.218"><vh>style-sheet (base dark)</vh>
<v t="ekr.20180307015158.219"><vh>active pane highlighting (base dark)</vh></v>
<v t="ekr.20180307015158.220"><vh>body editor (base dark)</vh></v>
<v t="ekr.20180307015158.221"><vh>bookmarks (base dark)</vh></v>
<v t="ekr.20180307015158.222"><vh>buttons (base dark)</vh></v>
<v t="ekr.20180307015158.223"><vh>log pane (base dark)</vh></v>
<v t="ekr.20180307015158.224"><vh>menus (base dark)</vh></v>
<v t="ekr.20180307015158.225"><vh>mini-buffer (base dark)</vh></v>
<v t="ekr.20180307015158.226"><vh>status line (base dark)</vh></v>
<v t="ekr.20180307015158.227"><vh>scrollbar (base dark)</vh></v>
<v t="ekr.20180307015158.228"><vh>splitters (base dark)</vh></v>
<v t="ekr.20180307015158.229"><vh>tab bar (base dark)</vh></v>
<v t="ekr.20180307015158.230"><vh>tree (base dark) </vh></v>
<v t="ekr.20180307015158.231"><vh>widgets (base dark)</vh></v>
</v>
<v t="ekr.20180307015158.232"><vh>zz overrides</vh></v>
</v>
</v>
<v t="ekr.20180307015158.233"><vh>@theme linux ekr dark</vh>
<v t="ekr.20180307015158.234"><vh>settings</vh>
<v t="ekr.20180307015158.235"><vh>style sheet settings (base dark)</vh>
<v t="ekr.20180307015158.236"><vh>border settings (base dark)</vh>
<v t="ekr.20180307015158.237"><vh>@@@color focused-border-hover-color = red</vh></v>
<v t="ekr.20180307015158.238"><vh>@color focused-border-focus-color = red</vh></v>
<v t="ekr.20180307015158.239"><vh>@string focused-border-style = solid</vh></v>
<v t="ekr.20180307015158.240"><vh>@string focused-border-unfocus-color = @solarized-base02</vh></v>
<v t="ekr.20180307015158.241"><vh>@string focused-border-width = 5px</vh></v>
</v>
<v t="ekr.20180307015158.242"><vh>color settings (base dark)</vh>
<v t="ekr.20180307015158.243"><vh>@color button-hover-bg = @solarized-base01</vh></v>
<v t="ekr.20180307015158.244"><vh>@color button-hover-fg = @solarized-base03</vh></v>
<v t="ekr.20180307015158.245"><vh>@color log_error_color = #dc322f</vh></v>
<v t="ekr.20180307015158.246"><vh>@color log_text_background_color = #073642</vh></v>
<v t="ekr.20180307015158.247"><vh>@color log_text_foreground_color = #93a1a1</vh></v>
<v t="ekr.20180307015158.248"><vh>@color log_warning_color = #268bd2</vh></v>
<v t="ekr.20180307015158.249"><vh>@color minibuffer_background_color = @solarized-base03</vh></v>
<v t="ekr.20180307015158.250"><vh>@color minibuffer_error_color = @solarized-red</vh></v>
<v t="ekr.20180307015158.251"><vh>@color minibuffer_foreground_color = @solarized-yellow</vh></v>
<v t="ekr.20180307015158.252"><vh>@color minibuffer_warning_color = @solarized-base02</vh></v>
<v t="ekr.20180307015158.253"><vh>@color splitter-bg = @solarized-base01</vh></v>
<v t="ekr.20180307015158.254"><vh>@color splitter-hover-bg = @solarized-violet</vh></v>
<v t="ekr.20180307015158.255"><vh>@color text-background = @solarized-base03</vh></v>
<v t="ekr.20180307015158.256"><vh>@color text-background-bright = @solarized-base02</vh></v>
<v t="ekr.20180307015158.257"><vh>@color text-foreground = @solarized-base0</vh></v>
<v t="ekr.20180307015158.258"><vh>@color text-foreground-bright = @solarized-base2</vh></v>
</v>
<v t="ekr.20180307015158.259"><vh>font settings (base dark)</vh>
<v t="ekr.20180307015158.260"><vh>@string font-family = DejaVu Sans Mono</vh></v>
<v t="ekr.20180307015158.261"><vh>@string font-family = DejaVu Sans Mono</vh></v>
<v t="ekr.20180307015158.262"><vh>@string font-family-tree = @font-family</vh></v>
<v t="ekr.20180307015158.263"><vh>@string font-family-body = @font-family</vh></v>
<v t="ekr.20180307015158.264"><vh>@string font-family-log = @font-family</vh></v>
<v t="ekr.20180307015158.265"><vh>@string font-size = 12pt</vh></v>
<v t="ekr.20180307015158.266"><vh>@string font-size-body = 12pt</vh></v>
<v t="ekr.20180307015158.267"><vh>@string font-size-tree = 12pt</vh></v>
<v t="ekr.20180307015158.268"><vh>@string font-size-log = 12pt</vh></v>
</v>
<v t="ekr.20180307015158.269"><vh>gradients (base dark)</vh>
<v t="ekr.20180307015158.270"><vh>@string bg-gradient = qlineargradient( x1:0 y1:0, x2:0 y2:1, stop:0.1 @text-background-bright, stop:0.4 @text-background, stop:0.6 @text-background, stop:0.9 @text-background-bright)</vh></v>
<v t="ekr.20180307015158.271"><vh>@string bg-gradient-hover = qlineargradient( x1:0 y1:0, x2:0 y2:1, stop:0.1 @solarized-base00, stop:0.4 @solarized-base0, stop:0.6 @solarized-base0, stop:0.9 @solarized-base00)</vh></v>
</v>
<v t="ekr.20180307015158.272"><vh>outline indicators (base dark)</vh>
<v t="ekr.20180307015158.273"><vh>@string tree-image-closed = nodes-dark/triangles/closed.png</vh></v>
<v t="ekr.20180307015158.274"><vh>@string tree-image-open = nodes-dark/triangles/open.png</vh></v>
</v>
<v t="ekr.20180307015158.275"><vh>plugins settings (base dark)</vh>
<v t="ekr.20180307015158.276"><vh>bookmark settings (base dark)</vh>
<v t="ekr.20180307015158.277"><vh>@color bookmarks_current_color = @solarized-orange</vh></v>
</v>
</v>
</v>
<v t="ekr.20180307015158.278"><vh>syntax coloring settings (common to all themes)</vh>
<v t="ekr.20180307015158.279"><vh>Colors for Leo constructs (all themes)</vh>
<v t="ekr.20180307015158.280"><vh>@color doc_part_color = #d33682</vh></v>
<v t="ekr.20180307015158.281"><vh>@color leo_keyword_color = #268bd2</vh></v>
<v t="ekr.20180307015158.282"><vh>@color section_name_brackets_color = #268bd2</vh></v>
<v t="ekr.20180307015158.283"><vh>@color section_name_color = #d33682</vh></v>
<v t="ekr.20180307015158.284"><vh>@color show_invisibles_space_color = #d33682</vh></v>
<v t="ekr.20180307015158.285"><vh>@color show_invisibles_tab_color = red</vh></v>
<v t="ekr.20180307015158.286"><vh>@color undefined_section_name_color = #d33682</vh></v>
<v t="ekr.20180307015158.287"><vh>@color url_color = #6c71c4</vh></v>
</v>
<v t="ekr.20180307015158.288"><vh>Colors for jEdit constructs (all themes)</vh>
<v t="ekr.20180307015158.289"><vh>@color blank_color = #d33682</vh></v>
<v t="ekr.20180307015158.290"><vh>@color comment1_color = #d33682</vh></v>
<v t="ekr.20180307015158.291"><vh>@color comment2_color = #d33682</vh></v>
<v t="ekr.20180307015158.292"><vh>@color comment3_color = #d33682</vh></v>
<v t="ekr.20180307015158.293"><vh>@color comment4_color = #d33682</vh></v>
<v t="ekr.20180307015158.294"><vh>@color keyword1_color = #268bd2</vh></v>
<v t="ekr.20180307015158.295"><vh>@color keyword2_color = #268bd2</vh></v>
<v t="ekr.20180307015158.296"><vh>@color keyword3_color = #268bd2</vh></v>
<v t="ekr.20180307015158.297"><vh>@color keyword4_color = #268bd2</vh></v>
<v t="ekr.20180307015158.298"><vh>@color literal1_color = #2aa198</vh></v>
<v t="ekr.20180307015158.299"><vh>@color literal2_color = #2aa198</vh></v>
<v t="ekr.20180307015158.300"><vh>@color literal3_color = #2aa198</vh></v>
<v t="ekr.20180307015158.301"><vh>@color literal4_color = #2aa198</vh></v>
<v t="ekr.20180307015158.302"><vh>@color markup_color = #eee8d5</vh></v>
<v t="ekr.20180307015158.303"><vh>@color operator_color = #eee8d5</vh></v>
<v t="ekr.20180307015158.304"><vh>@color plain null color = None</vh></v>
<v t="ekr.20180307015158.305"><vh>@color tab_color = red</vh></v>
</v>
</v>
<v t="ekr.20180307015158.306"><vh>zz settings overrides (windows ekr dark)</vh>
<v t="ekr.20180307015158.307"><vh>@string focused-border-width = 5px</vh></v>
<v t="ekr.20180307015158.308"><vh>@string font-size = 14pt</vh></v>
<v t="ekr.20180307015158.309"><vh>@string font-size-body = 14pt</vh></v>
<v t="ekr.20180307015158.310"><vh>@string font-size-tree = 14pt</vh></v>
<v t="ekr.20180307015158.311"><vh>@string font-size-log = 14pt</vh></v>
</v>
<v t="ekr.20180307015158.312"><vh>theme settings</vh>
<v t="ekr.20180307015158.313"><vh>@string color_theme = leo_dark_0</vh></v>
<v t="ekr.20180307015158.314"><vh>@bool color_theme_is_dark = True</vh></v>
</v>
</v>
<v t="ekr.20180307015158.315"><vh>@data qt-gui-plugin-style-sheet</vh>
<v t="ekr.20180307015158.316"><vh>style-sheet (base dark)</vh>
<v t="ekr.20180307015158.317"><vh>active pane highlighting (base dark)</vh></v>
<v t="ekr.20180307015158.318"><vh>body editor (base dark)</vh></v>
<v t="ekr.20180307015158.319"><vh>bookmarks (base dark)</vh></v>
<v t="ekr.20180307015158.320"><vh>buttons (base dark)</vh></v>
<v t="ekr.20180307015158.321"><vh>log pane (base dark)</vh></v>
<v t="ekr.20180307015158.322"><vh>menus (base dark)</vh></v>
<v t="ekr.20180307015158.323"><vh>mini-buffer (base dark)</vh></v>
<v t="ekr.20180307015158.324"><vh>status line (base dark)</vh></v>
<v t="ekr.20180307015158.325"><vh>scrollbar (base dark)</vh></v>
<v t="ekr.20180307015158.326"><vh>splitters (base dark)</vh></v>
<v t="ekr.20180307015158.327"><vh>tab bar (base dark)</vh></v>
<v t="ekr.20180307015158.328"><vh>tree (base dark) </vh></v>
<v t="ekr.20180307015158.329"><vh>widgets (base dark)</vh></v>
</v>
<v t="ekr.20180307015158.330"><vh>zz overrides (linux ekr dark)</vh></v>
</v>
</v>
<v t="ekr.20180307015158.331"><vh>Monolithic themes</vh>
<v t="ekr.20180307015158.332"><vh>@theme leo_dark theme 0</vh>
<v t="ekr.20180307015158.333"><vh>settings</vh>
<v t="ekr.20180307015158.334"><vh>style sheet settings</vh>
<v t="ekr.20180307015158.335"><vh>@ignore border</vh>
<v t="ekr.20180307015158.336"><vh>@string focused-border-style = solid</vh></v>
<v t="ekr.20180307015158.337"><vh>@string focused-border-width = 3px</vh></v>
<v t="ekr.20180307015158.338"><vh>@color focused-border-focus-color = red</vh></v>
<v t="ekr.20180307015158.339"><vh>@color focused-border-hover-color = red</vh></v>
<v t="ekr.20180307015158.340"><vh>@string focused-border-unfocus-color = white</vh></v>
</v>
<v t="ekr.20180307015158.341"><vh>colors</vh>
<v t="ekr.20180307015158.342"><vh>@color button-hover-bg = @solarized-base01</vh></v>
<v t="ekr.20180307015158.343"><vh>@color button-hover-fg = @solarized-base03</vh></v>
<v t="ekr.20180307015158.344"><vh>@color log_error_color = #dc322f</vh></v>
<v t="ekr.20180307015158.345"><vh>@color log_text_background_color = #073642</vh></v>
<v t="ekr.20180307015158.346"><vh>@color log_text_foreground_color = #93a1a1</vh></v>
<v t="ekr.20180307015158.347"><vh>@color log_warning_color = #268bd2</vh></v>
<v t="ekr.20180307015158.348"><vh>@color minibuffer_background_color = @solarized-base03</vh></v>
<v t="ekr.20180307015158.349"><vh>@color minibuffer_error_color = @solarized-red</vh></v>
<v t="ekr.20180307015158.350"><vh>@color minibuffer_foreground_color = @solarized-yellow</vh></v>
<v t="ekr.20180307015158.351"><vh>@color minibuffer_warning_color = @solarized-base02</vh></v>
<v t="ekr.20180307015158.352"><vh>@color splitter-bg = @solarized-base01</vh></v>
<v t="ekr.20180307015158.353"><vh>@color splitter-hover-bg = @solarized-violet</vh></v>
<v t="ekr.20180307015158.354"><vh>@color text-background = @solarized-base03</vh></v>
<v t="ekr.20180307015158.355"><vh>@color text-background-bright = @solarized-base02</vh></v>
<v t="ekr.20180307015158.356"><vh>@color text-foreground = @solarized-base0</vh></v>
<v t="ekr.20180307015158.357"><vh>@color text-foreground-bright = @solarized-base2</vh></v>
</v>
<v t="ekr.20180307015158.358"><vh>fonts</vh>
<v t="ekr.20180307015158.359"><vh>@string font-family = DejaVu Sans Mono</vh></v>
<v t="ekr.20180307015158.360"><vh>@string font-family = DejaVu Sans Mono</vh></v>
<v t="ekr.20180307015158.361"><vh>@string font-family-tree = @font-family</vh></v>
<v t="ekr.20180307015158.362"><vh>@string font-family-body = @font-family</vh></v>
<v t="ekr.20180307015158.363"><vh>@string font-family-log = @font-family</vh></v>
<v t="ekr.20180307015158.364"><vh>@string font-size-body = 16pt</vh></v>
<v t="ekr.20180307015158.365"><vh>@string font-size-tree = 16pt</vh></v>
<v t="ekr.20180307015158.366"><vh>@string font-size-log = 16pt</vh></v>
</v>
<v t="ekr.20180307015158.367"><vh>gradients</vh>
<v t="ekr.20180307015158.368"><vh>@string bg-gradient = qlineargradient( x1:0 y1:0, x2:0 y2:1, stop:0.1 @text-background-bright, stop:0.4 @text-background, stop:0.6 @text-background, stop:0.9 @text-background-bright)</vh></v>
<v t="ekr.20180307015158.369"><vh>@string bg-gradient-hover = qlineargradient( x1:0 y1:0, x2:0 y2:1, stop:0.1 @solarized-base00, stop:0.4 @solarized-base0, stop:0.6 @solarized-base0, stop:0.9 @solarized-base00)</vh></v>
</v>
<v t="ekr.20180307015158.370"><vh>outline indicators</vh>
<v t="ekr.20180307015158.371"><vh>@string tree-image-closed = nodes-dark/triangles/closed.png</vh></v>
<v t="ekr.20180307015158.372"><vh>@string tree-image-open = nodes-dark/triangles/open.png</vh></v>
</v>
<v t="ekr.20180307015158.373"><vh>plugins</vh>
<v t="ekr.20180307015158.374"><vh>bookmarks</vh>
<v t="ekr.20180307015158.375"><vh>@color bookmarks_current_color = @solarized-orange</vh></v>
</v>
</v>
</v>
<v t="ekr.20180307015158.552"></v>
<v t="ekr.20180307015158.404"><vh>theme settings</vh>
<v t="ekr.20180307015158.405"><vh>@string color_theme = leo_dark_0</vh></v>
<v t="ekr.20180307015158.406"><vh>@bool color_theme_is_dark = True</vh></v>
</v>
</v>
<v t="ekr.20180307015158.407"><vh>@data qt-gui-plugin-style-sheet</vh>
<v t="ekr.20180307015158.408"><vh>active pane highlighting</vh></v>
<v t="ekr.20180307015158.409"><vh>body editor</vh></v>
<v t="ekr.20180307015158.410"><vh>bookmarks</vh></v>
<v t="ekr.20180307015158.411"><vh>buttons</vh></v>
<v t="ekr.20180307015158.412"><vh>log pane</vh></v>
<v t="ekr.20180307015158.413"><vh>menus</vh></v>
<v t="ekr.20180307015158.414"><vh>mini-buffer</vh></v>
<v t="ekr.20180307015158.415"><vh>status line</vh></v>
<v t="ekr.20180307015158.416"><vh>scrollbar</vh></v>
<v t="ekr.20180307015158.417"><vh>splitters</vh></v>
<v t="ekr.20180307015158.418"><vh>tab bar</vh></v>
<v t="ekr.20180307015158.419"><vh>tree</vh></v>
<v t="ekr.20180307015158.420"><vh>widgets</vh></v>
</v>
</v>
<v t="ekr.20180307015158.421"><vh>@theme leo_dark theme 1</vh>
<v t="ekr.20180307015158.422"><vh>settings</vh>
<v t="ekr.20180307015158.423"><vh>style sheet settings</vh>
<v t="ekr.20180307015158.424"><vh>@ignore border</vh>
<v t="ekr.20180307015158.425"><vh>@string focused-border-style = solid</vh></v>
<v t="ekr.20180307015158.426"><vh>@string focused-border-width = 3px</vh></v>
<v t="ekr.20180307015158.427"><vh>@color focused-border-focus-color = red</vh></v>
<v t="ekr.20180307015158.428"><vh>@color focused-border-hover-color = red</vh></v>
<v t="ekr.20180307015158.429"><vh>@string focused-border-unfocus-color = white</vh></v>
</v>
<v t="ekr.20180307015158.430"><vh>colors</vh>
<v t="ekr.20180307015158.431"><vh>Body pane colors</vh>
<v t="ekr.20180307015158.432"><vh>@color body_text_background_color = #002b36</vh></v>
<v t="ekr.20180307015158.433"><vh>@color unselected_body_bg_color = #002b36</vh></v>
<v t="ekr.20180307015158.434"><vh>@color unselected_body_fg_color = #839496</vh></v>
<v t="ekr.20180307015158.435"><vh>@color body_text_foreground_color = #839496</vh></v>
<v t="ekr.20180307015158.436"><vh>@color insert_mode_bg_color = #002b36</vh></v>
<v t="ekr.20180307015158.437"><vh>@color insert_mode_fg_color = #839496</vh></v>
</v>
<v t="ekr.20180307015158.438"><vh>Log pane colors</vh>
<v t="ekr.20180307015158.439"><vh>@color log_error_color = #dc322f</vh></v>
<v t="ekr.20180307015158.440"><vh>@color log_warning_color = #268bd2</vh></v>
<v t="ekr.20180307015158.441"><vh>@color log_text_foreground_color = #93a1a1</vh></v>
<v t="ekr.20180307015158.442"><vh>@color log_text_background_color = #073642</vh></v>
<v t="ekr.20180307015158.443"><vh>@color log_pane_background_color = #002b36</vh></v>
<v t="ekr.20180307015158.444"><vh>@color log_pane_Find_tab_background_color = #d6c7d3</vh></v>
<v t="ekr.20180307015158.445"><vh>@color log_pane_Spell_tab_background_color = MistyRose1</vh></v>
</v>
<v t="ekr.20180307015158.446"><vh>Minibuffer colors</vh>
<v t="ekr.20180307015158.447"><vh>@color minibuffer_background_color = #073642</vh></v>
<v t="ekr.20180307015158.448"><vh>@color minibuffer_foreground_color = #b58900</vh></v>
</v>
<v t="ekr.20180307015158.449"><vh>Outline pane colors</vh>
<v t="ekr.20180307015158.450"><vh>@color headline_text_unselected_background_color = #ffffff</vh></v>
<v t="ekr.20180307015158.451"><vh>@color headline_text_unselected_foreground_color = None</vh></v>
<v t="ekr.20180307015158.452"><vh>@color headline_text_selected_background_color = #586e75</vh></v>
<v t="ekr.20180307015158.453"><vh>@color headline_text_selected_foreground_color = #002b36</vh></v>
<v t="ekr.20180307015158.454"><vh>@color headline_text_editing_background_color = None</vh></v>
<v t="ekr.20180307015158.455"><vh>@color headline_text_editing_foreground_color = None</vh></v>
<v t="ekr.20180307015158.456"><vh>@color headline_text_editing_selection_foreground_color = None</vh></v>
<v t="ekr.20180307015158.457"><vh>@color headline_text_editing_selection_background_color = None</vh></v>
<v t="ekr.20180307015158.458"><vh>@color outline_pane_background_color = #ffffff</vh></v>
</v>
<v t="ekr.20180307015158.459"><vh>Outline indicators</vh>
<v t="ekr.20180307015158.460"><vh>@string tree-image-closed = nodes-dark/triangles/closed.png</vh></v>
<v t="ekr.20180307015158.461"><vh>@string tree-image-open = nodes-dark/triangles/open.png</vh></v>
</v>
</v>
<v t="ekr.20180307015158.462"><vh>gradients</vh>
<v t="ekr.20180307015158.463"><vh>@string bg-gradient = qlineargradient( x1:0 y1:0, x2:0 y2:1, stop:0.1 @text-background-bright, stop:0.4 @text-background, stop:0.6 @text-background, stop:0.9 @text-background-bright)</vh></v>
<v t="ekr.20180307015158.464"><vh>@string bg-gradient-hover = qlineargradient( x1:0 y1:0, x2:0 y2:1, stop:0.1 @solarized-base00, stop:0.4 @solarized-base0, stop:0.6 @solarized-base0, stop:0.9 @solarized-base00)</vh></v>
</v>
</v>
<v t="ekr.20180307015158.552"></v>
<v t="ekr.20180307015158.493"><vh>theme settings</vh>
<v t="ekr.20180307015158.494"><vh>@string color_theme = leo_dark_1</vh></v>
<v t="ekr.20180307015158.495"><vh>@bool color_theme_is_dark = True</vh></v>
</v>
</v>
<v t="ekr.20180307015158.496"><vh>@data qt-gui-plugin-style-sheet</vh>
<v t="ekr.20180307015158.497"><vh>body pane</vh></v>
<v t="ekr.20180307015158.498"><vh>buttons</vh></v>
<v t="ekr.20180307015158.499"><vh>log</vh></v>
<v t="ekr.20180307015158.500"><vh>menus</vh></v>
<v t="ekr.20180307015158.501"><vh>mini-buffer</vh></v>
<v t="ekr.20180307015158.502"><vh>scroll bars</vh></v>
<v t="ekr.20180307015158.503"><vh>splitters</vh></v>
<v t="ekr.20180307015158.504"><vh>status line</vh></v>
<v t="ekr.20180307015158.505"><vh>tab bar</vh></v>
<v t="ekr.20180307015158.506"><vh>tree</vh></v>
<v t="ekr.20180307015158.507"><vh>widgets</vh></v>
</v>
</v>
<v t="ekr.20180307015158.508"><vh>@theme leo_dark theme 2</vh>
<v t="ekr.20180307015158.509"><vh>settings</vh>
<v t="ekr.20180307015158.510"><vh>style sheet settings</vh>
<v t="ekr.20180307015158.511"><vh>@ignore border</vh>
<v t="ekr.20180307015158.512"><vh>@string focused-border-style = solid</vh></v>
<v t="ekr.20180307015158.513"><vh>@string focused-border-width = 3px</vh></v>
<v t="ekr.20180307015158.514"><vh>@color focused-border-focus-color = red</vh></v>
<v t="ekr.20180307015158.515"><vh>@color focused-border-hover-color = red</vh></v>
<v t="ekr.20180307015158.516"><vh>@string focused-border-unfocus-color = white</vh></v>
</v>
<v t="ekr.20180307015158.517"><vh>colors</vh>
<v t="ekr.20180307015158.518"><vh>Body pane colors</vh>
<v t="ekr.20180307015158.519"><vh>@color body_text_background_color = #002b36</vh></v>
<v t="ekr.20180307015158.520"><vh>@color unselected_body_bg_color = #002b36</vh></v>
<v t="ekr.20180307015158.521"><vh>@color unselected_body_fg_color = #839496</vh></v>
<v t="ekr.20180307015158.522"><vh>@color body_text_foreground_color = #839496</vh></v>
<v t="ekr.20180307015158.523"><vh>@color insert_mode_bg_color = #002b36</vh></v>
<v t="ekr.20180307015158.524"><vh>@color insert_mode_fg_color = #839496</vh></v>
</v>
<v t="ekr.20180307015158.525"><vh>Log pane colors</vh>
<v t="ekr.20180307015158.526"><vh>@color log_error_color = #dc322f</vh></v>
<v t="ekr.20180307015158.527"><vh>@color log_warning_color = #268bd2</vh></v>
<v t="ekr.20180307015158.528"><vh>@color log_text_foreground_color = #93a1a1</vh></v>
<v t="ekr.20180307015158.529"><vh>@color log_text_background_color = #073642</vh></v>
<v t="ekr.20180307015158.530"><vh>@color log_pane_background_color = #002b36</vh></v>
<v t="ekr.20180307015158.531"><vh>@color log_pane_Find_tab_background_color = #d6c7d3</vh></v>
<v t="ekr.20180307015158.532"><vh>@color log_pane_Spell_tab_background_color = MistyRose1</vh></v>
</v>
<v t="ekr.20180307015158.533"><vh>Minibuffer colors</vh>
<v t="ekr.20180307015158.534"><vh>@color minibuffer_background_color = #073642</vh></v>
<v t="ekr.20180307015158.535"><vh>@color minibuffer_foreground_color = #b58900</vh></v>
</v>
<v t="ekr.20180307015158.536"><vh>Outline indicators</vh>
<v t="ekr.20180307015158.537"><vh>@string tree-image-closed = nodes-dark/triangles/closed.png</vh></v>
<v t="ekr.20180307015158.538"><vh>@string tree-image-open = nodes-dark/triangles/open.png</vh></v>
</v>
<v t="ekr.20180307015158.539"><vh>Outline pane colors</vh>
<v t="ekr.20180307015158.540"><vh>@color headline_text_unselected_background_color = #ffffff</vh></v>
<v t="ekr.20180307015158.541"><vh>@color headline_text_unselected_foreground_color = None</vh></v>
<v t="ekr.20180307015158.542"><vh>@color headline_text_selected_background_color = #586e75</vh></v>
<v t="ekr.20180307015158.543"><vh>@color headline_text_selected_foreground_color = #002b36</vh></v>
<v t="ekr.20180307015158.544"><vh>@color headline_text_editing_background_color = None</vh></v>
<v t="ekr.20180307015158.545"><vh>@color headline_text_editing_foreground_color = None</vh></v>
<v t="ekr.20180307015158.546"><vh>@color headline_text_editing_selection_foreground_color = None</vh></v>
<v t="ekr.20180307015158.547"><vh>@color headline_text_editing_selection_background_color = None</vh></v>
<v t="ekr.20180307015158.548"><vh>@color outline_pane_background_color = #ffffff</vh></v>
</v>
</v>
<v t="ekr.20180307015158.549"><vh>gradients</vh>
<v t="ekr.20180307015158.550"><vh>@string bg-gradient = qlineargradient( x1:0 y1:0, x2:0 y2:1, stop:0.1 @text-background-bright, stop:0.4 @text-background, stop:0.6 @text-background, stop:0.9 @text-background-bright)</vh></v>
<v t="ekr.20180307015158.551"><vh>@string bg-gradient-hover = qlineargradient( x1:0 y1:0, x2:0 y2:1, stop:0.1 @solarized-base00, stop:0.4 @solarized-base0, stop:0.6 @solarized-base0, stop:0.9 @solarized-base00)</vh></v>
</v>
</v>
<v t="ekr.20180307015158.552"></v>
<v t="ekr.20180307015158.580"><vh>theme settings</vh>
<v t="ekr.20180307015158.581"><vh>@string color_theme = leo_dark_2</vh></v>
<v t="ekr.20180307015158.582"><vh>@bool color_theme_is_dark = True</vh></v>
</v>
</v>
<v t="ekr.20180307015158.583"><vh>@data qt-gui-plugin-style-sheet</vh>
<v t="ekr.20180307015158.584"><vh>body editor</vh></v>
<v t="ekr.20180307015158.585"><vh>log</vh></v>
<v t="ekr.20180307015158.586"><vh>menus</vh></v>
<v t="ekr.20180307015158.587"><vh>mini-buffer</vh></v>
<v t="ekr.20180307015158.588"><vh>scroll bars</vh></v>
<v t="ekr.20180307015158.589"><vh>splitters</vh></v>
<v t="ekr.20180307015158.590"><vh>status area</vh></v>
<v t="ekr.20180307015158.591"><vh>tab bar</vh></v>
<v t="ekr.20180307015158.592"><vh>tree</vh></v>
<v t="ekr.20180307015158.593"><vh>widgets</vh></v>
</v>
</v>
</v>
</v>
</vnodes>
<tnodes>
<t tx="ekr.20180307015158.1">@language rest
@wrap

This file contains a list of older themes, that is, themes not in the leo/themes folder.

A **theme** is a combination of settings, stylesheets and optional icons. Most themes create @data qt-gui-plugin-style-sheet. Leo looks for icons in /leo/themes and ~/.leo/themes.

To enable a theme:

- *Select* one of the @theme trees below.
- *Copy* the entire @theme tree to myLeoSettings.leo.
- *Move* the copied tree to the *end* of the @settings tree.
- *Test* by restarting Leo.

To disable a theme:
- Move the entire @theme node out of the @settings tree *or*
- Change the headline to @ignore @theme...
</t>
<t tx="ekr.20180307015158.100">/* ===== active pane highlighting ===== */
QTextEdit#log-widget,
LeoQTreeWidget#treeWidget,
QTextEdit#richTextEdit { 
    border-color:   @focused-border-unfocus-color; 
    border-style:   @focused-border-style;
    border-width:   @focused-border-width; 
}

QTextEdit:focus#log-widget,
LeoQTreeWidget:focus#treeWidget,
QTextEdit:focus#richTextEdit { 
    border-color:   @focused-border-focus-color; 
}

QTextEdit:hover#log-widget,
LeoQTreeWidget:hover#treeWidget,
QTextEdit:hover#richTextEdit { 
  border-color:     @focused-border-hover-color; 
}
</t>
<t tx="ekr.20180307015158.101">/* ===== The body pane ===== */

QTextEdit#richTextEdit {
    background-color:           @test-background; /* @solarized-base03; */
    color:                      @text-foreground;
    font-family:                @font-family-body;
    font-size:                  @font-size-body;
    font-weight:                normal; /* normal,bold,100,..,900 */
    font-style:                 normal; /* normal,italic,oblique */
    selection-color:            @solarized-base03;
    selection-background-color: @solarized-yellow;
}</t>
<t tx="ekr.20180307015158.102">/* ===== bookmarks plugin styling ===== */

#show_bookmarks QPushButton { 
    margin: 0; padding: 1; border: none;
    font-size: @bookmarks_base_size;
    color: @bookmarks_base_color;
    font-weight: @bookmarks_base_weight;
    text-decoration: @bookmarks_base_decoration;
}
#show_bookmarks QPushButton[style_class~='bookmark_children'] {
    font-size: @bookmarks_children_size;
    color: @bookmarks_children_color;
    font-weight: @bookmarks_children_weight;
    text-decoration: @bookmarks_children_decoration;
}
#show_bookmarks QPushButton[style_class~='bookmark_expanded'] {
    font-size: @bookmarks_expanded_size;
    color: @bookmarks_expanded_color;
    font-weight: @bookmarks_expanded_weight;
    text-decoration: @bookmarks_expanded_decoration;
}
#show_bookmarks QPushButton[style_class~='bookmark_current'] {
    font-size: @bookmarks_current_size;
    color: @bookmarks_current_color;
    font-weight: @bookmarks_current_weight;
    text-decoration: @bookmarks_current_decoration;
}
</t>
<t tx="ekr.20180307015158.103">/* ===== Buttons ===== */

QPushButton {
    background: @bg-gradient;
    color:      @text-foreground;
}
QPushButton:hover {
    background: @bg-gradient-hover;
    color:      @button-hover-fg;
}</t>
<t tx="ekr.20180307015158.104">/* ===== Log panes ===== */

QTextEdit#log-widget {
    background-color:           @log_text_background_color;
    color:                      @log_text_foreground_color;
    font-family:                @font-family-log;
    font-size:                  @font-size-log;
    font-style:                 normal; /* normal, italic,oblique */
    font-weight:                normal; /* normal,bold,100,..,900 */
    selection-background-color: blue;
    selection-color:            white;
}
</t>
<t tx="ekr.20180307015158.105">/* ===== Menues ===== */

QMenu {
    color:      @text-foreground-bright;
}
QMenu::item:selected {
    color:      @button-hover-fg;
    background: @bg-gradient-hover;
}

QMenuBar::item {
    color:      @text-foreground;
    background: @bg-gradient;
}
QMenuBar::item:selected {
    color:      @button-hover-fg;
    background: @bg-gradient-hover;
}
QMenuBar::item:pressed {
    color:      @text-foreground-bright;
    background: @bg-gradient;
}
</t>
<t tx="ekr.20180307015158.106">/* ===== Mini-buffer ===== */

QLineEdit#lineEdit {
    color:                      @minibuffer_foreground_color;
    background-color:           @minibuffer_background_color;
    font-family:                @font-family;
    font-size:                  @font-size;
    font-weight:                normal; /* normal,bold,100,..,900 */
    font-style:                 normal; /* normal,italic,oblique */
    selection-color:            red;
    selection-background-color: lightgrey;
}

QLabel#minibufferLabel {
    color:              @solarized-violet;
}
QLineEdit#lineEdit[style_class ~= 'minibuffer_warning'] {
    background-color:   @minibuffer_warning_color;
}
QLineEdit#lineEdit[style_class ~= 'minibuffer_error'] {
    color:              @minibuffer_error_color;
    background-color:   @minibuffer_warning_color;
}
</t>
<t tx="ekr.20180307015158.107">/* ===== Status line ===== */

QLineEdit#status1,
QLineEdit#status2 
{
    background-color:   @solarized-base03;
    border-color:       @solarized-base02;
    border-style:       solid;
    border-width:       1px;
}

</t>
<t tx="ekr.20180307015158.108">/* ===== Scroll bars ===== */

QScrollBar::horizontal {
     height: 7px;
}
QScrollBar::vertical {
     width: 7px;
}
QScrollBar::add-page,
QScrollBar::sub-page {
    background: @solarized-base03;
}
QScrollBar::handle { 
    background: @solarized-base01;
    color:      @solarized-base01;
}
QScrollBar::handle:hover { 
  background:   @solarized-base0;
  color:        @solarized-base0;
}
/* to make these show up, remove the ::handle style above... bug? */
QScrollBar::add-line,
QScrollBar::sub-line { 
  background:   @solarized-base01;
  color:        @solarized-base01;
}</t>
<t tx="ekr.20180307015158.109">/* ===== Splitters ===== */

QSplitter::handle {
    background-color: @splitter-bg;
}
QSplitter::handle:hover {
    background-color: @splitter-hover-bg;
}
</t>
<t tx="ekr.20180307015158.110">/* ===== Tab bar ===== */

QTabBar::tab { 
   margin-right:    5px;
   padding:         2px; 
}
QTabBar::tab {
    background:     @bg-gradient;
    color:          @text-foreground; 
    margin-right:   5px;
    padding:        2px; 
}
QTabBar::tab:selected {
    color:          @solarized-green;
}
QTabBar::tab:hover {
    background:     @bg-gradient-hover;
    color:          @button-hover-fg;
}</t>
<t tx="ekr.20180307015158.111">/* ===== Tree Widgets ===== */

QTreeWidget {
    /* These apply to the selected item, but not to editing items.*/
    font-family:    @font-family-tree;
    font-size:      @font-size-tree;
    font-weight:    normal; /* normal,bold,100,..,900 */
    font-style:     normal; /* normal, italic,oblique */
}
QTreeWidget QLineEdit {
    /* Headline edit widgets */
    font-family:    @font-family-tree;
    font-size:      @font-size-tree;
    font-weight:    normal; /* normal,bold,100,..,900 */
    font-style:     normal; /* normal, italic,oblique */ 
}
QTreeWidget::selected {
    background:     @solarized-green;
    color:          @solarized-base03; 
}
QTreeWidget::active:selected {
    background:     @solarized-yellow;
    color:          @solarized-base03; 
}

/* ===== Tree Views ===== */

QTreeView {
    /* These apply to the selected item, but not to editing items.*/
    background-color:           @solarized-base03;
    color:                      @solarized-base0;
    selection-color:            @solarized-orange;
    selection-background-color: @solarized-base03;
    show-decoration-selected:   0;
}
QTreeView::item:selected {
    background:                 @solarized-green;
    color:                      @solarized-base03; 
}
QTreeView::item:active:selected {
    background:                 @solarized-yellow;
    color:                      @solarized-base03; 
}
QTreeView QLineEdit {
    /* Headline edit widgets */
    color:                      @solarized-base03;
    background-color:           @solarized-yellow;
    selection-color:            @solarized-base3;
    selection-background-color: @solarized-blue;  
}
QTreeView::branch:closed:has-children{
    image: @tree-image-closed;
}
QTreeView::branch:open:has-children{
    image: @tree-image-open;
}
</t>
<t tx="ekr.20180307015158.112">/* ===== widgets ===== */

QLabel {
    color: @solarized-base1;
}
QLineEdit {
    border:     none;
    padding:    3px;
}
QPushButton, QDoubleSpinBox, QSpinBox, QDateEdit, QTimeEdit {
    border:         none;
    margin-right:   5px;
    padding:        3px;
}
QWidget {
    background-color:   @solarized-base03; 
    border-color:       @solarized-base1; 
    color:              @solarized-base1;
    font-size:          @font-size;
}
QWidget#body-text-renderer {
    background-color:   white;
    color:              black;
}
</t>
<t tx="ekr.20180307015158.113">This theme uses the default qt-gui-plugin-style-sheet.</t>
<t tx="ekr.20180307015158.114"></t>
<t tx="ekr.20180307015158.115">/*
@language css

    old_themes.leo: @data qt-gui-plugin-style-sheet (ekr light)

    =========== Leo's new, fully parameterized, stylesheet. ===========
    
    This stylesheet is responsible for most of Leo's appearance.
    This stylesheet is composed of this nodes and all its descendants, in outline order.
    
    Leo inserts the settings in the tree "Qt Gui Stylesheet settings" into this stylesheet.
    Modify those settings, *not* this stylesheet.
    
    About Qt stylesheets: http://qt-project.org/doc/qt-4.8/stylesheet.html
*/

</t>
<t tx="ekr.20180307015158.116">/* ========== Body pane ========== */

QTextEdit#richTextEdit {
    background-color:           @body-bg;
    color:                      @body-fg;
    selection-color:            @body-sel-fg;
    selection-background-color: @body-sel-bg;
    font-family:                @body-font-family;
    font-size:                  @font-size-body;
    /* Don't use body-font-size for the font-size. */
    font-weight:                @body-font-weight;
    font-style:                 @body-font-style;
}

QTextEdit#bigtextwarning {
    background-color: red; /* no longer used */
}</t>
<t tx="ekr.20180307015158.117">/* ========== Buttons ========== 

    Examples::
    
        QPushButton#&lt;button text&gt;-button { &lt;style&gt; }
        QPushButton[button_kind="&lt;button kind&gt;"] { &lt;style&gt; }
*/

/*
    Default for all buttons.
    If you specify the size, you should also specify the font.
*/

/* -----
QPushButton {
    font-family: @push-button-font-family;
    font-size:   @push-button-font-size;
}
----- */

QPushButton[button_kind="at-button"] {
    /* Buttons created by @button nodes. */
    background-color: @at-button-btn-bg;
}
QPushButton[button_kind="debug-script"] {
    background-color: @debug-script-btn-bg;
}
QPushButton[button_kind="generic-button"] {
    /* The default styling for buttons. */
    background-color: @generic-button-btn-bg;
}
QPushButton[button_kind="run-script"] {
    /* The singleton run-script button. */
    background-color: @run-script-btn-bg;
}
QPushButton[button_kind="script-button"] {
    /* Buttons created by the script-button button. */
    background-color: @script-button-btn-bg;
}
QPushButton#script-button-button { 
    /* The singleton script-button button. */
    background-color: @script-button-button-btn-bg;
}
</t>
<t tx="ekr.20180307015158.118">/*  ========== Dialogs (QLabel) ========== 

    Use care when changing these settings: they are used for dialog text. 
*/

QLabel {
    border:         @dialog-border;
    margin:         @dialog-margin;
    font-family:    @dialog-font-family;
    font-size:      @dialog-font-size;
    font-weight:    @dialog-font-weight;
    font-style:     @dialog-font-style;
}

QCheckBox#TipCheckbox {
    background: lightgrey;
}
</t>
<t tx="ekr.20180307015158.119">/* ========== Components of the Find Tab ========== */

QWidget#findTab {
    background-color: @find-tab-bg;
}

QLabel#findHeading, QLabel#findHelp {
    font-family:    @find-font-family;
    font-size:      @find-font-size; 
    font-weight:    @find-font-weight;
    font-style:     @find-font-style; 
}

QLabel#findLabel, QLabel#changeLabel {
    font-family:    @find-font-family;
    font-size:      @find-font-size;
    font-weight:    @find-font-weight;
    font-style:     @find-font-style;
}

QLineEdit#findPattern, QLineEdit#findChange {
    font-family:    @find-pattern-font-family;
    font-size:      @find-font-size;
    font-weight:    @find-font-weight;
    font-style:     @find-font-style;
}

QCheckBox, QRadioButton {
    /* For the Find Tab. */
    font-family:    @checkbox-font-family;
    font-size:      @checkbox-font-size;
}
</t>
<t tx="ekr.20180307015158.120">/* ===== Optional line-number gutter ===== */

QFrame#gutter {
    background-color:           @gutter-bg;
    color:                      @gutter-fg;
    font-family:                @gutter-font-family;
    font-size:                  @gutter-font-size;
    font-weight:                @gutter-font-weight;
    font-style:                 @gutter-font-style;
}</t>
<t tx="ekr.20180307015158.121">/* ========== The log pane &amp; other text widgets ========== */

QTextEdit:focus {
  border-color: @focused-border-focus-color; 
}

QTextEdit {
    border-color:               @focused-border-unfocus-color; 
    border-style:               @focused-border-style;
    border-width:               @focused-border-width; 
    background-color:           @log-bg;
    color:                      @log-fg;
    selection-color:            @log-sel-fg;
    selection-background-color: @log-sel-bg;
    font-family:                @log-font-family;
    font-size:                  @log-font-size;
    font-weight:                @log-font-weight;
    font-style:                 @log-font-style;
}
</t>
<t tx="ekr.20180307015158.122">/* ==========  Minibuffer ========== */

/* ----- The minibuffer itself ----- */

QLineEdit#lineEdit {
    color:                      @minibuffer-fg;
    background-color:           @minibuffer-bg;
    selection-color:            @minibuffer-sel-fg;
    selection-background-color: @minibuffer-sel-bg;
    font-family:                @minibuffer-font-family;
    font-size:                  @minibuffer-font-size;
    font-weight:                @minibuffer-font-weight;
    font-style:                 @minibuffer-font-style;
}

/* ----- The label of the minibuffer ----- */

QLabel#minibufferLabel {
    border:         @minibuffer-border;
    margin:         @minibuffer-margin;
    font-family:    @minibuffer-font-family;
    font-size:      @minibuffer-font-size;
    font-weight:    @minibuffer-font-weight;
    font-style:     @minibuffer-font-style;
}
</t>
<t tx="ekr.20180307015158.123">/* ========== Outline pane ========== */

QTreeWidget {
    /* Outline pane defaults. */
    border-style:               @focused-border-style;
    border-width:               @focused-border-width; 
    border-color:               @focused-border-unfocus-color; 
    color:                      @tree-fg;
    background-color:           @tree-bg;
    font-family:                @tree-font-family;
    font-size:                  @tree-font-size;
    font-weight:                @tree-font-weight;
    font-style:                 @tree-font-style;
    show-decoration-selected:   0; /* 1: select entire row */
}

QTreeWidget QLineEdit {
    /* Headlines when they *are* being edited. */
    color:                      @head-fg;
    background-color:           @head-bg;
    selection-color:            @head-sel-fg; 
    selection-background-color: @head-sel-bg;
    font-family:                @head-font-family;
    font-size:                  @head-font-size; 
    font-weight:                @head-font-weight;
    font-style:                 @head-font-style;
}

QTreeWidget:focus {
  border-style:         @focused-border-style;
  border-width:         @focused-border-width; 
  border-color:         @focused-border-focus-color; 
}

QTreeWidget::item:selected {
    /* Headlines when they selected but *not* edited. */
    color:              @edit-label-fg;
    background-color:   @edit-label-bg;
    font-family:        @edit-label-font-family;
    font-size:          @edit-label-font-size;
    font-weight:        @edit-label-font-weight;
    font-style:         @edit-label-font-style;
}

/* ===== 

QTreeView::branch:open{
    color:                      @tree-fg;
    background-color:           @tree-bg;
}

QTreeView::branch:closed{
    color:                      @tree-fg;
    background-color:           @tree-bg;
}

QTreeView::branch:closed:has-children{
    image: AT-tree-image-closed;
}

QTreeView::branch:open:has-children{
    image: At-tree-image-open;
}

===== */

</t>
<t tx="ekr.20180307015158.124"></t>
<t tx="ekr.20180307015158.125">/* ========== bookmarks.py plugin ========== */

#show_bookmarks QPushButton {
    color:              @bookmarks_base_color;
    margin:             @bookmarks_base_margin;
    padding:            @bookmarks_base_padding;
    border:             @bookmarks_base_border;
    font-family:        @bookmarks_base_family;
    font-size:          @bookmarks_base_size;
    font-style:         @bookmarks_base_style;
    font-weight:        @bookmarks_base_weight;
    text-decoration:    @bookmarks_base_decoration;
}

</t>
<t tx="ekr.20180307015158.126">/* ========== screencast.py plugin========== */

QPlainTextEdit#screencastcaption {
    background-color:   @screencast-bg;
    font-family:        @screencast-font-family;
    font-size:          @screencast-font-size;
    font-weight:        @screencast-font-weight;
    font-style:         @screencast-font-style;
}
</t>
<t tx="ekr.20180307015158.127">/* ========== interact.py plugin ========== */

QPushButton[button_kind="interact"] {
    /* Buttons from the interact plugin. */
    background-color: @interact-btn-bg;
}
</t>
<t tx="ekr.20180307015158.128">/* ========== quickmove.py plugin ========== */

QPushButton[button_kind="quick-move"] { 
    /* Buttons from the quickmove plugin. */
    background-color: @quick-move-btn-bg;
}</t>
<t tx="ekr.20180307015158.129">QWidget#body-text-renderer {
    color:              @render-fg;
    background-color:   @render-bg;
}</t>
<t tx="ekr.20180307015158.130">QSplitter {
    border-color:       @splitter-border-fg;
    background-color:   @splitter-bg;
    border-style:       @splitter-border-style;
}

QSplitter::handle {
    /* Supports only background attributes. */
    background-color:   @splitter-handle-bg;
}

QSplitter::handle:hover {
    background-color:   @splitter-hover-bg;
}
</t>
<t tx="ekr.20180307015158.131">/* Status areas. */

QLineEdit#status1, QLineEdit#status2 {
    background-color:   @status-bg;
    color:              @status-fg;
    border-color:       @status-border-color;
    border-width:       @status-border-width;
    border-style:       @status-border-style;
    font-family:        @status-font-family;
    font-size:          @status-font-size;
    font-weight:        @status-font-weight;
    font-style:         @status-font-style;
}

QLineEdit#status1[style_class ~= 'info'], QLineEdit#status2[style_class ~= 'info'] {
    background-color:   @find-found-bg;
    color:              @find-found-fg;
}

QLineEdit#status1[style_class ~= 'fail'], QLineEdit#status2[style_class ~= 'fail'] {
    background-color:   @find-not-found-bg;
    color:              @find-not-found-fg;
}
</t>
<t tx="ekr.20180307015158.132">/* Vim mode borders... */

QTextEdit#richTextEdit[vim_state~="vim_normal"] {
  border: @vim-mode-normal-border;
}

QTextEdit#richTextEdit[vim_state~="vim_insert"] {
  border: @vim-mode-insert-border;
}

QTextEdit#richTextEdit[vim_state~="vim_visual"] {
  border: @vim-mode-visual-border;
}
</t>
<t tx="ekr.20180307015158.133">/* ========== Widgets ========== */

/* ----- Destroys other background colors!
QFrame {
    background-color: at-frame-bg;
}
----- */

QScrollArea {
    background-color:   @scroll-area-bg;
}

QTabbedWidget {
    background-color:   @tabbed-widget-bg;
}

QTabBar::tab {
    background:         @unselected-tab-bg;
}

QTabBar::tab:selected, QTabBar::tab:hover {
    background:         @selected-tab-bg;
}

QStackedWidget {
    border-color:       @stacked-widget-border-color;
    background-color:   @stacked-widget-bg;
    padding:            @stacked-widget-padding;
}
</t>
<t tx="ekr.20180307015158.134">/*
@language css

old_themes.leo: qt-gui-user-style-sheet (ekr light)
*/

/*
    solarized-base3 (lightest) provides contrast in the main window.
    QWidget styling is useful for testing, and not much else.
*/

/* Defaults */
QWidget, QFrame {
    background: @solarized-base2;
}
QDialog {
    background:     lightgrey;
}
QDialog &gt; QLabel {
    font-size:      12pt;
}
QLabel, QScrollBar, QStatusBar {
    background:     lightgrey;
}

/* Widgets */
/* ===== covered by defaults.
QCheckBox,  QComboBox, QGroupBox, QPushButton, QRadioButton,
QLineEdit,
QTabBar, QTabWidget, QToolBar,
{
    background:     @solarized-base2;
}
===== */

/* ===== Not used
QDoubleSpinBox, QSpinBox, QDateEdit, QTimeEdit {
    border:         none;
    margin-right:   5px;
    padding:        3px;
}
===== */

QTextEdit#log-widget {
    background:         @LightSteelBlue1;
    /* border-color interferes with border coloring. */
}
QTreeView,
QTreeWidget,
QTextEdit#richTextEdit {
    background-color:   @solarized-base2;
    /* border-color interferes with border coloring. */
    /* border-color:           @solarized-base2;  */
}

/* Menu Bar and menus */
QMenu,
QMenuBar,
QMenu::item,
QMenuBar::item {
    background:         @solarized-base2;
}
QMenu::item:selected,
QMenuBar::item:selected,
QMenuBar::item:pressed {
    background:         @LightSteelBlue1;
    color: black;
}
</t>
<t tx="ekr.20180307015158.135">Same as @theme base dark except for zz nodes.</t>
<t tx="ekr.20180307015158.136"></t>
<t tx="ekr.20180307015158.137"></t>
<t tx="ekr.20180307015158.138"></t>
<t tx="ekr.20180307015158.139"></t>
<t tx="ekr.20180307015158.140">Was cyan</t>
<t tx="ekr.20180307015158.141"></t>
<t tx="ekr.20180307015158.142"></t>
<t tx="ekr.20180307015158.143"></t>
<t tx="ekr.20180307015158.144">Here you can edit the colors by Leo, just edit the
node headings, and click the reload-style button.
</t>
<t tx="ekr.20180307015158.145"></t>
<t tx="ekr.20180307015158.146"></t>
<t tx="ekr.20180307015158.147">Color for error messages written to the log window.</t>
<t tx="ekr.20180307015158.148">Background color of log text.</t>
<t tx="ekr.20180307015158.149">Foreground color of log text.

</t>
<t tx="ekr.20180307015158.150"></t>
<t tx="ekr.20180307015158.151"></t>
<t tx="ekr.20180307015158.152"></t>
<t tx="ekr.20180307015158.153"></t>
<t tx="ekr.20180307015158.154"></t>
<t tx="ekr.20180307015158.155"></t>
<t tx="ekr.20180307015158.156"></t>
<t tx="ekr.20180307015158.157"></t>
<t tx="ekr.20180307015158.158">@solarized-base02</t>
<t tx="ekr.20180307015158.159"></t>
<t tx="ekr.20180307015158.160"></t>
<t tx="ekr.20180307015158.161"></t>
<t tx="ekr.20180307015158.162">test text</t>
<t tx="ekr.20180307015158.163">test text</t>
<t tx="ekr.20180307015158.164"></t>
<t tx="ekr.20180307015158.165"></t>
<t tx="ekr.20180307015158.166"></t>
<t tx="ekr.20180307015158.167"></t>
<t tx="ekr.20180307015158.168">(some body text here so there's something to see)</t>
<t tx="ekr.20180307015158.169"></t>
<t tx="ekr.20180307015158.170"></t>
<t tx="ekr.20180307015158.171"></t>
<t tx="ekr.20180307015158.172"></t>
<t tx="ekr.20180307015158.173"></t>
<t tx="ekr.20180307015158.174">Outline indicators indicate the expansion state of outline nodes. The leo/Icons/nodes-dark folders contains two sets of indicators::
    
    leo/Icons/nodes-dark/plusminus/
    leo/Icons/nodes-dark/triangles/
    
The following settings specify the indicators.  You can use an absolute path, or more conveniently, a path relative either to:

- Your home directory or
- Leo's leo/Icons directory
</t>
<t tx="ekr.20180307015158.175">Must be relative to either the users home directory or leo/Icons directory.

url(/home/edward/leo.repo/leo-editor/leo/Icons/nodes-dark/triangles/closed.png)</t>
<t tx="ekr.20180307015158.176">url(/home/edward/leo.repo/leo-editor/leo/Icons/nodes-dark/triangles/open.png)</t>
<t tx="ekr.20180307015158.177"></t>
<t tx="ekr.20180307015158.178"></t>
<t tx="ekr.20180307015158.179"></t>
<t tx="ekr.20180307015158.180"></t>
<t tx="ekr.20180307015158.181">@language rest
@wrap

Note: Do not use @-constants here.</t>
<t tx="ekr.20180307015158.182">The color of text in doc parts.

was firebrick3. now comment1_color
</t>
<t tx="ekr.20180307015158.183">The color of Leo keywords such as @ignore, @color, etc.

Was #00aa00.
Now solarized-blue
</t>
<t tx="ekr.20180307015158.184">Was blue, now solarized-blue
</t>
<t tx="ekr.20180307015158.185">The color of name in &lt; &lt; name &gt; &gt; when name is defined.

was red. Now comment1_color</t>
<t tx="ekr.20180307015158.186">The background color that represents spaces when Show Invisibles mode is in effect.

solarized-magenta</t>
<t tx="ekr.20180307015158.187">The foreground color that represents tabs when Show Invisibles mode is in effect.

gray80: #CCCCCC
gray90: #E5E5E5
</t>
<t tx="ekr.20180307015158.188">The color of name in &lt;&lt; name &gt;&gt; when name is undefined.

Was red. Now now comment1_color</t>
<t tx="ekr.20180307015158.189"></t>
<t tx="ekr.20180307015158.190">Note: Do not use @-constants here.</t>
<t tx="ekr.20180307015158.191">solarized-magenta
</t>
<t tx="ekr.20180307015158.192"></t>
<t tx="ekr.20180307015158.193"></t>
<t tx="ekr.20180307015158.194"></t>
<t tx="ekr.20180307015158.195"></t>
<t tx="ekr.20180307015158.196"></t>
<t tx="ekr.20180307015158.197"></t>
<t tx="ekr.20180307015158.198"></t>
<t tx="ekr.20180307015158.199"></t>
<t tx="ekr.20180307015158.200">#00aa00 (Idle comment green)

</t>
<t tx="ekr.20180307015158.201"></t>
<t tx="ekr.20180307015158.202"></t>
<t tx="ekr.20180307015158.203"></t>
<t tx="ekr.20180307015158.204"></t>
<t tx="ekr.20180307015158.205">base2     #eee8d5</t>
<t tx="ekr.20180307015158.206"></t>
<t tx="ekr.20180307015158.207"></t>
<t tx="ekr.20180307015158.208"></t>
<t tx="ekr.20180307015158.209"></t>
<t tx="ekr.20180307015158.210"></t>
<t tx="ekr.20180307015158.211">(some body text here so there's something to see)</t>
<t tx="ekr.20180307015158.212"></t>
<t tx="ekr.20180307015158.213"></t>
<t tx="ekr.20180307015158.214"></t>
<t tx="ekr.20180307015158.215">Name of the theme, used to find icon files</t>
<t tx="ekr.20180307015158.216">Set to true for dark themes, so bookmarks.py can generate
random background colors which are appropriate etc.</t>
<t tx="ekr.20180307015158.217">/*
@language css

old_themes.leo: qt-gui-user-style-sheet (ekr dark)
*/</t>
<t tx="ekr.20180307015158.218"></t>
<t tx="ekr.20180307015158.219">/* ===== active pane highlighting ===== */
QTextEdit#log-widget,
LeoQTreeWidget#treeWidget,
QTextEdit#richTextEdit { 
    border-color:   @focused-border-unfocus-color; 
    border-style:   @focused-border-style;
    border-width:   @focused-border-width; 
}

QTextEdit:focus#log-widget,
LeoQTreeWidget:focus#treeWidget,
QTextEdit:focus#richTextEdit { 
    border-color:   @focused-border-focus-color; 
}

QTextEdit:hover#log-widget,
LeoQTreeWidget:hover#treeWidget,
QTextEdit:hover#richTextEdit { 
  border-color:     @focused-border-hover-color; 
}
</t>
<t tx="ekr.20180307015158.22"></t>
<t tx="ekr.20180307015158.220">/* ===== The body pane ===== */

QTextEdit#richTextEdit {
    background-color:           @test-background; /* @solarized-base03; */
    color:                      @text-foreground;
    font-family:                @font-family-body;
    font-size:                  @font-size-body;
    font-weight:                normal; /* normal,bold,100,..,900 */
    font-style:                 normal; /* normal,italic,oblique */
    selection-color:            @solarized-base03;
    selection-background-color: @solarized-yellow;
}</t>
<t tx="ekr.20180307015158.221">/* ===== bookmarks plugin styling ===== */

#show_bookmarks QPushButton { 
    margin: 0; padding: 1; border: none;
    font-size: @bookmarks_base_size;
    color: @bookmarks_base_color;
    font-weight: @bookmarks_base_weight;
    text-decoration: @bookmarks_base_decoration;
}
#show_bookmarks QPushButton[style_class~='bookmark_children'] {
    font-size: @bookmarks_children_size;
    color: @bookmarks_children_color;
    font-weight: @bookmarks_children_weight;
    text-decoration: @bookmarks_children_decoration;
}
#show_bookmarks QPushButton[style_class~='bookmark_expanded'] {
    font-size: @bookmarks_expanded_size;
    color: @bookmarks_expanded_color;
    font-weight: @bookmarks_expanded_weight;
    text-decoration: @bookmarks_expanded_decoration;
}
#show_bookmarks QPushButton[style_class~='bookmark_current'] {
    font-size: @bookmarks_current_size;
    color: @bookmarks_current_color;
    font-weight: @bookmarks_current_weight;
    text-decoration: @bookmarks_current_decoration;
}
</t>
<t tx="ekr.20180307015158.222">/* ===== Buttons ===== */

QPushButton {
    background: @bg-gradient;
    color:      @text-foreground;
}
QPushButton:hover {
    background: @bg-gradient-hover;
    color:      @button-hover-fg;
}</t>
<t tx="ekr.20180307015158.223">/* ===== Log panes ===== */

QTextEdit#log-widget {
    background-color:           @log_text_background_color;
    color:                      @log_text_foreground_color;
    font-family:                @font-family-log;
    font-size:                  @font-size-log;
    font-style:                 normal; /* normal, italic,oblique */
    font-weight:                normal; /* normal,bold,100,..,900 */
    selection-background-color: blue;
    selection-color:            white;
}
</t>
<t tx="ekr.20180307015158.224">/* ===== Menues ===== */

QMenu {
    color:      @text-foreground-bright;
}
QMenu::item:selected {
    color:      @button-hover-fg;
    background: @bg-gradient-hover;
}

QMenuBar::item {
    color:      @text-foreground;
    background: @bg-gradient;
}
QMenuBar::item:selected {
    color:      @button-hover-fg;
    background: @bg-gradient-hover;
}
QMenuBar::item:pressed {
    color:      @text-foreground-bright;
    background: @bg-gradient;
}
</t>
<t tx="ekr.20180307015158.225">/* ===== Mini-buffer ===== */

QLineEdit#lineEdit {
    color:                      @minibuffer_foreground_color;
    background-color:           @minibuffer_background_color;
    font-family:                @font-family;
    font-size:                  @font-size;
    font-weight:                normal; /* normal,bold,100,..,900 */
    font-style:                 normal; /* normal,italic,oblique */
    selection-color:            red;
    selection-background-color: lightgrey;
}

QLabel#minibufferLabel {
    color:              @solarized-violet;
}
QLineEdit#lineEdit[style_class ~= 'minibuffer_warning'] {
    background-color:   @minibuffer_warning_color;
}
QLineEdit#lineEdit[style_class ~= 'minibuffer_error'] {
    color:              @minibuffer_error_color;
    background-color:   @minibuffer_warning_color;
}
</t>
<t tx="ekr.20180307015158.226">/* ===== Status line ===== */

QLineEdit#status1,
QLineEdit#status2 
{
    background-color:   @solarized-base03;
    border-color:       @solarized-base02;
    border-style:       solid;
    border-width:       1px;
}

</t>
<t tx="ekr.20180307015158.227">/* ===== Scroll bars ===== */

QScrollBar::horizontal {
     height: 7px;
}
QScrollBar::vertical {
     width: 7px;
}
QScrollBar::add-page,
QScrollBar::sub-page {
    background: @solarized-base03;
}
QScrollBar::handle { 
    background: @solarized-base01;
    color:      @solarized-base01;
}
QScrollBar::handle:hover { 
  background:   @solarized-base0;
  color:        @solarized-base0;
}
/* to make these show up, remove the ::handle style above... bug? */
QScrollBar::add-line,
QScrollBar::sub-line { 
  background:   @solarized-base01;
  color:        @solarized-base01;
}</t>
<t tx="ekr.20180307015158.228">/* ===== Splitters ===== */

QSplitter::handle {
    background-color: @splitter-bg;
}
QSplitter::handle:hover {
    background-color: @splitter-hover-bg;
}
</t>
<t tx="ekr.20180307015158.229">/* ===== Tab bar ===== */

QTabBar::tab { 
   margin-right:    5px;
   padding:         2px; 
}
QTabBar::tab {
    background:     @bg-gradient;
    color:          @text-foreground; 
    margin-right:   5px;
    padding:        2px; 
}
QTabBar::tab:selected {
    color:          @solarized-green;
}
QTabBar::tab:hover {
    background:     @bg-gradient-hover;
    color:          @button-hover-fg;
}</t>
<t tx="ekr.20180307015158.23"></t>
<t tx="ekr.20180307015158.230">/* ===== Tree Widgets ===== */

QTreeWidget {
    /* These apply to the selected item, but not to editing items.*/
    font-family:    @font-family-tree;
    font-size:      @font-size-tree;
    font-weight:    normal; /* normal,bold,100,..,900 */
    font-style:     normal; /* normal, italic,oblique */
}
QTreeWidget QLineEdit {
    /* Headline edit widgets */
    font-family:    @font-family-tree;
    font-size:      @font-size-tree;
    font-weight:    normal; /* normal,bold,100,..,900 */
    font-style:     normal; /* normal, italic,oblique */ 
}
QTreeWidget::selected {
    background:     @solarized-green;
    color:          @solarized-base03; 
}
QTreeWidget::active:selected {
    background:     @solarized-yellow;
    color:          @solarized-base03; 
}

/* ===== Tree Views ===== */

QTreeView {
    /* These apply to the selected item, but not to editing items.*/
    background-color:           @solarized-base03;
    color:                      @solarized-base0;
    selection-color:            @solarized-orange;
    selection-background-color: @solarized-base03;
    show-decoration-selected:   0;
}
QTreeView::item:selected {
    background:                 @solarized-green;
    color:                      @solarized-base03; 
}
QTreeView::item:active:selected {
    background:                 @solarized-yellow;
    color:                      @solarized-base03; 
}
QTreeView QLineEdit {
    /* Headline edit widgets */
    color:                      @solarized-base03;
    background-color:           @solarized-yellow;
    selection-color:            @solarized-base3;
    selection-background-color: @solarized-blue;  
}
QTreeView::branch:closed:has-children{
    image: @tree-image-closed;
}
QTreeView::branch:open:has-children{
    image: @tree-image-open;
}
</t>
<t tx="ekr.20180307015158.231">/* ===== widgets ===== */

QLabel {
    color: @solarized-base1;
}
QLineEdit {
    border:     none;
    padding:    3px;
}
QPushButton, QDoubleSpinBox, QSpinBox, QDateEdit, QTimeEdit {
    border:         none;
    margin-right:   5px;
    padding:        3px;
}
QWidget {
    background-color:   @solarized-base03; 
    border-color:       @solarized-base1; 
    color:              @solarized-base1;
    font-size:          @font-size;
}
QWidget#body-text-renderer {
    background-color:   white;
    color:              black;
}
</t>
<t tx="ekr.20180307015158.232">/* ===== Overrides of previous settings ===== */

QTreeWidget QLineEdit {
    /* Editing */
    background:                 @solarized-base1;
    selection-color:            @solarized-base1;
    selection-background-color: @solarized-blue;
}
QTreeWidget::selected,
QTreeWidget::active:selected,
QTreeView::item:selected,
QTreeView::item:active:selected {
    background: @solarized-base01; /* one step darker than backround */
}
</t>
<t tx="ekr.20180307015158.233">Same as @theme base dark, except for overrides in zz nodes.</t>
<t tx="ekr.20180307015158.234"></t>
<t tx="ekr.20180307015158.235"></t>
<t tx="ekr.20180307015158.236"></t>
<t tx="ekr.20180307015158.237"></t>
<t tx="ekr.20180307015158.238">Was cyan</t>
<t tx="ekr.20180307015158.239"></t>
<t tx="ekr.20180307015158.24"></t>
<t tx="ekr.20180307015158.240"></t>
<t tx="ekr.20180307015158.241"></t>
<t tx="ekr.20180307015158.242">Here you can edit the colors by Leo, just edit the
node headings, and click the reload-style button.
</t>
<t tx="ekr.20180307015158.243"></t>
<t tx="ekr.20180307015158.244"></t>
<t tx="ekr.20180307015158.245">Color for error messages written to the log window.</t>
<t tx="ekr.20180307015158.246">Background color of log text.</t>
<t tx="ekr.20180307015158.247">Foreground color of log text.

</t>
<t tx="ekr.20180307015158.248"></t>
<t tx="ekr.20180307015158.249"></t>
<t tx="ekr.20180307015158.25"></t>
<t tx="ekr.20180307015158.250"></t>
<t tx="ekr.20180307015158.251"></t>
<t tx="ekr.20180307015158.252"></t>
<t tx="ekr.20180307015158.253"></t>
<t tx="ekr.20180307015158.254"></t>
<t tx="ekr.20180307015158.255"></t>
<t tx="ekr.20180307015158.256">@solarized-base02</t>
<t tx="ekr.20180307015158.257"></t>
<t tx="ekr.20180307015158.258"></t>
<t tx="ekr.20180307015158.259"></t>
<t tx="ekr.20180307015158.26"></t>
<t tx="ekr.20180307015158.260">test text</t>
<t tx="ekr.20180307015158.261">test text</t>
<t tx="ekr.20180307015158.262"></t>
<t tx="ekr.20180307015158.263"></t>
<t tx="ekr.20180307015158.264"></t>
<t tx="ekr.20180307015158.265"></t>
<t tx="ekr.20180307015158.266">(some body text here so there's something to see)</t>
<t tx="ekr.20180307015158.267"></t>
<t tx="ekr.20180307015158.268"></t>
<t tx="ekr.20180307015158.269"></t>
<t tx="ekr.20180307015158.27">Was cyan</t>
<t tx="ekr.20180307015158.270"></t>
<t tx="ekr.20180307015158.271"></t>
<t tx="ekr.20180307015158.272">Outline indicators indicate the expansion state of outline nodes. The leo/Icons/nodes-dark folders contains two sets of indicators::
    
    leo/Icons/nodes-dark/plusminus/
    leo/Icons/nodes-dark/triangles/
    
The following settings specify the indicators.  You can use an absolute path, or more conveniently, a path relative either to:

- Your home directory or
- Leo's leo/Icons directory
</t>
<t tx="ekr.20180307015158.273">Must be relative to either the users home directory or leo/Icons directory.

url(/home/edward/leo.repo/leo-editor/leo/Icons/nodes-dark/triangles/closed.png)</t>
<t tx="ekr.20180307015158.274">url(/home/edward/leo.repo/leo-editor/leo/Icons/nodes-dark/triangles/open.png)</t>
<t tx="ekr.20180307015158.275"></t>
<t tx="ekr.20180307015158.276"></t>
<t tx="ekr.20180307015158.277"></t>
<t tx="ekr.20180307015158.278"></t>
<t tx="ekr.20180307015158.279">@language rest
@wrap

Note: Do not use @-constants here.</t>
<t tx="ekr.20180307015158.28"></t>
<t tx="ekr.20180307015158.280">The color of text in doc parts.

was firebrick3. now comment1_color
</t>
<t tx="ekr.20180307015158.281">The color of Leo keywords such as @ignore, @color, etc.

Was #00aa00.
Now solarized-blue
</t>
<t tx="ekr.20180307015158.282">Was blue, now solarized-blue
</t>
<t tx="ekr.20180307015158.283">The color of name in &lt; &lt; name &gt; &gt; when name is defined.

was red. Now comment1_color</t>
<t tx="ekr.20180307015158.284">The background color that represents spaces when Show Invisibles mode is in effect.

solarized-magenta</t>
<t tx="ekr.20180307015158.285">The foreground color that represents tabs when Show Invisibles mode is in effect.

gray80: #CCCCCC
gray90: #E5E5E5
</t>
<t tx="ekr.20180307015158.286">The color of name in &lt;&lt; name &gt;&gt; when name is undefined.

Was red. Now now comment1_color</t>
<t tx="ekr.20180307015158.287"></t>
<t tx="ekr.20180307015158.288">Note: Do not use @-constants here.</t>
<t tx="ekr.20180307015158.289">solarized-magenta
</t>
<t tx="ekr.20180307015158.29"></t>
<t tx="ekr.20180307015158.290"></t>
<t tx="ekr.20180307015158.291"></t>
<t tx="ekr.20180307015158.292"></t>
<t tx="ekr.20180307015158.293"></t>
<t tx="ekr.20180307015158.294"></t>
<t tx="ekr.20180307015158.295"></t>
<t tx="ekr.20180307015158.296"></t>
<t tx="ekr.20180307015158.297"></t>
<t tx="ekr.20180307015158.298">#00aa00 (Idle comment green)

</t>
<t tx="ekr.20180307015158.299"></t>
<t tx="ekr.20180307015158.30"></t>
<t tx="ekr.20180307015158.300"></t>
<t tx="ekr.20180307015158.301"></t>
<t tx="ekr.20180307015158.302"></t>
<t tx="ekr.20180307015158.303">base2     #eee8d5</t>
<t tx="ekr.20180307015158.304"></t>
<t tx="ekr.20180307015158.305"></t>
<t tx="ekr.20180307015158.306"></t>
<t tx="ekr.20180307015158.307"></t>
<t tx="ekr.20180307015158.308"></t>
<t tx="ekr.20180307015158.309">(some body text here so there's something to see)</t>
<t tx="ekr.20180307015158.31">Here you can edit the colors by Leo, just edit the
node headings, and click the reload-style button.
</t>
<t tx="ekr.20180307015158.310"></t>
<t tx="ekr.20180307015158.311"></t>
<t tx="ekr.20180307015158.312"></t>
<t tx="ekr.20180307015158.313">Name of the theme, used to find icon files</t>
<t tx="ekr.20180307015158.314">Set to true for dark themes, so bookmarks.py can generate
random background colors which are appropriate etc.</t>
<t tx="ekr.20180307015158.315">/*
@language css

old_themes.leo: qt-gui-user-style-sheet (linux ekr dark)
*/</t>
<t tx="ekr.20180307015158.316"></t>
<t tx="ekr.20180307015158.317">/* ===== active pane highlighting ===== */
QTextEdit#log-widget,
LeoQTreeWidget#treeWidget,
QTextEdit#richTextEdit { 
    border-color:   @focused-border-unfocus-color; 
    border-style:   @focused-border-style;
    border-width:   @focused-border-width; 
}

QTextEdit:focus#log-widget,
LeoQTreeWidget:focus#treeWidget,
QTextEdit:focus#richTextEdit { 
    border-color:   @focused-border-focus-color; 
}

QTextEdit:hover#log-widget,
LeoQTreeWidget:hover#treeWidget,
QTextEdit:hover#richTextEdit { 
  border-color:     @focused-border-hover-color; 
}
</t>
<t tx="ekr.20180307015158.318">/* ===== The body pane ===== */

QTextEdit#richTextEdit {
    background-color:           @test-background; /* @solarized-base03; */
    color:                      @text-foreground;
    font-family:                @font-family-body;
    font-size:                  @font-size-body;
    font-weight:                normal; /* normal,bold,100,..,900 */
    font-style:                 normal; /* normal,italic,oblique */
    selection-color:            @solarized-base03;
    selection-background-color: @solarized-yellow;
}</t>
<t tx="ekr.20180307015158.319">/* ===== bookmarks plugin styling ===== */

#show_bookmarks QPushButton { 
    margin: 0; padding: 1; border: none;
    font-size: @bookmarks_base_size;
    color: @bookmarks_base_color;
    font-weight: @bookmarks_base_weight;
    text-decoration: @bookmarks_base_decoration;
}
#show_bookmarks QPushButton[style_class~='bookmark_children'] {
    font-size: @bookmarks_children_size;
    color: @bookmarks_children_color;
    font-weight: @bookmarks_children_weight;
    text-decoration: @bookmarks_children_decoration;
}
#show_bookmarks QPushButton[style_class~='bookmark_expanded'] {
    font-size: @bookmarks_expanded_size;
    color: @bookmarks_expanded_color;
    font-weight: @bookmarks_expanded_weight;
    text-decoration: @bookmarks_expanded_decoration;
}
#show_bookmarks QPushButton[style_class~='bookmark_current'] {
    font-size: @bookmarks_current_size;
    color: @bookmarks_current_color;
    font-weight: @bookmarks_current_weight;
    text-decoration: @bookmarks_current_decoration;
}
</t>
<t tx="ekr.20180307015158.32"></t>
<t tx="ekr.20180307015158.320">/* ===== Buttons ===== */

QPushButton {
    background: @bg-gradient;
    color:      @text-foreground;
}
QPushButton:hover {
    background: @bg-gradient-hover;
    color:      @button-hover-fg;
}</t>
<t tx="ekr.20180307015158.321">/* ===== Log panes ===== */

QTextEdit#log-widget {
    background-color:           @log_text_background_color;
    color:                      @log_text_foreground_color;
    font-family:                @font-family-log;
    font-size:                  @font-size-log;
    font-style:                 normal; /* normal, italic,oblique */
    font-weight:                normal; /* normal,bold,100,..,900 */
    selection-background-color: blue;
    selection-color:            white;
}
</t>
<t tx="ekr.20180307015158.322">/* ===== Menues ===== */

QMenu {
    color:      @text-foreground-bright;
}
QMenu::item:selected {
    color:      @button-hover-fg;
    background: @bg-gradient-hover;
}

QMenuBar::item {
    color:      @text-foreground;
    background: @bg-gradient;
}
QMenuBar::item:selected {
    color:      @button-hover-fg;
    background: @bg-gradient-hover;
}
QMenuBar::item:pressed {
    color:      @text-foreground-bright;
    background: @bg-gradient;
}
</t>
<t tx="ekr.20180307015158.323">/* ===== Mini-buffer ===== */

QLineEdit#lineEdit {
    color:                      @minibuffer_foreground_color;
    background-color:           @minibuffer_background_color;
    font-family:                @font-family;
    font-size:                  @font-size;
    font-weight:                normal; /* normal,bold,100,..,900 */
    font-style:                 normal; /* normal,italic,oblique */
    selection-color:            red;
    selection-background-color: lightgrey;
}

QLabel#minibufferLabel {
    color:              @solarized-violet;
}
QLineEdit#lineEdit[style_class ~= 'minibuffer_warning'] {
    background-color:   @minibuffer_warning_color;
}
QLineEdit#lineEdit[style_class ~= 'minibuffer_error'] {
    color:              @minibuffer_error_color;
    background-color:   @minibuffer_warning_color;
}
</t>
<t tx="ekr.20180307015158.324">/* ===== Status line ===== */

QLineEdit#status1,
QLineEdit#status2 
{
    background-color:   @solarized-base03;
    border-color:       @solarized-base02;
    border-style:       solid;
    border-width:       1px;
}

</t>
<t tx="ekr.20180307015158.325">/* ===== Scroll bars ===== */

QScrollBar::horizontal {
     height: 7px;
}
QScrollBar::vertical {
     width: 7px;
}
QScrollBar::add-page,
QScrollBar::sub-page {
    background: @solarized-base03;
}
QScrollBar::handle { 
    background: @solarized-base01;
    color:      @solarized-base01;
}
QScrollBar::handle:hover { 
  background:   @solarized-base0;
  color:        @solarized-base0;
}
/* to make these show up, remove the ::handle style above... bug? */
QScrollBar::add-line,
QScrollBar::sub-line { 
  background:   @solarized-base01;
  color:        @solarized-base01;
}</t>
<t tx="ekr.20180307015158.326">/* ===== Splitters ===== */

QSplitter::handle {
    background-color: @splitter-bg;
}
QSplitter::handle:hover {
    background-color: @splitter-hover-bg;
}
</t>
<t tx="ekr.20180307015158.327">/* ===== Tab bar ===== */

QTabBar::tab { 
   margin-right:    5px;
   padding:         2px; 
}
QTabBar::tab {
    background:     @bg-gradient;
    color:          @text-foreground; 
    margin-right:   5px;
    padding:        2px; 
}
QTabBar::tab:selected {
    color:          @solarized-green;
}
QTabBar::tab:hover {
    background:     @bg-gradient-hover;
    color:          @button-hover-fg;
}</t>
<t tx="ekr.20180307015158.328">/* ===== Tree Widgets ===== */

QTreeWidget {
    /* These apply to the selected item, but not to editing items.*/
    font-family:    @font-family-tree;
    font-size:      @font-size-tree;
    font-weight:    normal; /* normal,bold,100,..,900 */
    font-style:     normal; /* normal, italic,oblique */
}
QTreeWidget QLineEdit {
    /* Headline edit widgets */
    font-family:    @font-family-tree;
    font-size:      @font-size-tree;
    font-weight:    normal; /* normal,bold,100,..,900 */
    font-style:     normal; /* normal, italic,oblique */ 
}
QTreeWidget::selected {
    background:     @solarized-green;
    color:          @solarized-base03; 
}
QTreeWidget::active:selected {
    background:     @solarized-yellow;
    color:          @solarized-base03; 
}

/* ===== Tree Views ===== */

QTreeView {
    /* These apply to the selected item, but not to editing items.*/
    background-color:           @solarized-base03;
    color:                      @solarized-base0;
    selection-color:            @solarized-orange;
    selection-background-color: @solarized-base03;
    show-decoration-selected:   0;
}
QTreeView::item:selected {
    background:                 @solarized-green;
    color:                      @solarized-base03; 
}
QTreeView::item:active:selected {
    background:                 @solarized-yellow;
    color:                      @solarized-base03; 
}
QTreeView QLineEdit {
    /* Headline edit widgets */
    color:                      @solarized-base03;
    background-color:           @solarized-yellow;
    selection-color:            @solarized-base3;
    selection-background-color: @solarized-blue;  
}
QTreeView::branch:closed:has-children{
    image: @tree-image-closed;
}
QTreeView::branch:open:has-children{
    image: @tree-image-open;
}
</t>
<t tx="ekr.20180307015158.329">/* ===== widgets ===== */

QLabel {
    color: @solarized-base1;
}
QLineEdit {
    border:     none;
    padding:    3px;
}
QPushButton, QDoubleSpinBox, QSpinBox, QDateEdit, QTimeEdit {
    border:         none;
    margin-right:   5px;
    padding:        3px;
}
QWidget {
    background-color:   @solarized-base03; 
    border-color:       @solarized-base1; 
    color:              @solarized-base1;
    font-size:          @font-size;
}
QWidget#body-text-renderer {
    background-color:   white;
    color:              black;
}
</t>
<t tx="ekr.20180307015158.33"></t>
<t tx="ekr.20180307015158.330">/* ===== Overrides of previous settings ===== */

QTreeWidget {
    font-size:                  14pt;
    background:                 @solarized-base02;
}
QTreeWidget QLineEdit {
    /* Editing */
    font-size:                  14pt;
    background:                 @solarized-base1;
    selection-color:            @solarized-base1;
    selection-background-color: @solarized-blue;
}
QTreeWidget::selected,
QTreeWidget::active:selected,
QTreeView::item:selected,
QTreeView::item:active:selected {
    background: @solarized-base01; /* one step darker than backround */
}
</t>
<t tx="ekr.20180307015158.331">@language rest
@wrap

The differences between these themes are not confined to "zz" nodes, as is true of most of the other themes in this file. As a result, it is difficult to understand the differences between them.

No further work is planned on these themes.</t>
<t tx="ekr.20180307015158.332">Solarized" dark theme.

</t>
<t tx="ekr.20180307015158.333"></t>
<t tx="ekr.20180307015158.334"></t>
<t tx="ekr.20180307015158.335"></t>
<t tx="ekr.20180307015158.336"></t>
<t tx="ekr.20180307015158.337"></t>
<t tx="ekr.20180307015158.338">Was cyan</t>
<t tx="ekr.20180307015158.339"></t>
<t tx="ekr.20180307015158.34">Color for error messages written to the log window.</t>
<t tx="ekr.20180307015158.340"></t>
<t tx="ekr.20180307015158.341">Here you can edit the colors by Leo, just edit the
node headings, and click the reload-style button.
</t>
<t tx="ekr.20180307015158.342"></t>
<t tx="ekr.20180307015158.343"></t>
<t tx="ekr.20180307015158.344">Color for error messages written to the log window.</t>
<t tx="ekr.20180307015158.345">Background color of log text.</t>
<t tx="ekr.20180307015158.346">Foreground color of log text.

</t>
<t tx="ekr.20180307015158.347"></t>
<t tx="ekr.20180307015158.348"></t>
<t tx="ekr.20180307015158.349"></t>
<t tx="ekr.20180307015158.35">Background color of log text.</t>
<t tx="ekr.20180307015158.350"></t>
<t tx="ekr.20180307015158.351"></t>
<t tx="ekr.20180307015158.352"></t>
<t tx="ekr.20180307015158.353"></t>
<t tx="ekr.20180307015158.354"></t>
<t tx="ekr.20180307015158.355"></t>
<t tx="ekr.20180307015158.356"></t>
<t tx="ekr.20180307015158.357"></t>
<t tx="ekr.20180307015158.358"></t>
<t tx="ekr.20180307015158.359">test text</t>
<t tx="ekr.20180307015158.36">Foreground color of log text.

</t>
<t tx="ekr.20180307015158.360">test text</t>
<t tx="ekr.20180307015158.361"></t>
<t tx="ekr.20180307015158.362"></t>
<t tx="ekr.20180307015158.363"></t>
<t tx="ekr.20180307015158.364">(some body text here so there's something to see)</t>
<t tx="ekr.20180307015158.365"></t>
<t tx="ekr.20180307015158.366"></t>
<t tx="ekr.20180307015158.367"></t>
<t tx="ekr.20180307015158.368"></t>
<t tx="ekr.20180307015158.369"></t>
<t tx="ekr.20180307015158.37"></t>
<t tx="ekr.20180307015158.370">Outline indicators indicate the expansion state of outline nodes. The leo/Icons/nodes-dark folders contains two sets of indicators::
    
    leo/Icons/nodes-dark/plusminus/
    leo/Icons/nodes-dark/triangles/
    
The following settings specify the indicators.  You can use an absolute path, or more conveniently, a path relative either to:

- Your home directory or
- Leo's leo/Icons directory
</t>
<t tx="ekr.20180307015158.371">Must be relative to either the users home directory or leo/Icons directory.

url(/home/edward/leo.repo/leo-editor/leo/Icons/nodes-dark/triangles/closed.png)</t>
<t tx="ekr.20180307015158.372">url(/home/edward/leo.repo/leo-editor/leo/Icons/nodes-dark/triangles/open.png)</t>
<t tx="ekr.20180307015158.373"></t>
<t tx="ekr.20180307015158.374"></t>
<t tx="ekr.20180307015158.375"></t>
<t tx="ekr.20180307015158.38"></t>
<t tx="ekr.20180307015158.39"></t>
<t tx="ekr.20180307015158.40"></t>
<t tx="ekr.20180307015158.404"></t>
<t tx="ekr.20180307015158.405">Name of the theme, used to find icon files</t>
<t tx="ekr.20180307015158.406">Set to true for dark themes, so bookmarks.py can generate
random background colors which are appropriate etc.</t>
<t tx="ekr.20180307015158.407">/*
@language css

old_themes.leo: qt-gui-user-style-sheet (leo_dark theme 0)
*/</t>
<t tx="ekr.20180307015158.408">/* ===== active pane highlighting ===== */
QTextEdit#log-widget,
LeoQTreeWidget#treeWidget,
QTextEdit#richTextEdit { 
    border-color:   @focused-border-unfocus-color; 
    border-style:   @focused-border-style;
    border-width:   @focused-border-width; 
}

QTextEdit:focus#log-widget,
LeoQTreeWidget:focus#treeWidget,
QTextEdit:focus#richTextEdit { 
    border-color:   @focused-border-focus-color; 
}

QTextEdit:hover#log-widget,
LeoQTreeWidget:hover#treeWidget,
QTextEdit:hover#richTextEdit { 
    border-color:   @focused-border-hover-color; 
}
</t>
<t tx="ekr.20180307015158.409">/* ===== The body pane ===== */
QTextEdit#richTextEdit {
    background-color:           @solarized-base03;
    color:                      @text-foreground;
    font-family:                @font-family-body;
    font-size:                  @font-size-body;
    font-weight:                normal; /* normal,bold,100,..,900 */
    font-style:                 normal; /* normal,italic,oblique */
    selection-color:            @solarized-base03;
    selection-background-color: @solarized-yellow;
}
</t>
<t tx="ekr.20180307015158.41"></t>
<t tx="ekr.20180307015158.410">/* ===== bookmarks plugin styling ===== */
#show_bookmarks QPushButton { 
    margin: 0; padding: 1; border: none;
    font-size: @bookmarks_base_size;
    color: @bookmarks_base_color;
    font-weight: @bookmarks_base_weight;
    text-decoration: @bookmarks_base_decoration;
}
#show_bookmarks QPushButton[style_class~='bookmark_children'] {
    font-size: @bookmarks_children_size;
    color: @bookmarks_children_color;
    font-weight: @bookmarks_children_weight;
    text-decoration: @bookmarks_children_decoration;
}
#show_bookmarks QPushButton[style_class~='bookmark_expanded'] {
    font-size: @bookmarks_expanded_size;
    color: @bookmarks_expanded_color;
    font-weight: @bookmarks_expanded_weight;
    text-decoration: @bookmarks_expanded_decoration;
}
#show_bookmarks QPushButton[style_class~='bookmark_current'] {
    font-size: @bookmarks_current_size;
    color: @bookmarks_current_color;
    font-weight: @bookmarks_current_weight;
    text-decoration: @bookmarks_current_decoration;
}
</t>
<t tx="ekr.20180307015158.411">/* ===== Buttons ===== */

QPushButton {
    background: @bg-gradient;
    color:      @text-foreground;
}

QPushButton:hover {
    background: @bg-gradient-hover;
    color:      @button-hover-fg;
}</t>
<t tx="ekr.20180307015158.412">/* ===== Log panes ===== */

QTextEdit#log-widget {
    background-color:           @log_text_background_color;
    color:                      @log_text_foreground_color;
    font-family:                @font-family-log;
    font-size:                  @font-size-log;
    font-style:                 normal; /* normal, italic,oblique */
    font-weight:                normal; /* normal,bold,100,..,900 */
    selection-background-color: blue;
    selection-color:            white;
}
</t>
<t tx="ekr.20180307015158.413">/* ===== Menues ===== */

QMenu {
    color:      @text-foreground-bright;
}
QMenu::item:selected {
    color:      @button-hover-fg;
    background: @bg-gradient-hover;
}

QMenuBar::item {
    color:      @text-foreground;
    background: @bg-gradient;
}
QMenuBar::item:selected {
    color:      @button-hover-fg;
    background: @bg-gradient-hover;
}
QMenuBar::item:pressed {
    color:      @text-foreground-bright;
    background: @bg-gradient;
}
</t>
<t tx="ekr.20180307015158.414">/* ===== Mini-buffer ===== */

QLineEdit#lineEdit {
    color:                      @minibuffer_foreground_color;
    background-color:           @minibuffer_background_color;
    font-family:                @font-family;
    font-size:                  @font-size;
    font-weight:                normal; /* normal,bold,100,..,900 */
    font-style:                 normal; /* normal,italic,oblique */
    selection-color:            red;
    selection-background-color: lightgrey;
}
QLabel#minibufferLabel {
    color:              @solarized-violet;
}
QLineEdit#lineEdit[style_class ~= 'minibuffer_warning'] {
    background-color:   @minibuffer_warning_color;
}
QLineEdit#lineEdit[style_class ~= 'minibuffer_error'] {
    color:              @minibuffer_error_color;
    background-color:   @minibuffer_warning_color;
}
</t>
<t tx="ekr.20180307015158.415">/* ===== Status line ===== */

QLineEdit#status1,
QLineEdit#status2 {
    background-color:   @solarized-base03;
    border-color:       @solarized-base02;
    border-style:       solid;
    border-width:       1px;
}

</t>
<t tx="ekr.20180307015158.416">/* ===== Scroll bars ===== */

QScrollBar::horizontal {
     height: 7px;
}
QScrollBar::vertical {
     width: 7px;
}
QScrollBar::add-page, QScrollBar::sub-page {
    background: @solarized-base03;
}
QScrollBar::handle { 
    background: @solarized-base01;
    color:      @solarized-base01;
}
QScrollBar::handle:hover { 
  background:   @solarized-base0;
  color:        @solarized-base0;
}
/* to make these show up, remove the ::handle style above... bug? */
QScrollBar::add-line, QScrollBar::sub-line { 
  background:   @solarized-base01;
  color:        @solarized-base01;
}</t>
<t tx="ekr.20180307015158.417">/* ===== Splitters ===== */

QSplitter::handle {
    background-color: @splitter-bg;
}
QSplitter::handle:hover {
    background-color: @splitter-hover-bg;
}
</t>
<t tx="ekr.20180307015158.418">/* ===== Tab bar ===== */

QTabBar::tab { 
   margin-right:    5px;
   padding:         2px; 
}
QTabBar::tab {
    background:     @bg-gradient;
    color:          @text-foreground; 
    margin-right:   5px;
    padding:        2px; 
}
QTabBar::tab:selected {
    color:          @solarized-green;
}
QTabBar::tab:hover {
    background:     @bg-gradient-hover;
    color:          @button-hover-fg;
}</t>
<t tx="ekr.20180307015158.419">/* ===== Tree Widgets ===== */

QTreeWidget {
    /* Selected items, but NOT editing items.*/
    font-family:    @font-family-tree;
    font-size:      @font-size-tree;
    font-weight:    normal; /* normal,bold,100,..,900 */
    font-style:     normal; /* normal, italic,oblique */
}
QTreeWidget QLineEdit {
    /* Headline edit widgets */
    font-family:    @font-family-tree;
    font-size:      @font-size-tree;
    font-weight:    normal; /* normal,bold,100,..,900 */
    font-style:     normal; /* normal, italic,oblique */ 
}
QTreeWidget::selected {
    background:     @solarized-green;
    color:          @solarized-base03; 
}
QTreeWidget::active:selected {
    background:     @solarized-yellow;
    color:          @solarized-base03; 
}

/* ===== Tree Views ===== */

QTreeView {
    /* These apply to the selected item, but not to editing items.*/
    background-color:           @solarized-base03;
    color:                      @solarized-base0;
    selection-color:            @solarized-orange;
    selection-background-color: @solarized-base03;
    show-decoration-selected:   0;
}
QTreeView::item:selected {
    background:                 @solarized-green;
    color:                      @solarized-base03; 
}
QTreeView::item:active:selected {
    background:                 @solarized-yellow;
    color:                      @solarized-base03; 
}
QTreeView QLineEdit {
    /* Headline edit widgets */
    color:                      @solarized-base03;
    background-color:           @solarized-yellow;
    selection-color:            @solarized-base3;
    selection-background-color: @solarized-blue;  
}
QTreeView::branch:closed:has-children{
    image:                      @tree-image-closed;
}
QTreeView::branch:open:has-children{
    image:                      @tree-image-open;
}
</t>
<t tx="ekr.20180307015158.42"></t>
<t tx="ekr.20180307015158.420">/* ===== widgets ===== */

QLabel {
    color:          @solarized-base1;
}
QLineEdit {
    border:         none;
    padding:        3px;
}
QPushButton, QDoubleSpinBox, QSpinBox, QDateEdit, QTimeEdit {
    border:         none;
    margin-right:   5px;
    padding:        3px;
}
QWidget {
    background-color:   @solarized-base03; 
    border-color:       @solarized-base1; 
    color:              @solarized-base1;
    font-size:          16px;
}
QWidget#body-text-renderer {
    background-color:   white;
    color:              black;
}
</t>
<t tx="ekr.20180307015158.421">Sublime Text 2-like dark theme.
</t>
<t tx="ekr.20180307015158.422"></t>
<t tx="ekr.20180307015158.423"></t>
<t tx="ekr.20180307015158.424"></t>
<t tx="ekr.20180307015158.425"></t>
<t tx="ekr.20180307015158.426"></t>
<t tx="ekr.20180307015158.427">Was cyan</t>
<t tx="ekr.20180307015158.428"></t>
<t tx="ekr.20180307015158.429"></t>
<t tx="ekr.20180307015158.43"></t>
<t tx="ekr.20180307015158.430"></t>
<t tx="ekr.20180307015158.431"></t>
<t tx="ekr.20180307015158.432">Background color of body text.  This setting *is* used in the QtGui.

#ffecea

Note: this setting can be overridden by the x_mode_bg_color settings.</t>
<t tx="ekr.20180307015158.433">#f9f0f4 light pink
#fbfdfd very light blue

For some reason, colors in the text widget do not match the colors in the canvas widget.</t>
<t tx="ekr.20180307015158.434"></t>
<t tx="ekr.20180307015158.435">Foreground color of body text.  This setting *is* used in the QtGui.

Note: this setting can be overridden by the x_mode_fg_color settings.</t>
<t tx="ekr.20180307015158.436">Overrides body_text_background_color.

#fdf5f5 A light pink.
#f0fde1 A light green.
#f9e6dd A light orange.</t>
<t tx="ekr.20180307015158.437">Overrides body_text_foreground_color.</t>
<t tx="ekr.20180307015158.438"></t>
<t tx="ekr.20180307015158.439">Color for error messages written to the log window.</t>
<t tx="ekr.20180307015158.44"></t>
<t tx="ekr.20180307015158.440"></t>
<t tx="ekr.20180307015158.441">Foreground color of log text.

</t>
<t tx="ekr.20180307015158.442">Background color of log text.</t>
<t tx="ekr.20180307015158.443">LightYellow1

#f2fdff</t>
<t tx="ekr.20180307015158.444">#d6c7d3
#d2cad0
#c6d3d7</t>
<t tx="ekr.20180307015158.445">#d6c7d3
#d2cad0
#c6d3d7
#ffffec # Same as outline.</t>
<t tx="ekr.20180307015158.446"></t>
<t tx="ekr.20180307015158.447"></t>
<t tx="ekr.20180307015158.448"></t>
<t tx="ekr.20180307015158.449"></t>
<t tx="ekr.20180307015158.45">@solarized-base02</t>
<t tx="ekr.20180307015158.450">Background color of unselected headline text.

LavenderBlush1</t>
<t tx="ekr.20180307015158.451">Foreground color of unselected headline text.</t>
<t tx="ekr.20180307015158.452">Background color of selected headline text that is not being edited.

LavenderBlush2</t>
<t tx="ekr.20180307015158.453">Foreground color of selected headline text that is not being edited.

DodgerBlue4</t>
<t tx="ekr.20180307015158.454">Background color of unselected headline text in a headline that is being edited.

Foreground color must also be specified for either setting to take effect.</t>
<t tx="ekr.20180307015158.455">Foreground color of unselected headline text in a headline that is being edited.

Background color must also be specified for either setting to take effect.</t>
<t tx="ekr.20180307015158.456">Foreground color of selected text headline text in a headline that is being edited.

Background must also be specified for either setting to take effect.</t>
<t tx="ekr.20180307015158.457">Background color of selected text headline text in a headline that is being edited.

Foreground must also be specified for either setting to take effect.</t>
<t tx="ekr.20180307015158.458">Background color of outline pane itself.

LavenderBlush1
#ffffe1 # a little too yellow.
#ffffec
LightSteelBlue1 # Good for testing.</t>
<t tx="ekr.20180307015158.459">Outline indicators indicate the expansion state of outline nodes. The leo/Icons/nodes-dark folders contains two sets of indicators::
    
    leo/Icons/nodes-dark/plusminus/
    leo/Icons/nodes-dark/triangles/
    
The following settings specify the indicators.  You can use an absolute path, or more conveniently, a path relative either to:

- Your home directory or
- Leo's leo/Icons directory
</t>
<t tx="ekr.20180307015158.46"></t>
<t tx="ekr.20180307015158.460">Must be relative to either the users home directory or leo/Icons directory.

url(/home/edward/leo.repo/leo-editor/leo/Icons/nodes-dark/triangles/closed.png)</t>
<t tx="ekr.20180307015158.461">url(/home/edward/leo.repo/leo-editor/leo/Icons/nodes-dark/triangles/open.png)</t>
<t tx="ekr.20180307015158.462"></t>
<t tx="ekr.20180307015158.463"></t>
<t tx="ekr.20180307015158.464"></t>
<t tx="ekr.20180307015158.47"></t>
<t tx="ekr.20180307015158.48"></t>
<t tx="ekr.20180307015158.49">test text</t>
<t tx="ekr.20180307015158.493"></t>
<t tx="ekr.20180307015158.494"></t>
<t tx="ekr.20180307015158.495"></t>
<t tx="ekr.20180307015158.496">/*
@language css

old_themes.leo: qt-gui-user-style-sheet (leo_dark theme 1)
*/</t>
<t tx="ekr.20180307015158.497">/* ===== Body pane ===== */

QTextEdit#richTextEdit {
    background-color:           @solarized-base03;
    color:                      @bodytextforegroundcolor;
    selection-color:            @solarized-base03;
    selection-background-color: @solarized-yellow;
    font-family:                @font-family-body;
    font-size:                  @font-size-body;
    font-style:                 normal; /* normal,italic,oblique */
    font-weight:                normal; /* normal,bold,100,..,900 */
}
</t>
<t tx="ekr.20180307015158.498">QPushButton {
    background: @bg-gradient;
    color:      @text-foreground;
}
QPushButton:hover {
    background: @bg-gradient-hover;
    color:      @button-hover-fg;
}
</t>
<t tx="ekr.20180307015158.499">/* ===== The log panes ===== */

QTextEdit#log-widget {
    background-color:           @solarized-base02;
    color:                      @solarized-base0;
    font-family:                @font-family-log;
    font-size:                  16px;
    font-weight:                normal; /* normal,bold,100,..,900 */
    font-style:                 normal; /* normal, italic,oblique */
    selection-color:            white;
    selection-background-color: blue;
}
</t>
<t tx="ekr.20180307015158.50">test text</t>
<t tx="ekr.20180307015158.500">/* ===== Menus ===== */

QMenu {
    color:      @text-foreground-bright;
}
QMenu::item:selected {
    color:      @button-hover-fg;
    background: @bg-gradient-hover;
}

QMenuBar::item:hover {
    background: white;
    color:      red;
}
QMenuBar::item {
    background: @bg-gradient;
    color:      @text-foreground;
}
QMenuBar::item:pressed {
    background: @bg-gradient;
    color:      @text-foreground-bright;
}
</t>
<t tx="ekr.20180307015158.501">/* ===== The mini-buffer ===== */
QLineEdit#lineEdit {
    background-color:           @solarized-base03;
    color:                      red; 
    font-family:                @font-family;
    font-size:                  @font-size;
    font-weight:                normal; /* normal,bold,100,..,900 */
    font-style:                 normal; /* normal,italic,oblique */
    selection-color:            red;
    selection-background-color: lightgrey;
}

QLabel#minibufferLabel {
    color: @solarized-violet;
}
</t>
<t tx="ekr.20180307015158.502">QScrollBar::horizontal {
    height: 7px;
}
QScrollBar::vertical {
    width: 7px;
}
QScrollBar::add-page, QScrollBar::sub-page {
    background: @solarized-base03;
}
QScrollBar::handle { 
    background: @solarized-base01;
    color:      @solarized-base01;
}
QScrollBar::handle:hover { 
    background: @solarized-base0;
    color:      @solarized-base0;
}
/* to make these show up, remove the ::handle style above... bug? */
QScrollBar::add-line, QScrollBar::sub-line { 
    background: @solarized-base01;
    color:      @solarized-base01;
}
</t>
<t tx="ekr.20180307015158.503">/* ===== Splitters ===== */

QSplitter::handle {
    background-color: @splitter-bg;
}
QSplitter::handle:hover {
    background-color: @splitter-hover-bg;
}
</t>
<t tx="ekr.20180307015158.504">/* ===== Status line ===== */

QLineEdit#status1, QLineEdit#status2 {
    background-color:   @solarized-base03;
    border-color:       @solarized-base02;
    border-style:       solid;
    border-width:       1px;
}
</t>
<t tx="ekr.20180307015158.505">/* ===== Tab bar ===== */

QTabBar::tab {
    color:          @text-foreground; 
    background:     @bg-gradient;
    margin-right:   5px;
    padding:        2px; 
}
QTabBar::tab:selected {
    color:          @solarized-green;
} 
QTabBar::tab:hover {
    background:     @bg-gradient-hover;
    color:          @button-hover-fg;
}</t>
<t tx="ekr.20180307015158.506">/* ===== Tree Widgets ===== */

QTreeWidget {
    /* Selected items, but NOT edit items.*/
    font-family:    @font-family-tree;
    font-size:      16px;
    font-weight:    normal; /* normal,bold,100,..,900 */
    font-style:     normal; /* normal, italic,oblique */
}
QTreeWidget QLineEdit View{
    /* Headline edit widgets */
    font-family:    @font-family-tree;
    font-size:      16px;
    font-weight:    normal; /* normal,bold,100,..,900 */
    font-style:     normal; /* normal, italic,oblique */ 
}
QTreeWidget::selected {
    background:     @solarized-green;
    color:          @solarized-base03; 
}
QTreeWidget::active:selected {
    background:     @solarized-yellow;
    color:          @solarized-base03; 
}

/* ===== Tree Views ===== */

QTreeView {
    /* Selected items, but NOT edit items.*/
    background-color:           @solarized-base03;
    color:                      @solarized-base0;
    selection-color:            @solarized-orange;
    selection-background-color: @solarized-base03;
    show-decoration-selected:   0;
}
QTreeView QLineEdit {
    /* Headline edit widgets */
    color:                      @solarized-base03;
    background-color:           @solarized-yellow;
    selection-color:            @solarized-base3;
    selection-background-color: @solarized-blue;  
}
QTreeView::item:selected {
    background:                 @solarized-green;
    color:                      @solarized-base03; 
}
QTreeView::item:active:selected {
    background:                 @solarized-yellow;
    color:                      @solarized-base03; 
}
QTreeView::branch:closed:has-children{
    image:                      @tree-image-closed;
}
QTreeView::branch:open:has-children{
    image:                      @tree-image-open;
}
</t>
<t tx="ekr.20180307015158.507">/* ===== Widgets ===== */

QWidget {
    color:              @solarized-base1;
    background-color:   @solarized-base03; 
    border-color:       @solarized-base1;
    font-size:          16px;
}
QLabel {
    color:              @solarized-base1;
}
QLineEdit {
    border:         none;
    padding:        3px;
}
QPushButton, QDoubleSpinBox, QSpinBox, QDateEdit, QTimeEdit {
    border:         none;
    margin-right:   5px;
    padding:        3px;
}
</t>
<t tx="ekr.20180307015158.508">Sublime Text 2-like dark theme.

This is like leo_dark_1, but more appealing on Mac
</t>
<t tx="ekr.20180307015158.509"></t>
<t tx="ekr.20180307015158.51"></t>
<t tx="ekr.20180307015158.510"></t>
<t tx="ekr.20180307015158.511"></t>
<t tx="ekr.20180307015158.512"></t>
<t tx="ekr.20180307015158.513"></t>
<t tx="ekr.20180307015158.514">Was cyan</t>
<t tx="ekr.20180307015158.515"></t>
<t tx="ekr.20180307015158.516"></t>
<t tx="ekr.20180307015158.517"></t>
<t tx="ekr.20180307015158.518"></t>
<t tx="ekr.20180307015158.519">Background color of body text.  This setting *is* used in the QtGui.

#ffecea

Note: this setting can be overridden by the x_mode_bg_color settings.</t>
<t tx="ekr.20180307015158.52"></t>
<t tx="ekr.20180307015158.520">#f9f0f4 light pink
#fbfdfd very light blue

For some reason, colors in the text widget do not match the colors in the canvas widget.</t>
<t tx="ekr.20180307015158.521"></t>
<t tx="ekr.20180307015158.522">Foreground color of body text.  This setting *is* used in the QtGui.

Note: this setting can be overridden by the x_mode_fg_color settings.</t>
<t tx="ekr.20180307015158.523">Overrides body_text_background_color.

#fdf5f5 A light pink.
#f0fde1 A light green.
#f9e6dd A light orange.</t>
<t tx="ekr.20180307015158.524">Overrides body_text_foreground_color.</t>
<t tx="ekr.20180307015158.525"></t>
<t tx="ekr.20180307015158.526">Color for error messages written to the log window.</t>
<t tx="ekr.20180307015158.527"></t>
<t tx="ekr.20180307015158.528">Foreground color of log text.

</t>
<t tx="ekr.20180307015158.529">Background color of log text.</t>
<t tx="ekr.20180307015158.53"></t>
<t tx="ekr.20180307015158.530">LightYellow1

#f2fdff</t>
<t tx="ekr.20180307015158.531">#d6c7d3
#d2cad0
#c6d3d7</t>
<t tx="ekr.20180307015158.532">#d6c7d3
#d2cad0
#c6d3d7
#ffffec # Same as outline.</t>
<t tx="ekr.20180307015158.533"></t>
<t tx="ekr.20180307015158.534"></t>
<t tx="ekr.20180307015158.535"></t>
<t tx="ekr.20180307015158.536">Outline indicators indicate the expansion state of outline nodes. The leo/Icons/nodes-dark folders contains two sets of indicators::
    
    leo/Icons/nodes-dark/plusminus/
    leo/Icons/nodes-dark/triangles/
    
The following settings specify the indicators.  You can use an absolute path, or more conveniently, a path relative either to:

- Your home directory or
- Leo's leo/Icons directory
</t>
<t tx="ekr.20180307015158.537">Must be relative to either the users home directory or leo/Icons directory.

url(/home/edward/leo.repo/leo-editor/leo/Icons/nodes-dark/triangles/closed.png)</t>
<t tx="ekr.20180307015158.538">url(/home/edward/leo.repo/leo-editor/leo/Icons/nodes-dark/triangles/open.png)</t>
<t tx="ekr.20180307015158.539"></t>
<t tx="ekr.20180307015158.54"></t>
<t tx="ekr.20180307015158.540">Background color of unselected headline text.

LavenderBlush1</t>
<t tx="ekr.20180307015158.541">Foreground color of unselected headline text.</t>
<t tx="ekr.20180307015158.542">Background color of selected headline text that is not being edited.

LavenderBlush2</t>
<t tx="ekr.20180307015158.543">Foreground color of selected headline text that is not being edited.

DodgerBlue4</t>
<t tx="ekr.20180307015158.544">Background color of unselected headline text in a headline that is being edited.

Foreground color must also be specified for either setting to take effect.</t>
<t tx="ekr.20180307015158.545">Foreground color of unselected headline text in a headline that is being edited.

Background color must also be specified for either setting to take effect.</t>
<t tx="ekr.20180307015158.546">Foreground color of selected text headline text in a headline that is being edited.

Background must also be specified for either setting to take effect.</t>
<t tx="ekr.20180307015158.547">Background color of selected text headline text in a headline that is being edited.

Foreground must also be specified for either setting to take effect.</t>
<t tx="ekr.20180307015158.548">Background color of outline pane itself.

LavenderBlush1
#ffffe1 # a little too yellow.
#ffffec
LightSteelBlue1 # Good for testing.</t>
<t tx="ekr.20180307015158.549"></t>
<t tx="ekr.20180307015158.55">(some body text here so there's something to see)</t>
<t tx="ekr.20180307015158.550"></t>
<t tx="ekr.20180307015158.551"></t>
<t tx="ekr.20180307015158.552"># All colors are solarized colors, except for 'red', 'white', etc.</t>
<t tx="ekr.20180307015158.553">@language rest
@wrap

Note: Do not use @-constants here.</t>
<t tx="ekr.20180307015158.554">solarized-magenta</t>
<t tx="ekr.20180307015158.555">solarized-blue
</t>
<t tx="ekr.20180307015158.556">solarized-blue
</t>
<t tx="ekr.20180307015158.557">solarized-magenta</t>
<t tx="ekr.20180307015158.558">solarized-magenta</t>
<t tx="ekr.20180307015158.559"></t>
<t tx="ekr.20180307015158.56"></t>
<t tx="ekr.20180307015158.560">solarized-magenta</t>
<t tx="ekr.20180307015158.561">Solarized violet
</t>
<t tx="ekr.20180307015158.562">Note: Do not use @-constants here.</t>
<t tx="ekr.20180307015158.563">solarized-magenta
</t>
<t tx="ekr.20180307015158.564">solarized-magenta</t>
<t tx="ekr.20180307015158.565">solarized-magenta</t>
<t tx="ekr.20180307015158.566">solarized-magenta</t>
<t tx="ekr.20180307015158.567">solarized-magenta</t>
<t tx="ekr.20180307015158.568">solarized-blue
</t>
<t tx="ekr.20180307015158.569">solarized-blue
</t>
<t tx="ekr.20180307015158.57"></t>
<t tx="ekr.20180307015158.570">solarized-blue
</t>
<t tx="ekr.20180307015158.571">solarized-blue
</t>
<t tx="ekr.20180307015158.572">solarized-cyan</t>
<t tx="ekr.20180307015158.573">solarized-cyan</t>
<t tx="ekr.20180307015158.574">solarized-cyan</t>
<t tx="ekr.20180307015158.575">solarized-cyan</t>
<t tx="ekr.20180307015158.576">solarized-base2
</t>
<t tx="ekr.20180307015158.577">solarized-base2
</t>
<t tx="ekr.20180307015158.578"></t>
<t tx="ekr.20180307015158.579"></t>
<t tx="ekr.20180307015158.58"></t>
<t tx="ekr.20180307015158.580"></t>
<t tx="ekr.20180307015158.581"></t>
<t tx="ekr.20180307015158.582"></t>
<t tx="ekr.20180307015158.583">/*
@language css

old_themes.leo: qt-gui-user-style-sheet (leo_dark theme 2)
*/</t>
<t tx="ekr.20180307015158.584">/* ===== Body Editor ===== */

QTextEdit#richTextEdit {
    background-color:           @solarized-base03;
    color:                      @bodytextforegroundcolor;
    font-family:                @font-family-body;
    font-size:                  @font-size-body;
    font-weight:                normal; /* normal,bold,100,..,900 */
    font-style:                 normal; /* normal,italic,oblique */
    selection-color:            @solarized-base03;
    selection-background-color: @solarized-yellow;
}
</t>
<t tx="ekr.20180307015158.585">/* ===== Log panes ===== */

QTextEdit#log-widget {
    background-color:           @solarized-base02;
    color:                      @solarized-base0;
    font-family:                @font-family-log;
    font-size:                  @font-size-other;
    font-weight:                normal; /* normal,bold,100,..,900 */
    font-style:                 normal; /* normal, italic,oblique */
    selection-color:            white;
    selection-background-color: blue;
}
</t>
<t tx="ekr.20180307015158.586">/* ===== Menus ===== */

QMenu {
    color:      @text-foreground-bright;
}
QMenu::item:selected {
    color:      @button-hover-fg;
    background: @bg-gradient-hover;
}

QMenuBar::item:hover {
    background: white;
    color:      red;
}
QMenuBar::item {
    background: @bg-gradient;
    color:      @text-foreground;
}
QMenuBar::item:pressed {
    background: @bg-gradient;
    color:      @text-foreground-bright;
}
</t>
<t tx="ekr.20180307015158.587">/* ===== The mini-buffer ===== */

QLineEdit#lineEdit {
    background-color:           @solarized-base03;
    color:                      red; 
    font-family:                @font-family;
    font-size:                  @font-size;
    font-weight:                normal; /* normal,bold,100,..,900 */
    font-style:                 normal; /* normal,italic,oblique */
    selection-color:            red;
    selection-background-color: lightgrey;
}

QLabel#minibufferLabel {
    color:                      @solarized-violet;
}
</t>
<t tx="ekr.20180307015158.588">/* ===== Scroll bars ===== */

QScrollBar::horizontal {
    height: 7px;
}
QScrollBar::vertical {
    width: 7px;
}
QScrollBar::add-page,
QScrollBar::sub-page {
    background:     @solarized-base03;
}
QScrollBar::handle { 
    background:     @solarized-base01;
    color:          @solarized-base01;
}
QScrollBar::handle:hover { 
    background:     @solarized-base0;
    color:          @solarized-base0;
}
/* to make these show up, remove the ::handle style above... bug? */
QScrollBar::add-line,
QScrollBar::sub-line { 
    background:     @solarized-base01;
    color:          @solarized-base01;
}
</t>
<t tx="ekr.20180307015158.589">/* ===== Splitters ===== */

QSplitter::handle {
    background-color: @splitter-bg;
}
QSplitter::handle:hover {
    background-color: @splitter-hover-bg;
}
</t>
<t tx="ekr.20180307015158.59"></t>
<t tx="ekr.20180307015158.590">QLineEdit#status1,
QLineEdit#status2 {
    background-color:   @solarized-base03;
    border-color:       @solarized-base02;
    border-style:       solid;
    border-width:       1px;
}
</t>
<t tx="ekr.20180307015158.591">/* ===== Tab bar ===== */

QTabBar::tab { 
    margin-right:   5px;
    padding:        2px; 
}
QTabBar::tab {
    color:          @text-foreground; 
    background:     @bg-gradient;
    margin-right:   5px;
    padding:        2px; 
}
QTabBar::tab:selected {
    color:          @solarized-green;
} 
QTabBar::tab:hover {
    background:     @bg-gradient-hover;
    color:          @button-hover-fg;
}
</t>
<t tx="ekr.20180307015158.592">/* ===== Tree Widgets ===== */

QTreeWidget {
    /* Selected items, but NOT edit items.*/
    font-family:    @font-family-tree;
    font-size:      @font-size-other;
    font-weight:    normal; /* normal,bold,100,..,900 */
    font-style:     normal; /* normal, italic,oblique */
}
QTreeWidget QLineEdit View{
    /* Headline edit widgets */
    font-family:    @font-family-tree;
    font-size:      @font-size-other;
    font-weight:    normal; /* normal,bold,100,..,900 */
    font-style:     normal; /* normal, italic,oblique */ 
}
QTreeWidget::selected {
    background:                 @solarized-green;
    color:                      @solarized-base03; 
}
QTreeWidget::active:selected {
    background:                 @solarized-yellow;
    color:                      @solarized-base03; 
}

/* ===== Tree Views ===== */

QTreeView {
    /* Selected items, but NOT edit items.*/
    background-color:           @solarized-base03;
    color:                      @solarized-base0;
    selection-color:            @solarized-orange;
    selection-background-color: @solarized-base03;
    show-decoration-selected:   0;
}
QTreeView::item:selected {
    background:                 @solarized-green;
    color:                      @solarized-base03; 
}
QTreeView::item:active:selected {
    background:                 @solarized-yellow;
    color:                      @solarized-base03; 
}
QTreeView QLineEdit {
    /* Headline edit widgets */
    background-color:           @solarized-yellow;
    color:                      @solarized-base03;
    selection-color:            @solarized-base3;
    selection-background-color: @solarized-blue;  
}
QTreeView::branch:closed:has-children{
    image:                      @tree-image-closed;
}
QTreeView::branch:open:has-children{
    image:                      @tree-image-open;
}
</t>
<t tx="ekr.20180307015158.593">/* ===== Widgets ===== */

QWidget {
    background-color:   @solarized-base03; 
    border-color:       @solarized-base1; 
    color:              @solarized-base1;
    font-size:          @font-size-other;
}
QLabel {
    color:              @solarized-base1;
}
QLineEdit {
    border:         none;
    padding:        3px;
}
QPushButton, QDoubleSpinBox, QSpinBox, QDateEdit, QTimeEdit {
    border:         none;
    margin-right:   5px;
    padding:        3px;
}
QPushButton {
    background:     @bg-gradient;
    color:          @text-foreground;
}
QPushButton:hover {
    background:     @bg-gradient-hover;
    color:          @button-hover-fg;
}

</t>
<t tx="ekr.20180307015158.60"></t>
<t tx="ekr.20180307015158.61">Outline indicators indicate the expansion state of outline nodes. The leo/Icons/nodes-dark folders contains two sets of indicators::
    
    leo/Icons/nodes-dark/plusminus/
    leo/Icons/nodes-dark/triangles/
    
The following settings specify the indicators.  You can use an absolute path, or more conveniently, a path relative either to:

- Your home directory or
- Leo's leo/Icons directory
</t>
<t tx="ekr.20180307015158.62">Must be relative to either the users home directory or leo/Icons directory.

url(/home/edward/leo.repo/leo-editor/leo/Icons/nodes-dark/triangles/closed.png)</t>
<t tx="ekr.20180307015158.63">url(/home/edward/leo.repo/leo-editor/leo/Icons/nodes-dark/triangles/open.png)</t>
<t tx="ekr.20180307015158.64"></t>
<t tx="ekr.20180307015158.65"></t>
<t tx="ekr.20180307015158.66"></t>
<t tx="ekr.20180307015158.95"></t>
<t tx="ekr.20180307015158.96">Name of the theme, used to find icon files</t>
<t tx="ekr.20180307015158.97">Set to true for dark themes, so bookmarks.py can generate
random background colors which are appropriate etc.</t>
<t tx="ekr.20180307015158.98">/*
@language css

old_themes.leo: @data qt-gui-plugin-style-sheet (base dark)
    
*/</t>
<t tx="ekr.20180307015158.99"></t>
<t tx="ekr.20190106114300.1">/* ----- Minibuffer ----- */

QLineEdit#lineEdit[style_class ~= 'minibuffer_warning'] {
    background-color: @minibuffer_warning_color;
}

QLineEdit#lineEdit[style_class ~= 'minibuffer_error'] {
    color: @minibuffer_error_color;
    background-color: @minibuffer_warning_color;
}

/* Bookmarks plugin */

#show_bookmarks QPushButton[style_class~='bookmark_children'] {
    color:              @bookmarks_children_color;
    font-family:        @bookmarks_children_family;
    font-size:          @bookmarks_children_size;
    font-weight:        @bookmarks_children_weight;
    text-decoration:    @bookmarks_children_decoration;
}

#show_bookmarks QPushButton[style_class~='bookmark_expanded'] {
    font-size:          @bookmarks_expanded_size;
    color:              @bookmarks_expanded_color;
    font-style:         @bookmarks_expanded_style;
    font-weight:        @bookmarks_expanded_weight;
    text-decoration:    @bookmarks_expanded_decoration;
}

#show_bookmarks QPushButton[style_class~='bookmark_current'] {
    font-size:          @bookmarks_current_size;
    color:              @bookmarks_current_color;
    font-style:         @bookmarks_expanded_style;
    font-weight:        @bookmarks_current_weight;
    text-decoration:    @bookmarks_current_decoration;
}

</t>
</tnodes>
</leo_file>
