<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.52" body_secondary_ratio="0.71">
	<global_window_position top="165" left="453" height="677" width="957"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="ekr.20180317170608.1"><vh>test_theme.leo: readme</vh></v>
<v t="ekr.20180317170734.1"><vh>@settings</vh>
<v t="ekr.20180319153405.1"><vh>Convenience settings</vh>
<v t="ekr.20180317170734.2"><vh>@bool minibuffer_find_mode = False</vh></v>
<v t="ekr.20180317170734.3"><vh>@bool show-tips = False</vh></v>
<v t="ekr.20180317170734.4"><vh>@bool use-gutter = False</vh></v>
</v>
<v t="ekr.20180319153417.1"><vh>Theme description settings</vh>
<v t="ekr.20180319153417.2"><vh>@bool color_theme_is_dark = True</vh></v>
<v t="ekr.20180319153417.3"><vh>@string color_theme = dark</vh></v>
<v t="ekr.20180319153417.4"><vh>@string theme-name = Breeze Dark Theme</vh></v>
</v>
</v>
</vnodes>
<tnodes>
<t tx="ekr.20180317170608.1" str_leo_pos="1,1,2">@language rest
@wrap

Opening this file will test the Breeze Dark Theme</t>
<t tx="ekr.20180317170734.1"></t>
<t tx="ekr.20180317170734.2"></t>
<t tx="ekr.20180317170734.3">True: show user tips on startup.</t>
<t tx="ekr.20180317170734.4"># For line_numbering plugin.</t>
<t tx="ekr.20180319153405.1"></t>
<t tx="ekr.20180319153417.1"></t>
<t tx="ekr.20180319153417.2" lineYOffset="4b002e">Set to true for dark themes, so bookmarks.py can generate
random background colors which are appropriate etc.</t>
<t tx="ekr.20180319153417.3" lineYOffset="4b002e">Name of the theme,
used to find icon files</t>
<t tx="ekr.20180319153417.4"></t>
</tnodes>
</leo_file>
