<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5" body_secondary_ratio="0.5">
	<global_window_position top="50" left="50" height="500" width="700"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="ekr.20180317170608.1"><vh>test_theme.leo: readme</vh></v>
<v t="ekr.20180317170734.1" a="E"><vh>@settings</vh>
<v t="ekr.20180317170734.2"><vh>@bool minibuffer_find_mode = False</vh></v>
<v t="ekr.20180317170734.3"><vh>@bool show-tips = False</vh></v>
<v t="ekr.20180317170734.4"><vh>@bool use-gutter = False</vh></v>
</v>
</vnodes>
<tnodes>
<t tx="ekr.20180317170608.1">@language rest
@wrap

This is a do-nothing file, except for defining setting useful for testing theme .leo files.

</t>
<t tx="ekr.20180317170734.1"></t>
<t tx="ekr.20180317170734.2"></t>
<t tx="ekr.20180317170734.3">True: show user tips on startup.</t>
<t tx="ekr.20180317170734.4"># For line_numbering plugin.</t>
</tnodes>
</leo_file>
