<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<?xml-stylesheet type="text/xsl" href="/leo_to_html.xsl"?>
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.50" body_secondary_ratio="0.66">
	<global_window_position top="114" left="773" height="947" width="930"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="ekr.20150308092755.2"><vh>To do</vh>
<v t="ekr.20150307092801.3"><vh>@file clone-test.txt</vh></v>
</v>
<v t="ekr.20150308092755.3"><vh>To do: Leo 5.1 b1</vh>
<v t="ekr.20150307092801.4"><vh>Doc</vh></v>
</v>
</vnodes>
<tnodes>
<t tx="ekr.20150307092801.4"></t>
<t tx="ekr.20150308092755.2" str_leo_pos="1"></t>
<t tx="ekr.20150308092755.3"></t>
</tnodes>
</leo_file>
