<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet ekr_test?>
<leo_file>
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5">
	<global_window_position top="150" left="342" height="600" width="800"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="ekr.20080806220518.1" str_leo_pos="1,1,0"><vh>@chapters</vh></v>
<v t="ekr.20080806220518.298" a="E"><vh>Python Server stuff: @path c/python/Lib</vh>
<v t="ekr.20080806220518.299"><vh>@url http://hoohoo.ncsa.uiuc.edu/cgi/primer.html</vh></v>
<v t="ekr.20080806220518.300" a="E"><vh>@auto socket.py</vh></v>
<v t="ekr.20080806220518.301"><vh>@auto SocketServer.py</vh></v>
<v t="ekr.20080806220518.302"><vh>@auto CGIHTTPServer.py</vh></v>
<v t="ekr.20080806220518.304"><vh>@auto BaseHTTPServer.py</vh></v>
<v t="ekr.20080806220518.305"><vh>@auto SimpleHTTPServer.py</vh></v>
<v t="ekr.20080806220518.306"><vh>@auto httplib.py</vh></v>
<v t="ekr.20080806220518.307"><vh>@auto htmllib.py</vh></v>
</v>
</vnodes>
<tnodes>
<t tx="ekr.20080806220518.1"></t>
<t tx="ekr.20080806220518.298">@path c:/python25/Lib</t>
<t tx="ekr.20080806220518.299"># Referenced from class CGIHTTPRequestHandler.run_cgi.</t>
</tnodes>
</leo_file>
