<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet ekr_test?>
<leo_file>
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5" body_secondary_ratio="0.5">
	<global_window_position top="50" left="50" height="500" width="700"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="ekr.20100124110656.2061"><vh>@chapters</vh></v>
<v t="ekr.20100124110656.2060"><vh>testCloneUpdate.leo</vh></v>
<v t="ekr.20100124110656.2062"><vh>@thin testCloneUpdate.txt</vh></v>
<v t="ekr.20100124113912.1310" a="E"><vh>@thin testAtAllCloneUpdate.txt</vh></v>
<v t="ekr.20100124110656.2063"><vh>node</vh></v>
</vnodes>
<tnodes>
<t tx="ekr.20100124110656.2060"></t>
<t tx="ekr.20100124110656.2061" str_leo_pos="3,0"></t>
<t tx="ekr.20100124110656.2063">Node line 1. changed 4.</t>
</tnodes>
</leo_file>
