<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet ekr_test?>
<leo_file>
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5">
	<global_window_position top="50" left="50" height="500" width="700"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="bobjack.20080329075629.2"><vh>@startup</vh>
<v t="bobjack.20080324163716.1"><vh>@chapters</vh>
<v t="bobjack.20080413203125.1"><vh>@chapter three</vh>
<v t="bobjack.20080413203125.2"><vh>three node 1</vh></v>
</v>
<v t="bobjack.20080402160713.6"><vh>@chapter two</vh>
<v t="bobjack.20080402160713.7"><vh>two node 1</vh></v>
</v>
<v t="bobjack.20080402160713.8"><vh>@chapter one</vh>
<v t="bobjack.20080402160713.9"><vh>one node 1</vh></v>
</v>
</v>
</v>
<v t="bobjack.20080412154131.2"><vh>Buttons</vh>
<v t="bobjack.20080329063457.1"><vh>@button show-menu-tables</vh></v>
<v t="bobjack.20080404113810.1"><vh>@button show button events</vh></v>
<v t="bobjack.20080405081601.2"><vh>@button show-button-data</vh></v>
<v t="bobjack.20080414080643.1"><vh>@button Do Unit Tests</vh></v>
</v>
<v t="bobjack.20080329075629.3"><vh>Notes</vh>
<v t="bobjack.20080414143159.5"><vh>&lt;&lt; description of menu_table format &gt;&gt;</vh></v>
</v>
<v t="bobjack.20080414143159.2"><vh>Howto . . . </vh>
<v t="bobjack.20080414143159.3"><vh>. . . Write Generator Commands 1</vh>
<v t="bobjack.20080414143159.4"><vh>&lt;&lt;description of the contents of keywords&gt;&gt;</vh></v>
<v t="bobjack.20080414143159.5"><vh>&lt;&lt; description of menu_table format &gt;&gt;</vh></v>
</v>
<v t="bobjack.20080415130112.2"><vh>. . . Write Generator Commands 2</vh></v>
<v t="bobjack.20080414155140.2"><vh>. . . Use Radio Buttons</vh></v>
<v t="bobjack.20080415090247.2"><vh>. . . Use Check Buttons</vh></v>
</v>
<v t="bobjack.20080329075629.4"><vh>Experiments</vh>
<v t="bobjack.20080330095006.2" lineYOffset="4b002e"><vh>Replacing the log menu</vh></v>
<v t="bobjack.20080330095006.3" lineYOffset="4b002e"><vh>Editing the 'edit-menu' fragment</vh></v>
</v>
<v t="bobjack.20080329070612.1"><vh>Test context sesitive items</vh>
<v t="bobjack.20080329070612.2"><vh>&lt;&lt; test 'Help on: ...' &gt;&gt;	</vh></v>
<v t="bobjack.20080416183608.1"><vh>&lt;&lt;test having a &lt; or &gt; in the section headline &gt;&gt;</vh></v>
<v t="bobjack.20080329070612.3"><vh>&lt;&lt; test 'Open URL: ...'&gt;&gt;</vh></v>
</v>
<v t="bobjack.20080324164314.1"><vh>@settings</vh>
<v t="bobjack.20080415093045.2"><vh>@bool fixedWindow = True</vh></v>
<v t="bobjack.20080402071100.2"><vh>@string rclick-show-help = print log  browser</vh></v>
<v t="bobjack.20080329054053.1"><vh>provide a fragment for use in other menus</vh>
<v t="bobjack.20080329053100.1"><vh>@popup find change fragment</vh>
<v t="bobjack.20080326150321.6"><vh>@item find-next</vh></v>
<v t="bobjack.20080326150321.7"><vh>@item find-prev</vh></v>
<v t="bobjack.20080326150321.8"><vh>@item change</vh></v>
<v t="bobjack.20080326150321.9"><vh>@item change-then-find</vh></v>
</v>
</v>
<v t="bobjack.20080329062304.13"><vh>Provide context menus for ...</vh>
<v t="bobjack.20080329054053.2"><vh>... the log pane</vh>
<v t="bobjack.20080326150321.5"><vh>@popup log</vh>
<v t="bobjack.20080329051459.3"><vh>column one</vh>
<v t="bobjack.20080329043447.3"><vh>@item &amp;</vh></v>
</v>
<v t="bobjack.20080329051459.7"><vh>Test Radio Groups</vh>
<v t="bobjack.20080329043447.2"><vh>@item |</vh></v>
<v t="bobjack.20080404054928.7"><vh>@item Radio</vh></v>
<v t="bobjack.20080403171532.7"><vh>@item rclick-button</vh></v>
<v t="bobjack.20080403171532.8"><vh>@item rclick-button</vh></v>
<v t="bobjack.20080404111009.1"><vh>@item -</vh></v>
<v t="bobjack.20080403171532.9"><vh>@item rclick-button</vh></v>
<v t="bobjack.20080403171532.11"><vh>@item rclick-button</vh></v>
</v>
<v t="bobjack.20080404054928.8"><vh>Test Check Buttons</vh>
<v t="bobjack.20080404054928.9"><vh>@item |</vh></v>
<v t="bobjack.20080404054928.10"><vh>@item *Check</vh></v>
<v t="bobjack.20080404054928.6"><vh>@item rclick-button</vh></v>
<v t="bobjack.20080404054928.11"><vh>@item rclick-button</vh></v>
<v t="bobjack.20080404054928.12"><vh>@item rclick-button</vh></v>
<v t="bobjack.20080404054928.13"><vh>@item rclick-button</vh></v>
</v>
<v t="bobjack.20080329051459.4"><vh>column four</vh>
<v t="bobjack.20080329052834.1"><vh>@item |</vh></v>
<v t="bobjack.20080329053100.2"><vh>@item &amp;</vh></v>
</v>
</v>
</v>
<v t="bobjack.20080329054053.3"><vh>... the body pane</vh>
<v t="bobjack.20080329054053.4"><vh>@popup body</vh>
<v t="bobjack.20080329061920.1"><vh>@item undo</vh></v>
<v t="bobjack.20080329061920.2"><vh>@item -</vh></v>
<v t="bobjack.20080329054053.5"><vh>@item cut-text</vh></v>
<v t="bobjack.20080329054053.6"><vh>@item copy-text</vh></v>
<v t="bobjack.20080329054053.7"><vh>@item paste-text</vh></v>
<v t="bobjack.20080329054053.8"><vh>@item -</vh></v>
<v t="bobjack.20080329054053.9"><vh>@item select-all</vh></v>
<v t="bobjack.20080329054053.10"><vh>@item -</vh></v>
<v t="bobjack.20080329054053.11"><vh>@menu Block Ops</vh>
<v t="bobjack.20080329054053.12"><vh>@item indent-region</vh></v>
<v t="bobjack.20080329054053.13"><vh>@item unindent-region</vh></v>
</v>
<v t="bobjack.20080329054053.15"><vh>@menu Find Change</vh>
<v t="bobjack.20080329054053.16"><vh>@item &amp;</vh></v>
</v>
<v t="bobjack.20080329061442.1"><vh>another pre-defined fragment</vh>
<v t="bobjack.20080329061442.2"><vh>@item &amp;</vh></v>
</v>
<v t="bobjack.20080329054053.17"><vh>@item -</vh></v>
<v t="bobjack.20080402175002.5"><vh>@item *add-editor</vh></v>
<v t="bobjack.20080402175002.6"><vh>@item *delete-editor</vh></v>
<v t="bobjack.20080329054053.18"><vh>@item *execute-script</vh></v>
<v t="bobjack.20080329054053.19"><vh>@item *</vh></v>
</v>
</v>
<v t="bobjack.20080329062304.14"><vh>... the find-text entry</vh>
<v t="bobjack.20080401213500.1"><vh>@popup find_change_text_menu</vh>
<v t="bobjack.20080329062304.2"><vh>column one</vh>
<v t="bobjack.20080329062304.3"><vh>@item &amp;</vh></v>
</v>
<v t="bobjack.20080329062304.10"><vh>column two</vh>
<v t="bobjack.20080329062304.11"><vh>@item |</vh></v>
<v t="bobjack.20080329062304.12"><vh>@item &amp;</vh></v>
</v>
</v>
<v t="bobjack.20080329062304.1"><vh>@popup find-text</vh>
<v t="bobjack.20080401213339.1"><vh>@item label for menu</vh></v>
<v t="bobjack.20080401213339.2"><vh>@item -</vh></v>
<v t="bobjack.20080401213500.2"><vh>@item &amp;</vh></v>
</v>
</v>
<v t="bobjack.20080329062304.15"><vh>... the change-text entry</vh>
<v t="bobjack.20080329062956.1"><vh>@popup change-text</vh>
<v t="bobjack.20080401213023.1"><vh>@item label for menu</vh></v>
<v t="bobjack.20080401213339.3"><vh>@item -</vh></v>
<v t="bobjack.20080402160713.11"><vh>@item &amp;</vh></v>
</v>
</v>
<v t="bobjack.20080401143613.2"><vh>... the tree canvas</vh>
<v t="bobjack.20080401113850.2"><vh>@popup canvas</vh>
<v t="bobjack.20080401113850.3"><vh>@item label for menu</vh></v>
<v t="bobjack.20080402154726.5"><vh>@item -</vh></v>
<v t="bobjack.20080402172239.2"><vh>@menu Clone To Chapter</vh>
<v t="bobjack.20080402160713.10"><vh>@item *</vh></v>
</v>
<v t="bobjack.20080402172239.3"><vh>@menu Copy To Chapter</vh>
<v t="bobjack.20080402172239.4"><vh>@item *</vh></v>
</v>
<v t="bobjack.20080402172239.5"><vh>@menu Move To Chapter</vh>
<v t="bobjack.20080402172239.6"><vh>@item *</vh></v>
</v>
<v t="bobjack.20080414164823.2"><vh>@menu  Goto To Chapter</vh>
<v t="bobjack.20080414164823.1"><vh>@item *</vh></v>
</v>
<v t="bobjack.20080402175002.3"><vh>@item -</vh></v>
<v t="bobjack.20080402175002.2"><vh>@item create-chapter</vh></v>
<v t="bobjack.20080402175002.4"><vh>@item remove-chapter</vh></v>
</v>
</v>
<v t="bobjack.20080401143954.2"><vh>... the plus box</vh>
<v t="bobjack.20080401143954.3"><vh>@popup plusbox</vh>
<v t="bobjack.20080401143954.4"><vh>@item label for menu</vh></v>
</v>
</v>
<v t="bobjack.20080401143613.3"><vh>... headlines</vh>
<v t="bobjack.20080401143613.4"><vh>@popup headline</vh>
<v t="bobjack.20080401143613.5"><vh>@item label for menu</vh></v>
</v>
</v>
<v t="bobjack.20080401214039.1"><vh>... the icon box</vh>
<v t="bobjack.20080401214039.2"><vh>@popup iconbox</vh>
<v t="bobjack.20080401214039.3"><vh>@item label for menu</vh></v>
</v>
</v>
</v>
<v t="bobjack.20080413173856.2"><vh>Unit Test Stuff - Do Not Change</vh>
<v t="bobjack.20080413173856.3"><vh>@popup unit-test-one</vh>
<v t="bobjack.20080413173856.4"><vh>@item -</vh></v>
<v t="bobjack.20080413173856.5"><vh>@item |</vh></v>
<v t="bobjack.20080413173856.6"><vh>@item "</vh></v>
<v t="bobjack.20080413191217.3"><vh>@item *</vh></v>
<v t="bobjack.20080413191217.4"><vh>@item &amp;</vh></v>
</v>
<v t="bobjack.20080413191217.5"><vh>@popup unit-test-two</vh>
<v t="bobjack.20080413191217.6"><vh>@item *rclick-unit-&amp;test-invoke-one</vh></v>
<v t="bobjack.20080413191217.7"><vh>@item     *rclick-&amp;unit-test-&amp;invoke-two  </vh></v>
<v t="bobjack.20080413194942.2"><vh>@item rclick-unit-test-invoke-three</vh></v>
<v t="bobjack.20080413194942.3"><vh>@item     rclick-unit-test-invoke-four  </vh></v>
<v t="bobjack.20080413200228.1"><vh>@item rclick-unit-&amp;test-invoke-five</vh></v>
<v t="bobjack.20080413200228.4"><vh>@item     rclick-&amp;unit-test-&amp;invoke-six  </vh></v>
</v>
<v t="bobjack.20080413203324.2"><vh>@popup unit-test-three</vh>
<v t="bobjack.20080413203324.3"><vh>@menu unit-test-submenu-one</vh></v>
<v t="bobjack.20080413203324.4"><vh>@menu unit-test-submenu-two</vh>
<v t="bobjack.20080413203324.5"><vh>@menu   unit-test-submenu-three   </vh>
<v t="bobjack.20080413203324.6"><vh>@item first place holder</vh></v>
<v t="bobjack.20080413203324.7"><vh>@item second place holder</vh></v>
</v>
</v>
</v>
<v t="bobjack.20080413211455.1"><vh>@popup unit-test-four</vh>
<v t="bobjack.20080413211455.4"><vh>@item rclick-button</vh></v>
</v>
<v t="bobjack.20080416154107.7"><vh>@popup unit-test-five</vh></v>
</v>
</v>
<v t="bobjack.20080413173856.7"><vh>Unit Tests</vh>
<v t="bobjack.20080413173856.9"><vh>@test c.context_menus exists and is well formed</vh></v>
<v t="bobjack.20080413200905.1"><vh>Test @popup to rclick format</vh>
<v t="bobjack.20080413173856.10"><vh>@test single character items translate correctly</vh></v>
<v t="bobjack.20080413191217.8"><vh>@test minbuffer command items translate correctly</vh></v>
<v t="bobjack.20080413203324.8"><vh>@test @menu items translate correctly</vh></v>
<v t="bobjack.20080413210035.1"><vh>@test key value pairs in the body</vh></v>
</v>
<v t="bobjack.20080416154107.4"><vh>Test generators</vh>
<v t="bobjack.20080416154107.8"><vh>@test generator functions</vh></v>
</v>
</v>
</vnodes>
<tnodes>
<t tx="bobjack.20080324163716.1"></t>
<t tx="bobjack.20080324164314.1"></t>
<t tx="bobjack.20080326150321.5"></t>
<t tx="bobjack.20080326150321.6"></t>
<t tx="bobjack.20080326150321.7"></t>
<t tx="bobjack.20080326150321.8"></t>
<t tx="bobjack.20080326150321.9"></t>
<t tx="bobjack.20080329043447.2"></t>
<t tx="bobjack.20080329043447.3">edit-menu</t>
<t tx="bobjack.20080329051459.3">Example of using a pre-defined fragment.</t>
<t tx="bobjack.20080329051459.4">Example of using a user defined fragment.</t>
<t tx="bobjack.20080329051459.7">These do nothing! but could be made
to do something if you want.</t>
<t tx="bobjack.20080329052834.1"></t>
<t tx="bobjack.20080329053100.1">Example of a user defined fragment for inclusion
in other menus.</t>
<t tx="bobjack.20080329053100.2">find change fragment</t>
<t tx="bobjack.20080329054053.1"></t>
<t tx="bobjack.20080329054053.2"></t>
<t tx="bobjack.20080329054053.3"></t>
<t tx="bobjack.20080329054053.4"></t>
<t tx="bobjack.20080329054053.5">Cut</t>
<t tx="bobjack.20080329054053.6">Copy</t>
<t tx="bobjack.20080329054053.7">Paste</t>
<t tx="bobjack.20080329054053.8"></t>
<t tx="bobjack.20080329054053.9"></t>
<t tx="bobjack.20080329054053.10">this is an optional label</t>
<t tx="bobjack.20080329054053.11"></t>
<t tx="bobjack.20080329054053.12">Indent</t>
<t tx="bobjack.20080329054053.13">Dedent</t>
<t tx="bobjack.20080329054053.15"></t>
<t tx="bobjack.20080329054053.16">find change fragment</t>
<t tx="bobjack.20080329054053.17"></t>
<t tx="bobjack.20080329054053.18"></t>
<t tx="bobjack.20080329054053.19">rclick-gen-context-sensitive-commands</t>
<t tx="bobjack.20080329061442.1"></t>
<t tx="bobjack.20080329061442.2">recent-files-menu</t>
<t tx="bobjack.20080329061920.1"></t>
<t tx="bobjack.20080329061920.2"></t>
<t tx="bobjack.20080329062304.1"></t>
<t tx="bobjack.20080329062304.2">Example of using a pre-defined fragment.</t>
<t tx="bobjack.20080329062304.3">edit-menu</t>
<t tx="bobjack.20080329062304.10">Example of using a user defined fragment.</t>
<t tx="bobjack.20080329062304.11"></t>
<t tx="bobjack.20080329062304.12">find change fragment</t>
<t tx="bobjack.20080329062304.13"></t>
<t tx="bobjack.20080329062304.14"></t>
<t tx="bobjack.20080329062304.15">Set this to use the same menu as the find-text entry</t>
<t tx="bobjack.20080329062956.1"></t>
<t tx="bobjack.20080329063457.1">from pprint import pformat

g.es_print(pformat(c.context_menus))</t>
<t tx="bobjack.20080329070612.1">Here is a couple of tests you might like to try out:

    &lt;&lt; test 'Help on: ...' &gt;&gt;
    
    &lt;&lt; test having a &lt; or &gt; in the section headline &gt;&gt;
    
    &lt;&lt; test 'Open URL: ...'&gt;&gt;
    
    http://localhost/
    
Select all the text above then right click.</t>
<t tx="bobjack.20080329070612.2">@
Hello,why don't you right click on

leoGlobals

then click on 'Help on: leoGlobals'</t>
<t tx="bobjack.20080329070612.3">@
Place the cursor in the url below, then right click.

    http://code.launchpad.net/leo-editor/
    
    http://localhost/</t>
<t tx="bobjack.20080329075629.2">print
print
print</t>
<t tx="bobjack.20080329075629.3">@
@popup &lt;name&gt; menus are converted to a list of tuples and stored in::
    
     c.context_menus[&lt;name&gt;]

Some of these names are special, like 'body', 'log', 'find-text', 'change-text'
'headline', 'canvas', 'plusbox', 'clickbox'.


Other names are not special. Menus with these names are 'fragments', that is
they are not meant to be full menus (although they could be used as such) but
are there to be included in other menus.

These fragments can be included in other menus by using ('&amp;','&lt;name&gt;') tuples in
a menu list or an '@item &amp;' node with the name of the fragment to be included as
the body text of the node.

&lt;&lt; description of menu_table format &gt;&gt;

Widgets may be given a context_menu attribute, eg

    w.context_menu = 'my special menu' | [&lt;menu list&gt;]

in which case the menu table in c.context_menus['my special menu'] will be used
as the popup if a string is provided, or if a list is provided that list will
be used as the menu table.  So each widget can have an individual menu.


Widgets must have &lt;Button-3&gt; bound to a callback that eventually raises either
a 'bodyrclick1' hook, such as c.frame.OnBodyRClick or a 'rclick-popup' hook.

Any keyword arguments included in the doHook call will be passed to generator
callbacks and invocation callbacks.
    
Menu tables in c.context_menus are live, they can be manipulated by scripts and
the changes will show up immediately.  See 'experiments' and 'Howto ...'.

Changes to a fragment that is included in other menus will likewise show up
immediately in all those menus.


To get a right click menu for a widget use::
    
    g.doHook('rclick-popup', c=c, event=event, context_menu='&lt;default menu name&gt;', &lt;any key=value pairs...&gt;)


Make sure the event has passed through the master rclick handler before using the hook.
</t>
<t tx="bobjack.20080329075629.4"># Experiment with using scripts to create or manipulate menu tables.





</t>
<t tx="bobjack.20080330095006.2">def cb( x=None):

    def testMenuCallback(c, keywords, x=x):

        event = keywords.get('event')
        if x is None:
            x = keywords.get('rc_label')
        g.es('%s in %s' %(x,c.widget_name(event.widget)), color='blue')

    return testMenuCallback

c.context_menus['log'] = [

    ('11', cb()),
    ('12', cb('12')),
    ('13', cb('13')),
    ('14', cb('14')),
    ('|', ''),
    ('xone', cb('one')),
    ('xtwo', cb()),
    ('xthree', cb('three')),
    ('xfour', cb('four')),
    ('|', ''),    
    ('&amp;', 'edit-menu'),
]
g.es('replaced log menu', color='blue')
</t>
<t tx="bobjack.20080330095006.3">"""This change will be reflected in all menus that use the 'edit-menu'
fragment. Check before and after in the log and find and change text boxes. """

et = c.context_menus['edit-menu'] 
c.context_menus['edit-menu'] = et[:-2]
g.es('removed select-all from ALL edit-menus', color='blue')</t>
<t tx="bobjack.20080401113850.2"></t>
<t tx="bobjack.20080401113850.3">Canvas Menu</t>
<t tx="bobjack.20080401143613.2"></t>
<t tx="bobjack.20080401143613.3"></t>
<t tx="bobjack.20080401143613.4">@
Remove the '@item headline menu' node to leave an '@popup headline' node with no children to restore the standard tree popup menu.
 
Alternatively, setting

    c.context_menus['headline'] = []
    
will also restore the leo standard popup menu. Highlight the code above and execute it to see the effect.</t>
<t tx="bobjack.20080401143613.5">Headline Menu</t>
<t tx="bobjack.20080401143954.2"></t>
<t tx="bobjack.20080401143954.3"></t>
<t tx="bobjack.20080401143954.4">Plus Box Menu</t>
<t tx="bobjack.20080401213023.1">Change Text Menu</t>
<t tx="bobjack.20080401213339.1">Find Text Menu</t>
<t tx="bobjack.20080401213339.2"></t>
<t tx="bobjack.20080401213339.3"></t>
<t tx="bobjack.20080401213500.1"></t>
<t tx="bobjack.20080401213500.2">find_change_text_menu</t>
<t tx="bobjack.20080401214039.1"></t>
<t tx="bobjack.20080401214039.2">@
Icon box menus will be disabled by cleo or other plugins using the same hook.

Remove the '@item iconbox menu' node to leave an '@popup iconbox' node with no children to restore the standard tree popup menu.
 
Alternatively, setting

    c.context_menus['iconbox'] = []
    
will also restore the leo standard popup menu. Highlight the code above and execute it to see the effect.</t>
<t tx="bobjack.20080401214039.3">Icon Box Menu</t>
<t tx="bobjack.20080402071100.2">@
This setting determines where the output of rclick's "Help on: ...""
menu item goes.

The setting can contain a list of words which may include 'print', 'log', 'browser' or 'all'.

if 'log' appears in the list, output will go to the log pane.
if 'print' appears in the list, output will be sent to standard out.

if 'browser' appears in the list then a browser will be launched and the output will be displayed as a web page.

If 'all' appears in the list, output will go to all these destinations
regardless of what else is in the list.

Example::
    
    @string rclick-show-help = print log
    </t>
<t tx="bobjack.20080402154726.5"></t>
<t tx="bobjack.20080402160713.6"></t>
<t tx="bobjack.20080402160713.7"></t>
<t tx="bobjack.20080402160713.8"></t>
<t tx="bobjack.20080402160713.9"></t>
<t tx="bobjack.20080402160713.10">clone-node-to-chapter-menu</t>
<t tx="bobjack.20080402160713.11">find_change_text_menu</t>
<t tx="bobjack.20080402172239.2"></t>
<t tx="bobjack.20080402172239.3"></t>
<t tx="bobjack.20080402172239.4">copy-node-to-chapter-menu</t>
<t tx="bobjack.20080402172239.5"></t>
<t tx="bobjack.20080402172239.6">move-node-to-chapter-menu</t>
<t tx="bobjack.20080402175002.2"></t>
<t tx="bobjack.20080402175002.3"></t>
<t tx="bobjack.20080402175002.4"></t>
<t tx="bobjack.20080402175002.5"></t>
<t tx="bobjack.20080402175002.6"></t>
<t tx="bobjack.20080403171532.7">1
kind = radio
group = test1
name = test-one-one
</t>
<t tx="bobjack.20080403171532.8">2
kind = radio
group = test1
name = test-one-two

</t>
<t tx="bobjack.20080403171532.9">3
kind = radio
group = test2
name = test-two-three</t>
<t tx="bobjack.20080403171532.11">4
kind = radio
group = test2
name = test-two-four

</t>
<t tx="bobjack.20080404054928.6">1
kind = check
name = check-one

</t>
<t tx="bobjack.20080404054928.7"></t>
<t tx="bobjack.20080404054928.8">Although the general purpose rclick-check-button is used here
which emits </t>
<t tx="bobjack.20080404054928.9"></t>
<t tx="bobjack.20080404054928.10"></t>
<t tx="bobjack.20080404054928.11">2
kind = check
name = check-two



</t>
<t tx="bobjack.20080404054928.12">3
kind = check
name = check-three

</t>
<t tx="bobjack.20080404054928.13">4
kind = check
name = check-four


</t>
<t tx="bobjack.20080404111009.1"></t>
<t tx="bobjack.20080404113810.1"># Run this as a script to enable reporting of changes
# to the check/radio menu items in the log panel menu.

# Example: how to initialize/modify item settings

cm = c.theContextMenuController

groups = cm.radio_group_data
checks = cm.check_button_data

groups['test1'] = 'test-one-two'
groups['test2'] = 'test-two-one'
checks['check-two'] = True

def report_item_clicked(tag, keywords):

    """
    Note: This keywords is different from the the

        c.theContextMenuControler.mb_keywords

    which contains all the information about the right click
    that posted the menu that this event derives from.

    mb_keywords tells which widget the right click occurred in,
    among other things.
    """

    kind, selected, name, group = \
        [keywords.get(v) for v in (
            'kind', 'selected', 'name', 'group')]

    if kind == 'radio':
         g.es("Rclick Test Radio Group['%s'] Selected['%s']"%(
            group, selected))

    if kind == 'check':
        g.es("Rclick Test Check Button Name['%s']  Checked:[%s]"% (
            name, bool(selected)))

import leoPlugins
leoPlugins.registerHandler("rclick-button-clicked", report_item_clicked)

g.es('registered to recieve radio/check button events', color='blue')
</t>
<t tx="bobjack.20080405081601.2">cm = c.theContextMenuController

groups = cm.radio_group_data
checks = cm.check_button_data

g.es('\ngroups\n======', color='blue')

for group, selected in sorted(groups.iteritems()):
    g.es("'%s' -&gt; '%s'"%(group, selected), color='blue')

g.es("\nchecks\n======", color = 'blue')

for check, selected in sorted(checks.iteritems()):
    g.es("'%s' -&gt; %s"%(check, selected), color='blue')

</t>
<t tx="bobjack.20080412154131.2">@
The following button are provided:
    
    show-menu-tables:
        
        This button pretty prints the rclick menu tables in
        c.context_menus to the log panel.
        
    show-button-events:
        
        After clicking this button, all clicks to the radio and
        check button menu items will be reported in the log
        panel.
        
        
    show-button-data:
        
        This button prints the status of the radio groups and check
        buttons that are used in the menus.
        
    do-unit-tests:
        
        This button runs all the unit tests for the rClick
        plugin.  There are not many of them yet but that will
        change over time.
    </t>
<t tx="bobjack.20080413173856.2"></t>
<t tx="bobjack.20080413173856.3">Test that single character items translate correctly.</t>
<t tx="bobjack.20080413173856.4">separator</t>
<t tx="bobjack.20080413173856.5">column break</t>
<t tx="bobjack.20080413173856.6">comment</t>
<t tx="bobjack.20080413173856.7">print
print
print
</t>
<t tx="bobjack.20080413173856.9">@
This test checks the integrity of the rClick menu tables stored in
c.context_menus. It can be copied to other leo files and used to check
that scripts which modify the menus are at least producing valid menus.

This node can be run using execute-script as well as the unit test command.
@c
assert hasattr(c, 'context_menus'), \
    'c has no context menus'

menus = c.context_menus
assert isinstance(menus, dict), \
    'c.context_menus must be a dictionary'

def test_menu_list(menu_table):

     for item in menu_table:

        assert isinstance(item, tuple) and len(item)==2,\
            'items in menu_tables must be tuples of length two'

        label, cmd = item
        
        assert isinstance(label, basestring),\
            'the label for a menu_table item must be a string'
            
        if isinstance(cmd, list):
            test_menu_list(cmd)
            
        #cmd can be ANY object for '-', '|' or '"'
        elif label in ('-', '|', '"'):
            pass

        else:
            assert  isinstance(cmd, basestring) \
                or callable(cmd) or cmd is None, \
            'the command for a mentu_table item  other than  - | and " must ' + \
            'be None, a list, a string, or a callable object.'
            

for key, value in menus.iteritems():

    assert isinstance(key, basestring),\
        'keys for c.context_menus must be strings'

    assert isinstance(value, list),\
        'values for c.context_menus must be lists'

    test_menu_list(value)





</t>
<t tx="bobjack.20080413173856.10">menu_name = u'unit-test-one'

assert menu_name in c.context_menus, \
    '%s is not in context_menus' % menu_name

menu_table = c.context_menus[menu_name]

assert len(menu_table) == 5, \
    "wrong number of items in menu_table"
    
for kind, argument, item in zip(
        ('-', '|', '"', '*', '&amp;'),
        ('separator', 'column break', 'comment',
          'rclick-unit-test-generator', 'rclick-unit-test-include'),
        menu_table ):
            
    assert kind == item[0], \
        "Wrong marker"
    
    #print 'argument', item[1]    
    assert  item[1] == argument, \
        "Wrong argument"
        
    
        
        </t>
<t tx="bobjack.20080413191217.3">rclick-unit-test-generator</t>
<t tx="bobjack.20080413191217.4">rclick-unit-test-include
</t>
<t tx="bobjack.20080413191217.5">Test @item *minibuffer-command-items translate correctly.

If there are spaces before and after the text in the headline, then this
is deliberate, do not remove theme.</t>
<t tx="bobjack.20080413191217.6">bad</t>
<t tx="bobjack.20080413191217.7">bad



</t>
<t tx="bobjack.20080413191217.8">menu_name = u'unit-test-two'

assert menu_name in c.context_menus, \
    '%s is not in context_menus' % menu_name

menu_table = c.context_menus[menu_name]

nItems = 6
assert len(menu_table) == nItems, \
    "wrong number of items in menu_table"
    
labels = (
    'Rclick Unit Test Invoke One',
    'Rclick Unit Test Invoke Two',
    'three',
    'four',
    'Rclick Unit Test Invoke Five',
    'Rclick Unit Test Invoke Six',
)

commands = (
    'rclick-unit-test-invoke-one',
    'rclick-unit-test-invoke-two',
    'rclick-unit-test-invoke-three',
    'rclick-unit-test-invoke-four',
    'rclick-unit-test-invoke-five',
    'rclick-unit-test-invoke-six',
)

assert len(labels)==nItems and len(commands)==nItems, \
    "Wrong number of items in test tables."
    
for label, command, item in zip(labels, commands, menu_table):
             
    assert label == item[0], \
        "Wrong label"
        
    assert  item[1] == command, \
        "Wrong command\n\tGot: %s\n\tExpected: %s" % (item[1], command)</t>
<t tx="bobjack.20080413194942.2">three</t>
<t tx="bobjack.20080413194942.3">f&amp;our


</t>
<t tx="bobjack.20080413200228.1"></t>
<t tx="bobjack.20080413200228.4">



</t>
<t tx="bobjack.20080413200905.1"></t>
<t tx="bobjack.20080413203125.1"></t>
<t tx="bobjack.20080413203125.2"></t>
<t tx="bobjack.20080413203324.2"></t>
<t tx="bobjack.20080413203324.3"></t>
<t tx="bobjack.20080413203324.4"></t>
<t tx="bobjack.20080413203324.5"></t>
<t tx="bobjack.20080413203324.6">first


</t>
<t tx="bobjack.20080413203324.7">second

</t>
<t tx="bobjack.20080413203324.8">menu_name = u'unit-test-three'

assert menu_name in c.context_menus, \
    '%s is not in context_menus' % menu_name

menu_table = c.context_menus[menu_name]

assert len(menu_table) == 2, \
    "wrong number of items in menu_table"
    
    
item = menu_table[0]
assert item[0] == 'unit-test-submenu-one', 'Wrong Label'

# Test empty menu item produces an empty list
submenu_table = item[1]
assert isinstance(submenu_table, list), 'Expecting a list'
assert not submenu_table, 'submenu table should be empty'


item = menu_table[1]
assert item[0] == 'unit-test-submenu-two'

submenu_table = item[1]
assert isinstance(submenu_table, list), 'Expecting a list'
assert len(submenu_table) == 1, 'submenu table should of length one'
            
item = submenu_table[0]
assert item[0] == 'unit-test-submenu-three'

submenu_table = item[1]
assert isinstance(submenu_table, list), 'Expecting a list'
assert len(submenu_table) == 2, 'submenu table should of length two'

</t>
<t tx="bobjack.20080413210035.1">menu_name = u'unit-test-four'

assert menu_name in c.context_menus, \
    '%s is not in context_menus' % menu_name

menu_table = c.context_menus[menu_name]

assert len(menu_table) == 1, \
    "wrong number of items in menu_table"
    
item = menu_table[0]


#print 'label', item[0]
assert item[0] == 'Rclick Unit Test One', \
    "wrong label"

#print 'cmd', item[1]

expected = """rclick-button
kind=radio
group=rclick_unit_test_group
name=rclick_unit_test_one
test=this has an = sign"""

expected = '\n'.join(expected.strip().splitlines())

assert item[1] ==  expected, "cmd string is wrong" </t>
<t tx="bobjack.20080413211455.1">Test </t>
<t tx="bobjack.20080413211455.4">Rclick Unit Test One

# this is a comment because it starts with #
and this is a comment because it does not contain an equal sign

kind = radio
group =   rclick_unit_test_group
name = rclick_unit_test_one

test = this has an = sign


#

</t>
<t tx="bobjack.20080414080643.1">@color

import leoTest
leoTest.doTests(c,all=True)
</t>
<t tx="bobjack.20080414143159.2"></t>
<t tx="bobjack.20080414143159.3">@
How to write generator commands version 1.
==========================================

After reading this node you can use Execute Script on it to see the example code
in action.

A generator command is a minibuffer command that is used to add items to a right
click menu at the time it is being created. They are only of use in @popup trees
and rClick menu tables.

A generator command can be used in @popup trees like this::

    @popup some-menu
        @item *   (body: my-cool-command)

Notice there is only a single * after the @item in the headline, and the name of
the command is in the first line of the body.

We will now write a simple minibuffer command 'demo-editor-items' which will add
menu items to add a new editor and delete an editor preceded by a separator. Of
course we wouldn't want to write a command to do this normally but we have to
start somewhere.

First of all define the function that will be used for the command.

@c
def do_demo_editor_items(event):

    # get the keywords dictionary that the rClick menu has prepared for us

    controller = c.theContextMenuController

    keywords = controller.mb_keywords

    &lt;&lt; description of the contents of keywords &gt;&gt;

    # for this exercise we only need the table of items yet to be converted

    menu_table = keywords['rc_menu_table']

    &lt;&lt; description of menu_table format &gt;&gt;

    new_items = [
        ('-', ''),
        ('Add Editor Test', 'add-editor'),
        ('Delete Editor Test', 'delete-editor'),
    ]

    # insert the new items at the top of the menu_table which is the table of items waiting
    # to be converted into real menu items.

    # menu_table must be altered in situ you can NOT do keyword['rc_menu_table'] = new_menu.

    menu_table[:0] = new_items

    # We do not need really to do this as mb_retval is set to None before we are called

    controller.mb_retval = None

@
Now we have a function lets register it as a minibuffer command
@c

c.k.registerCommand('demo-editor-items', shortcut=None, func=do_demo_editor_items)

@
Our command has to be inserted into a menu to be of any use, so here we insert it into
the second position of the body menu.
@c

c.context_menus['body'][1:1] = [('*', 'demo-editor-items')]

@
All that is left to do is for you to execute this node as a script, do that now.

Right click the body pane to see the new menu items appear.











</t>
<t tx="bobjack.20080414143159.4">@

keywords['event']:

    The event object obtain from the right click event.

    keywords['event'].widget:

         The widget in which the right click was detected.


keywords['rc_rmenu']:

     The gui menu widget that has been generated from previous items.

     This menu may be changed.


keywords['rc_menu_table']:

    The list of menu items that have yet to be converted into gui menu
    items. 

    This list may be manipulated or extended at will or even replaced
    entirely.

    The list must be manipulated in-situ, you can not replace it.

</t>
<t tx="bobjack.20080414143159.5">@

Generate custom menu items.
@item *  (body: generator-command)  or ('*', 'generator-command')

Include another menu in this menu.
@item &amp;  (body: menu name)          or ('&amp;', 'menu name')

Start another column in a menu.
@item |  (body: a comment)          or ('|', 'a comment')

Insert a separator.
@item  -  (body: a comment)         or ('-', 'a comment')

Comment - this item is ignored.
@item  "  (body: a comment)         or ('"', 'a comment')

Minibuffer Command with label.
@item mini-buffer-command (body: menu label)    or ('menu label', mini-buffer-command)

Minibuffer Command with no label.
@item mini-buffer-command (body: empty)    or ('Mini Buffer Command', mini-buffer-command)
@item *mini-buffer-command (body: empty)   or ('Mini Buffer Command', mini-buffer-command)

Submenu.
@menu menu label (body: &lt;empty&gt;     or ('menu label', [ &lt;menu_list&gt; ])


</t>
<t tx="bobjack.20080414155140.2">@
How to use radio buttons.
=========================

After reading this node you can use Execute Script on it to see the example code
in action.

Radio buttons can be placed in @popup menus using the following form::

    @popup some-menu
        @item rclick-button  body:  Demo Radio One
                                    kind = radio
                                    group = demo-group
                                    name = demo-radio-button-one

Notice that 'Demo Radio One' which is the first line of the body is used as the
label for the radio button. The second line of the body identifies this as a
radio button, the third line says which group the button belongs too and the
fourth line identifies this button uniquely within the group 'demo-group'.

The three lines with '=' in can appear in any order, space around the '=' will
be deleted. Any other text such as comments may appear in the body, any line
without an '=' will be ignored as will any line with '#' as the first character.

Button belonging to the same radio group can be appear in many different menus.
Button having the same name and belonging to the same group are effectively the
same button, regardless of what menu or how many menus they appear in.

Here we will insert three radio buttons into the second position of the body menu.

Notice that in the menu tables the label is the first item of the tuple and the
minibuffer command 'rclick' button is the first line of the second item of the
tuple, which may be the opposite of what you expect.

@c
new_items = [

('-', ''), #separator

('Demo Radio One', """rclick-button
    kind = radio
    group = demo-group
    name = demo-radio-one
"""),

('Demo Radio Two', """rclick-button
    kind = radio
    group = demo-group
    name = demo-radio-two
"""),

('Demo Radio Three', """rclick-button
    kind = radio
    group = demo-group
    name = demo-radio-three
""")

]

# Insert the menu items into the second position of the 'body' menu.
# Notice we must change the menu in situ.

c.context_menus['body'][1:1] = new_items

# Choose the button we want selected initially

cm = c.theContextMenuController
cm.radio_group_data['demo-group'] = 'demo-radio-two'

#define a callback so we can print a message when one of our buttons is clicked

def demo_radio_callback(self, keywords):

    kind, selected, name, group = \
        [keywords.get(v) for v in (
            'kind', 'selected', 'name', 'group')]

    if kind == 'radio' and group=='demo-group':
         g.es("Demo Radio Group Selected['%s']"%selected)

# register the callback to receive notification of rclick button events

import leoPlugins
leoPlugins.registerHandler("rclick-button-clicked", demo_radio_callback)

# Execute this node as a script and right click the body to see the results.






















</t>
<t tx="bobjack.20080414164823.1">select-chapter-menu</t>
<t tx="bobjack.20080414164823.2"></t>
<t tx="bobjack.20080415090247.2">@
How to use check buttons.
=========================

After reading this node you can use Execute Script on it to see the example code in action.

Check buttons can be placed in @popup menus using the following form::

    @popup some-menu
        @item rclick-button  body:  Demo Check One
                                    kind = check
                                    name = demo-check-button-one

Notice that 'Demo Check One' which is the first line of the body is used as the label
for the check button. The second line of the body identifies this as a check
button, the third line says which group the button belongs too and the fourth line
identifies this button uniquely within the group 'demo-group'.

The lines with '=' in can appear in any order, space around the '=' will
be deleted. Any other text such as comments may appear in the body, any line
without an '=' will be ignored as will any line with '#' as the first character.

rclick-button check buttons with the same name are effectively the same button, any number
of identical buttons can appear in any number of menus and submenus.

Here we will insert two check buttons into the second position of the body menu.

Notice that in the menu tables the label is the first item of the tuple and the
minibuffer command 'rclick' button  is the first line of the second item of the tuple.
This is done so that @item in @popup menus are compatible with @item in @menus.

@c
new_items = [
('-', ''),

('Demo Check One', """rclick-button
    kind = check
    name = demo-check-one
"""),

('Demo Check Two', """rclick-button
    kind = check
    name = demo-check-two
"""),

]


# Insert the menu items into the second position of the 'body' menu.
# Notice we must change the menu in situ.

c.context_menus['body'][1:1] = new_items


# Choose the button we want selected initially

cm = c.theContextMenuController
btns = ('demo-check-one', 'demo-check-two')
for btn in btns:
    cm.check_button_data[btn] = True

#define a callback so we can print a message when one of our buttons is clicked

def demo_check_callback(self, keywords):

    kind, selected, name = \
        [keywords.get(v) for v in (
            'kind', 'selected', 'name')]

    if kind == 'check' and name in btns:
         g.es("Demo Check Button[%s] Selected[%s]"%(name, selected))

# register the callback to receive notification of rclick button events

import leoPlugins
leoPlugins.registerHandler("rclick-button-clicked", demo_check_callback)

# Execute this node as a script and right click the body to see the results.






















</t>
<t tx="bobjack.20080415093045.2"></t>
<t tx="bobjack.20080415130112.2">@
How to write generator commands version 2.
==========================================

This is an alternative method of writing generator commands. 

The advantage of using this method is that the do_demo_editor_items function can
be used directly in rclick menu tables as well as being accessed through the
minibuffer command.

First define the base function.
@c

def do_demo_editor_items(keywords):

    menu_table = None #keywords['rc_menu_table']

    new_items = [
        ('-', ''),
        ('Add Editor Test', 'add-editor'),
        ('Delete Editor Test', 'delete-editor'),
    ]

    menu_table[:0] = new_items

# Now define a wrapper to convert the minibuffer command event.

def demo_editor_items(event):

    cm = c.theContextMenuController
    cm.mb_retval = do_demo_editor_items(cm.mb_keywords)

c.k.registerCommand('demo-editor-items', shortcut=None, func=demo_editor_items)

c.context_menus['body'][1:1] = [
    ('*', do_demo_editor_items), # do it once using the function directly
    ('*', 'demo-editor-items')   # do it again using minbuffer command
]


@


Execute this node as a script.

Right click the body pane to see the new menu items appear.











</t>
<t tx="bobjack.20080416154107.4"></t>
<t tx="bobjack.20080416154107.7"></t>
<t tx="bobjack.20080416154107.8">call_status = 'not called'

def do_demo_editor_items(*args, **kw):

    global call_status
    call_status = 'error'

    assert len(args) == 1 and not kw, \
        "Expected one and only one argument and no keyword arguments."

    keywords = args[0]

    assert isinstance(keywords, dict), \
        "Expected the argument to be a dictionary."
        
    for key, value in (
        ('event', None),
        ('testOne', 'test one'),
        ('testTwo', 'test two'),
        #('rc_phase', 'generate'),
        ('rc_label', '*'),
    ):
        assert key in keywords, \
            'Expected key %s to be in keywords' % key

        assert keywords[key] == value, \
            'Expected keywords[%s] == %s' %(key, value)

    for key in (
        'rc_rmenu',
        'rc_menu_table',
        'rc_label', 
        'rc_item_data',
    ):
        assert key in keywords, \
            'Expected key %s to be in keywords' % key

    msg = 'Expected keywords[%s] %s'

    key = 'rc_rmenu'
    menu = keywords[key]
    new_menu = c.frame.menu.new_menu(None)

    assert isinstance(menu, new_menu.__class__), \
        msg % (key, 'to be a gui menu class %s' % new_menu.__class__.__name__)

    key = 'rc_menu_table'
    menu_table = keywords[key]
    assert isinstance(menu_table, list), \
        msg % (key, 'to be a list.')

    key = 'rc_item_data'
    item_data = keywords[key]
    assert isinstance(item_data, dict) and not item_data, \
        msg % (key, 'to be an empty dictionary')

    menu_table = keywords['rc_menu_table']

    new_items = [
        ('-', ''),
        ('Add Editor Test', 'add-editor'),
        ('Delete Editor Test', 'delete-editor'),
    ]

    menu_table[:0] = new_items

    call_status = 'done'
    return 'hello'

    ## End of Function

menu = [('*', do_demo_editor_items)]

result = g.doHook('rclick-popup',
    c=c, event=None, context_menu = menu,
    testOne='test one', testTwo='test two'
)

retval = c.theContextMenuController.mb_retval

assert call_status == 'done', \
    'The function call status was "%s", expected "done"' % call_status

assert retval == 'hello', \
    'The return value is "%s", expected "hello"' % retval



</t>
<t tx="bobjack.20080416183608.1">The old re wouldn't recognise this section headline

hopefully the new one does.</t>
</tnodes>
</leo_file>
