<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet ekr_test?>
<leo_file>
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5">
	<global_window_position top="165" left="321" height="590" width="1060"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="bobjack.20080329075629.2" str_leo_pos="3"><vh>@startup</vh>
<v t="bobjack.20080324163716.1"><vh>@chapters</vh>
<v t="bobjack.20080402160713.6"><vh>@chapter two</vh>
<v t="bobjack.20080402160713.7"><vh>two node 1</vh></v>
</v>
<v t="bobjack.20080402160713.8"><vh>@chapter one</vh>
<v t="bobjack.20080402160713.9"><vh>one node 1</vh></v>
</v>
</v>
<v t="bobjack.20080412154131.2"><vh>Buttons</vh>
<v t="bobjack.20080329063457.1"><vh>@button show-menu-tables</vh></v>
<v t="bobjack.20080404113810.1"><vh>@button show button events</vh></v>
<v t="bobjack.20080405081601.2"><vh>@button show-button-data</vh></v>
</v>
</v>
<v t="bobjack.20080329075629.3"><vh>Notes</vh></v>
<v t="bobjack.20080329075629.4"><vh>Experiments</vh>
<v t="bobjack.20080330095006.2" lineYOffset="4b002e"><vh>Replacing the log menu</vh></v>
<v t="bobjack.20080330095006.3" lineYOffset="4b002e"><vh>Editing the 'edit-menu' fragment</vh></v>
</v>
<v t="bobjack.20080329070612.1"><vh>Test context sesitive items</vh>
<v t="bobjack.20080329070612.2"><vh>&lt;&lt; test 'Help on: ...' &gt;&gt;	</vh></v>
<v t="bobjack.20080329070612.3"><vh>&lt;&lt; test 'Open URL: ...'&gt;&gt;</vh></v>
</v>
<v t="bobjack.20080324164314.1"><vh>@settings</vh>
<v t="bobjack.20080402071100.2"><vh>@string rclick-show-help = print log  </vh></v>
<v t="bobjack.20080329054053.1"><vh>provide a fragment for use in other menus</vh>
<v t="bobjack.20080329053100.1"><vh>@popup find change fragment</vh>
<v t="bobjack.20080326150321.6"><vh>@item *find-next</vh></v>
<v t="bobjack.20080326150321.7"><vh>@item *find-prev</vh></v>
<v t="bobjack.20080326150321.8"><vh>@item *change</vh></v>
<v t="bobjack.20080326150321.9"><vh>@item *change-then-find</vh></v>
</v>
</v>
<v t="bobjack.20080329062304.13"><vh>Provide context menus for ...</vh></v>
<v t="bobjack.20080329054053.2"><vh>... the log pane</vh>
<v t="bobjack.20080326150321.5"><vh>@popup log</vh>
<v t="bobjack.20080329051459.3"><vh>column one</vh>
<v t="bobjack.20080329043447.3"><vh>@item &amp;</vh></v>
</v>
<v t="bobjack.20080329051459.7"><vh>Test Radio Groups</vh>
<v t="bobjack.20080329043447.2"><vh>@item |</vh></v>
<v t="bobjack.20080404054928.7"><vh>@item *Radio</vh></v>
<v t="bobjack.20080403171532.7"><vh>@item rclick-button</vh></v>
<v t="bobjack.20080403171532.8"><vh>@item rclick-button</vh></v>
<v t="bobjack.20080404111009.1"><vh>@item -</vh></v>
<v t="bobjack.20080403171532.9"><vh>@item rclick-button</vh></v>
<v t="bobjack.20080403171532.11"><vh>@item rclick-button</vh></v>
</v>
<v t="bobjack.20080404054928.8"><vh>Test Check Buttons</vh>
<v t="bobjack.20080404054928.9"><vh>@item |</vh></v>
<v t="bobjack.20080404054928.10"><vh>@item *Check</vh></v>
<v t="bobjack.20080404054928.6"><vh>@item rclick-button</vh></v>
<v t="bobjack.20080404054928.11"><vh>@item rclick-button</vh></v>
<v t="bobjack.20080404054928.12"><vh>@item rclick-button</vh></v>
<v t="bobjack.20080404054928.13"><vh>@item rclick-button</vh></v>
</v>
<v t="bobjack.20080329051459.4"><vh>column four</vh>
<v t="bobjack.20080329052834.1"><vh>@item |</vh></v>
<v t="bobjack.20080329053100.2"><vh>@item &amp;</vh></v>
</v>
</v>
</v>
<v t="bobjack.20080329054053.3"><vh>... the body pane</vh>
<v t="bobjack.20080329054053.4"><vh>@popup body</vh>
<v t="bobjack.20080329061920.1"><vh>@item *undo</vh></v>
<v t="bobjack.20080329061920.2"><vh>@item -</vh></v>
<v t="bobjack.20080329054053.5"><vh>@item cut-text</vh></v>
<v t="bobjack.20080329054053.6"><vh>@item copy-text</vh></v>
<v t="bobjack.20080329054053.7"><vh>@item paste-text</vh></v>
<v t="bobjack.20080329054053.8"><vh>@item -</vh></v>
<v t="bobjack.20080329054053.9"><vh>@item *select-all</vh></v>
<v t="bobjack.20080329054053.10"><vh>@item -</vh></v>
<v t="bobjack.20080329054053.11"><vh>@menu Block Ops</vh>
<v t="bobjack.20080329054053.12"><vh>@item indent-region</vh></v>
<v t="bobjack.20080329054053.13"><vh>@item unindent-region</vh></v>
</v>
<v t="bobjack.20080329054053.15"><vh>@menu Find Change</vh>
<v t="bobjack.20080329054053.16"><vh>@item &amp;</vh></v>
</v>
<v t="bobjack.20080329061442.1"><vh>another pre-defined fragment</vh>
<v t="bobjack.20080329061442.2"><vh>@item &amp;</vh></v>
</v>
<v t="bobjack.20080329054053.17"><vh>@item -</vh></v>
<v t="bobjack.20080402175002.5"><vh>@item *add-editor</vh></v>
<v t="bobjack.20080402175002.6"><vh>@item *delete-editor</vh></v>
<v t="bobjack.20080329054053.18"><vh>@item *execute-script</vh></v>
<v t="bobjack.20080329054053.19"><vh>@item *</vh></v>
</v>
</v>
<v t="bobjack.20080329062304.14"><vh>... the find-text entry</vh>
<v t="bobjack.20080401213500.1"><vh>@popup find_change_text_menu</vh>
<v t="bobjack.20080329062304.2"><vh>column one</vh>
<v t="bobjack.20080329062304.3"><vh>@item &amp;</vh></v>
</v>
<v t="bobjack.20080329062304.10"><vh>column two</vh>
<v t="bobjack.20080329062304.11"><vh>@item |</vh></v>
<v t="bobjack.20080329062304.12"><vh>@item &amp;</vh></v>
</v>
</v>
<v t="bobjack.20080329062304.1"><vh>@popup find-text</vh>
<v t="bobjack.20080401213339.1"><vh>@item label for menu</vh></v>
<v t="bobjack.20080401213339.2"><vh>@item -</vh></v>
<v t="bobjack.20080401213500.2"><vh>@item &amp;</vh></v>
</v>
</v>
<v t="bobjack.20080329062304.15"><vh>... the change-text entry</vh>
<v t="bobjack.20080329062956.1"><vh>@popup change-text</vh>
<v t="bobjack.20080401213023.1"><vh>@item label for menu</vh></v>
<v t="bobjack.20080401213339.3"><vh>@item -</vh></v>
<v t="bobjack.20080402160713.11"><vh>@item &amp;</vh></v>
</v>
</v>
<v t="bobjack.20080401143613.2"><vh>... the tree canvas</vh>
<v t="bobjack.20080401113850.2"><vh>@popup canvas</vh>
<v t="bobjack.20080401113850.3"><vh>@item label for menu</vh></v>
<v t="bobjack.20080402154726.5"><vh>@item -</vh></v>
<v t="bobjack.20080402172239.2"><vh>@menu Clone To Chapter</vh>
<v t="bobjack.20080402160713.10"><vh>@item *</vh></v>
</v>
<v t="bobjack.20080402172239.3"><vh>@menu Copy To Chapter</vh>
<v t="bobjack.20080402172239.4"><vh>@item *</vh></v>
</v>
<v t="bobjack.20080402172239.5"><vh>@menu Move To Chapter</vh>
<v t="bobjack.20080402172239.6"><vh>@item *</vh></v>
</v>
<v t="bobjack.20080402175002.3"><vh>@item -</vh></v>
<v t="bobjack.20080402175002.2"><vh>@item *create-chapter</vh></v>
<v t="bobjack.20080402175002.4"><vh>@item *remove-chapter</vh></v>
</v>
</v>
<v t="bobjack.20080401143954.2"><vh>... the plus box</vh>
<v t="bobjack.20080401143954.3"><vh>@popup plusbox</vh>
<v t="bobjack.20080401143954.4"><vh>@item label for menu</vh></v>
</v>
</v>
<v t="bobjack.20080401143613.3"><vh>... headlines</vh>
<v t="bobjack.20080401143613.4"><vh>@popup headline</vh>
<v t="bobjack.20080401143613.5"><vh>@item label for menu</vh></v>
</v>
</v>
<v t="bobjack.20080401214039.1"><vh>... the icon box</vh>
<v t="bobjack.20080401214039.2"><vh>@popup iconbox</vh>
<v t="bobjack.20080401214039.3"><vh>@item label for menu</vh></v>
</v>
</v>
</v>
</vnodes>
<tnodes>
<t tx="bobjack.20080324163716.1"></t>
<t tx="bobjack.20080324164314.1"></t>
<t tx="bobjack.20080326150321.5"></t>
<t tx="bobjack.20080326150321.6"></t>
<t tx="bobjack.20080326150321.7"></t>
<t tx="bobjack.20080326150321.8"></t>
<t tx="bobjack.20080326150321.9"></t>
<t tx="bobjack.20080329043447.2"></t>
<t tx="bobjack.20080329043447.3">edit-menu</t>
<t tx="bobjack.20080329051459.3">Example of using a pre-defined fragment.</t>
<t tx="bobjack.20080329051459.4">Example of using a user defined fragment.</t>
<t tx="bobjack.20080329051459.7">These do nothing! but could be made
to do something if you want.</t>
<t tx="bobjack.20080329052834.1"></t>
<t tx="bobjack.20080329053100.1">Example of a user defined fragment for inclusion
in other menus.</t>
<t tx="bobjack.20080329053100.2">find change fragment</t>
<t tx="bobjack.20080329054053.1"></t>
<t tx="bobjack.20080329054053.2"></t>
<t tx="bobjack.20080329054053.3"></t>
<t tx="bobjack.20080329054053.4"></t>
<t tx="bobjack.20080329054053.5">Cut</t>
<t tx="bobjack.20080329054053.6">Copy</t>
<t tx="bobjack.20080329054053.7">Paste</t>
<t tx="bobjack.20080329054053.8"></t>
<t tx="bobjack.20080329054053.9"></t>
<t tx="bobjack.20080329054053.10">this is an optional label</t>
<t tx="bobjack.20080329054053.11"></t>
<t tx="bobjack.20080329054053.12">Indent</t>
<t tx="bobjack.20080329054053.13">Dedent</t>
<t tx="bobjack.20080329054053.15"></t>
<t tx="bobjack.20080329054053.16">find change fragment</t>
<t tx="bobjack.20080329054053.17"></t>
<t tx="bobjack.20080329054053.18"></t>
<t tx="bobjack.20080329054053.19">rclick-gen-context-sensitive-commands</t>
<t tx="bobjack.20080329061442.1"></t>
<t tx="bobjack.20080329061442.2">recent-files-menu</t>
<t tx="bobjack.20080329061920.1"></t>
<t tx="bobjack.20080329061920.2"></t>
<t tx="bobjack.20080329062304.1"></t>
<t tx="bobjack.20080329062304.2">Example of using a pre-defined fragment.</t>
<t tx="bobjack.20080329062304.3">edit-menu</t>
<t tx="bobjack.20080329062304.10">Example of using a user defined fragment.</t>
<t tx="bobjack.20080329062304.11"></t>
<t tx="bobjack.20080329062304.12">find change fragment</t>
<t tx="bobjack.20080329062304.13"></t>
<t tx="bobjack.20080329062304.14"></t>
<t tx="bobjack.20080329062304.15">Set this to use the same menu as the find-text entry</t>
<t tx="bobjack.20080329062956.1"></t>
<t tx="bobjack.20080329063457.1">from pprint import pformat

g.es_print(pformat(c.context_menus))</t>
<t tx="bobjack.20080329070612.1">Here is a couple of tests you might like to try out:

    &lt;&lt; test 'Help on: ...' &gt;&gt;
    
    &lt;&lt; test 'Open URL: ...'&gt;&gt;
    
    http://localhost/
    
Select all the text above then right click.</t>
<t tx="bobjack.20080329070612.2">@
Hello,why don't you right click on

leoGlobals

then click on 'Help on: leoGlobals'</t>
<t tx="bobjack.20080329070612.3">@
Place the cursor in the url below, then right click.

    http://code.launchpad.net/leo-editor/
    
    http://localhost/</t>
<t tx="bobjack.20080329075629.2">


</t>
<t tx="bobjack.20080329075629.3">@popup &lt;name&gt; menus are converted to a list of tuples and stored in::
    
     c.context_menus[&lt;name&gt;]

Some of these names are special, like 'body', 'log', 'find-text', 'change-text'
'headline', 'canvas'.


Other names are not special. Menus with these names are 'fragments', that is
they are not meant to be full menus (although they could be used as such) but
are there to be included in other menus.

These fragments can be included in other menus by using ('&amp;','&lt;name&gt;') tuples in
a menu list or an '@item &amp;' node with the name of the fragment to be included as
the body text of the node.

Widgets may be given a context_menu attribute, eg

    w.context_menu = 'my special menu' | [&lt;menu list&gt;]

in which case the menu table in c.context_menus['my special menu'] will be used
as the popup if a string is provided, or if a list is provided that list will
be used as the menu table.  So each widget can have an individual menu.


Widgets must have &lt;Button-3&gt; bound to a callback that eventually raises either
a 'bodyrclick1' hook, such as c.frame.OnBodyRClick or a 'rclick-popup' hook.

Any keyword arguments included in the doHook call will be passed to generator
callbacks and invocation callbacks.
    
Menu tables in c.context_menus are live, they can be manipulated by scripts and
the changes will show up immediately.  See 'experiments'.

Changes to a fragment that is included in other menus will likewise show up
immediately in all those menus.


To get a right click menu for a widget use::
    
    g.doHook('rclick-popup', c=c, event=event, context_menu='&lt;default menu name&gt;', &lt;any key=value pairs...&gt;)


Make sure the event has passed through the master rclick handler before using the hook.
</t>
<t tx="bobjack.20080329075629.4"># Experiment with using scripts to create or manipulate menu tables.





</t>
<t tx="bobjack.20080330095006.2">def cb( x=None):

    def testMenuCallback(c, keywords, x=x):

        event = keywords.get('event')
        if x is None:
            x = keywords.get('rc_label')
        g.es('%s in %s' %(x,c.widget_name(event.widget)), color='blue')

    return testMenuCallback

c.context_menus['log'] = [

    ('11', cb()),
    ('12', cb('12')),
    ('13', cb('13')),
    ('14', cb('14')),
    ('|', None),
    ('xone', cb('one')),
    ('xtwo', cb()),
    ('xthree', cb('three')),
    ('xfour', cb('four')),
    ('|', None),    
    ('&amp;', 'edit-menu'),
]
g.es('replaced log menu', color='blue')
</t>
<t tx="bobjack.20080330095006.3">"""This change will be reflected in all menus that use the 'edit-menu'
fragment. Check before and after in the log and find and change text boxes. """

et = c.context_menus['edit-menu'] 
c.context_menus['edit-menu'] = et[:-2]
g.es('removed select-all from ALL edit-menus', color='blue')</t>
<t tx="bobjack.20080401113850.2"></t>
<t tx="bobjack.20080401113850.3">Canvas Menu</t>
<t tx="bobjack.20080401143613.2"></t>
<t tx="bobjack.20080401143613.3"></t>
<t tx="bobjack.20080401143613.4">@
Remove the '@item headline menu' node to leave an '@popup headline' node with no childeren to restore the standard tree popup menu.
 
Alternativly, setting

    c.context_menus['headline'] = []
    
will also restore the leo standard popup menu. Highlight the code above and execute it to see the effect.</t>
<t tx="bobjack.20080401143613.5">Headline Menu</t>
<t tx="bobjack.20080401143954.2"></t>
<t tx="bobjack.20080401143954.3"></t>
<t tx="bobjack.20080401143954.4">Plus Box Menu</t>
<t tx="bobjack.20080401213023.1">Change Text Menu</t>
<t tx="bobjack.20080401213339.1">Find Text Menu</t>
<t tx="bobjack.20080401213339.2"></t>
<t tx="bobjack.20080401213339.3"></t>
<t tx="bobjack.20080401213500.1"></t>
<t tx="bobjack.20080401213500.2">find_change_text_menu</t>
<t tx="bobjack.20080401214039.1"></t>
<t tx="bobjack.20080401214039.2">@
Icon box menus will be disabled by cleo or other plugind using the same hook.

Remove the '@item iconbox menu' node to leave an '@popup iconbox' node with no childeren to restore the standard tree popup menu.
 
Alternativly, setting

    c.context_menus['iconbox'] = []
    
will also restore the leo standard popup menu. Highlight the code above and execute it to see the effect.</t>
<t tx="bobjack.20080401214039.3">Icon Box Menu</t>
<t tx="bobjack.20080402071100.2">@
This setting determines where the output of rclick's "Help on: ...""
menu item goes.

The setting can contain a list of words which may include 'print', 'log', 'browser' or 'all'.

if 'log' appears in the list, output will go to the log pane.
if 'print' appears in the list, output will be sent to standard out.

if 'browser' appears in the list then a browser will be launched and the output will be displayed as a web page.

If 'all' appears in the list, output will go to all these destinations
regardless of what else is in the list.

Example::
    
    @string rclick-show-help = print log
    </t>
<t tx="bobjack.20080402154726.5"></t>
<t tx="bobjack.20080402160713.6"></t>
<t tx="bobjack.20080402160713.7"></t>
<t tx="bobjack.20080402160713.8"></t>
<t tx="bobjack.20080402160713.9"></t>
<t tx="bobjack.20080402160713.10">clone-node-to-chapter-menu</t>
<t tx="bobjack.20080402160713.11">find_change_text_menu</t>
<t tx="bobjack.20080402172239.2"></t>
<t tx="bobjack.20080402172239.3"></t>
<t tx="bobjack.20080402172239.4">copy-node-to-chapter-menu</t>
<t tx="bobjack.20080402172239.5"></t>
<t tx="bobjack.20080402172239.6">move-node-to-chapter-menu</t>
<t tx="bobjack.20080402175002.2"></t>
<t tx="bobjack.20080402175002.3"></t>
<t tx="bobjack.20080402175002.4"></t>
<t tx="bobjack.20080402175002.5"></t>
<t tx="bobjack.20080402175002.6"></t>
<t tx="bobjack.20080403171532.7">1
kind = radio
group = test1
name = test-one-one
</t>
<t tx="bobjack.20080403171532.8">2
kind = radio
group = test1
name = test-one-two

</t>
<t tx="bobjack.20080403171532.9">3
kind = radio
group = test2
name = test-two-three</t>
<t tx="bobjack.20080403171532.11">4
kind = radio
group = test2
name = test-two-four

</t>
<t tx="bobjack.20080404054928.6">1
kind = check
name = check-one

</t>
<t tx="bobjack.20080404054928.7"></t>
<t tx="bobjack.20080404054928.8">Although the general purpose rclick-check-button is used here
which emits </t>
<t tx="bobjack.20080404054928.9"></t>
<t tx="bobjack.20080404054928.10"></t>
<t tx="bobjack.20080404054928.11">2
kind = check
name = check-two



</t>
<t tx="bobjack.20080404054928.12">3
kind = check
name = check-three

</t>
<t tx="bobjack.20080404054928.13">4
kind = check
name = check-four


</t>
<t tx="bobjack.20080404111009.1"></t>
<t tx="bobjack.20080404113810.1"># Run this as a script to enable reporting of changes
# to the check/radio menu items in the log panel menu.

# Example: how to initialize/modify item settings

cm = c.theContextMenuController

groups = cm.radio_group_data
checks = cm.check_button_data

groups['test1'] = 'test-one-two'
groups['test2'] = 'test-two-one'
checks['check-two'] = True

def report_item_clicked(tag, keywords):

    """
    Note: This keywords is different from the the

        c.theContextMenuControler.mb_keywords

    which contains all the information about the right click
    that posted the menu that this event derives from.

    mb_keywords tells which widget the right click occured in,
    among other things.
    """

    kind, selected, name, group = \
        [keywords.get(v) for v in (
            'kind', 'selected', 'name', 'group')]

    if kind == 'radio':
         g.es("Rclick Test Radio Group['%s'] Selected['%s']"%(
            group, selected))

    if kind == 'check':
        g.es("Rclick Test Check Button Name['%s']  Checked:[%s]"% (
            name, bool(selected)))

import leoPlugins
leoPlugins.registerHandler("rclick-button-clicked", report_item_clicked)

g.es('registered to recieve radio/check button events', color='blue')
</t>
<t tx="bobjack.20080405081601.2">cm = c.theContextMenuController

groups = cm.radio_group_data
checks = cm.check_button_data

g.es('\ngroups\n======', color='blue')

for group, selected in sorted(groups.iteritems()):
    g.es("'%s' -&gt; '%s'"%(group, selected), color='blue')

g.es("\nchecks\n======", color = 'blue')

for check, selected in sorted(checks.iteritems()):
    g.es("'%s' -&gt; %s"%(check, selected), color='blue')

</t>
<t tx="bobjack.20080412154131.2"></t>
</tnodes>
</leo_file>
