# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_main.ui'
#
# Created: Sun Oct 19 07:32:18 2008
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(957, 778)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter_2 = QtGui.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.treeWidget = QtGui.QTreeWidget(self.splitter)
        self.treeWidget.setObjectName("treeWidget")
        self.tabWidget = QtGui.QTabWidget(self.splitter)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textBrowser = QtGui.QTextBrowser(self.tab)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_3.addWidget(self.textBrowser)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout = QtGui.QGridLayout(self.tab_2)
        self.gridLayout.setObjectName("gridLayout")
        self.findPattern = QtGui.QLineEdit(self.tab_2)
        self.findPattern.setObjectName("findPattern")
        self.gridLayout.addWidget(self.findPattern, 0, 1, 1, 1)
        self.findChange = QtGui.QLineEdit(self.tab_2)
        self.findChange.setObjectName("findChange")
        self.gridLayout.addWidget(self.findChange, 1, 1, 1, 1)
        self.checkBoxWholeWord = QtGui.QCheckBox(self.tab_2)
        self.checkBoxWholeWord.setObjectName("checkBoxWholeWord")
        self.gridLayout.addWidget(self.checkBoxWholeWord, 2, 0, 1, 1)
        self.checkBoxEntireOutline = QtGui.QCheckBox(self.tab_2)
        self.checkBoxEntireOutline.setObjectName("checkBoxEntireOutline")
        self.gridLayout.addWidget(self.checkBoxEntireOutline, 2, 1, 1, 1)
        self.checkBoxIgnoreCase = QtGui.QCheckBox(self.tab_2)
        self.checkBoxIgnoreCase.setObjectName("checkBoxIgnoreCase")
        self.gridLayout.addWidget(self.checkBoxIgnoreCase, 3, 0, 1, 1)
        self.checkBoxSubroutineOnly = QtGui.QCheckBox(self.tab_2)
        self.checkBoxSubroutineOnly.setObjectName("checkBoxSubroutineOnly")
        self.gridLayout.addWidget(self.checkBoxSubroutineOnly, 3, 1, 1, 1)
        self.checkBoxWrapAround = QtGui.QCheckBox(self.tab_2)
        self.checkBoxWrapAround.setObjectName("checkBoxWrapAround")
        self.gridLayout.addWidget(self.checkBoxWrapAround, 4, 0, 1, 1)
        self.checkBoxNodeOnly = QtGui.QCheckBox(self.tab_2)
        self.checkBoxNodeOnly.setObjectName("checkBoxNodeOnly")
        self.gridLayout.addWidget(self.checkBoxNodeOnly, 4, 1, 1, 1)
        self.checkBoxReverse = QtGui.QCheckBox(self.tab_2)
        self.checkBoxReverse.setObjectName("checkBoxReverse")
        self.gridLayout.addWidget(self.checkBoxReverse, 5, 0, 1, 1)
        self.checkBoxSearchHeadline = QtGui.QCheckBox(self.tab_2)
        self.checkBoxSearchHeadline.setObjectName("checkBoxSearchHeadline")
        self.gridLayout.addWidget(self.checkBoxSearchHeadline, 5, 1, 1, 1)
        self.checkBoxRexexp = QtGui.QCheckBox(self.tab_2)
        self.checkBoxRexexp.setObjectName("checkBoxRexexp")
        self.gridLayout.addWidget(self.checkBoxRexexp, 6, 0, 1, 1)
        self.checkBoxSearchBody = QtGui.QCheckBox(self.tab_2)
        self.checkBoxSearchBody.setObjectName("checkBoxSearchBody")
        self.gridLayout.addWidget(self.checkBoxSearchBody, 6, 1, 1, 1)
        self.checkBoxMarkFinds = QtGui.QCheckBox(self.tab_2)
        self.checkBoxMarkFinds.setObjectName("checkBoxMarkFinds")
        self.gridLayout.addWidget(self.checkBoxMarkFinds, 7, 0, 1, 1)
        self.checkBoxMarkChanges = QtGui.QCheckBox(self.tab_2)
        self.checkBoxMarkChanges.setObjectName("checkBoxMarkChanges")
        self.gridLayout.addWidget(self.checkBoxMarkChanges, 7, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.stackedWidget = QtGui.QStackedWidget(self.splitter_2)
        self.stackedWidget.setAcceptDrops(True)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textEdit = Qsci.QsciScintilla(self.page)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.textEdit)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.richTextEdit = QtGui.QTextEdit(self.page_2)
        self.richTextEdit.setObjectName("richTextEdit")
        self.verticalLayout_4.addWidget(self.richTextEdit)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.splitter_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 957, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionIPython = QtGui.QAction(MainWindow)
        self.actionIPython.setObjectName("actionIPython")
        self.label.setBuddy(self.lineEdit)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.treeWidget, QtCore.SIGNAL("itemSelectionChanged()"), MainWindow.showNormal)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Leo", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxWholeWord.setText(QtGui.QApplication.translate("MainWindow", "Whole Word", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxEntireOutline.setText(QtGui.QApplication.translate("MainWindow", "Entire Outline", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxIgnoreCase.setText(QtGui.QApplication.translate("MainWindow", "Ignore Case", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxSubroutineOnly.setText(QtGui.QApplication.translate("MainWindow", "Subroutine Only", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxWrapAround.setText(QtGui.QApplication.translate("MainWindow", "Wrap Around", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxNodeOnly.setText(QtGui.QApplication.translate("MainWindow", "Node Only", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxReverse.setText(QtGui.QApplication.translate("MainWindow", "Reverse", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxSearchHeadline.setText(QtGui.QApplication.translate("MainWindow", "Search Headline", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxRexexp.setText(QtGui.QApplication.translate("MainWindow", "Regexp", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxSearchBody.setText(QtGui.QApplication.translate("MainWindow", "Search Body", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxMarkFinds.setText(QtGui.QApplication.translate("MainWindow", "Mark Finds", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxMarkChanges.setText(QtGui.QApplication.translate("MainWindow", "Mark Changes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Find:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Change:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Tab 2", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Page", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Minibuffer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIPython.setText(QtGui.QApplication.translate("MainWindow", "IPython", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import Qsci
