<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet ekr_test?>
<leo_file>
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5">
	<global_window_position top="215" left="332" height="600" width="800"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="ekr.20100224071313.1852" str_leo_pos="1,0"><vh>@chapters</vh></v>
<v t="ekr.20100224071313.1851" a="E" tnodeList="ekr.20100224071313.1851,ekr.20100224071313.1853"><vh>@file at-file-test.py</vh>
<v t="ekr.20100224071313.1853"><vh>spam</vh></v>
</v>
</vnodes>
<tnodes>
<t tx="ekr.20100224071313.1851">@others</t>
<t tx="ekr.20100224071313.1852"></t>
<t tx="ekr.20100224071313.1853">def spam():
    pass</t>
</tnodes>
</leo_file>
