#!/usr/bin/env python
"""This file is automatically generated by generate_version_info
It uses the current working tree to determine the revision.
So don't edit it. :)
"""

version_info = {'branch_nick': 'trunk',
 'build_date': '2011-12-14 10:59:57 -0500',
 'clean': None,
 'date': '2011-12-14 10:57:26 -0500',
 'revision_id': 'edreamleo@gmail.com-20111214155726-h20z8hr5xspx5vb8',
 'revno': '4878'}

revisions = {}

file_revisions = {}


if __name__ == '__main__':
    print('revision: %(revno)s' % version_info)
    print('nick: %(branch_nick)s' % version_info)
    print('revision id: %(revision_id)s' % version_info)
