#!/usr/bin/env python
"""This file is automatically generated by generate_version_info
It uses the current working tree to determine the revision.
So don't edit it. :)
"""

version_info = {'branch_nick': 'trunk',
 'build_date': '2011-11-24 14:56:52 -0600',
 'clean': None,
 'date': '2011-11-24 14:56:14 -0600',
 'revision_id': 'edreamleo@gmail.com-20111124205614-zyp47ax8q7jpf4jk',
 'revno': '4847'}

revisions = {}

file_revisions = {}


if __name__ == '__main__':
    print('revision: %(revno)s' % version_info)
    print('nick: %(branch_nick)s' % version_info)
    print('revision id: %(revision_id)s' % version_info)
