# Leo colorizer control file for cobol mode.
# This file is in the public domain.

# Properties for cobol mode.
properties = {
    "lineComment": "*",
}

# Attributes dict for cobol_main ruleset.
cobol_main_attributes_dict = {
    "default": "null",
    "digit_re": "",
    "escape": "\\",
    "highlight_digits": "true",
    "ignore_case": "true",
    "no_word_sep": "",
}

# Dictionary of attributes dictionaries for cobol mode.
attributesDictDict = {
    "cobol_main": cobol_main_attributes_dict,
}

# Keywords dict for cobol_main ruleset.
cobol_main_keywords_dict = {
    "[copy-prefix]": "literal2",
    "[count]": "literal2",
    "[display]": "literal2",
    "[execute]": "literal2",
    "[pg]": "literal2",
    "[prefix]": "literal2",
    "[program]": "literal2",
    "[special-prefix]": "literal2",
    "[testcase]": "literal2",
    "accept": "keyword1",
    "access": "keyword1",
    "acos": "keyword2",
    "actual": "keyword1",
    "add": "keyword1",
    "address": "keyword1",
    "advancing": "keyword1",
    "after": "keyword1",
    "all": "keyword1",
    "alphabet": "keyword1",
    "alphabetic": "keyword1",
    "alphabetic-lower": "keyword1",
    "alphabetic-upper": "keyword1",
    "alphanumeric": "keyword1",
    "alphanumeric-edited": "keyword1",
    "also": "keyword1",
    "alter": "keyword1",
    "alternate": "keyword1",
    "and": "keyword1",
    "annuity": "keyword2",
    "any": "keyword1",
    "api": "keyword1",
    "apply": "keyword1",
    "are": "keyword1",
    "area": "keyword1",
    "areas": "keyword1",
    "ascending": "keyword1",
    "asin": "keyword2",
    "assign": "keyword1",
    "at": "keyword1",
    "atan": "keyword2",
    "author": "keyword1",
    "auto": "keyword1",
    "auto-skip": "keyword1",
    "automatic": "keyword1",
    "background-color": "keyword1",
    "background-colour": "keyword1",
    "backward": "keyword1",
    "basis": "keyword1",
    "beep": "keyword1",
    "before": "keyword1",
    "beginning": "keyword1",
    "bell": "keyword1",
    "binary": "keyword1",
    "blank": "keyword1",
    "blink": "keyword1",
    "block": "keyword1",
    "bottom": "keyword1",
    "by": "keyword1",
    "c01": "keyword1",
    "c02": "keyword1",
    "c03": "keyword1",
    "c04": "keyword1",
    "c05": "keyword1",
    "c06": "keyword1",
    "c07": "keyword1",
    "c08": "keyword1",
    "c09": "keyword1",
    "c10": "keyword1",
    "c11": "keyword1",
    "c12": "keyword1",
    "call": "keyword1",
    "call-convention": "keyword1",
    "cancel": "keyword1",
    "cbl": "keyword1",
    "cd": "keyword1",
    "cf": "keyword1",
    "ch": "keyword1",
    "chain": "keyword1",
    "chaining": "keyword1",
    "changed": "keyword1",
    "char": "keyword2",
    "character": "keyword1",
    "characters": "keyword1",
    "class": "keyword1",
    "clock-units": "keyword1",
    "close": "keyword1",
    "cobol": "keyword1",
    "code": "keyword1",
    "code-set": "keyword1",
    "col": "keyword1",
    "collating": "keyword1",
    "column": "keyword1",
    "com-reg": "keyword1",
    "comma": "keyword1",
    "commit": "keyword1",
    "common": "keyword1",
    "communication": "keyword1",
    "comp": "keyword1",
    "comp-0": "keyword1",
    "comp-1": "keyword1",
    "comp-2": "keyword1",
    "comp-3": "keyword1",
    "comp-4": "keyword1",
    "comp-5": "keyword1",
    "comp-6": "keyword1",
    "comp-x": "keyword1",
    "computational": "keyword1",
    "computational-0": "keyword1",
    "computational-1": "keyword1",
    "computational-2": "keyword1",
    "computational-3": "keyword1",
    "computational-4": "keyword1",
    "computational-5": "keyword1",
    "computational-6": "keyword1",
    "computational-x": "keyword1",
    "compute": "keyword1",
    "configuration": "keyword1",
    "console": "keyword1",
    "contains": "keyword1",
    "content": "keyword1",
    "continue": "keyword1",
    "control": "keyword1",
    "controls": "keyword1",
    "converting": "keyword1",
    "copy": "keyword1",
    "core-index": "keyword1",
    "corr": "keyword1",
    "corresponding": "keyword1",
    "cos": "keyword2",
    "count": "keyword1",
    "crt": "keyword1",
    "crt-under": "keyword1",
    "currency": "keyword1",
    "current-date": "keyword2",
    "cursor": "keyword1",
    "cycle": "keyword1",
    "cyl-index": "keyword1",
    "cyl-overflow": "keyword1",
    "data": "keyword1",
    "date": "keyword1",
    "date-compiled": "keyword1",
    "date-of-integer": "keyword2",
    "date-written": "keyword1",
    "day": "keyword1",
    "day-of-integer": "keyword2",
    "day-of-week": "keyword1",
    "dbcs": "keyword1",
    "de": "keyword1",
    "debug": "keyword1",
    "debug-contents": "keyword1",
    "debug-item": "keyword1",
    "debug-line": "keyword1",
    "debug-name": "keyword1",
    "debug-sub-1": "keyword1",
    "debug-sub-2": "keyword1",
    "debug-sub-3": "keyword1",
    "debugging": "keyword1",
    "decimal-point": "keyword1",
    "declaratives": "keyword1",
    "delete": "keyword1",
    "delimited": "keyword1",
    "delimiter": "keyword1",
    "depending": "keyword1",
    "descending": "keyword1",
    "destination": "keyword1",
    "detail": "keyword1",
    "disable": "keyword1",
    "disk": "keyword1",
    "disp": "keyword1",
    "display": "keyword1",
    "display-1": "keyword1",
    "display-st": "keyword1",
    "divide": "keyword1",
    "division": "keyword1",
    "down": "keyword1",
    "duplicates": "keyword1",
    "dynamic": "keyword1",
    "echo": "keyword1",
    "egcs": "keyword1",
    "egi": "keyword1",
    "eject": "keyword1",
    "else": "keyword1",
    "emi": "keyword1",
    "empty-check": "keyword1",
    "enable": "keyword1",
    "end": "keyword1",
    "end-accept": "keyword1",
    "end-add": "keyword1",
    "end-call": "keyword1",
    "end-chain": "keyword1",
    "end-compute": "keyword1",
    "end-delete": "keyword1",
    "end-display": "keyword1",
    "end-divide": "keyword1",
    "end-evaluate": "keyword1",
    "end-if": "keyword1",
    "end-invoke": "keyword1",
    "end-multiply": "keyword1",
    "end-of-page": "keyword1",
    "end-perform": "keyword1",
    "end-read": "keyword1",
    "end-receive": "keyword1",
    "end-return": "keyword1",
    "end-rewrite": "keyword1",
    "end-search": "keyword1",
    "end-start": "keyword1",
    "end-string": "keyword1",
    "end-subtract": "keyword1",
    "end-unstring": "keyword1",
    "end-write": "keyword1",
    "ending": "keyword1",
    "enter": "keyword1",
    "entry": "keyword1",
    "environment": "keyword1",
    "eol": "keyword1",
    "eop": "keyword1",
    "eos": "keyword1",
    "equal": "keyword1",
    "equals": "keyword1",
    "erase": "keyword1",
    "error": "keyword1",
    "escape": "keyword1",
    "esi": "keyword1",
    "evaluate": "keyword1",
    "every": "keyword1",
    "examine": "keyword1",
    "exceeds": "keyword1",
    "exception": "keyword1",
    "excess-3": "keyword1",
    "exclusive": "keyword1",
    "exec": "keyword1",
    "execute": "keyword1",
    "exhibit": "keyword1",
    "exit": "keyword1",
    "extend": "keyword1",
    "extended-search": "keyword1",
    "external": "keyword1",
    "factorial": "keyword2",
    "factory": "keyword1",
    "false": "keyword1",
    "fd": "keyword1",
    "fh-fcd": "keyword1",
    "fh-keydef": "keyword1",
    "file": "keyword1",
    "file-control": "keyword1",
    "file-id": "keyword1",
    "file-limit": "keyword1",
    "file-limits": "keyword1",
    "filler": "keyword1",
    "final": "keyword1",
    "first": "keyword1",
    "fixed": "keyword1",
    "footing": "keyword1",
    "for": "keyword1",
    "foreground-color": "keyword1",
    "foreground-colour": "keyword1",
    "from": "keyword1",
    "full": "keyword1",
    "function": "keyword1",
    "generate": "keyword1",
    "giving": "keyword1",
    "global": "keyword1",
    "go": "keyword1",
    "goback": "keyword1",
    "greater": "keyword1",
    "grid": "keyword1",
    "group": "keyword1",
    "heading": "keyword1",
    "high": "keyword1",
    "high-value": "keyword1",
    "high-values": "keyword1",
    "highlight": "keyword1",
    "i-o": "keyword1",
    "i-o-control": "keyword1",
    "id": "keyword1",
    "identification": "keyword1",
    "if": "keyword1",
    "ignore": "keyword1",
    "in": "keyword1",
    "index": "keyword1",
    "indexed": "keyword1",
    "indicate": "keyword1",
    "inheriting": "keyword1",
    "initial": "keyword1",
    "initialize": "keyword1",
    "initiate": "keyword1",
    "input": "keyword1",
    "input-output": "keyword1",
    "insert": "keyword1",
    "inspect": "keyword1",
    "installation": "keyword1",
    "integer": "keyword2",
    "integer-of-date": "keyword2",
    "integer-of-day": "keyword2",
    "integer-part": "keyword2",
    "into": "keyword1",
    "invalid": "keyword1",
    "invoke": "keyword1",
    "is": "keyword1",
    "japanese": "keyword1",
    "just": "keyword1",
    "justified": "keyword1",
    "kanji": "keyword1",
    "kept": "keyword1",
    "key": "keyword1",
    "keyboard": "keyword1",
    "label": "keyword1",
    "last": "keyword1",
    "leading": "keyword1",
    "leave": "keyword1",
    "left": "keyword1",
    "left-justify": "keyword1",
    "leftline": "keyword1",
    "length": "keyword1",
    "length-check": "keyword1",
    "less": "keyword1",
    "limit": "keyword1",
    "limits": "keyword1",
    "lin": "keyword1",
    "linage": "keyword1",
    "linage-counter": "keyword1",
    "line": "keyword1",
    "line-counter": "keyword1",
    "lines": "keyword1",
    "linkage": "keyword1",
    "local-storage": "keyword1",
    "lock": "keyword1",
    "locking": "keyword1",
    "log": "keyword2",
    "log10": "keyword2",
    "low": "keyword1",
    "low-value": "keyword1",
    "low-values": "keyword1",
    "lower": "keyword1",
    "lower-case": "keyword2",
    "lowlight": "keyword1",
    "manual": "keyword1",
    "master-index": "keyword1",
    "max": "keyword2",
    "mean": "keyword2",
    "median": "keyword2",
    "memory": "keyword1",
    "merge": "keyword1",
    "message": "keyword1",
    "method": "keyword1",
    "midrange": "keyword2",
    "min": "keyword2",
    "mod": "keyword2",
    "mode": "keyword1",
    "modules": "keyword1",
    "more-labels": "keyword1",
    "move": "keyword1",
    "multiple": "keyword1",
    "multiply": "keyword1",
    "name": "keyword1",
    "named": "keyword1",
    "national": "keyword1",
    "national-edited": "keyword1",
    "native": "keyword1",
    "nchar": "keyword1",
    "negative": "keyword1",
    "next": "keyword1",
    "no": "keyword1",
    "no-echo": "keyword1",
    "nominal": "keyword1",
    "not": "keyword1",
    "note": "keyword1",
    "nstd-reels": "keyword1",
    "null": "keyword1",
    "nulls": "keyword1",
    "number": "keyword1",
    "numeric": "keyword1",
    "numeric-edited": "keyword1",
    "numval": "keyword2",
    "numval-c": "keyword2",
    "object": "keyword1",
    "object-computer": "keyword1",
    "object-storage": "keyword1",
    "occurs": "keyword1",
    "of": "keyword1",
    "off": "keyword1",
    "omitted": "keyword1",
    "on": "keyword1",
    "oostackptr": "keyword1",
    "open": "keyword1",
    "optional": "keyword1",
    "or": "keyword1",
    "ord": "keyword2",
    "ord-max": "keyword2",
    "ord-min": "keyword2",
    "order": "keyword1",
    "organization": "keyword1",
    "other": "keyword1",
    "otherwise": "keyword1",
    "output": "keyword1",
    "overflow": "keyword1",
    "overline": "keyword1",
    "packed-decimal": "keyword1",
    "padding": "keyword1",
    "page": "keyword1",
    "page-counter": "keyword1",
    "paragraph": "keyword1",
    "password": "keyword1",
    "perform": "keyword1",
    "pf": "keyword1",
    "ph": "keyword1",
    "pic": "keyword1",
    "picture": "keyword1",
    "plus": "keyword1",
    "pointer": "keyword1",
    "pos": "keyword1",
    "position": "keyword1",
    "positioning": "keyword1",
    "positive": "keyword1",
    "present-value": "keyword2",
    "previous": "keyword1",
    "print": "keyword1",
    "print-switch": "keyword1",
    "printer": "keyword1",
    "printer-1": "keyword1",
    "printing": "keyword1",
    "private": "keyword1",
    "procedure": "keyword1",
    "procedure-pointer": "keyword1",
    "procedures": "keyword1",
    "proceed": "keyword1",
    "processing": "keyword1",
    "program": "keyword1",
    "program-id": "keyword1",
    "prompt": "keyword1",
    "protected": "keyword1",
    "public": "keyword1",
    "purge": "keyword1",
    "queue": "keyword1",
    "quote": "keyword1",
    "quotes": "keyword1",
    "random": "keyword2",
    "range": "keyword2",
    "rd": "keyword1",
    "read": "keyword1",
    "ready": "keyword1",
    "receive": "keyword1",
    "record": "keyword1",
    "record-overflow": "keyword1",
    "recording": "keyword1",
    "records": "keyword1",
    "redefines": "keyword1",
    "reel": "keyword1",
    "reference": "keyword1",
    "references": "keyword1",
    "relative": "keyword1",
    "release": "keyword1",
    "reload": "keyword1",
    "rem": "keyword2",
    "remainder": "keyword1",
    "remarks": "keyword1",
    "removal": "keyword1",
    "renames": "keyword1",
    "reorg-criteria": "keyword1",
    "replace": "keyword1",
    "replacing": "keyword1",
    "report": "keyword1",
    "reporting": "keyword1",
    "reports": "keyword1",
    "required": "keyword1",
    "reread": "keyword1",
    "rerun": "keyword1",
    "reserve": "keyword1",
    "reset": "keyword1",
    "return": "keyword1",
    "return-code": "keyword1",
    "returning": "keyword1",
    "reverse": "keyword2",
    "reverse-video": "keyword1",
    "reversed": "keyword1",
    "rewind": "keyword1",
    "rewrite": "keyword1",
    "rf": "keyword1",
    "rh": "keyword1",
    "right": "keyword1",
    "right-justify": "keyword1",
    "rollback": "keyword1",
    "rounded": "keyword1",
    "run": "keyword1",
    "s01": "keyword1",
    "s02": "keyword1",
    "s03": "keyword1",
    "s04": "keyword1",
    "s05": "keyword1",
    "same": "keyword1",
    "screen": "keyword1",
    "sd": "keyword1",
    "search": "keyword1",
    "section": "keyword1",
    "secure": "keyword1",
    "security": "keyword1",
    "seek": "keyword1",
    "segment": "keyword1",
    "segment-limit": "keyword1",
    "select": "keyword1",
    "selective": "keyword1",
    "send": "keyword1",
    "sentence": "keyword1",
    "separate": "keyword1",
    "sequence": "keyword1",
    "sequential": "keyword1",
    "service": "keyword1",
    "set": "keyword1",
    "shift-in": "keyword1",
    "shift-out": "keyword1",
    "sign": "keyword1",
    "sin": "keyword2",
    "size": "keyword1",
    "skip1": "keyword1",
    "skip2": "keyword1",
    "skip3": "keyword1",
    "sort": "keyword1",
    "sort-control": "keyword1",
    "sort-core-size": "keyword1",
    "sort-file-size": "keyword1",
    "sort-merge": "keyword1",
    "sort-message": "keyword1",
    "sort-mode-size": "keyword1",
    "sort-option": "keyword1",
    "sort-return": "keyword1",
    "source": "keyword1",
    "source-computer": "keyword1",
    "space": "keyword1",
    "space-fill": "keyword1",
    "spaces": "keyword1",
    "special-names": "keyword1",
    "sqrt": "keyword2",
    "standard": "keyword1",
    "standard-1": "keyword1",
    "standard-2": "keyword1",
    "standard-deviation": "keyword2",
    "start": "keyword1",
    "status": "keyword1",
    "stop": "keyword1",
    "store": "keyword1",
    "string": "keyword1",
    "sub-queue-1": "keyword1",
    "sub-queue-2": "keyword1",
    "sub-queue-3": "keyword1",
    "subtract": "keyword1",
    "sum": "keyword2",
    "super": "keyword1",
    "suppress": "keyword1",
    "symbolic": "keyword1",
    "sync": "keyword1",
    "synchronized": "keyword1",
    "sysin": "keyword1",
    "sysipt": "keyword1",
    "syslst": "keyword1",
    "sysout": "keyword1",
    "syspch": "keyword1",
    "syspunch": "keyword1",
    "tab": "keyword1",
    "table": "keyword1",
    "tally": "keyword1",
    "tallying": "keyword1",
    "tan": "keyword2",
    "tape": "keyword1",
    "terminal": "keyword1",
    "terminate": "keyword1",
    "test": "keyword1",
    "text": "keyword1",
    "than": "keyword1",
    "then": "keyword1",
    "through": "keyword1",
    "thru": "keyword1",
    "time": "keyword1",
    "time-of-day": "keyword1",
    "time-out": "keyword1",
    "timeout": "keyword1",
    "times": "keyword1",
    "title": "keyword1",
    "to": "keyword1",
    "top": "keyword1",
    "totaled": "keyword1",
    "totaling": "keyword1",
    "trace": "keyword1",
    "track-area": "keyword1",
    "track-limit": "keyword1",
    "tracks": "keyword1",
    "trailing": "keyword1",
    "trailing-sign": "keyword1",
    "transform": "keyword1",
    "true": "keyword1",
    "type": "keyword1",
    "typedef": "keyword1",
    "underline": "keyword1",
    "unequal": "keyword1",
    "unit": "keyword1",
    "unlock": "keyword1",
    "unstring": "keyword1",
    "until": "keyword1",
    "up": "keyword1",
    "update": "keyword1",
    "upon": "keyword1",
    "upper": "keyword1",
    "upper-case": "keyword2",
    "upsi-0": "keyword1",
    "upsi-1": "keyword1",
    "upsi-2": "keyword1",
    "upsi-3": "keyword1",
    "upsi-4": "keyword1",
    "upsi-5": "keyword1",
    "upsi-6": "keyword1",
    "upsi-7": "keyword1",
    "usage": "keyword1",
    "use": "keyword1",
    "user": "keyword1",
    "using": "keyword1",
    "value": "keyword1",
    "values": "keyword1",
    "variable": "keyword1",
    "variance": "keyword2",
    "varying": "keyword1",
    "wait": "keyword1",
    "when": "keyword1",
    "when-compiled": "keyword2",
    "with": "keyword1",
    "words": "keyword1",
    "working-storage": "keyword1",
    "write": "keyword1",
    "write-only": "keyword1",
    "write-verify": "keyword1",
    "zero": "keyword1",
    "zero-fill": "keyword1",
    "zeroes": "keyword1",
    "zeros": "keyword1",
}

# Dictionary of keywords dictionaries for cobol mode.
keywordsDictDict = {
    "cobol_main": cobol_main_keywords_dict,
}

# Rules for cobol_main ruleset.

def cobol_rule0(colorer, s, i):
    return colorer.match_eol_span(s, i, kind="comment1", seq="*",
          at_line_start=True)

def cobol_rule1(colorer, s, i):
    return colorer.match_span(s, i, kind="literal1", begin="\"", end="\"")

def cobol_rule2(colorer, s, i):
    return colorer.match_span(s, i, kind="literal1", begin="'", end="'")

def cobol_rule3(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq="=")

def cobol_rule4(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq=" >=")

def cobol_rule5(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq=" <=")

def cobol_rule6(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq="+")

def cobol_rule7(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq="-")

def cobol_rule8(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq="/")

def cobol_rule9(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq="*")

def cobol_rule10(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq="**")

def cobol_rule11(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq=" > ")

def cobol_rule12(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq=" < ")

def cobol_rule13(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq="%")

def cobol_rule14(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq=" & ")

def cobol_rule15(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq="|")

def cobol_rule16(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq="^")

def cobol_rule17(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq="~")

def cobol_rule18(colorer, s, i):
    return colorer.match_span(s, i, kind="comment2", begin="EXEC SQL", end="END-EXEC")

def cobol_rule19(colorer, s, i):
    return colorer.match_keywords(s, i)

# Rules dict for cobol_main ruleset.
rulesDict1 = {
    " ": [cobol_rule4, cobol_rule5, cobol_rule11, cobol_rule12, cobol_rule14,],
    "\"": [cobol_rule1,],
    "%": [cobol_rule13,],
    "'": [cobol_rule2,],
    "*": [cobol_rule0, cobol_rule9, cobol_rule10,],
    "+": [cobol_rule6,],
    "-": [cobol_rule7, cobol_rule19,],
    "/": [cobol_rule8,],
    "0": [cobol_rule19,],
    "1": [cobol_rule19,],
    "2": [cobol_rule19,],
    "3": [cobol_rule19,],
    "4": [cobol_rule19,],
    "5": [cobol_rule19,],
    "6": [cobol_rule19,],
    "7": [cobol_rule19,],
    "8": [cobol_rule19,],
    "9": [cobol_rule19,],
    "=": [cobol_rule3,],
    "@": [cobol_rule19,],
    "A": [cobol_rule19,],
    "B": [cobol_rule19,],
    "C": [cobol_rule19,],
    "D": [cobol_rule19,],
    "E": [cobol_rule18, cobol_rule19,],
    "F": [cobol_rule19,],
    "G": [cobol_rule19,],
    "H": [cobol_rule19,],
    "I": [cobol_rule19,],
    "J": [cobol_rule19,],
    "K": [cobol_rule19,],
    "L": [cobol_rule19,],
    "M": [cobol_rule19,],
    "N": [cobol_rule19,],
    "O": [cobol_rule19,],
    "P": [cobol_rule19,],
    "Q": [cobol_rule19,],
    "R": [cobol_rule19,],
    "S": [cobol_rule19,],
    "T": [cobol_rule19,],
    "U": [cobol_rule19,],
    "V": [cobol_rule19,],
    "W": [cobol_rule19,],
    "X": [cobol_rule19,],
    "Y": [cobol_rule19,],
    "Z": [cobol_rule19,],
    "[": [cobol_rule19,],
    "]": [cobol_rule19,],
    "^": [cobol_rule16,],
    "a": [cobol_rule19,],
    "b": [cobol_rule19,],
    "c": [cobol_rule19,],
    "d": [cobol_rule19,],
    "e": [cobol_rule19,],
    "f": [cobol_rule19,],
    "g": [cobol_rule19,],
    "h": [cobol_rule19,],
    "i": [cobol_rule19,],
    "j": [cobol_rule19,],
    "k": [cobol_rule19,],
    "l": [cobol_rule19,],
    "m": [cobol_rule19,],
    "n": [cobol_rule19,],
    "o": [cobol_rule19,],
    "p": [cobol_rule19,],
    "q": [cobol_rule19,],
    "r": [cobol_rule19,],
    "s": [cobol_rule19,],
    "t": [cobol_rule19,],
    "u": [cobol_rule19,],
    "v": [cobol_rule19,],
    "w": [cobol_rule19,],
    "x": [cobol_rule19,],
    "y": [cobol_rule19,],
    "z": [cobol_rule19,],
    "|": [cobol_rule15,],
    "~": [cobol_rule17,],
}

# x.rulesDictDict for cobol mode.
rulesDictDict = {
    "cobol_main": rulesDict1,
}

# Import dict for cobol mode.
importDict = {}
