# Leo colorizer control file for i4gl mode.
# This file is in the public domain.

# Properties for i4gl mode.
properties = {
    "commentEnd": "}",
    "commentStart": "{",
    "lineComment": "--",
    "noWordSep": "_",
    "wordBreakChars": ",+-=<>/?^&*",
}

# Attributes dict for i4gl_main ruleset.
i4gl_main_attributes_dict = {
    "default": "null",
    "digit_re": "",
    "escape": "\\",
    "highlight_digits": "true",
    "ignore_case": "true",
    "no_word_sep": "",
}

# Dictionary of attributes dictionaries for i4gl mode.
attributesDictDict = {
    "i4gl_main": i4gl_main_attributes_dict,
}

# Keywords dict for i4gl_main ruleset.
i4gl_main_keywords_dict = {
    "abort": "keyword1",
    "abs": "keyword1",
    "absolute": "keyword1",
    "accept": "keyword1",
    "access": "keyword1",
    "acos": "keyword1",
    "ada": "keyword1",
    "add": "keyword1",
    "after": "keyword1",
    "all": "keyword1",
    "allocate": "keyword1",
    "alter": "keyword1",
    "and": "keyword1",
    "ansi": "keyword1",
    "any": "keyword1",
    "append": "keyword1",
    "arg_val": "keyword1",
    "arr_count": "keyword1",
    "arr_curr": "keyword1",
    "array": "keyword1",
    "as": "keyword1",
    "asc": "keyword1",
    "ascending": "keyword1",
    "ascii": "keyword1",
    "asin": "keyword1",
    "at": "keyword1",
    "atan": "keyword1",
    "atan2": "keyword1",
    "attach": "keyword1",
    "attribute": "keyword1",
    "attributes": "keyword1",
    "audit": "keyword1",
    "authorization": "keyword1",
    "auto": "keyword1",
    "autonext": "keyword1",
    "average": "keyword1",
    "avg": "keyword1",
    "before": "keyword1",
    "begin": "keyword1",
    "between": "keyword1",
    "black": "keyword1",
    "blink": "keyword1",
    "blue": "keyword1",
    "bold": "keyword1",
    "border": "keyword1",
    "both": "keyword1",
    "bottom": "keyword1",
    "break": "keyword1",
    "buffered": "keyword1",
    "by": "keyword1",
    "byte": "keyword1",
    "call": "keyword1",
    "cascade": "keyword1",
    "case": "keyword1",
    "char": "keyword1",
    "char_length": "keyword1",
    "character": "keyword1",
    "character_length": "keyword1",
    "check": "keyword1",
    "class_origin": "keyword1",
    "clear": "keyword1",
    "clipped": "keyword1",
    "close": "keyword1",
    "cluster": "keyword1",
    "cobol": "keyword1",
    "color": "keyword1",
    "column": "keyword1",
    "columns": "keyword1",
    "command": "keyword1",
    "comment": "keyword1",
    "comments": "keyword1",
    "commit": "keyword1",
    "committed": "keyword1",
    "composites": "keyword1",
    "compress": "keyword1",
    "concurrent": "keyword1",
    "connect": "keyword1",
    "connection": "keyword1",
    "connection_alias": "keyword1",
    "constrained": "keyword1",
    "constraint": "keyword1",
    "constraints": "keyword1",
    "construct": "keyword1",
    "continue": "keyword1",
    "control": "keyword1",
    "cos": "keyword1",
    "count": "keyword1",
    "create": "keyword1",
    "current": "keyword1",
    "cursor": "keyword1",
    "cyan": "keyword1",
    "data": "keyword1",
    "database": "keyword1",
    "dataskip": "keyword1",
    "date": "keyword1",
    "datetime": "keyword1",
    "day": "keyword1",
    "dba": "keyword1",
    "dbinfo": "keyword1",
    "dbservername": "keyword1",
    "deallocate": "keyword1",
    "debug": "keyword1",
    "dec": "keyword1",
    "decimal": "keyword1",
    "declare": "keyword1",
    "default": "keyword1",
    "defaults": "keyword1",
    "defer": "keyword1",
    "deferred": "keyword1",
    "define": "keyword1",
    "delete": "keyword1",
    "delimiter": "keyword1",
    "delimiters": "keyword1",
    "desc": "keyword1",
    "descending": "keyword1",
    "describe": "keyword1",
    "descriptor": "keyword1",
    "detach": "keyword1",
    "diagnostics": "keyword1",
    "dim": "keyword1",
    "dirty": "keyword1",
    "disabled": "keyword1",
    "disconnect": "keyword1",
    "display": "keyword1",
    "distinct": "keyword1",
    "distributions": "keyword1",
    "do": "keyword1",
    "dormant": "keyword1",
    "double": "keyword1",
    "down": "keyword1",
    "downshift": "keyword1",
    "drop": "keyword1",
    "each": "keyword1",
    "elif": "keyword1",
    "else": "keyword1",
    "enabled": "keyword1",
    "end": "keyword1",
    "entry": "keyword1",
    "err_get": "keyword1",
    "err_print": "keyword1",
    "err_quit": "keyword1",
    "error": "keyword1",
    "errorlog": "keyword1",
    "esc": "keyword1",
    "escape": "keyword1",
    "every": "keyword1",
    "exception": "keyword1",
    "exclusive": "keyword1",
    "exec": "keyword1",
    "execute": "keyword1",
    "exists": "keyword1",
    "exit": "keyword1",
    "exp": "keyword1",
    "explain": "keyword1",
    "expression": "keyword1",
    "extend": "keyword1",
    "extent": "keyword1",
    "extern": "keyword1",
    "external": "keyword1",
    "f1": "keyword1",
    "f10": "keyword1",
    "f11": "keyword1",
    "f12": "keyword1",
    "f13": "keyword1",
    "f14": "keyword1",
    "f15": "keyword1",
    "f16": "keyword1",
    "f17": "keyword1",
    "f18": "keyword1",
    "f19": "keyword1",
    "f2": "keyword1",
    "f20": "keyword1",
    "f21": "keyword1",
    "f22": "keyword1",
    "f23": "keyword1",
    "f24": "keyword1",
    "f25": "keyword1",
    "f26": "keyword1",
    "f27": "keyword1",
    "f28": "keyword1",
    "f29": "keyword1",
    "f3": "keyword1",
    "f30": "keyword1",
    "f31": "keyword1",
    "f32": "keyword1",
    "f33": "keyword1",
    "f34": "keyword1",
    "f35": "keyword1",
    "f36": "keyword1",
    "f37": "keyword1",
    "f38": "keyword1",
    "f39": "keyword1",
    "f4": "keyword1",
    "f40": "keyword1",
    "f41": "keyword1",
    "f42": "keyword1",
    "f43": "keyword1",
    "f44": "keyword1",
    "f45": "keyword1",
    "f46": "keyword1",
    "f47": "keyword1",
    "f48": "keyword1",
    "f49": "keyword1",
    "f5": "keyword1",
    "f50": "keyword1",
    "f51": "keyword1",
    "f52": "keyword1",
    "f53": "keyword1",
    "f54": "keyword1",
    "f55": "keyword1",
    "f56": "keyword1",
    "f57": "keyword1",
    "f58": "keyword1",
    "f59": "keyword1",
    "f6": "keyword1",
    "f60": "keyword1",
    "f61": "keyword1",
    "f62": "keyword1",
    "f63": "keyword1",
    "f64": "keyword1",
    "f7": "keyword1",
    "f8": "keyword1",
    "f9": "keyword1",
    "false": "literal2",
    "fetch": "keyword1",
    "fgl_getenv": "keyword1",
    "fgl_keyval": "keyword1",
    "fgl_lastkey": "keyword1",
    "field": "keyword1",
    "field_touched": "keyword1",
    "file": "keyword1",
    "fillfactor": "keyword1",
    "filtering": "keyword1",
    "finish": "keyword1",
    "first": "keyword1",
    "float": "keyword1",
    "flush": "keyword1",
    "for": "keyword1",
    "foreach": "keyword1",
    "foreign": "keyword1",
    "form": "keyword1",
    "format": "keyword1",
    "formonly": "keyword1",
    "fortran": "keyword1",
    "found": "keyword1",
    "fraction": "keyword1",
    "fragment": "keyword1",
    "free": "keyword1",
    "from": "keyword1",
    "function": "keyword1",
    "get_fldbuf": "keyword1",
    "global": "keyword1",
    "globals": "keyword1",
    "go": "keyword1",
    "goto": "keyword1",
    "grant": "keyword1",
    "green": "keyword1",
    "group": "keyword1",
    "having": "keyword1",
    "header": "keyword1",
    "help": "keyword1",
    "hex": "keyword1",
    "hide": "keyword1",
    "high": "keyword1",
    "hold": "keyword1",
    "hour": "keyword1",
    "idata": "keyword1",
    "if": "keyword1",
    "ilength": "keyword1",
    "immediate": "keyword1",
    "in": "keyword1",
    "include": "keyword1",
    "index": "keyword1",
    "indexes": "keyword1",
    "indicator": "keyword1",
    "infield": "keyword1",
    "init": "keyword1",
    "initialize": "keyword1",
    "input": "keyword1",
    "insert": "keyword1",
    "instructions": "keyword1",
    "int": "keyword1",
    "int_flag": "keyword1",
    "integer": "keyword1",
    "interrupt": "keyword1",
    "interval": "keyword1",
    "into": "keyword1",
    "invisible": "keyword1",
    "is": "keyword1",
    "isam": "keyword1",
    "isolation": "keyword1",
    "itype": "keyword1",
    "key": "keyword1",
    "label": "keyword1",
    "language": "keyword1",
    "last": "keyword1",
    "leading": "keyword1",
    "left": "keyword1",
    "length": "keyword1",
    "let": "keyword1",
    "like": "keyword1",
    "line": "keyword1",
    "lineno": "keyword1",
    "lines": "keyword1",
    "load": "keyword1",
    "locate": "keyword1",
    "lock": "keyword1",
    "log": "keyword1",
    "log10": "keyword1",
    "logn": "keyword1",
    "long": "keyword1",
    "low": "keyword1",
    "magenta": "keyword1",
    "main": "keyword1",
    "margin": "keyword1",
    "matches": "keyword1",
    "max": "keyword1",
    "mdy": "keyword1",
    "medium": "keyword1",
    "memory": "keyword1",
    "menu": "keyword1",
    "message": "keyword1",
    "message_length": "keyword1",
    "message_text": "keyword1",
    "min": "keyword1",
    "minute": "keyword1",
    "mod": "keyword1",
    "mode": "keyword1",
    "modify": "keyword1",
    "module": "keyword1",
    "money": "keyword1",
    "month": "keyword1",
    "more": "keyword1",
    "name": "keyword1",
    "nchar": "keyword1",
    "need": "keyword1",
    "new": "keyword1",
    "next": "keyword1",
    "nextpage": "keyword1",
    "no": "keyword1",
    "nocr": "keyword1",
    "noentry": "keyword1",
    "none": "keyword1",
    "normal": "keyword1",
    "not": "keyword1",
    "notfound": "keyword1",
    "null": "literal2",
    "nullable": "keyword1",
    "num_args": "keyword1",
    "number": "keyword1",
    "numeric": "keyword1",
    "nvarchar": "keyword1",
    "octet_length": "keyword1",
    "of": "keyword1",
    "off": "keyword1",
    "old": "keyword1",
    "on": "keyword1",
    "only": "keyword1",
    "open": "keyword1",
    "optimization": "keyword1",
    "option": "keyword1",
    "options": "keyword1",
    "or": "keyword1",
    "order": "keyword1",
    "otherwise": "keyword1",
    "outer": "keyword1",
    "output": "keyword1",
    "page": "keyword1",
    "pageno": "keyword1",
    "pascal": "keyword1",
    "pause": "keyword1",
    "pdqpriority": "keyword1",
    "percent": "keyword1",
    "picture": "keyword1",
    "pipe": "keyword1",
    "pli": "keyword1",
    "pow": "keyword1",
    "precision": "keyword1",
    "prepare": "keyword1",
    "previous": "keyword1",
    "prevpage": "keyword1",
    "primary": "keyword1",
    "print": "keyword1",
    "printer": "keyword1",
    "prior": "keyword1",
    "private": "keyword1",
    "privileges": "keyword1",
    "procedure": "keyword1",
    "program": "keyword1",
    "prompt": "keyword1",
    "public": "keyword1",
    "put": "keyword1",
    "quit": "keyword1",
    "quit_flag": "keyword1",
    "raise": "keyword1",
    "range": "keyword1",
    "read": "keyword1",
    "readonly": "keyword1",
    "real": "keyword1",
    "record": "keyword1",
    "recover": "keyword1",
    "red": "keyword1",
    "references": "keyword1",
    "referencing": "keyword1",
    "register": "keyword1",
    "relative": "keyword1",
    "remainder": "keyword1",
    "remove": "keyword1",
    "rename": "keyword1",
    "reoptimization": "keyword1",
    "repeatable": "keyword1",
    "report": "keyword1",
    "required": "keyword1",
    "resolution": "keyword1",
    "resource": "keyword1",
    "restrict": "keyword1",
    "resume": "keyword1",
    "return": "keyword1",
    "returned_sqlstate": "keyword1",
    "returning": "keyword1",
    "reverse": "keyword1",
    "revoke": "keyword1",
    "right": "keyword1",
    "robin": "keyword1",
    "role": "keyword1",
    "rollback": "keyword1",
    "rollforward": "keyword1",
    "root": "keyword1",
    "round": "keyword1",
    "row": "keyword1",
    "row_count": "keyword1",
    "rowid": "keyword1",
    "rowids": "keyword1",
    "rows": "keyword1",
    "run": "keyword1",
    "scale": "keyword1",
    "schema": "keyword1",
    "scr_line": "keyword1",
    "screen": "keyword1",
    "scroll": "keyword1",
    "second": "keyword1",
    "section": "keyword1",
    "select": "keyword1",
    "serial": "keyword1",
    "serializable": "keyword1",
    "server_name": "keyword1",
    "session": "keyword1",
    "set": "keyword1",
    "set_count": "keyword1",
    "share": "keyword1",
    "short": "keyword1",
    "show": "keyword1",
    "sitename": "keyword1",
    "size": "keyword1",
    "sizeof": "keyword1",
    "skip": "keyword1",
    "sleep": "keyword1",
    "smallfloat": "keyword1",
    "smallint": "keyword1",
    "some": "keyword1",
    "space": "keyword1",
    "spaces": "keyword1",
    "sql": "keyword1",
    "sqlawarn": "keyword1",
    "sqlca": "keyword1",
    "sqlcode": "keyword1",
    "sqlerrd": "keyword1",
    "sqlerrm": "keyword1",
    "sqlerror": "keyword1",
    "sqlerrp": "keyword1",
    "sqlstate": "keyword1",
    "sqlwarning": "keyword1",
    "sqrt": "keyword1",
    "stability": "keyword1",
    "start": "keyword1",
    "startlog": "keyword1",
    "static": "keyword1",
    "statistics": "keyword1",
    "status": "keyword1",
    "stdev": "keyword1",
    "step": "keyword1",
    "stop": "keyword1",
    "string": "keyword1",
    "struct": "keyword1",
    "subclass_origin": "keyword1",
    "sum": "keyword1",
    "switch": "keyword1",
    "synonym": "keyword1",
    "sysblobs": "keyword1",
    "syschecks": "keyword1",
    "syscolauth": "keyword1",
    "syscoldepend": "keyword1",
    "syscolumns": "keyword1",
    "sysconstraints": "keyword1",
    "sysdefaults": "keyword1",
    "sysdepend": "keyword1",
    "sysdistrib": "keyword1",
    "sysfragauth": "keyword1",
    "sysfragments": "keyword1",
    "sysindexes": "keyword1",
    "sysobjstate": "keyword1",
    "sysopclstr": "keyword1",
    "sysprocauth": "keyword1",
    "sysprocbody": "keyword1",
    "sysprocedures": "keyword1",
    "sysprocplan": "keyword1",
    "sysreferences": "keyword1",
    "sysroleauth": "keyword1",
    "syssynonyms": "keyword1",
    "syssyntable": "keyword1",
    "systabauth": "keyword1",
    "systables": "keyword1",
    "system": "keyword1",
    "systrigbody": "keyword1",
    "systriggers": "keyword1",
    "sysusers": "keyword1",
    "sysviews": "keyword1",
    "sysviolations": "keyword1",
    "tab": "keyword1",
    "table": "keyword1",
    "tables": "keyword1",
    "tan": "keyword1",
    "temp": "keyword1",
    "text": "keyword1",
    "then": "keyword1",
    "through": "keyword1",
    "thru": "keyword1",
    "time": "keyword1",
    "to": "keyword1",
    "today": "keyword1",
    "top": "keyword1",
    "total": "keyword1",
    "trace": "keyword1",
    "trailer": "keyword1",
    "trailing": "keyword1",
    "transaction": "keyword1",
    "trigger": "keyword1",
    "triggers": "keyword1",
    "trim": "keyword1",
    "true": "literal2",
    "trunc": "keyword1",
    "type": "keyword1",
    "typedef": "keyword1",
    "uncommitted": "keyword1",
    "unconstrained": "keyword1",
    "underline": "keyword1",
    "union": "keyword1",
    "unique": "keyword1",
    "units": "keyword1",
    "unload": "keyword1",
    "unlock": "keyword1",
    "unsigned": "keyword1",
    "up": "keyword1",
    "update": "keyword1",
    "upshift": "keyword1",
    "user": "keyword1",
    "using": "keyword1",
    "validate": "keyword1",
    "value": "keyword1",
    "values": "keyword1",
    "varchar": "keyword1",
    "variables": "keyword1",
    "variance": "keyword1",
    "varying": "keyword1",
    "verify": "keyword1",
    "view": "keyword1",
    "violations": "keyword1",
    "wait": "keyword1",
    "waiting": "keyword1",
    "warning": "keyword1",
    "weekday": "keyword1",
    "when": "keyword1",
    "whenever": "keyword1",
    "where": "keyword1",
    "while": "keyword1",
    "white": "keyword1",
    "window": "keyword1",
    "with": "keyword1",
    "without": "keyword1",
    "wordwrap": "keyword1",
    "work": "keyword1",
    "wrap": "keyword1",
    "write": "keyword1",
    "year": "keyword1",
    "yellow": "keyword1",
    "zerofill": "keyword1",
}

# Dictionary of keywords dictionaries for i4gl mode.
keywordsDictDict = {
    "i4gl_main": i4gl_main_keywords_dict,
}

# Rules for i4gl_main ruleset.

def i4gl_rule0(colorer, s, i):
    return colorer.match_span(s, i, kind="literal1", begin="'", end="'")

def i4gl_rule1(colorer, s, i):
    return colorer.match_span(s, i, kind="literal1", begin="\"", end="\"")

def i4gl_rule2(colorer, s, i):
    return colorer.match_eol_span(s, i, kind="comment1", seq="--")

def i4gl_rule3(colorer, s, i):
    return colorer.match_eol_span(s, i, kind="comment1", seq="#")

def i4gl_rule4(colorer, s, i):
    return colorer.match_span(s, i, kind="comment1", begin="{", end="}")

def i4gl_rule5(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="null", seq=")")

def i4gl_rule6(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="null", seq="]")

def i4gl_rule7(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="null", seq="[")

def i4gl_rule8(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="null", seq=".")

def i4gl_rule9(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="null", seq=",")

def i4gl_rule10(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="null", seq=";")

def i4gl_rule11(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="null", seq=":")

def i4gl_rule12(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq="=")

def i4gl_rule13(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq="==")

def i4gl_rule14(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq="!=")

def i4gl_rule15(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq=">=")

def i4gl_rule16(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq="<=")

def i4gl_rule17(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq="<>")

def i4gl_rule18(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq=">")

def i4gl_rule19(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq="<")

def i4gl_rule20(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq="+")

def i4gl_rule21(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq="-")

def i4gl_rule22(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq="/")

def i4gl_rule23(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq="*")

def i4gl_rule24(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq="||")

def i4gl_rule25(colorer, s, i):
    return colorer.match_mark_previous(s, i, kind="function", pattern="(",
          exclude_match=True)

def i4gl_rule26(colorer, s, i):
    return colorer.match_keywords(s, i)

# Rules dict for i4gl_main ruleset.
rulesDict1 = {
    "!": [i4gl_rule14,],
    "\"": [i4gl_rule1,],
    "#": [i4gl_rule3,],
    "'": [i4gl_rule0,],
    "(": [i4gl_rule25,],
    ")": [i4gl_rule5,],
    "*": [i4gl_rule23,],
    "+": [i4gl_rule20,],
    ",": [i4gl_rule9,],
    "-": [i4gl_rule2, i4gl_rule21,],
    ".": [i4gl_rule8,],
    "/": [i4gl_rule22,],
    "0": [i4gl_rule26,],
    "1": [i4gl_rule26,],
    "2": [i4gl_rule26,],
    "3": [i4gl_rule26,],
    "4": [i4gl_rule26,],
    "5": [i4gl_rule26,],
    "6": [i4gl_rule26,],
    "7": [i4gl_rule26,],
    "8": [i4gl_rule26,],
    "9": [i4gl_rule26,],
    ":": [i4gl_rule11,],
    ";": [i4gl_rule10,],
    "<": [i4gl_rule16, i4gl_rule17, i4gl_rule19,],
    "=": [i4gl_rule12, i4gl_rule13,],
    ">": [i4gl_rule15, i4gl_rule18,],
    "@": [i4gl_rule26,],
    "A": [i4gl_rule26,],
    "B": [i4gl_rule26,],
    "C": [i4gl_rule26,],
    "D": [i4gl_rule26,],
    "E": [i4gl_rule26,],
    "F": [i4gl_rule26,],
    "G": [i4gl_rule26,],
    "H": [i4gl_rule26,],
    "I": [i4gl_rule26,],
    "J": [i4gl_rule26,],
    "K": [i4gl_rule26,],
    "L": [i4gl_rule26,],
    "M": [i4gl_rule26,],
    "N": [i4gl_rule26,],
    "O": [i4gl_rule26,],
    "P": [i4gl_rule26,],
    "Q": [i4gl_rule26,],
    "R": [i4gl_rule26,],
    "S": [i4gl_rule26,],
    "T": [i4gl_rule26,],
    "U": [i4gl_rule26,],
    "V": [i4gl_rule26,],
    "W": [i4gl_rule26,],
    "X": [i4gl_rule26,],
    "Y": [i4gl_rule26,],
    "Z": [i4gl_rule26,],
    "[": [i4gl_rule7,],
    "]": [i4gl_rule6,],
    "_": [i4gl_rule26,],
    "a": [i4gl_rule26,],
    "b": [i4gl_rule26,],
    "c": [i4gl_rule26,],
    "d": [i4gl_rule26,],
    "e": [i4gl_rule26,],
    "f": [i4gl_rule26,],
    "g": [i4gl_rule26,],
    "h": [i4gl_rule26,],
    "i": [i4gl_rule26,],
    "j": [i4gl_rule26,],
    "k": [i4gl_rule26,],
    "l": [i4gl_rule26,],
    "m": [i4gl_rule26,],
    "n": [i4gl_rule26,],
    "o": [i4gl_rule26,],
    "p": [i4gl_rule26,],
    "q": [i4gl_rule26,],
    "r": [i4gl_rule26,],
    "s": [i4gl_rule26,],
    "t": [i4gl_rule26,],
    "u": [i4gl_rule26,],
    "v": [i4gl_rule26,],
    "w": [i4gl_rule26,],
    "x": [i4gl_rule26,],
    "y": [i4gl_rule26,],
    "z": [i4gl_rule26,],
    "{": [i4gl_rule4,],
    "|": [i4gl_rule24,],
}

# x.rulesDictDict for i4gl mode.
rulesDictDict = {
    "i4gl_main": rulesDict1,
}

# Import dict for i4gl mode.
importDict = {}
