# Leo colorizer control file for pvwave mode.
# This file is in the public domain.

# Properties for pvwave mode.
properties = {
    "lineComment": ";",
}

# Attributes dict for pvwave_main ruleset.
pvwave_main_attributes_dict = {
    "default": "null",
    "digit_re": "",
    "escape": "",
    "highlight_digits": "true",
    "ignore_case": "true",
    "no_word_sep": "",
}

# Dictionary of attributes dictionaries for pvwave mode.
attributesDictDict = {
    "pvwave_main": pvwave_main_attributes_dict,
}

# Keywords dict for pvwave_main ruleset.
pvwave_main_keywords_dict = {
    "abs": "keyword1",
    "acos": "keyword1",
    "add_exec_on_select": "keyword1",
    "addsysvar": "keyword1",
    "addvar": "keyword1",
    "affine": "keyword1",
    "alog": "keyword1",
    "alog10": "keyword1",
    "and": "keyword3",
    "asarr": "keyword1",
    "asin": "keyword1",
    "askeys": "keyword1",
    "assoc": "keyword1",
    "atan": "keyword1",
    "avg": "keyword1",
    "axis": "keyword1",
    "bar": "keyword1",
    "bar2d": "keyword1",
    "bar3d": "keyword1",
    "begin": "keyword2",
    "beseli": "keyword1",
    "beselj": "keyword1",
    "besely": "keyword1",
    "bilinear": "keyword1",
    "bindgen": "keyword1",
    "blob": "keyword1",
    "blobcount": "keyword1",
    "boundary": "keyword1",
    "breakpoint": "keyword2",
    "build_table": "keyword1",
    "buildresourcefilename": "keyword1",
    "bytarr": "keyword1",
    "byte": "keyword1",
    "byteorder": "keyword1",
    "bytscl": "keyword1",
    "c_edit": "keyword1",
    "call_unix": "keyword1",
    "case": "keyword2",
    "cd": "keyword1",
    "center_view": "keyword1",
    "chebyshev": "keyword1",
    "check_math": "keyword1",
    "checkfile": "keyword1",
    "cindgen": "keyword1",
    "close": "keyword1",
    "color_convert": "keyword1",
    "color_edit": "keyword1",
    "color_palette": "keyword1",
    "common": "keyword2",
    "compile": "keyword2",
    "complex": "keyword1",
    "complexarr": "keyword1",
    "cone": "keyword1",
    "congrid": "keyword1",
    "conj": "keyword1",
    "contour": "keyword1",
    "contour2": "keyword1",
    "contourfill": "keyword1",
    "conv_from_rect": "keyword1",
    "conv_to_rect": "keyword1",
    "convert_coord": "keyword1",
    "convol": "keyword1",
    "correlate": "keyword1",
    "cos": "keyword1",
    "cosh": "keyword1",
    "cosines": "keyword1",
    "cprod": "keyword1",
    "create_holidays": "keyword1",
    "create_weekdends": "keyword1",
    "crossp": "keyword1",
    "cursor": "keyword1",
    "curvatures": "keyword1",
    "curvefit": "keyword1",
    "cylinder": "keyword1",
    "day_name": "keyword1",
    "day_of_week": "keyword1",
    "day_of_year": "keyword1",
    "dblarr": "keyword1",
    "dc_error_msg": "keyword1",
    "dc_options": "keyword1",
    "dc_read_24_bit": "keyword1",
    "dc_read_8_bit": "keyword1",
    "dc_read_container": "keyword1",
    "dc_read_dib": "keyword1",
    "dc_read_fixed": "keyword1",
    "dc_read_free": "keyword1",
    "dc_read_tiff": "keyword1",
    "dc_scan_container": "keyword1",
    "dc_write_24_bit": "keyword1",
    "dc_write_8_bit": "keyword1",
    "dc_write_dib": "keyword1",
    "dc_write_fixed": "keyword1",
    "dc_write_free": "keyword1",
    "dc_write_tiff": "keyword1",
    "dcindgen": "keyword1",
    "dcomplex": "keyword1",
    "dcomplexarr": "keyword1",
    "declare": "keyword2",
    "define_key": "keyword1",
    "defroi": "keyword1",
    "defsysv": "keyword1",
    "del_file": "keyword1",
    "delfunc": "keyword1",
    "dellog": "keyword1",
    "delproc": "keyword1",
    "delstruct": "keyword1",
    "delvar": "keyword1",
    "demo": "keyword1",
    "deriv": "keyword1",
    "derivn": "keyword1",
    "determ": "keyword1",
    "device": "keyword1",
    "diag": "keyword1",
    "dicm_tag_info": "keyword1",
    "digital_filter": "keyword1",
    "dilate": "keyword1",
    "dindgen": "keyword1",
    "dist": "keyword1",
    "dminit": "keyword1",
    "do": "keyword2",
    "doc_lib_unix": "keyword1",
    "doc_library": "keyword1",
    "double": "keyword1",
    "drop_exec_on_select": "keyword1",
    "dt_add": "keyword1",
    "dt_addly": "keyword1",
    "dt_compress": "keyword1",
    "dt_duration": "keyword1",
    "dt_print": "keyword1",
    "dt_subly": "keyword1",
    "dt_subtract": "keyword1",
    "dt_to_sec": "keyword1",
    "dt_to_str": "keyword1",
    "dt_to_var": "keyword1",
    "dtegn": "keyword1",
    "else": "keyword2",
    "empty": "keyword1",
    "end": "keyword2",
    "endcase": "keyword2",
    "endelse": "keyword2",
    "endfor": "keyword2",
    "endif": "keyword2",
    "endrepeat": "keyword2",
    "endwhile": "keyword2",
    "environment": "keyword1",
    "eof": "keyword1",
    "eq": "keyword3",
    "erase": "keyword1",
    "erode": "keyword1",
    "errorf": "keyword1",
    "errplot": "keyword1",
    "euclidean": "keyword1",
    "exec_on_select": "keyword1",
    "execute": "keyword1",
    "exit": "keyword2",
    "exp": "keyword1",
    "expand": "keyword1",
    "expon": "keyword1",
    "extrema": "keyword1",
    "factor": "keyword1",
    "fast_grid2": "keyword1",
    "fast_grid3": "keyword1",
    "fast_grid4": "keyword1",
    "fft": "keyword1",
    "filepath": "keyword1",
    "findfile": "keyword1",
    "findgen": "keyword1",
    "finite": "keyword1",
    "fix": "keyword1",
    "float": "keyword1",
    "fltarr": "keyword1",
    "flush": "keyword1",
    "for": "keyword2",
    "free_lun": "keyword1",
    "fstat": "keyword1",
    "func": "keyword2",
    "funct": "keyword1",
    "function": "keyword2",
    "gamma": "keyword1",
    "gaussfit": "keyword1",
    "gaussint": "keyword1",
    "gcd": "keyword1",
    "ge": "keyword3",
    "get_kbrd": "keyword1",
    "get_lun": "keyword1",
    "get_named_color": "keyword1",
    "getenv": "keyword1",
    "getncerr": "keyword1",
    "getncopts": "keyword1",
    "getparam": "keyword1",
    "goto": "keyword2",
    "great_int": "keyword1",
    "grid": "keyword1",
    "grid_2d": "keyword1",
    "grid_3d": "keyword1",
    "grid_4d": "keyword1",
    "grid_sphere": "keyword1",
    "gridn": "keyword1",
    "group_by": "keyword1",
    "gt": "keyword3",
    "hak": "keyword1",
    "hanning": "keyword1",
    "hdf_test": "keyword1",
    "hdfgetsds": "keyword1",
    "help": "keyword2",
    "hilbert": "keyword1",
    "hist_equal": "keyword1",
    "hist_equal_ct": "keyword1",
    "histn": "keyword1",
    "histogram": "keyword1",
    "hls": "keyword1",
    "hsv": "keyword1",
    "hsv_to_rgd": "keyword1",
    "if": "keyword2",
    "image_check": "keyword1",
    "image_color_quant": "keyword1",
    "image_cont": "keyword1",
    "image_create": "keyword1",
    "image_display": "keyword1",
    "image_filetypes": "keyword1",
    "image_query_file": "keyword1",
    "image_read": "keyword1",
    "image_write": "keyword1",
    "imaginary": "keyword1",
    "img_true8": "keyword1",
    "index_and": "keyword1",
    "index_conv": "keyword1",
    "index_or": "keyword1",
    "indgen": "keyword1",
    "info": "keyword2",
    "intarr": "keyword1",
    "interpol": "keyword1",
    "interpolate": "keyword1",
    "intrp": "keyword1",
    "invert": "keyword1",
    "isaskey": "keyword1",
    "ishft": "keyword1",
    "jacobian": "keyword1",
    "journal": "keyword2",
    "jul_to_dt": "keyword1",
    "keyword_set": "keyword1",
    "lcm": "keyword1",
    "le": "keyword3",
    "leefilt": "keyword1",
    "legend": "keyword1",
    "lindgen": "keyword1",
    "linknload": "keyword1",
    "list": "keyword1",
    "listarr": "keyword1",
    "load_holidays": "keyword1",
    "load_option": "keyword1",
    "load_weekends": "keyword1",
    "loadct": "keyword1",
    "loadct_custom": "keyword1",
    "loadresources": "keyword1",
    "loadstrings": "keyword1",
    "locals": "keyword2",
    "lonarr": "keyword1",
    "long": "keyword1",
    "lt": "keyword3",
    "lubksb": "keyword1",
    "ludcmp": "keyword1",
    "make_array": "keyword1",
    "map": "keyword1",
    "map_axes": "keyword1",
    "map_contour": "keyword1",
    "map_grid": "keyword1",
    "map_plots": "keyword1",
    "map_polyfill": "keyword1",
    "map_proj": "keyword1",
    "map_reverse": "keyword1",
    "map_velovect": "keyword1",
    "map_version": "keyword1",
    "map_xyouts": "keyword1",
    "max": "keyword1",
    "median": "keyword1",
    "mesh": "keyword1",
    "message": "keyword1",
    "min": "keyword1",
    "mod": "keyword3",
    "modifyct": "keyword1",
    "molec": "keyword1",
    "moment": "keyword1",
    "month_name": "keyword1",
    "movie": "keyword1",
    "mprove": "keyword1",
    "msword_cgm_setup": "keyword1",
    "n_elements": "keyword1",
    "n_params": "keyword1",
    "n_tags": "keyword1",
    "ne": "keyword3",
    "nint": "keyword1",
    "normals": "keyword1",
    "not": "keyword3",
    "null_processor": "keyword1",
    "of": "keyword2",
    "on_error": "keyword2",
    "on_error_goto": "keyword2",
    "on_ioerror": "keyword2",
    "openr": "keyword1",
    "openu": "keyword1",
    "openw": "keyword1",
    "oplot": "keyword1",
    "oploterr": "keyword1",
    "option_is_loaded": "keyword1",
    "or": "keyword3",
    "order_by": "keyword1",
    "packimage": "keyword1",
    "packtable": "keyword1",
    "padit": "keyword1",
    "palette": "keyword1",
    "param_present": "keyword1",
    "parsefilename": "keyword1",
    "pie": "keyword1",
    "pie_chart": "keyword1",
    "plot": "keyword1",
    "plot_field": "keyword1",
    "plot_histogram": "keyword1",
    "plot_io": "keyword1",
    "plot_oi": "keyword1",
    "plot_oo": "keyword1",
    "plot_windrose": "keyword1",
    "ploterr": "keyword1",
    "plots": "keyword1",
    "pm": "keyword1",
    "pmf": "keyword1",
    "point_lun": "keyword1",
    "poly": "keyword1",
    "poly_2d": "keyword1",
    "poly_area": "keyword1",
    "poly_c_conv": "keyword1",
    "poly_count": "keyword1",
    "poly_dev": "keyword1",
    "poly_fit": "keyword1",
    "poly_merge": "keyword1",
    "poly_norm": "keyword1",
    "poly_plot": "keyword1",
    "poly_sphere": "keyword1",
    "poly_surf": "keyword1",
    "poly_trans": "keyword1",
    "polyfill": "keyword1",
    "polyfillv": "keyword1",
    "polyfitw": "keyword1",
    "polyshade": "keyword1",
    "polywarp": "keyword1",
    "popd": "keyword1",
    "prime": "keyword1",
    "print": "keyword1",
    "printd": "keyword1",
    "printf": "keyword1",
    "pro": "keyword2",
    "profile": "keyword1",
    "profiles": "keyword1",
    "prompt": "keyword1",
    "pseudo": "keyword1",
    "pushd": "keyword1",
    "query_table": "keyword1",
    "quit": "keyword2",
    "randomn": "keyword1",
    "randomu": "keyword1",
    "rdpix": "keyword1",
    "read": "keyword1",
    "read_airs": "keyword1",
    "read_xbm": "keyword1",
    "readf": "keyword1",
    "readu": "keyword1",
    "rebin": "keyword1",
    "reform": "keyword1",
    "regress": "keyword1",
    "rename": "keyword1",
    "render": "keyword1",
    "render24": "keyword1",
    "repeat": "keyword2",
    "replicate": "keyword1",
    "replv": "keyword1",
    "resamp": "keyword1",
    "restore": "keyword2",
    "retall": "keyword2",
    "return": "keyword2",
    "reverse": "keyword1",
    "rgb_to_hsv": "keyword1",
    "rm": "keyword1",
    "rmf": "keyword1",
    "roberts": "keyword1",
    "rot": "keyword1",
    "rot_int": "keyword1",
    "rotate": "keyword1",
    "same": "keyword1",
    "save": "keyword2",
    "scale3d": "keyword1",
    "sec_to_dt": "keyword1",
    "select_read_lun": "keyword1",
    "set_plot": "keyword1",
    "set_screen": "keyword1",
    "set_shading": "keyword1",
    "set_symbol": "keyword1",
    "set_view3d": "keyword1",
    "set_viewport": "keyword1",
    "set_xy": "keyword1",
    "setdemo": "keyword1",
    "setenv": "keyword1",
    "setimagesize": "keyword1",
    "setlog": "keyword1",
    "setncopts": "keyword1",
    "setup_keys": "keyword1",
    "sgn": "keyword1",
    "shade_surf": "keyword1",
    "shade_surf_irr": "keyword1",
    "shade_volume": "keyword1",
    "shif": "keyword1",
    "shift": "keyword1",
    "show3": "keyword1",
    "show_options": "keyword1",
    "sigma": "keyword1",
    "sin": "keyword1",
    "sindgen": "keyword1",
    "sinh": "keyword1",
    "size": "keyword1",
    "skipf": "keyword1",
    "slice": "keyword1",
    "slice_vol": "keyword1",
    "small_int": "keyword1",
    "smooth": "keyword1",
    "sobel": "keyword1",
    "socket_accept": "keyword1",
    "socket_close": "keyword1",
    "socket_connect": "keyword1",
    "socket_getport": "keyword1",
    "socket_init": "keyword1",
    "socket_read": "keyword1",
    "socket_write": "keyword1",
    "sort": "keyword1",
    "sortn": "keyword1",
    "spawn": "keyword1",
    "sphere": "keyword1",
    "spline": "keyword1",
    "sqrt": "keyword1",
    "stdev": "keyword1",
    "stop": "keyword2",
    "str_to_dt": "keyword1",
    "strarr": "keyword1",
    "strcompress": "keyword1",
    "stretch": "keyword1",
    "string": "keyword1",
    "strjoin": "keyword1",
    "strlen": "keyword1",
    "strlookup": "keyword1",
    "strlowcase": "keyword1",
    "strmatch": "keyword1",
    "strmessage": "keyword1",
    "strmid": "keyword1",
    "strpos": "keyword1",
    "strput": "keyword1",
    "strsplit": "keyword1",
    "strsubst": "keyword1",
    "strtrim": "keyword1",
    "structref": "keyword1",
    "strupcase": "keyword1",
    "sum": "keyword1",
    "surface": "keyword1",
    "surface_fit": "keyword1",
    "surfr": "keyword1",
    "svbksb": "keyword1",
    "svd": "keyword1",
    "svdfit": "keyword1",
    "systime": "keyword1",
    "t3d": "keyword1",
    "tag_names": "keyword1",
    "tan": "keyword1",
    "tanh": "keyword1",
    "tek_color": "keyword1",
    "tensor_add": "keyword1",
    "tensor_div": "keyword1",
    "tensor_eq": "keyword1",
    "tensor_exp": "keyword1",
    "tensor_ge": "keyword1",
    "tensor_gt": "keyword1",
    "tensor_le": "keyword1",
    "tensor_lt": "keyword1",
    "tensor_max": "keyword1",
    "tensor_min": "keyword1",
    "tensor_mod": "keyword1",
    "tensor_mul": "keyword1",
    "tensor_ne": "keyword1",
    "tensor_sub": "keyword1",
    "then": "keyword2",
    "threed": "keyword1",
    "today": "keyword1",
    "total": "keyword1",
    "tqli": "keyword1",
    "transpose": "keyword1",
    "tred2": "keyword1",
    "tridag": "keyword1",
    "tv": "keyword1",
    "tvcrs": "keyword1",
    "tvlct": "keyword1",
    "tvrd": "keyword1",
    "tvscl": "keyword1",
    "tvsize": "keyword1",
    "uniqn": "keyword1",
    "unique": "keyword1",
    "unix_listen": "keyword1",
    "unix_reply": "keyword1",
    "unload_option": "keyword1",
    "upvar": "keyword1",
    "usersym": "keyword1",
    "usgs_names": "keyword1",
    "value_length": "keyword1",
    "var_match": "keyword1",
    "var_to_dt": "keyword1",
    "vector_field3": "keyword1",
    "vel": "keyword1",
    "velovect": "keyword1",
    "viewer": "keyword1",
    "vol_marker": "keyword1",
    "vol_pad": "keyword1",
    "vol_red": "keyword1",
    "vol_trans": "keyword1",
    "volume": "keyword1",
    "vtkaddattribute": "keyword1",
    "vtkaxes": "keyword1",
    "vtkcamera": "keyword1",
    "vtkclose": "keyword1",
    "vtkcolorbar": "keyword1",
    "vtkcolornames": "keyword1",
    "vtkcommand": "keyword1",
    "vtkerase": "keyword1",
    "vtkformat": "keyword1",
    "vtkgrid": "keyword1",
    "vtkhedgehog": "keyword1",
    "vtkinit": "keyword1",
    "vtklight": "keyword1",
    "vtkplots": "keyword1",
    "vtkpolydata": "keyword1",
    "vtkpolyformat": "keyword1",
    "vtkpolyshade": "keyword1",
    "vtkppmread": "keyword1",
    "vtkppmwrite": "keyword1",
    "vtkreadvtk": "keyword1",
    "vtkrectilineargrid": "keyword1",
    "vtkrenderwindow": "keyword1",
    "vtkscatter": "keyword1",
    "vtkslicevol": "keyword1",
    "vtkstructuredgrid": "keyword1",
    "vtkstructuredpoints": "keyword1",
    "vtksurface": "keyword1",
    "vtksurfgen": "keyword1",
    "vtktext": "keyword1",
    "vtktvrd": "keyword1",
    "vtkunstructuredgrid": "keyword1",
    "vtkwdelete": "keyword1",
    "vtkwindow": "keyword1",
    "vtkwritevrml": "keyword1",
    "vtkwset": "keyword1",
    "wait": "keyword1",
    "wavedatamanager": "keyword1",
    "waveserver": "keyword1",
    "wcopy": "keyword1",
    "wdelete": "keyword1",
    "wganimatetool": "keyword3",
    "wgcbartool": "keyword3",
    "wgcttool": "keyword3",
    "wgisosurftool": "keyword3",
    "wgmovietool": "keyword3",
    "wgsimagetool": "keyword3",
    "wgslicetool": "keyword3",
    "wgsurfacetool": "keyword3",
    "wgtexttool": "keyword3",
    "where": "keyword1",
    "wherein": "keyword1",
    "while": "keyword2",
    "whow": "keyword1",
    "window": "keyword1",
    "wmenu": "keyword1",
    "woaddbuttons": "keyword3",
    "woaddmessage": "keyword3",
    "woaddstatus": "keyword3",
    "wobuttonbar": "keyword3",
    "wocheckfile": "keyword3",
    "wocolorbutton": "keyword3",
    "wocolorconvert": "keyword3",
    "wocolorgrid": "keyword3",
    "wocolorwheel": "keyword3",
    "woconfirmclose": "keyword3",
    "wodialogstatus": "keyword3",
    "wofontoptionmenu": "keyword3",
    "wogenericdialog": "keyword3",
    "wolabeledtext": "keyword3",
    "womenubar": "keyword3",
    "womessage": "keyword3",
    "wosaveaspixmap": "keyword3",
    "wosetcursor": "keyword3",
    "wosetwindowtitle": "keyword3",
    "wostatus": "keyword3",
    "wovariableoptionmenu": "keyword3",
    "wpaste": "keyword1",
    "wprint": "keyword1",
    "wread_dib": "keyword1",
    "wread_meta": "keyword1",
    "write_xbm": "keyword1",
    "writeu": "keyword1",
    "wset": "keyword1",
    "wtaddcallback": "keyword3",
    "wtaddhandler": "keyword3",
    "wtcursor": "keyword3",
    "wtget": "keyword3",
    "wtpointer": "keyword3",
    "wtset": "keyword3",
    "wttimer": "keyword3",
    "wwalert": "keyword3",
    "wwalertpopdown": "keyword3",
    "wwbuttonbox": "keyword3",
    "wwcallback": "keyword3",
    "wwcontrolsbox": "keyword3",
    "wwdialog": "keyword3",
    "wwdrawing": "keyword3",
    "wwfileselection": "keyword3",
    "wwgenericdialog": "keyword3",
    "wwgetbutton": "keyword3",
    "wwgetkey": "keyword3",
    "wwgetposition": "keyword3",
    "wwgetvalue": "keyword3",
    "wwhandler": "keyword3",
    "wwinit": "keyword3",
    "wwlayout": "keyword3",
    "wwlist": "keyword3",
    "wwlistutils": "keyword3",
    "wwloop": "keyword3",
    "wwmainwindow": "keyword3",
    "wwmenubar": "keyword3",
    "wwmenuitem": "keyword3",
    "wwmessage": "keyword3",
    "wwmulticlickhandler": "keyword3",
    "wwoptionmenu": "keyword3",
    "wwpickfile": "keyword3",
    "wwpopupmenu": "keyword3",
    "wwpreview": "keyword3",
    "wwpreviewutils": "keyword3",
    "wwradiobox": "keyword3",
    "wwresource": "keyword3",
    "wwrite_dib": "keyword1",
    "wwrite_meta": "keyword1",
    "wwseparator": "keyword3",
    "wwsetcursor": "keyword3",
    "wwsetvalue": "keyword3",
    "wwtable": "keyword3",
    "wwtableutils": "keyword3",
    "wwtext": "keyword3",
    "wwtimer": "keyword3",
    "wwtoolbox": "keyword3",
    "wzanimate": "keyword3",
    "wzcoloredit": "keyword3",
    "wzcontour": "keyword3",
    "wzexport": "keyword3",
    "wzhistogram": "keyword3",
    "wzimage": "keyword3",
    "wzimport": "keyword3",
    "wzmultiview": "keyword3",
    "wzplot": "keyword3",
    "wzpreview": "keyword3",
    "wzsurface": "keyword3",
    "wztable": "keyword3",
    "wzvariable": "keyword3",
    "xor": "keyword3",
    "xyouts": "keyword1",
    "zoom": "keyword1",
    "zroots": "keyword1",
}

# Dictionary of keywords dictionaries for pvwave mode.
keywordsDictDict = {
    "pvwave_main": pvwave_main_keywords_dict,
}

# Rules for pvwave_main ruleset.

def pvwave_rule0(colorer, s, i):
    return colorer.match_span(s, i, kind="literal1", begin="\"", end="\"",
          no_line_break=True)

def pvwave_rule1(colorer, s, i):
    return colorer.match_span(s, i, kind="literal1", begin="'", end="'",
          no_line_break=True)

def pvwave_rule2(colorer, s, i):
    return colorer.match_eol_span(s, i, kind="comment1", seq=";")

def pvwave_rule3(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq="(")

def pvwave_rule4(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq=")")

def pvwave_rule5(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq="=")

def pvwave_rule6(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq="+")

def pvwave_rule7(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq="-")

def pvwave_rule8(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq="/")

def pvwave_rule9(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq="*")

def pvwave_rule10(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq="#")

def pvwave_rule11(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq=">")

def pvwave_rule12(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq="<")

def pvwave_rule13(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq="^")

def pvwave_rule14(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq="}")

def pvwave_rule15(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq="{")

def pvwave_rule16(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq=".")

def pvwave_rule17(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq=",")

def pvwave_rule18(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq="]")

def pvwave_rule19(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq="[")

def pvwave_rule20(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="operator", seq=":")

def pvwave_rule21(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="label", seq="$")

def pvwave_rule22(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="label", seq="&")

def pvwave_rule23(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="label", seq="@")

def pvwave_rule24(colorer, s, i):
    return colorer.match_plain_seq(s, i, kind="label", seq="!")

def pvwave_rule25(colorer, s, i):
    return colorer.match_keywords(s, i)

# Rules dict for pvwave_main ruleset.
rulesDict1 = {
    "!": [pvwave_rule24,],
    "\"": [pvwave_rule0,],
    "#": [pvwave_rule10,],
    "$": [pvwave_rule21,],
    "&": [pvwave_rule22,],
    "'": [pvwave_rule1,],
    "(": [pvwave_rule3,],
    ")": [pvwave_rule4,],
    "*": [pvwave_rule9,],
    "+": [pvwave_rule6,],
    ",": [pvwave_rule17,],
    "-": [pvwave_rule7,],
    ".": [pvwave_rule16,],
    "/": [pvwave_rule8,],
    "0": [pvwave_rule25,],
    "1": [pvwave_rule25,],
    "2": [pvwave_rule25,],
    "3": [pvwave_rule25,],
    "4": [pvwave_rule25,],
    "5": [pvwave_rule25,],
    "6": [pvwave_rule25,],
    "7": [pvwave_rule25,],
    "8": [pvwave_rule25,],
    "9": [pvwave_rule25,],
    ":": [pvwave_rule20,],
    ";": [pvwave_rule2,],
    "<": [pvwave_rule12,],
    "=": [pvwave_rule5,],
    ">": [pvwave_rule11,],
    "@": [pvwave_rule23, pvwave_rule25,],
    "A": [pvwave_rule25,],
    "B": [pvwave_rule25,],
    "C": [pvwave_rule25,],
    "D": [pvwave_rule25,],
    "E": [pvwave_rule25,],
    "F": [pvwave_rule25,],
    "G": [pvwave_rule25,],
    "H": [pvwave_rule25,],
    "I": [pvwave_rule25,],
    "J": [pvwave_rule25,],
    "K": [pvwave_rule25,],
    "L": [pvwave_rule25,],
    "M": [pvwave_rule25,],
    "N": [pvwave_rule25,],
    "O": [pvwave_rule25,],
    "P": [pvwave_rule25,],
    "Q": [pvwave_rule25,],
    "R": [pvwave_rule25,],
    "S": [pvwave_rule25,],
    "T": [pvwave_rule25,],
    "U": [pvwave_rule25,],
    "V": [pvwave_rule25,],
    "W": [pvwave_rule25,],
    "X": [pvwave_rule25,],
    "Y": [pvwave_rule25,],
    "Z": [pvwave_rule25,],
    "[": [pvwave_rule19,],
    "]": [pvwave_rule18,],
    "^": [pvwave_rule13,],
    "_": [pvwave_rule25,],
    "a": [pvwave_rule25,],
    "b": [pvwave_rule25,],
    "c": [pvwave_rule25,],
    "d": [pvwave_rule25,],
    "e": [pvwave_rule25,],
    "f": [pvwave_rule25,],
    "g": [pvwave_rule25,],
    "h": [pvwave_rule25,],
    "i": [pvwave_rule25,],
    "j": [pvwave_rule25,],
    "k": [pvwave_rule25,],
    "l": [pvwave_rule25,],
    "m": [pvwave_rule25,],
    "n": [pvwave_rule25,],
    "o": [pvwave_rule25,],
    "p": [pvwave_rule25,],
    "q": [pvwave_rule25,],
    "r": [pvwave_rule25,],
    "s": [pvwave_rule25,],
    "t": [pvwave_rule25,],
    "u": [pvwave_rule25,],
    "v": [pvwave_rule25,],
    "w": [pvwave_rule25,],
    "x": [pvwave_rule25,],
    "y": [pvwave_rule25,],
    "z": [pvwave_rule25,],
    "{": [pvwave_rule15,],
    "}": [pvwave_rule14,],
}

# x.rulesDictDict for pvwave mode.
rulesDictDict = {
    "pvwave_main": rulesDict1,
}

# Import dict for pvwave mode.
importDict = {}
