<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<?xml-stylesheet type="text/xsl" href="leo_to_html.xsl"?>
<!-- does not work (same origin policy):
    see http://stackoverflow.com/questions/3420513/firefox-and-remote-xsl-stylesheets
    <?xml-stylesheet type="text/xsl" href="http://leoeditor.com/leo_to_html.xsl"?>
-->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5" body_secondary_ratio="0.5">
	<global_window_position top="50" left="50" height="500" width="700"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="ekr.20150217160307.26"><vh>test.leo</vh>
<v t="ekr.20150217160307.27"><vh>node 1</vh></v>
<v t="ekr.20150217160307.28"><vh>node 2</vh></v>
</v>
</vnodes>
<tnodes>
<t tx="ekr.20150217160307.26">This is a test</t>
<t tx="ekr.20150217160307.27">Node 1 text.</t>
<t tx="ekr.20150217160307.28">Node 2 text.</t>
</tnodes>
</leo_file>
