#!/usr/bin/python
import json
import os
import subprocess
import time

# http://stackoverflow.com/questions/3878624/how-do-i-programmatically-determine-if-there-are-uncommited-changes
diffs = subprocess.call(
    "git diff-index --cached --quiet HEAD --ignore-submodules --".split()
)
if not diffs:
    print("Version info update hook sees nothing to do")
    exit(0)

PATH = os.path.join("leo", "core", "commit_timestamp.json")

INFO = {
    'asctime': time.asctime(),
    'timestamp': time.strftime("%Y%m%d%H%M%S"),
}

try:
    INFO['parent'] = open(".git/refs/heads/master").read().strip()
except IOError:
    INFO['parent'] = "unknown"

json.dump(INFO, open(PATH, 'w'), sort_keys=True, indent=4)
print("Updating version info.")
time.sleep(2)
os.system('git add %s' % PATH)
